### ISSUE TITLE
Web UI: Preset/Bank Info: Comment: Zeilenumbrüche gehen verloren.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1023]
Es passiert nicht direkt nach dem Schreiben oder Schliessen/Öffnen des Info-Dialogs, aber spätestens nach dem Neu-Laden der GUI im Browser.

Im BOLED haben wir das Problem nicht.

**Comment by schlenkibus** [comment]
Auf aktuellem Master, kann ich das Problem nicht reproduzieren, Alle Texte werden mit Zeilenumbrüchen abgespeichert und nach Neustarts von WebUI/Playground erfolgreich abgerufen/angezeigt.
