### ISSUE TITLE
+/- Tasten neben dem SOLED sollten im Bank/Preset-Mode auch beim Halten repetieren

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1036]
Wie die "Dec"/"Inc"-Tasten unter dem BOLED.

Im Play/Edit-Modus (Oktave-Shift/Transponierung) besser nicht keine Repetition ergänzen, weil hier das Halten mit Funktionen belegt ist.

**Comment by KlausStrohhaecker** [comment]
Siehe auch Issue #964,
d.g. sowohl Autorepeat wie auch zyklisches Durchfahren
