### ISSUE TITLE
BOLED: Dual-Sound changed ambiguity

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1071]
What is the desired behavior for "changed overview" (Preset Focus + Shift -> changed parameter LEDs should blink):
Should only the current layer parameters be shown? If so the changed star can be misleading.

![Boled-Wed-Oct--2-16:18:32-2019
](https://user-images.githubusercontent.com/15381257/66052151-68be3e80-e530-11e9-809c-2981fb6d9661.png)

**Comment by schlenkibus** [comment]
An idea that was thought about was to add an sound type indication below the preset and bank number that could also hold additional information about what is changed: 
![Boled-Wed-Oct--9-17:46:28-2019
](https://user-images.githubusercontent.com/15381257/66497858-6bcfa680-eabd-11e9-997c-ccd23e77b816.png)

@nonlinear-labs your thoughts?

**Comment by nonlinear-labs** [comment]
When a dual preset has been loaded, we need a "voice group focus" indication ("I" or "II") on the Preset Screen, as a necessary information for the Activity Overview and for the Changed Overview on the Selection Panel LEDs.
Possible place for the "I" or "II": In the second line, center-aligned under the bank/preset number.

An indicator for "Split" or "Layer" is not required here. The dual mode indicator behind the preset name should be sufficient.

The "Changed" asterisk should reflect changes in both voice groups, independent from the voice group focus.
