### ISSUE TITLE
Split Point -> menu idea

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#1073]
HWUI Sound Menu ,Editmode , split Point : 
if you go into Split Point menu entry , split point can be adjusted by buttons 'C' and 'D' after you went into the submenu by pressing 'ENTER'
Inc / Dec buttons are withou use in this submenu
Menu can be left by pressing 'A'
ther are no Softbuttons at the bottom to make this behaviour clear for the user.

My recommendation / idea :

when 'Split Point' is selected overlay two softbuttons with the next half steps,
'ENTER' is not necessary
inc/dec  go to the next menu item (import.. , convert to ...)

![grafik](https://user-images.githubusercontent.com/4758563/66391199-c9d09100-e9cc-11e9-82ac-c67b0ea27282.png)

Split point      |                F#3                  |
                  
                       |       F        |   |        G        |              <-- Softbuttons

**Comment by schlenkibus** [comment]
Hi majjam,
thanks for your valuable input. I agree with you that the menu feels kinda clumsy. I will talk with Stephan about the menu on monday, maybe we can come up with some ideas about how to make the menu more self-explanatory. I will try to keep you updated on that one!

**Comment by schlenkibus** [comment]
Hi @majjam, did you close this issue because you are happy with how the current split point implementation feels?

**Comment by majjam** [comment]
Hi @schlenkibus i think it was an idea for a abandoned menu , so the was the reason.
another idea for the actual design is this as alternate menu if shift is pressed:

![grafik](https://user-images.githubusercontent.com/4758563/74769996-aa574800-528b-11ea-9cb4-ef14a5c6a46f.png)
