### ISSUE TITLE
Dual-Sound Impl: UI Changes

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1076]
- [x] VG-Select softbutton should act instantly (no highlight)
- [x] new VG Params (Level, Tune)
- [x] Voice Group Label
- [x] Rename Voice Group
- [x] Split and Layer Edit are identical now
- [x] Sound Screen -> Voices Screen -> Parameter Screen
- [x] Sound Overview Params are new VG params
- [x] Voices Screen: Mono / Unison
- [x] Parameter Screens: Mono / Unison 
- [x] Recall custom parameter screen -> (Split / Voice Group Master)
- [x] EditBuffer Name in all Sound Layouts
- [x] Replace new Preset Manager with old 
- [x] "Param" Layout -> not correct master parameters for Voice Group shown
- [x] Fix Convert 2 functionality
- [x] Layer Mode: Unison /Mono are only there once
- [x] VG Master rename module header to display "type" + vg
- [x] Split I/II -> Split I on Splitpoint parameter
- [x] Cleanup display -> Highlight == editable
- [x] cleanup menu usability -> no changes through softbuttons but encoder
- [x] Layer -> Voices -> I / II
- [x] Layer Mode Mono Layout not correct
- [x] Single Mode Mono Layout not correct
- [x] if VG II Selected -> mono layout not working correctly (wrong VG being shown)
- [x]  Load Single into Split/layer changed (also with convert single to split) (changed mod is being shown at master parameter button 95)
- [x] Master Button not assigned to Parameters
- [x] Unit Test Split Convert
- [x] Unit Test Init EditBuffer
- [x] Unit Test EditBuffer Load Presets 
- [x] Convert Sound -> install correct layout

**Comment by nonlinear-labs** [comment]
![BOLED_Voices-Mono-Unison_1 1](https://user-images.githubusercontent.com/33938408/67199344-56ce0e00-f401-11e9-9fce-9fbd9fb4c77d.png)
![Boled-Dual-Single_Mockup-1 0](https://user-images.githubusercontent.com/33938408/67199345-56ce0e00-f401-11e9-8bde-aab662d23374.png)
