### ISSUE TITLE
HWUI : Jump to parameter screen on preset loading

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#1174]
at current Master:
first scenario

1. DL enabled
2. Preset-Screen selected (by pressing Preset)
3. Inc or Dec button to select a different Preset
=> after loading new preset, preset menu view ends ,
      Oled shows parameter screen (last chosen Parameter)

-------------------------------------------------------
2nd scenario

1. DL disabled
2. Preset-Screen selected
3. Inc or Dec button to select a different Preset
4. Enter to loade selected Preset
=> after loading new preset, preset menu view ends ,
      Oled shows parameter screen (last chosen Parameter)

**Comment by schlenkibus** [comment]
Hi max,
das Verhalten ist bekannt aber ich muss über das schuldige feature noch nachdenken!
