### ISSUE TITLE
Mono + Layer

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1189]
Mono Parameters will be global (from vg I) and mono glide will be per voice group

**Comment by majjam** [comment]
Hi for my understanding :
Layer mode (and split mode, too)
It is not planned to have VG-I mono (with glide setting) and VG-II poly ?

**Comment by schlenkibus** [comment]
Your understanding is correct, for Layer mode, Unison Voices and Mono Enable, Legato and Priority are global for both Voice Groups. The remaining Unison Parameters and Mono Glide are per Voice Group (so Poly).

**Comment by majjam** [comment]
Schade ;)

**Comment by schlenkibus** [comment]
I think Stephan would be interested to know what the use-case of layered sounds with different mono settings would be. Do you have something in mind maybe it could be implemented if there was a need for that.

**Comment by majjam** [comment]
T
ok dont blame for the bad playing and recording, but to get the idea here is some short some short example of playing a layered sound: [monopoly.zip](https://github.com/nonlinear-labs-dev/C15/files/3962023/monopoly.zip)
so this is one poly-physical-piano with mono-legato-bass-sound low priority, played in two different styles

**Comment by nonlinear-labs** [comment]
Hi Majjam, thanks for your input! The current concept for the voice allocation is simple and straight-forward, and that's what I prefer for the first release of our Dual mode. Your examples can make sense sometimes, but in most cases I would recommend the Split mode to get a different sound or legato behaviour for a bass or lead voice.
In the Layer mode I expect a lot of surprises for the player when he releases a key and the mono voice is assigned to another key following the priority. To avoid this, you would have to play legato all the time.

**Comment by majjam** [comment]
Hi all,
yes you are right - the setting i mentioned is applicable in very rare situations only and usuallay one wants to clearly seperate both voices by a split point.
Therefore your plans for the voce allocation are straightforward and make sense.

On the other hand for people like me which cannot play the left hand anyhow decently i give you one more example (I know this instrument is meant for musicians)
    1st mono poly layered
    2nd mono mono layered
    3rd split 
[monoPoly-monoMono-monoSplitPoly.zip](https://github.com/nonlinear-labs-dev/C15/files/3972016/monoPoly-monoMono-monoSplitPoly.zip)

Dont get me wrong this is meant as food for thought and nothing more.
