### ISSUE TITLE
BOLED: Parameter-Screen: falsche Labels im Karussell

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1216]
Bitte wieder wie früher: Die Labels der Subparameter sollten nicht die Namen der Hauptparameter enthalten.
Beispiel: Statt "Pitch - Pitch Env - Pitch KT" sollte es heissen: "Pitch - Env C - Key Trk"

**Comment by schlenkibus** [comment]
Die [ParameterList_1.7B.ods](https://github.com/nonlinear-labs-dev/C15/blob/master/parameter-db/src/ParameterList_1.7B.ods) mit dem Original vergleichen und entsprechende Abweichungen anpassen.
