### ISSUE TITLE
Die restlichen neuen Parameter in die UI einbauen

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1253]
328 Env_A:Dec_1_Vel
330 Env_A:Dec_2_Vel
332 Env_A:Split
334 Env_B:Dec_1_Vel
336 Env_B:Dec_2_Vel
338 Env_B:Split
340 Env_C:Retr_H
346 FB_Mix:Osc    "A/B x"
348 FB_Mix:Osc_Src    "A - B"
350 FB_Mix:Comb_Src    "From x"
352 FB_Mix:SVF_Src    "From x"
354 FB_Mix:FX_Src    "From x"
389 Flanger:Tremolo
342 Echo:Send
344 Reverb:Send

362 Voice_Grp:To_FX  ->  sollten wir in den Output-Mixer unter den Key Pan verschieben.

Meine Vorschläge zu Labels und UI-Positionen sind in dieser Version der Parameter-Liste pink hinterlegt:
[ParameterList_1.7B ssc 01.ods.zip](https://github.com/nonlinear-labs-dev/C15/files/3985764/ParameterList_1.7B.ssc.01.ods.zip)

**Comment by schlenkibus** [comment]
@nonlinear-labs @MatthiasSeeber kann die hier angehängte Parameter Liste in den master branch übernommen werden oder müssen die UI positionen händisch übertragen werden?

**Comment by MatthiasSeeber** [comment]
@schlenkibus die Tabelle kann aus meiner Sicht für den Master branch übernommen werden.
Stichwort UI position - die erzeugten Playground Descriptoren besitzen momentan lediglich die Parameter und Group Labels, die inaktive CP sowie die Info Texte. Solltet ihr UI positionen benötigen, müssten die Descriptoren verändert werden.
