### ISSUE TITLE
Audio-Engine issues

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1279]
- MCs wirken nur in ihrer unteren Hälfte, darüber scheinen sie geclippt zu werden.
- Output Mixer - Drive funktioniert nicht.
- Cabinet - Mix: das Signal wird beim Aufdrehen sehr leise
- Flanger Feedback: bei Null ist das effektive Feedback 100 %
- Flanger-LFO hat kein Phase-Offset zwischen links und rechts

- Bitte für die 4 Decay-Velocities die Richtung umkehren (positiv = längeres Decay bei härterem Anschlag).

- Beim Einstellen der (Env A/B) Split-Levels ist eine sofortige Wirkung auf die Hüllkurven wünschenswert.

- Bitte testen, ob der LPC bei sehr hartem Anschlag korrekte Messages schickt, oder eventuell garnix...?

**Comment by MatthiasSeeber** [comment]
Folgendes konnte ich über das Test-Gerät feststellen:
- MCs: wirken in ihrer gesamten Range, allerdings scheinen die HW Sources vom LPC aus keine Werte mehr zu senden, wenn sie größer als 50% werden (dann kommt offenbar keine LPC-Nachricht mehr an)
- LPC bei sehr hartem Anschlag scheint (wie bei HW Sources) gar keine Nachrichten zu senden
- Drives sind getestet und funktionieren (Osc & Shaper, FB & Out Mixer, Cabinet)
- Cabinet: Wet-Pegel scheint nach wie vor zu niedrig (v.A. bei tiefen Tönen - evtl. liegt es also an den Filtern..)
- Flanger Feedback ist gefixt, genauso Flanger-LFO Phase
- Decay-Velocities: Richtung ist wie gefordert
- (Env A/B) Split Levels: haben sofortige Wirkung

**Comment by MatthiasSeeber** [comment]
Dieses Issue kann bei Erfolg zusammen mit #1314 geschlossen werden.
