### ISSUE TITLE
Velocity-Auflösung von 12 Bit (4095) auf 14 Bit (16383) erweitern

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1285]
Unsere Zeitmessung erfasst maximal 20972 Zeitschritte. Die stark nichtlineare Reziprok-Bildung erzeugt für hohe Velocities hohe Stufen pro Zeit-Increment. Hier wird die höhere Auflösung des Ergebnisses nichts bringen, aber für niedrige Velocities wird das Ergebnis signifikant genauer.

**Comment by MatthiasSeeber** [comment]
@nonlinear-labs Wenn der LPC 14 Bit Velocity Ranges beherrscht, kann dieses Issue geschlossen werden.
