### ISSUE TITLE
Neue Parameter in WebUI einbauen + Änderungen an vorhandenen Bedienelementen

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1304]
Envelope A:
- [x] "Decay 1 Velocity": kleiner horizontaler Fader unter "Decay 1"
- [x] "Decay 2 Velocity": kleiner horizontaler Fader unter "Decay 2"
- [x] "Split Levels": kleiner Knob unter "Sustain"
- [x] Die drei kleinen Fader "Level Vel", "Level KT", "Time KT" müssen nach unten verschoben werden.

Envelope B:
- [x] "Decay 1 Velocity": kleiner horizontaler Fader unter "Decay 1"
- [x] "Decay 2 Velocity": kleiner horizontaler Fader unter "Decay 2"
- [x] "Split Levels": kleiner Knob unter "Sustain"
- [x] Die drei kleinen Fader "Level Vel", "Level KT", "Time KT" müssen nach unten verschoben werden.

Feedback Mixer:
- [x] "Comb", "SV Filter" und "Effects" rücken ein Feld nach rechts
- [x] "Rev Mix" wird ein kleiner horizontaler Fader unter "Effects"
Neu:
- [x] "A/B x": grosser vertikaler Fader im ersten Feld
- [x] "A - B": kleiner horizontaler Fader (mit Punkt) unter "A/B x" 
- [x] "From II": kleiner horizontaler Fader (mit Punkt) unter "Comb"
- [x] "From II": kleiner horizontaler Fader (mit Punkt) unter "SV Filter"
- [x] "From II": kleiner horizontaler Fader (mit Punkt) unter "Effects" und "Rev Mix"

Output Mixer:
- [x] "Key Pan" wird ein kleiner horizontaler Fader unter "Level"
Neu:
- [x] "To FX x": kleiner horizontaler Fader unter "Level" und "Key Pan"

extrahiert nach: #1318 

![UI links Modifikationen](https://user-images.githubusercontent.com/33938408/71682199-34f0f000-2d8f-11ea-9329-e30914be4fc9.png)

Flanger:
- [x] "Tremolo": ein großer Knob rechts neben dem "Mix"-Fader

Echo:
- [x] "Send": ein großer Fader links neben dem "Mix"-Fader

Reverb:
- [x] "Send": ein großer Fader links neben dem "Mix"-Fader

Neue Gruppe "Voices":
- [x] Eine Zusammenfassung der neuen "Mono"-Gruppe und der bestehenden "Unison"-Gruppe.
  Beide sind als Unter-Überschriften vertreten.

"Mono"-Gruppe:
- [x] "Enable": Switch (On/Off)
- [x] "Priority": Switch (Last, Highest, Lowest)
- [x] "Legato": Switch (On/Off)
- [x] "Glide( Time)": kleiner horizontaler Fader

![UI rechts Modifikationen](https://user-images.githubusercontent.com/33938408/71693239-3e3c8580-2dac-11ea-84cd-23a25508b7c9.png)

**Comment by nonlinear-labs** [comment]
Hier noch eine von mir upgedatete ParameterList, wo meine Korrekturen und Ergänzungen in den WebUI-Spalten hellgrün markiert sind:

[ParameterList_1.7B ssc #1304.ods.zip](https://github.com/nonlinear-labs-dev/C15/files/4018895/ParameterList_1.7B.ssc.1304.ods.zip)

**Comment by schlenkibus** [comment]
> Hier noch eine von mir upgedatete ParameterList, wo meine Korrekturen und Ergänzungen in den WebUI-Spalten hellgrün markiert sind:
> 
> [ParameterList_1.7B ssc #1304.ods.zip](https://github.com/nonlinear-labs-dev/C15/files/4018895/ParameterList_1.7B.ssc.1304.ods.zip)

Die ZIP mit der Tabelle kommt bei mir auf dem Rechner mit 22byte an und ist keine korrekte zip Datei. Wenn das hier nicht geht kannst du die Tabelle auch per e-mail senden.

**Comment by nonlinear-labs** [comment]
Neuer Versuch:
[ParameterList_1.7B ssc #1304.ods.zip](https://github.com/nonlinear-labs-dev/C15/files/4022128/ParameterList_1.7B.ssc.1304.ods.zip)

**Comment by nonlinear-labs** [comment]
Hab noch einen Fehler korrigiert:
[ParameterList_1.7B ssc #1304 b.ods.zip](https://github.com/nonlinear-labs-dev/C15/files/4022147/ParameterList_1.7B.ssc.1304.b.ods.zip)
