### ISSUE TITLE
WebUI: finalize Dynamic Labels for parameters with 'x'

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1318]
- [x] Bei Dual-Sounds wird das "x" in den Labels in Part I durch "II" ersetzt, in Part II durch "I".

- [x] Bei Single-Sounds bleibt das "x" und der Parameter wird inaktiv dargestellt (grau?). Ggf. entfällt dabei das Label.

extrahiert aus #1304 

@nonlinear-labs soll das noch in den NAMM Milestone?

**Comment by MatthiasSeeber** [comment]
nur zur Sicherheit: der hier als 'x' bezeichnete regEx ist in der ParameterList (und somit auch in den Headern) folgendermaßen gekennzeichnet: ein String aus drei Zeichen:
- At-Symbol (kann ich hier nicht einfach so einfügen)
- V
- G
