### ISSUE TITLE
Feedback-Mixer - Drive: Wir müssen den Bereich um 20 dB nach unten erweitern

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1319]
Der Shaper im Ausgang des Feedback Mixers hat - zur guten Sättigung typischer Feedbacksignale - einen 10 mal so grossen Drive-Faktor als der Shaper im Output Mixer. Eigentlich ist es der Faktor 2.5 im Feedback Mixer im Vergleich zu 0.25 im Output Mixer.

Das wird bei der neuen Layer-Kopplung zum Problem. Die Signale aus der anderen Voice-Group werden zu stark verzerrt, wenn man die FB-Mixer-Kanäle auf mehr als 0.1 einstellt.

Wir sollten deshalb den Faktor 10 rausnehmen und den Bereich des Drive-Reglers auf 0 ... 70 dB erweitern. Aus den bisherigen "0 dB" wird in Zukunft "20 dB". Damit hat der User auch Klarheit über die wirkliche Gain-Struktur.

Für alte Presets muss beim Import der Drive folgendermaßen konvertiert werden:
alt 0 ... 50 dB -> neu 20 ... 70 dB
alte Control Position: 0.0 ... 1.0 -> neue Control Position: 0.2857 ... 1.0 = 2/7 ... 7/7

**Comment by MatthiasSeeber** [comment]
Mit dem PR hat die Audio-Engine den neuen Drive-Bereich.
Die Konvertierungen für Presets sowie neue Parameter-Eigenschaften müssen allerdings im Playground berücksichtigt werden. Die neuen Eigenschaften sind in der ParameterList grün hinterlegt.
