### ISSUE TITLE
BOLED: schrittweise Preset- und Bankwechsel führen zum Vor- und Zurückspringen

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1321]
Bänke werden oft übersprungen, Presetwechsel können zu wilden Irrfahrten werden...

**Comment by hhoegelo** [comment]
Es gibt offenbar 2 Probleme:
- Performance Probleme koennen dazu fuehren, dass Button-Up-Events solange verzoegert werden, bis das "ButtonRepeat" objekt meint, aktiv werden zu muessen. Diese Problem ist vermutlich hoffentlich eventuell vielleicht schon geloest worden.
- Ein Loop in der Kommunikation zwischen playground und WebUI fuehrt zu Preset-Huepfern: Die Klasse world.maps.presets.bank.Updater ruft in update() in die PresetList::selectPreset(). Dort wird wiederum getNonMaps().getServerProxy().selectPreset(uuid); aufgerufen. Ich habe ungetesteten Patch angehaengt, der zeigen soll, wie ich mir eine Loesung vorstellen kann.

[untested.patch.txt](https://github.com/nonlinear-labs-dev/C15/files/4049393/untested.patch.txt)

**Comment by MatthiasSeeber** [comment]
Problem besteht auch im future-master (commit e30f454):
- wie gehabt, wenn WebUI verbunden ist - und auch viele Single/Dual Wechsel

**Comment by schlenkibus** [comment]
auch ohne verbundene WebUI, ButtonRepeat ausbauen..
