### ISSUE TITLE
Unison-Detune lässt sich nicht über MCs steuern.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1340]
(Beispiel: Fuxis Swarms)
Über den Parameter lässt sich das Detune wirksam einstellen. Der MC (bzw. eine Hardware Source) hat in der Audio-Engine keinen Einfluss.

**Comment by MatthiasSeeber** [comment]
In der Preset Message besitzt Unison Detune (unabhängig vom Preset) stets ModSource = 0 und ModAmount = 0.

**Comment by MatthiasSeeber** [comment]
Nach PR #1343 ist die Parameter Range vom Feedback Mixer Drive zwar korrekt, allerdings stimmt der Default Wert noch nicht. Momentan ist er bei 40.0 dB (4/7), sollte aber auf 20.0 dB stehen (2/7)

**Comment by schlenkibus** [comment]
Can not reproduce on 'Frankenstein 1.7' with Version: {"master", 2850}

**Comment by schlenkibus** [comment]
> Nach PR #1343 ist die Parameter Range vom Feedback Mixer Drive zwar korrekt, allerdings stimmt der Default Wert noch nicht. Momentan ist er bei 40.0 dB (4/7), sollte aber auf 20.0 dB stehen (2/7)

@MatthiasSeeber extracted your comment into own issue #1346
