### ISSUE TITLE
MC Smoothing Times Parameter Descriptions

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1356]
For MC Smoothing Times A-D the info text is: [not implemented in this version]
For MC E & F the text is still empty

**Comment by MatthiasSeeber** [comment]
@schlenkibus the ParameterList spreadsheet from PR #1457 as well as the associated parameter-db header files do contain Info texts for the MC smoothing times. However, they do not seem to be implemented on Playground-side, as either "[not implemented in this version]" (MC A..D) or an empty string (MC E..F) will be shown
