### ISSUE TITLE
Gap Filter: Bei Mix = 100% und Balance = -100% kommt statt dem Tiefpass der Hochpass durch.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1381]
Mix = 100 %, Balance = -100%, Center = 120 st : es ist nur leises Hochpass-Zirpen zu hören.
Wenn man Center runterregelt, hört man die gleiche Filterung wie bei Balance = 100%. Es ist also der reine Hochpass zu hören.

Vielleicht wird von Balance der Betrag gebildet (Spiegelung an der Null).

**Comment by MatthiasSeeber** [comment]
fixed by #1392
