### ISSUE TITLE
WebUI: Chrome Touch Events

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1384]
The Touch event flags was removed in chrome 78
start chrome on windows like this:
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --touch-events
to ensure the webui works properly

**Comment by hhoegelo** [comment]
https://touchittechnologies.com/touch-events-api-chrome-browser/

**Comment by schlenkibus** [comment]
@hhoegelo This flag was removed in chrome 78 https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/43EvDVGan6E
I will look at this in more detail later

**Comment by schlenkibus** [comment]
Using 'Vanilla' Chrome:
open DevTools -> Sensors -> set 'Touch' to Force enabled
the swiping and pinching works again

**Comment by schlenkibus** [comment]
When opening an chrome intance with the flag and then open a 'vanilla' chrome the bug seem to have perished, but starting only vanilla chrome leads to the same bug. Don't get confused while debugging -> have only vanilla chrome open

**Comment by hhoegelo** [comment]
@nonlinear-labs I re-implemented the pointer bindings: previously, we used to bind to mouse and touch API, now that there is a 'pointer' api, we use this instead. I tested with:
- Chrome 79 @ Linux
- Firefox 73 @ Linux
- Chrome 80 @ MacOS X
- Safari 13 @ MacOS X
- Chrome 80 @ Android 9 (Google Pixel)
- Chrome 80 @ Android 4.4 (Samsung Tablet)
