### ISSUE TITLE
Bei "Load to Part" eines Single-Presets sollten wir sein Master Vol/Tune in die Vol/Tune des Parts schreiben

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1387]
Also das Gleiche wie beim Konvertieren eines Single Sounds in einen Dual Sound. 

Beispiel: 
- Ein Single-Preset mit MASTER Tune = +12 st wird in einen Split-Sound konvertiert. Damit haben beide Parts ein PART Tune von +12 st (das ist korrekt so) und der MASTER Tune steht auf 0 st.
- Ein Preset, dessen MASTER Tune auf 0 st steht wird in Part II geladen. In der momentanen Version bleibt der PART Tune bei +12 st und damit klingt Part II eine Oktave zu hoch. Damit das nicht passiert, muss der MASTER Tune des zu ladenden Presets in den PART Tune geschrieben werden.

Achtung: Beim "Load to Part" eines DUAL-Presets sollte die Summe aus PART-Volume/Tune des zu ladenden Parts und MASTER-Volume/Tune des Quell-Presets in den Ziel-Part übernommen werden. Also das Gleiche wie beim Konvertieren in einen Single-Sound.

**Comment by nonlinear-labs** [comment]
Load Single Preset to Part:
Leider wird jetzt Master Vol/Tune des hineingeladenen Presets auf beide Parts übertragen. Es sollte aber nur in den Part, der beim Laden überschrieben wird, kopiert werden.

**Comment by MatthiasSeeber** [comment]
Die Übertragung auf den jeweiligen Part ist korrekt, allerdings erscheint mir das "addieren" der Master- bzw. Part Volumes nicht korrekt. Das bloße Addieren der Control Positions ("CP") führt zu falschen Pegeln. Ein Beispiel: Part Vol: (CP = 0.5 ; DV: 0.0dB), Master Vol: (CP = 0.5 ; DV: 0.0dB) führt zum Resultat: (CP = 0.5 + 0.5 = 1.0 ; DV = 12.0dB)  ("DV" heißt Display Value)
