### ISSUE TITLE
Load Single Preset into Single Sound: Global Parameters are not loaded properly

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1389]
Macro controls and hardware positions are not loaded on single preset loading. Testcases to reproduce can be found  inside the 1389 Branch.

**Comment by MatthiasSeeber** [comment]
Ein reproduzierbarer Ablauf wäre wie folgt:
Der Branch engine-recall-fixes hat das Problem noch nicht beinhaltet. Mit dem Branch hatte ich Presets mit HW Modulationen angelegt und als Bänke gespeichert. Dann (nach PR #1390) mit neuem Master und Neubau der Applikationen besitzen die angelegten Bänke keine HW-Amounts mehr (alles null)
