### ISSUE TITLE
FB Mixer - Drive wird falsch konvertiert

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1399]
0   dB  ->  34.3 dB  (statt 20 dB)
0.5 dB  ->  34.6 dB  (statt 20.5 dB)
2   dB  ->  35.7 dB  (statt 22 dB)
5   dB  ->  37.9 dB  (statt 25 dB)
6   dB  ->  38.6 dB  (statt 26 dB)

Die Basis ist also um 14.3 dB zu hoch, die Steigung dann nur 5/7 der notwendigen Steigung.
Das entsteht wahrscheinlich so:
Neuer_Wert_in_dB = 20 + (2/7 + 5/7 * Alte_Pos) * 50;

Die Konvertierung sollte aber sein:
Neue_Pos = 2/7 + 5/7 * Alte_Pos;
Neuer_Wert in dB = (2/7 + 5/7 * Alte_Pos) * 70;

Test:
Alte_Pos: 0.0 ... 1.0  =>  Neue_Pos: 0.286 ... 1.0
Alter_Wert_in_dB: 0 ... 50  =>  Neue_Wert_in_dB: 20 ... 70

**Comment by schlenkibus** [comment]
Current conversion code looks like this: 
new_cp = std::min((5.0/7.0) * old_cp + (2.0/7.0) , 1.0);
@hhoegelo am i missing something here?

**Comment by nonlinear-labs** [comment]
Irgendwo steht noch eine alte 50 statt der neuen 70 (dB). 
Und der Versatz um 20 dB wird anscheinend NACH der Conversion noch draufgerechnet. Er ist aber in der Conversion-Formel schon drin.
