### ISSUE TITLE
Hide/Remove Compare Presets / Preset-EditBuffer temporarily

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1413]
"compare to.." leads to crashes of playground. Remove all references to compare and rewrite compare feature after NAMM

**Comment by majjam** [comment]
Seit dem ich von Euch die Möglichkeit bekommen habe für einzelene Parameter-Settings das Preset-Default zu laden (shift-Default), benutze ich die Compare funktion nur noch sehr selten.
(eine der besten pseudo Undo-Funktionen überhaupt)

Ich finde natürlich immer, dass "mehr Features = mehr Möglichkeiten" sind,  aber  eben auch "mehr Fehlerquellen" .

meine persönlichen 50 cent 
Gruß Max
