### ISSUE TITLE
Playground sends reserved setting ID 35 to LPC, causing malfunction with new LPC features

### ISSUE THREAD

**Issue by KlausStrohhaecker** [nonlinear-labs-dev/C15#1436]
For some reason, the playground seems to send at least one hitherto reserved Setting ID to the LPC when it sends the EditBuffer and the Settings.
The offending ID is 35 (with data value == 0) , highest official (as documented in LPC code) ID used was, up to now, "34 : Preset Glitch Suppression".

I've originally used unassigned ID's above 34 for the new LPC Settings functions like "Muting Control"(35) and "Send Raw Sensor Values on/off"(36), and more IDs will likely be added (for Pedals). For a quick fix, I will now move any new IDs to 0xFF01 and above, to avoid conflicts.

Anyway, please check what Setting ID 35 (and any other above 34) is used for, from playground side.

**Comment by schlenkibus** [comment]
@KlausStrohhaecker
Setting ID's are defined in `playground/src/proxies/lpc/LPCProxy.cpp`
ID 35 has been defined as `BENDER_RAMP_BYPASS` since 08.08.2019

The setting is not persistent and can be toggled from the developer options in the WebUI.

**Comment by KlausStrohhaecker** [comment]
OK, noted.

In the future, LPC and PG should use a shared sub-include at a global location (to be determined) for these and the many other definitions(!) shared betweem LPC code and others.

Something like "lpc_message_ids.inc", containing only #define assignment lines like
"#define LPC__SETTING_ID_VELOCITY_CURVE  (11)" or
"#define LPC__REQUEST_ID_SW_VERSION  (0x0000)"
which then can be used universally (LPC code is plain C).

See "C15\realtime-system\nl_lib\nl_lib_com\spibb\nl_bb_msg.h" in the branch " Milestone-1.7-LPC-NEWPEDALS ", all those definitions need to have their counterpart in the PG and/or other software (bridge?)

**Comment by schlenkibus** [comment]
@KlausStrohhaecker is this issue still relevant?
