### ISSUE TITLE
Switching from "select only" to "direct load" does NOT direct load the currently selected preset

### ISSUE THREAD

**Issue by KlausStrohhaecker** [nonlinear-labs-dev/C15#1437]
Switching from "select only" to "direct load" does NOT direct load the currently selected (under cursor) preset. Rather, an additional press of "Enter" is required, or a change of the preset via Encoder/+/-
Doesn't look consistent to me.

Using TopCover, the issue seems circumvented by the fact that switching between "select only" and "direct load" can only happen after the load/enter button ("Funct") has been pressed anyway, long enough.

**Comment by hhoegelo** [comment]
As far as I remember this is the intended behavior, @nonlinear-labs ?

**Comment by nonlinear-labs** [comment]
Wir mussten die Direct-Load-Funktionalität etwas ändern, weil der Softbutton bei Dual-Sounds nun drei Optionen (Load to I(II), Select only, Direct Load) anbietet. Man muss also zwischendurch auf "Direct Load" kommen können, ohne dabei ein Preset zu laden. Siehe auch #1470
