### ISSUE TITLE
Pressing load/enter ("Funct") on TopCover does not re-load an un-changed preset in "direct load" mode

### ISSUE THREAD

**Issue by KlausStrohhaecker** [nonlinear-labs-dev/C15#1438]
Pressing load/enter ("Funct") on TopCover does not re-load an un-changed preset in "direct load" mode. Whereas it does when this operation is performed on the panel unit.
The reload may seem redundant but it is always better to apply it, for robustness.

**Comment by schlenkibus** [comment]
While adding the 'load to Part' feature a lot of existing features had to be touched, maybe we should rework all preset loading ui's and make them consistent. We will have to consider if we add the 'load to Part' feature to the Base Unit and how this could be done.

**Comment by schlenkibus** [comment]
@KlausStrohhaecker the invalid label is used for issues that seem invalid, use bug or feature respectively.
