### ISSUE TITLE
Missing Parameter Infos

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1463]
Info Texts missing:
OSC_A: Reset (393)
OSC_B: Reset (394)
FB_Mix: osc (346), osc_src (348), comb_src (350), fx_src (352)
Out_Mix: to_fx (362)
Flanger: Tremolo (389)
Echo: Send (342)
Reverb: Send (344)
ENV_C: Retrig_H (340)
ENV_A: elevate (332), dec2_vel (330), dec1_vel (328)
ENV_B: elevate (338), dec2_vel (336), dec1_vel(334)
VoiceGroup: Volume (358), Tune (360)
Mono: 364, 365, 366, 367 (All)

HWUI Button Position missing:
OSC A/B Reset (393, 394)

**Comment by MatthiasSeeber** [comment]
A thorough Review/Evaluation of all Properties of all Parameters (including Info Texts, but also Labels, Units, Resolutions, Default Values, etc) is planned and in preparation, so this issue here fits right within that.
