### ISSUE TITLE
BOLED: Preset Screen: Menü über dem Softbutton 4 mit drei (oder zwei) Einträgen: "Load to I(II)", "Select only", "Direct Load"

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1470]
Bei Single-Sounds sind es nur diese zwei Einträge: "Select only", "Direct Load".

Ähnlich wie im Store-Screen das Menü "Append", "Overwrite", "Insert".

**Comment by schlenkibus** [comment]
Bitte Bestätigen: Toggle mit Softbutton 4 und Enter zum bestätigen und auswählen des Ladeverhaltens? 

Beim einstellen von Direct Load soll das aktuell selektierte und ungeladene Preset geladen werden?
@nonlinear-labs

**Comment by nonlinear-labs** [comment]
Softbutton 4 wählt nur die Lade-Methode vor:
"Load to I":  Das danach ausgewählte Preset wird mit Enter in den Part geladen.
"Select only": Das danach ausgewählte Preset wird mit Enter in den Sound geladen.
"Direct Load": Das nächste ausgewählte Preset wird sofort in den Sound geladen. Das aktuell ausgewählte Preset kann mit Enter geladen werden.
