### ISSUE TITLE
bbbb compile issue : libs not found

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#1472]
on restructured Master with DEV_PC=On (otherwise gtkmm not used for bbbb)
bbbb stops compiling through problems with finding headers within gtkmm.h
Compile output 
**/usr/include/gtkmm-3.0/gtkmm.h:90:10: fatal error: gdkmm/dragcontext.h: Datei oder Verzeichnis nicht gefunden**

Addtionally miminum cmake version should be 3.13 as the command **trarget_link_directories** is unknown at 3.12 and beneath

**Comment by hhoegelo** [comment]
@majjam I fixed the trarget_link_directories issue (by using link_directories instead), but I could not reproduce the gdkmm issue. The bbbb compiles for my dev pc without any issues. Is "gdkmm-3.0" installed on your system? Normally pkg_check_modules(REQUIRED ${name}) in Ln 31 should have told you, if the lib is missing. Which OS do your use for building?

**Comment by majjam** [comment]
Hi tested it with two ubuntu derviates (linux Mint Tina and Tricia)
**Linux q-Pc 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux**

gtkmm and gdkmm is installed (both 3.22). Files are at the usual locations

 - deleted CMakefiles folder within bbbb folder and started cmake Iget follwing messages :
command : "cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../build -DDEV_PC=On -DPROFILING=Off . "

C15 firmware version: C15--master--2020-01-30T15-03-33+01-00--b92cc3c6
Installing into: /home/q/Desktop/nonlin/build/C15--master--2020-01-30T15-03-33+01-00--b92cc3c6
CMake Warning at projects/parameter-db/CMakeLists.txt:11 (message):
  
  /home/q/Desktop/nonlin/C15/projects/parameter-db/src/ParameterList_1.7B.ods
  is newer than the generated header:
  /home/q/Desktop/nonlin/C15/projects/parameter-db/generated/parameter_list.h!
  Please regenerate the headers from the spritesheet!


-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Checking for module 'giomm-2.4'
--   Found giomm-2.4, version 2.56.0
-- Checking for module 'libsoup-2.4'
--   Found libsoup-2.4, version 2.62.1
-- Checking for module '**gtkmm-3.0'**
--   Found gtkmm-3.0, version 3.22.2
-- Checking for module '**gdkmm-3.0**'
--   Found gdkmm-3.0, version 3.22.2
-- Checking for module 'libpng'
--   Found libpng, version 1.6.34
-- Configuring done
-- Generating done
-- Build files have been written to: /home/q/Desktop/nonlin/C15


**pkg-config --libs gdkmm-3.0**
-lgdkmm-3.0 -lgiomm-2.4 -lpangomm-1.4 -lglibmm-2.4 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lgio-2.0 -lcairomm-1.0 -lcairo -lsigc-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0

**pkg-config --cflags gdkmm-3.0**
-pthread -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include

**Comment by majjam** [comment]
btw compiling other release without the restructured project path is working.

**Comment by hhoegelo** [comment]
@majjam Thanks for reporting, I could finally find the bug(s) in the CMakeLists - the fixes are pushed to master.
