### ISSUE TITLE
reflect WEBUI Part selection to HWUI [feature request]

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#1477]
For Split and Layer mode the part selection of WEBUI should be mirrored to the HWUI.

Use case :
One uses WEBUI for loading presets into part I/II but edits the parameters with the panel unit.
If the part selection is not equal it could end up irritating a user.

**Comment by schlenkibus** [comment]
We deliberately choose to not make the current selected VoiceGroup global state. This enables you to open multiple WebUis with different Voice Group focuses. I understand that this might lead to confusion but in the long term enables power users to work with the instrument more efficiently. 

@nonlinear-labs what are your thoughts?

**Comment by majjam** [comment]
already had similar thougths  at the moment this happends:
    1. webui part II selected
    2. hwui part I selected
    3. webui selects Parameter "tilt"->[II]
=> hwui follows webui to show "tilt" but [I]

But what you wrote about power users is correct.
My first idea when i started to write the ticket was to have two check fields (options).
    1 HWUI follows WEBUIs part selection
    2 WEBUI follows HWUIs part selection
if boxes 1 and 2 are false, i'ts completely free and all interfaces have their own state.
if boxes 1 and 2 are true,  HWUI and WEBUI are locked to each other
plus two different mixed modes where one follows the other but not vice versia

But I didnt had in mind to use two WEBUIs at the same time, which makes sense
**So perhaps to have one option to lock the states to each other -or not- could come in handy.**

**Comment by schlenkibus** [comment]
Feature is implemented in master and can be enabled/disabled as a system setting (Sync Parts across UIs)
