### ISSUE TITLE
Build System : bbb, epc target not built

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#1489]
At Master : All targets are build but **not BBB EPC** and **update** 

cmake -DDEV_PC=On -DBUILD_AUDIOENGINE=On -DBUILD_BBBB=On -DBUILD_PLAYGROUND=On -DBUILD_ONLINEHELP=On -DBUILD_TEXT2SOLED=On -DBUILD_TESTING=On **-DBUILD_BBB=On** **-DBUILD_EPC=On** -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../build .

"make"

Output :
**Docker group id is 133**

-- Configuring done
-- Generating done
-- Build files have been written to: /home/q/C15
[  1%] Built target nltools
[  8%] Built target audio-engine
[ 89%] Built target playground-lib
[ 94%] Built target playground-test
[ 94%] Built target playground
[ 94%] Unpack gwt
[ 94%] Built target NonMaps
[ 94%] Built target touch-bbb-cmakelists
[ 98%] Built target bbbb
[100%] Built target text2soled

user is within group **docker**
Version docker-ce **5:19.03.6~3-0~ubuntu-bionic**
systemctl status **active (running)**

Old deprecated docker repository is working fine.

Any ideas ?

**Comment by hhoegelo** [comment]
The custom targets defined in the build_tools folder are meant to be called explicitly. 
for example 

```
add_custom_target(epc-install-medium DEPENDS .nonlinux-install-medium)
```
can be triggered by

```
make epc-install-medium
```

whereas

```
add_custom_target(NonMaps ALL SOURCES ${OUTFILE})
```

is automatically added to the 'ALL' target, thus implicitly built by

```
make
```

**Comment by hhoegelo** [comment]
@majjam If the comment above answers your question and no actual task arises, please close the issue. If I misunderstood your request and there is something to do for me, please clarify the issue.

**Comment by majjam** [comment]
thanks for the explanation 
from the readme i expected -DBUILD_EPC=On to do a "make epc-install-medium"
