### ISSUE TITLE
Mono: mehr Legato-Optionen und Korrektur für Note-Off-Verhalten (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1508]
Envelopes sollten immer erst stoppen, wenn *alle* Tasten losgelassen wurden.

Zwei Flags für Legato:

"Envelopes not triggered at Legato"-Flag (Legato on Envelopes):
- off: Envelopes starten auch bei Legatospiel (-> jeweils neue Velocity)
- on: Envelopes starten bei Legatospiel nicht (-> alte Velocity bleibt weiter wirksam)

"Glide only at Legato"-Flag (Legato on Glide):
- off: Glide-Rampe bei allen Pitch-Wechseln
- on: Glide-Rampe nur bei gebundenen Pitch-Wechseln

Der "Legato"-Parameter bekommt vier statt zwei Werte:
1) "No Effect" ("None", "Not Applied", "No Influence")
2) "On Envelopes" ("Env", "Envelopes", "On Env")
3) "On Glide" ("Glide")
4) "On Env & Glide" ("Env+Glide", "Env & Glide") = Default

Im Parameter-Karussell sollte "Legato" nach unten rücken.

**Comment by hhoegelo** [comment]
@schlenkibus , @nonlinear-labs Is there anything to do? Can we maybe make sub tasks or check lists?
