### ISSUE TITLE
gettimefromepc.service - obsolete?

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#1511]
After an update to the current Master, do we really need the **gettimefromepc.service** 
`/etc/systemd/system/gettimefromepc.service` it's trying to call `/nonlinear/scripts/time.sh` which is now located under `/usr/C15/scripts/`
If we do not need the time on the BBB, we could kick the service altogether.

Redirecting the service to the script, would also mean, that the script itself should be changed, since it is relying on getting the time from the ePC via sshpass (currently not on the BBB).

**Comment by hhoegelo** [comment]
I already removed it on master
