### ISSUE TITLE
BOLED: Preset Screen: Bank selektieren, Edit-Button drücken: Das Menü erscheint mit Verzögerung.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1512]

**Comment by schlenkibus** [comment]
What to fix: `USBStickAvailableView::usbIsReady()` (blocking -> calls ssh to bbb) is called from inside buildMenu
Instead: Let the bbbb send messages to indicate whether or not the usb stick is available.
