### ISSUE TITLE
Gelegentliche Audio-Glitches, wahrscheinlich durch Buffer-Underrun.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1513]
Die kurzen "Blips" innerhalb von Tönen treten alle 20-40 Sekunden auf.
Bitte entspechende Logs erzeugen und auswerten.
Wo können wir noch etwas optimieren?

**Comment by hhoegelo** [comment]
@MatthiasSeeber 
I can't see buffer underruns in the log, but I found:

Info:  recall single voice reset
Info:  recall single voice reset
Warning:  keyUp(pos: 23 ) failed!
Info:  recall single voice reset
Info:  recall single voice reset

**Comment by MatthiasSeeber** [comment]
Hm, failed keyUps may arise in certain scenarios like when in Mono Mode. There is a Log for that, but this isn't really considered an error and should not raise performance issues. I shall disable the warning shortly.
