### ISSUE TITLE
Friendlier OLED Messages

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#1517]
The initial message could be friendlier than just 'initializing...'

How about Random Fortune Cookie Notes or Wise Quotes?
Or custom preset messages depending on the geographical location of the User?
 
Or simply something like "Welcome, those who love to play keys!" would do just fine!

**Comment by hhoegelo** [comment]
@nonlinear-labs 
How about:

- Startup
 - Soled: "Starting C15."
 - Boled: "Welcome, those who love to play keys!"
- Shutdown:
 - Soled: "Shutting down C15."
 - Boled: "Bye Bye, those who love to play keys!"

**Comment by AntonSchmied** [comment]
I like it! However I would suggest the Boled just shows "Bye, Bye!" on shut down. I feel it's a bit to much with "the keys".

**Comment by nonlinear-labs** [comment]
I agree with Anton.
