### ISSUE TITLE
BOLED Preset Screen: neues Typ/Part-Icon, Part-Selektion, Direct Load auch für "Load to Part" (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1559]
- [x] Wenn ein Single-Preset geladen ist, sieht der "Direct Load"-Button wieder aus wie früher.

- [x] Wenn ein Dual-Preset geladen ist, wird links oben das Typ/Part-Icon eingeblendet. Ggf auch das Part-Mute-Symbol.

- [x] Bei Dual-Presets wird das "Direct Load"-Buttonsymbol nach oben geschoben und verkürzt. An seiner Stelle sitzt nun das "To Part"-Buttonsymbol. "To Part" wird durch kurzes Drücken von Softbutton 4 ein- und ausgeschaltet, "Direct Load" durch langes Drücken.

- [x] Bei Dual-Presets wird das "Bank"-Buttonsymbol nach oben geschoben und verkürzt. An seiner Stelle sitzt nun das "I / II"-Buttonsymbol. "I / II" wird durch kurzes Drücken von Softbutton 4 getoggelt, der "Bank"-Focus durch langes Drücken ein- und ausgeschaltet.

- [x] Wenn "Edit" oder "Store" aktiviert wird, sieht der Screen bei Dual-Presets genauso aus wie bei Single-Presets. D.h. das Typ/Part-Icon und der "I / II"-Button werden verborgen und der "Bank"-Button sitzt unten.

![Preset Part DL 01](https://user-images.githubusercontent.com/33938408/76712370-85ce7e80-6718-11ea-87c7-5fb66578e6be.png)

**Comment by schlenkibus** [comment]
@nonlinear-labs die ui habe ich implementiert . Habe aber noch eine frage bezueglich des Verhaltens bei aktiviertem direct load und load to part. Was soll passieren wenn ein Dual Preset selektiert wird? Wird immer Part I in den aktiven Part geladen? 

Als vergleich: Beim manuellen laden via enter wird ein overlay zwischengeschoben in dem der user auswaehlen muss welcher part des presets geladen wird.

**Comment by nonlinear-labs** [comment]
@schlenkibus  Bei Direct Load würde ich genauso das Overlay dazwischen schieben. Der Geschwindigkeits-Vorteil von Direct Load kommt damit nur beim Laden aus Single Sounds zum Tragen. Das ist aber auch der Haupt-Anwendungsfall: das Suchen nach einer passenden Komponente für das Layer.

**Comment by nonlinear-labs** [comment]
Neue Lösung, die einen zwischengeschalteten Part-Auswahl-Screen vermeidet:

- [ ] Wenn ein Dual-Preset im Editbuffer ist und "To Part" an ist, wird ein Overlay mit folgendem Verhalten aktiviert:
- Auch bei aktivem "Direct Load" wird nur ein (nicht gefüllter) Selektions-Rahmen über die Quell-Presets gelegt.
- Bei "Direct Load"=On wird mit der Selektion sofort eine Lade-Aktion+Animation ausgeführt, bei "Direct Load"=Off wird sie erst mit Enter ausgeführt.
- Dual-Presets bekommen ein quadratisches Typ/Part-Icon an das Ende der Zeile gesetzt (die kleinen Layer/Split-Symbole entfallen. Bei nicht selektierten Presets sind beide Teilflächen des Icons dunkel.
- Wenn ein Dual-Preset als Quelle ausgewählt wird, wird dabei zuerst Part I selektiert, im nächsten Schritt dann Part II. Der selektierte Part wird im Typ/Part-Icon als helle Fläche sichtbar gemacht.

Diese Lösung können wir auch in der Preset-Bauchbinde der WebUI umsetzen. Bei direktem Klick auf ein Dual-Preset ist aber weiterhin ein dazwischengeschalteter Dialog notwendig, mit zwei Buttons zur Auswahl von Part I oder II (+ "Cancel").
