### ISSUE TITLE
WebUI: Preset-Bauchbinde: Statt dem Menü bitte einen "Direct Load"-Button (single) bzw. einen "Direct Load"- und einen "To Part"-Button (dual).

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1565]
Das Menü hat sowieso nicht funktioniert (war buggy) ;-)

Im Dual-Mode sollte das Layout vergleichbar zum BOLED sein: "Direct Load" über "To Part".

**Comment by hhoegelo** [comment]
@nonlinear-labs We (@schlenkibus and @hhoegelo ) would like to discuss this feature in a skype meeting first.
