### ISSUE TITLE
Wenn man die Osc-Phase über einen MC steuert, passiert nix. Beim Editieren des Parameters hört man eine Wirkung

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1567]
Beispiel: Gegenläufige Sägezähne zur Erzeugung einer Pulswelle (und PWM). Wenn man die Phase(n) am Parameterscreen editiert, verändert sich die Klangfarbe. Wenn man ein Pedal über einen MC anschliesst, bewegt sich der Parameter im Screen, aber im Audio verändert sich nichts.

**Comment by MatthiasSeeber** [comment]
Habe den Bug im aktuellen Master getestet und konnte beide Phasen (A, B) über HW Source modulieren.. Mit welcher Version ist die PWM über Macros buggy?

**Comment by nonlinear-labs** [comment]
Im Master 56c36706b nicht mehr reproduzierbar. Deshalb schliesse ich es (erstmal ;-) )
