### ISSUE TITLE
WebUI: Sound-Tab für Layer-Mode: Mute-Buttons für beide Parts (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1572]
Die Buttons können an und aus getoggelt werden. Sie lösen sich gegenseitig aus, sodass nie beide gleichzeitig an sind.

![Mute-Button-A_1 0](https://user-images.githubusercontent.com/33938408/76806631-42d8dd80-67e2-11ea-8de0-77fa7880e24a.png)

![Mute-Button-B_1 0](https://user-images.githubusercontent.com/33938408/76806634-440a0a80-67e2-11ea-9f28-c99da2fd93f2.png)

(Im Mockup fehlen noch die neuen Typ/Part-Icons)

**Comment by hhoegelo** [comment]
@nonlinear-labs  Justus konnte kein Mute-Symbol in der Wolke finden. Kannst Du Tino bitten, eines zu liefern?
