### ISSUE TITLE
BOLED: Sound-Edit-Menü: es fehlen noch die "Enter"-Symbole am Ende der Befehls-Zeilen.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1574]

**Comment by schlenkibus** [comment]
Folgende verschiedene Zeilen-Typen haben wir im Sound-Edit:
Aktionen: 
- Convert
- Init

Editoren mit Aktion:
- Randomize

Editor ohne Aktion:
- Part Label

Welcher Zeilentyp soll ein Enter bekommen? Und soll zb Randomize mit `...` gekennzeichnet werden (Wie im Setup?)
