### ISSUE TITLE
Slider "Fade From II" und Splitpoint II von rechts fuellen 

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1586]
gillt fuer webui und boled

**Comment by MatthiasSeeber** [comment]
Frage: wäre das nicht auch denkbar für "Fade Range II"? (die Range wirkt in II ebenfalls invertiert)

**Comment by schlenkibus** [comment]
@nonlinear-labs siehe matthias kommentar

**Comment by MatthiasSeeber** [comment]
Ich glaube, ich ziehe die Frage zurück. Es würde wahrscheinlich eher verwirren als alles andere.
