### ISSUE TITLE
WebUI: Oscillator A/B "Phase Reset" - Bedienung in der Bauchbinde erforder extrem langen Mausweg.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1589]
Sollte ähnlich wie in BOLED mit dem Encoder schon mit kleinen Rechts- und Links-Bewegungen an- und ausgeschaltet werden.

Bitte mit schaltbaren HW-Amounts vereinheitlichen.

**Comment by MatthiasSeeber** [comment]
this is a duplicate of #1501
