### ISSUE TITLE
BOLED: MC Parameter Screen: zwei Buttons neu belegen, zusätzlicher Screen für Smoothing Time und Mod Reset (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1593]
- [ ] Softbutton 1 wird bei Dual-Sounds zum "I / II"-Umschalter (Es ist nützlich, hier zwischen den Parts umzuschalten, um das unterschiedliche Mapping auf die Target-Parameter zu sehen.) Für Single-Sounds bleibt der Button leer.
- [ ] Softbutton 3 bekommt die Beschriftung "more.." und wird zum Öffnen eines weiteren Parameter-Screens benutzt.
(Die bisherigen "HW Pos" und "HW Amt" wird man nicht vermissen. Softbutton 2 und 4 funktionieren wie bisher und führen auf den HW-Assignment-Screen des MCs. Dort sind dann "HW Pos" und "HW Amt" wie bisher zu finden.)
Der zusätzliche Parameter- Screen enthält:
- [ ] die Smoothing-Time des MCs (bisher nur über das Edit-Menü erreichbar, dort bitte rausnehmen)
- [ ] auf Softbutton 2 die "Mod Reset"-Funktion (bisher nur über das Edit-Menü erreichbar, dort bitte rausnehmen)
- [ ] einen "back.."-Button (Softbutton 3), um in den Haupt-Screen des MCs zurückzukehren

[MC Smoothing.pdf](https://github.com/nonlinear-labs-dev/C15/files/4366452/MC.Smoothing.pdf)

**Comment by MatthiasSeeber** [comment]
![Reconsider_1593](https://user-images.githubusercontent.com/37212609/80599657-8ce0f000-8a2b-11ea-94d2-68f5d27f6e4f.png)
_Soft Button 1 and 3 are fine in all Sound Types, but SB 2 and 4 should still offer "HW Pos" and "HW Amt", otherwise the Screens behave not as intended._

**Comment by nonlinear-labs** [comment]
I agree with Matthias. This is what I intended with the remark in parenthesis behind the second bullet point.

**Comment by MatthiasSeeber** [comment]
fixed in #1749
