### ISSUE TITLE
BOLED: Grafik-Feinschliff im Preset-Screen (Dual, "To Part")

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1596]
- [ ] Bank-Header: Entweder sind die Links/Rechts-Pfeil-Felder zu niedrig oder der äussereRahmen einen Pixel zu hoch. Gab es nicht größere Pfeile von Tino?

![Preset Part DL 03](https://user-images.githubusercontent.com/33938408/77458322-4bdb3780-6dfe-11ea-91a6-e38dcf0bf1b1.png)

**Comment by schlenkibus** [comment]
Bezueglich Punkt 5: Die Rahmen wurden nicht angefasst und die benutzten Zeichen sind die Groesseren der beiden, die in den Schriftarten enthalten sind.

**Comment by schlenkibus** [comment]
Zu Punkt 1: Soll die Bank/Preset Nummer nur im "To Part" modus verschoben sein, oder in allen Preset Screens?

**Comment by nonlinear-labs** [comment]
Punkt 1: Bitte immer verschieben. Dann ist sie auch aligned mit dem Label im Header.

Punkt 5: Dann schaue ich noch einmal, wie das früher aussah und melde mich wieder.
