### ISSUE TITLE
Parameter-Ranges für Envelope A/B/C - Level Velocity nun bipolar (-60 ... 0 ... 60 dB) (Konvertierung s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1597]
Die alten Control Positions von 0.0...1.0 werden beim Import auf die obere Hälfte (also auch 0.0...1.0) abgebildet.

**Comment by schlenkibus** [comment]
@nonlinear-labs @MatthiasSeeber has the the parameter-db been updated accordingly?

**Comment by MatthiasSeeber** [comment]
@schlenkibus see branch "issue-1597"
- the AudioEngine can already handle bipolar level velocities (expected message position range: [-1 ... 1])
- the Parameter-DB has been updated (although the update was more of a cosmetical nature, header information is not expected to have changed much)
- feel free to commit Playground-side updates for the level velocities in the provided branch

**Comment by schlenkibus** [comment]
Shouldn't the parameter-db now include bipolar scale-converters (BIPOLAR_LINEAR_60_DB) instead of LINEAR_60_DB? Or am I missing something here?

**Comment by schlenkibus** [comment]
@MatthiasSeeber Did you test this functionality? If so: can i close this ticket?

**Comment by MatthiasSeeber** [comment]
I tested four NL Presets and checked the (now bipolar) level velocities for each envelope. The values from the original presets were spread between [0 ... 60]. So, for the four presets times three envelope level velocities, the twelve display values were accurate.
