### ISSUE TITLE
Manchmal bleibt die Audio-Engine beim Laden eines Presets stumm. Manchmal klingt das Preset falsch. Wahrscheinlicher Zusammenhang mit Unison und Glitch Suppression (s.u.).

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1600]
Wenn die Glitch Suppression an ist und man von einen Unison-Preset auf ein anderes Preset umschaltet, kann es passieren, dass die Audio-Engine verstummt oder das Preset falsch klingt.

Wenn die Audio Engine stumm geworden ist und man dann die Glitch Supression ausschaltet, bleibt sie dauerhaft stumm. (Nur mit Flag implementiert!)

**Comment by nonlinear-labs** [comment]
Hier die Bank, von der ich immer gekommen bin, und zwar von den"Trance Master"-Presets 005 und 006:
[Thomas Layer.zip](https://github.com/nonlinear-labs-dev/C15/files/4403245/Thomas.Layer.zip)

Danach habe ich NL Woodwind 11/"001 Circuit Paradigma" geladen. Oft bleibt es stumm oder klingt falsch. Bei wiederholtem Laden klingt es dann korrekt.

**Comment by MatthiasSeeber** [comment]
Standardmäßig fahre ich über QT Creator die AudioEngine mit der Command Line:
`-r **48000** -p 24 -a hw:2,0 -m hw:1,0,0 -n 4 -s **64** --playground-host=localhost --heartbeat=hw:1,0,0` (also 48kHz mit 64 Samples pro Buffer)
--> hier taucht gelegentlich das Verstummen auf (Klangveränderungen eigentlich nicht)

Wenn ich auf das auf dem EPC angewendete Setting wechsle:
`-r **48000** -p 24 -a hw:2,0 -m hw:1,0,0 -n 4 -s **49** --playground-host=localhost --heartbeat=hw:1,0,0` (also 48kHz mit 49 Samples pro Buffer)
--> Verstummen und Klangveränderungen passieren oft (und zwischen gleichen wie unterschiedlichen Typen: Single, Layer)

Eine im Code klar ersichtliche Ursache habe ich bisher nicht. @hhoegelo wäre das ein Hinweis auf Threading-Probleme?
