### ISSUE TITLE
Layer-Sound-Parameter in Single- und Split-Sounds unsichtbar machen [s.u.]

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1603]
Änderungen im **BOLED** für Single- und Split Sounds:
- [x] FB Mixer - A/B x: Dieser Screen wird "gesperrt", d.h. statt des Faders und des Values zeigen wir ein Rechteck mit dem Text: "Only available with Layer Sounds". Softbutton 2 bleibt ohne"MC Sel". Der Rest kann bleiben. Beim Wechsel auf "A - B" wechselt das Parameter-Label; alles andere bleibt.
- [x] FB Mixer - Comb - From II: ausblenden
- [x] FB Mixer - SV Filter - From II: ausblenden
- [x] FB Mixer - Effects - From II: ausblenden

Änderungen im **BOLED** *nur* für Single-Sounds:
- [x] Output Mixer - Level - To FX II: ausblenden

Änderungen in der **WebUI** für Single- und Split Sounds:
- [x] FB Mixer - A/B x: Dieses Parameterfeld wird "gesperrt", d.h. der Fader und der Value werden ausgeblendet, das Label im Kopf bleibt, eine Selektion ist möglich (weil es auch einen Button in der Hardware gibt) In der Bauchbinde werden Slider und Value ersetzt durch den Text: "Only available with Layer Sounds".  Der MC-Modulations-Button wird ausgeblendet. 
- [x] FB Mixer - A/B x - "A - B": Parameterfeld ausblenden
- [x] FB Mixer - Comb - From II: Parameterfeld ausblenden
- [x] FB Mixer - SV Filter - From II: Parameterfeld ausblenden
- [x] FB Mixer - Effects - From II: Parameterfeld ausblenden

Änderungen in der **WebUI** *nur* für Single-Sounds:
- [x] Output Mixer - Level - To FX II: Parameterfeld ausblenden

**Comment by MatthiasSeeber** [comment]
Für die AudioEngine ist es an der Stelle insbesondere wichtig, dass gesperrte/ausgeblendete Parameter nicht nur genullt, sondern auch keine Modulationsziele mehr sind, wenn das neue Split- bzw. Layer-Preset an die Engine übertragen wird. (Andernfalls könnte die Nutzung von MCs in Single- oder Split-Presets ungewollte Auswirkungen haben.)

**Comment by schlenkibus** [comment]
Im Layer Modus: Anzeigen der Unison/Mono Gruppe aus I wenn Part II Selektiert ist
(Done in Boled) Todo WebUI

**Comment by schlenkibus** [comment]
- [ ] ich hab beim Testen festgestellt, dass es in der WebUI noch modulierbare Parameter gibt, die nicht als solche bedienbar sind (Master Vol, Tune, To FX, Split Point) - Indikatoren von Zuweisungen sind wahrscheinlich ein Thema für sich
- [ ] Split Point und Part Vol/Tune sind im Ticket nicht erwähnt, aber auch betroffen. Ich hätte nach wie vor gerne den Split Point in der Part Gruppe (im Split Mode), die Fade From/Range (im Layer Mode)

**Comment by nonlinear-labs** [comment]
Zum ersten Punkt habe ich die Tickets 1733/1734 generiert.

Zum zweiten Punkt haben wir gerade besprochen, dass im Split Sound der "Split Point" in der Part Group steht, im Layer Sound stattdessen "Fade From" / "Fade Range".
