### ISSUE TITLE
Die Start- und Shutdown-Zeiten sind immer noch recht lang. Was kann man da noch rausholen?

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1615]
Das Laden der Bänke geht schön schnell, aber bis dahin dauert es quälend lange.

**Comment by KlausStrohhaecker** [comment]
Solange wir die zwei relativ voll ausgebauten Linux-Systeme jedesmal komplett kalt starten, sehe ich da wenig Möglichkeiten. Ausser wir entschlacken die Systeme maximal (aber das ist bestimmt extrem aufwändig und gefährlich).

Erst wenn beide Rechner in einen (komplett stromlos-fähigen) Hybernate-Modus gehen können beim Runterfahren mit vollständigem Speicherabbild auf der SSD/SD-Karte usw, könnte das signifikant schneller werden, denke ich, vielleicht gar unter 10 Sekunden.

**Comment by nonlinear-labs** [comment]
Mich würde schon einmal ein Protokoll interessieren, also:
- von Sekunde x bis Sekunde y macht er dies
- von Sekunde y bis Sekunde z macht er das
- etc

**Comment by KlausStrohhaecker** [comment]
Für den BBB :
Frühphase, bis zum Laden zB des ESPI-Treibers : < 1s
Dann, bis Sekunde 11, starten aller möglichen Treiber und der unzähliges Services und Mounts, u.A. die "Initializing" Meldung (
In Sekunde 12 startet er dann die Bridge, die dann in Sekunde 16 fertig ist.
Also diese 16 Sekunden dauert es mindestens auf dem BBB, bis etwas angezeigt werden kann (wenn Ethernet/Netzwerk bis dahin auch fertig ist mit allem). Plus Dunkelziffer, d.h. Zeit in der ganz frühen Boot-Phase, die nicht protokoliert werden kann, also das was ab Drücken des Power-Schalters passiert (schon im Spupervisor etwa knapp 1 Sekunde bis er überhaupt die Supply anmacht -- der BBB startet dann von allein-- , und kurz danach auch den ePC aufweckt).

Theoretisch könnte der PG auf dem ePC bereits vorher gestartet sein, würde halt erstmal blind (ohne UI input und output) anlaufen und müsste, sobald die Bridge da ist, "sanft" einsetzen und die Anzeigen nach-initialisieren. Ich vermute das ist derzeit blockierend, der PG wird warten bis die Bridge verfügbar ist.

Wie es auf dem ePC aussieht kann ich nicht genau sagen, weil noch ein frühes MS1.7 System wo der PG noch auf dem BBB läuft. Die Audio-Engine ist laut Log nach etwa 7 Sekunden gestartet, plus hier einer signifkanten Dunkelzeit bis das BIOS fertig ist und dann der Bootmanager nach einer Wartezeit überhaupt das Linux bootet, das sind ja auch bereits in der Summe ca 5 Sekunden.

**Comment by KlausStrohhaecker** [comment]
So, nun auf einem recht aktuellen MS1.7 gemessen, ePC:
9 Sekunden bis komplett alles fertig ist, ab Start des Loggings.
Playground und Audio-Engine sind nach spätestens 7 Sekunden da.

Gesamtzeit ab Power-On aber wie gehabt etwa 30 Sekunden.
D.h. es vergehen gut 20 Sekunden bis die Bootvorbereitungen auf dem ePC soweit abgeschlossen sind dass er sein Logging startet.... oder der PG ist zwar schon fertig und wartet auf die Bridge, die sicher nicht schneller startet wie vorher, also der BBB wohl gute 20Sekunden braucht bis die Bridge und Network usw alles läuft.

**Comment by KlausStrohhaecker** [comment]
Weiterer Test: BBB samt Bridge läuft schon, danach erst ePC booten.
Dauert 24 Sekunden bis der Playground sich meldet.
==>Also stimmt eher erste obige Annahme: der eCP braucht (auch) so lange.

Sprich, beide Systeme brauchen eben mindestens 20 Sekunden bis sie fertig sind mit Hochfahren, und dominant bei beiden ist die Frühphase des bootens.
