### ISSUE TITLE
WebUI: Sound-Bauchbinde: Verhalten der Value-Edit-Felder buggy (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1628]
- [x] Alle Editfelder sollten Pfeile nach links und rechts haben (im Moment haben sie es nur beim Single Sound)
- [x] Die Pfeile (s. Single Sound) waren auch schon mal weniger dünn... Also bitte mit einem doppelt so dicken Pinsel malen.
- [x] Die sensitiven Flächen für das Klicken auf die Pfeile sollte in der Mitte einen Bereich leer lassen, etwa so breit wie ein typischer Value. 
- [x] Auf dem Value sollte ein Doppelklick möglich sein, ohne dass man dabei erstmal den Wert verstellt.
- [x] Split: Doppelklicks auf den rechten Volume/Tune setzen den linken zurück.
- [x] Layer: Doppelklicks auf den unteren Volume/Tune setzen den oberen zurück.

**Comment by MatthiasSeeber** [comment]
The appearance is convincing when the Browser Window is maximized.
![Screenshot from 2020-04-04 12-19-41](https://user-images.githubusercontent.com/37212609/78424562-c4e45580-766e-11ea-9f37-804385308f3b.png)
Resizing the Browser Window leads to a less convincing appearance.
![Screenshot from 2020-04-04 12-20-14](https://user-images.githubusercontent.com/37212609/78424573-da597f80-766e-11ea-8a56-626cf6b12127.png)
Besides:
- double clicking on value fields invokes reset (seems right to me)
- double clicking on the arrows first changes the value, then invokes reset (seems wrong to me)
