### ISSUE TITLE
BOLED: MC Parameter Screen: Softbutton 1 mit "I / II" belegen, Typ/Part-Icon anschliessen (Priorisiert von #1593)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1633]
Der Typ/Part-Icon zeigt immer zwei graue Flächen. Er sollte aber genauso aussagekräftig sein wie bei den anderen Parametern.

"HW Pos" zeigen wir auf Softbutton 1, wenn HW Sel oder HW Amt im Fokus ist. Das reicht.

**Comment by MatthiasSeeber** [comment]
Seems legit und useful for Split/Layer Presets.
![Boled-Sat-Apr--4-12:06:37-2020
](https://user-images.githubusercontent.com/37212609/78424325-17bd0d80-766d-11ea-8222-7781ea34ceb6.png)
For Single Presets, however, Soft Button 1 has no purpose.
![Boled-Sat-Apr--4-12:06:42-2020
](https://user-images.githubusercontent.com/37212609/78424398-80a48580-766d-11ea-971f-3852bd3b8680.png)
I suggest to either leave SB1 blank, or to re-surface HW Pos, when in a Single Preset.

**Comment by MatthiasSeeber** [comment]
Soft Button 1 should be blank when in Single mode.
