### ISSUE TITLE
Unterstützung der Drucktasten-Funktion des neuen Encoders (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1669]
Klaus hat den Encoder-Taster an ein noch nicht voll ausgenutztes Shiftregister angeschlossen. Der Taster sollte also durch ein Bit in der seriellen Übertragung für die States der Panel-Buttons vertreten sein. Wir müssen den Treiber-Output danach durchsuchen.

Die erste Anwendung wäre eine Dopplung der Funktion der Enter-Taste.

**Comment by majjam** [comment]
Hallo ich melde mich mal wieder zu Wort:

Eine Erfahrung mit Drehencodern, die man auch drücken kann. 
Es ensteht immer die Gefahr, dass bein Drehen auch gedrückt wird, daher sind Funktionen, die auf _pressed liegen immer mit vorsicht zu genießen. Sie sollten einer Funktion mit

**Comment by KlausStrohhaecker** [comment]
Guter Einwand, und ganz meine Meinung.
Allerdings ist die zugehörige Encoder-Firmware so ausgelegt, dass eine große Hysterese vorhanden ist, womit das versehentliche Verstellen doch eher selten passiert.
Aber, in der Tat, Encoder Press => Wert übernehmen und Verlassen ist potentiell heikel. Im Zweifel sowas auf jeden Fall erst beim Loslassen des Encoders, nicht schon beim Drücken.

**Comment by nonlinear-labs** [comment]
Ich war noch nie ein Freund der drückbaren Dreh-Encoder, deswegen gab es auf dem C15 lang Zeit keinen solchen. Aber die Realität ist:
- Viele Leute erwarten so eine Funktion - das ist auf Messen zu beobachten.
- Es gibt nicht viele Encoder ohne Drucktastenfunktion. Der neue von Würth ist eine echter Fortschritt in Qualität und Drehgefühl. Ihn gibt es nur "mit".

Wir werden eine Weile mit der Funktions-Belegung experimentieren und vielleicht auch Optionen in den Settings anbieten wie z.B. "Enter / Fine / Off".

**Comment by KlausStrohhaecker** [comment]
> Der Taster sollte also durch ein Bit in der seriellen Übertragung für die States der Panel-Buttons vertreten sein. 
> Wir müssen den Treiber-Output danach durchsuchen.

Hab ich getan, die Tastennummer ist 0x72, kommt also im Treiber an, schickt Signal beim Drücken und Loslassen.

Größeres Problem ist die angedachte Hardware-Erkennung, weil leider alles event-basiert ist. D.h. die Erkennungsbits (also welche Hardware-Version vorliegt, bzw ob überhaupt eine Panel-Unit angeschlossen ist) kommen zwar low-level im Treiber an, werden aber nicht gemeldet weil sie sich nie ändern. Gleiches gilt für die Erkennung des TopCovers.

Die Hardware-Erkennung für die Implementierung der Encoder-Funktion zwar relativ egal, aber schön wäre es wenn man auch pollen oder eben das Auslesen der kompletten Schieberegister erzwingen könnte... bin uA ja grad an den Treibern eh dran, vlt kann ich das was machen...

**Comment by KlausStrohhaecker** [comment]
Hardware-Erkennung geht nun (damit erkennbar ob eine Panel-Unit dran ist, und welche Hardware-Revision mit/ohne Encoder-Button), konnte den Treiber schon mal experimentell anpassen dass die entsprechenden ID-Bits periodisch übermittelt werden.
@schlenkibus , du bekommst die Details dann von mir....
