### ISSUE TITLE
WebUI: Das Kontextmenü des Bank-Headers ist kaputtgegangen. Es kommt das globale Kontextmenü.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1677]
Ah - jetzt merke ich: das ist nur der Fall, wenn "To Part" an ist.

**Comment by schlenkibus** [comment]
Das Bank Edit Context-Menu soll auch im "to part modus" angezeigt werden?

**Comment by nonlinear-labs** [comment]
Achso - das war Absicht? Naja, für mich gab es keinen Grund, das Menü nicht zu erwarten. Die Preset-Kontextmenüs funktionieren da normal.
