### ISSUE TITLE
WebUI: triangular Part selection indicator

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#1681]
![Screenshot from 2020-04-09 15-56-27](https://user-images.githubusercontent.com/37212609/78903688-cc936800-7a7b-11ea-8596-b461ed989e96.png)

Is there a reason for the little triangle on the Part selector only appearing on the first instance (left) of the WebUI? (on the right is a second instance)

I first thought, the triangle may indicate the Part selection on the BOLED, but that does not seem to be the case.

**Comment by schlenkibus** [comment]
It indicates an active load to part mode. The arrow points to the part currently loading to

**Comment by MatthiasSeeber** [comment]
Alright, makes sense and seems to apply to multiple instances as well. Thanks
