### ISSUE TITLE
Dual Mode Conversion and (Load to Part Rules)

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1684]
[ModeConversionRules-Rev2.pdf](https://github.com/nonlinear-labs-dev/C15/files/4473896/ModeConversionRules-Rev2.pdf)

**Comment by MatthiasSeeber** [comment]
Here is my next Revision of the Conversion Process:
[ModeConversionRules_Rev3.pdf](https://github.com/nonlinear-labs-dev/C15/files/4475593/ModeConversionRules_Rev3.pdf)
- most rules haven't changed
- the "special" parameters are now considered separately (FB Mixer -> Cross FB, Out Mixer -> To FX)
- some details regarding these "special" params are now a little different
I would prefer to discuss this before adopting anything.

**Comment by MatthiasSeeber** [comment]
[ModeConversionRules_Rev4.pdf](https://github.com/nonlinear-labs-dev/C15/files/4477116/ModeConversionRules_Rev4.pdf)
