### ISSUE TITLE
Export einer Bank auf einen Stick: Auf dem Stick ist nur eine ".xml_tmp"-Datei zu finden.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1686]
Das ist bei Matthias Fuchs passiert und hier nicht sofort nachvollziehbar. Die dabei entstandene Datei scheint in Ordnung zu sein.

Es sieht aus wie eine temporäre Datei, die nach dem Schreibvorgang nicht gelöscht oder umbenannt wurde.

**Comment by hhoegelo** [comment]
Das einzige Fehlverhalten, das ich reproduzieren konnte, war mit einem nahezu vollen USB-Stick. Koennte das bei Matthias Fuchs der Fall gewesen sein?

**Comment by schlenkibus** [comment]
@hhoegelo @nonlinear-labs wollen wir ein Ticket fuer den check auf notwendigen Platz beim Kopieren in den backlog / beyond 1.7 milestone schieben und dieses Ticket schliessen?

**Comment by nonlinear-labs** [comment]
Ich konnte das Problem hier auf Anhieb reproduzieren (Version vom 04.06.). Es hat nichts damit zu tun, dass der Stick übervoll ist.
Das ist ein Fehler, der eine lange bestehende Funktion kaputt macht. Es lohnt sich also, ein bisschen Zeit zu investieren.

**Comment by hhoegelo** [comment]
I could reproduce that depending on how long user waits with pulling the stick right after exporting a bank, the system produces
a) no file, or
b) a xml_tmp file, or
c) the correct file
After tweaking the sshfs options and adding additional sync calls on bbb, I could still reproduce a) when pulling really fast, or c) when there is at least 2 seconds between user interaction and pulling the stick.
