### ISSUE TITLE
BOLED: Store

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1704]
wenn man einen geänderten Editbuffer über das BOLED neu abspeichert (also nicht overwrite), im Rename Screen dann bestätigt, landet man wieder im Preset Screen (soweit ok), allerdings ist der Store Mode weiterhin offen (sollte nach Abschließen des Store Vorgangs aber verschwunden sein)

**Comment by MatthiasSeeber** [comment]
Könnte es sein, dass wenn der Store Mode im Boled noch offen ist, die WebUI davon beeinträchtigt sein könnte? Ich hatte da vorhin komische Effekte, wo eine Preset-Selektion in der WebUI nicht möglich war.
