### ISSUE TITLE
HWUI : part indicator folgt nicht immer

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#1705]
tested on Layer sound on Master 2020-04-17

0. Part II was selected initially.
1. press [**Sound**] -> enter sound menu 
2. press [**SB_A**] -> part I is selected in Sound menu ; Pic1
3. press [**Preset**] -> part II is selected in preset menu (wrong); Pic2
4. press [**FB_Mixer**] - in parameter screen part I is selected ; Pic3
5. press [**Preset**] again -> Part I is selected as it should be ; Pic4

 _
1.
![grafik](https://user-images.githubusercontent.com/4758563/79562296-1a772400-80ab-11ea-80e5-d6a5d6ffa611.png)

2.
![grafik](https://user-images.githubusercontent.com/4758563/79562833-efd99b00-80ab-11ea-98d4-2a8158663df2.png)

3.
![grafik](https://user-images.githubusercontent.com/4758563/79562489-7e99e800-80ab-11ea-8726-84f3832f6781.png)

4.
![grafik](https://user-images.githubusercontent.com/4758563/79563120-742c1e00-80ac-11ea-849b-95be16bead47.png)

**Comment by schlenkibus** [comment]
This does not seem to be an issue in the current master branch anymore!
