### ISSUE TITLE
BOLED - Preset Button after Store Overwrite

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#1720]
I overwrote a Layer Sound by pressing Store, selecting Overwrite, then pressing Enter.
The Store Mode is still active after that (it is, in fact always still active after Storing, regardless of the Method). Then pressing Store again to de-activate the Store Mode at first seems to work, but pressing the Preset Button now will always switch between Preset and Store Screen.
The only way to break this behavior (that I found) is to load a Preset, change a Parameter, then reload the Preset by pressing Enter. Than, consecutive pressing of the Preset button went back to work as intended.

**Comment by MatthiasSeeber** [comment]
Also, in Dual Sounds, the Preset Button seems to be linked to Soft Button 4, enabling and disabling "To Part". Maybe, this can explain unwanted Store Mode behavior?

**Comment by schlenkibus** [comment]
Is the behaviour observed not correct inregards to this ticket / pdf : https://github.com/nonlinear-labs-dev/C15/issues/1500

so being in store and then changing focus to preset will save store as last focus and will return to that focus if the preset button is pressed again. Pressing Preset if to part is enabled will result in the "normal" preset screen as load to part also is a focus detail so the same applies as with store I think.
@nonlinear-labs @MatthiasSeeber 
can we reformulate this ticket or reopen 1500 in regards to the usability issues found in this ticket?

**Comment by MatthiasSeeber** [comment]
Yes, I think this can be reformulated.
- In my opinion, the Store focus detail should be disabled after completing a store process, then the Store Screen should not interfere anymore. It would then be only present immediately after pressing Store - when needed.
- The To Part detail is a little more subtle.
It indeed makes sense to leave this detail active, even after loading something, as the user may just browse presets until the right one is found.
However, in testing purposes, this rapidly leads to a little confusion when not used to it. I think, I just have to adjust my workflow, disabling to Part immediately after loading. Another possibility could be a Setup option, providing automatic disabling of To Part after loading something to a Part.
- The provided PDF in #1500 does not name To Part as an individual Screen, so I would suggest to treat this as the Preset Screen. This would mean, that whether To Part is active or not, pressing Preset twice should invoke the previous (Parameter, Sound, ..) Screen.

**Comment by schlenkibus** [comment]
I reopened #1500 and added it to the beyond 1.7 Milestone
