### ISSUE TITLE
WebUI Parameter Tab: To FX (und Split Point?) sind noch nicht einem MC zuweisbar.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1734]

**Comment by MatthiasSeeber** [comment]
![Issue-1734-Precise](https://user-images.githubusercontent.com/37212609/80380309-aead6c00-889f-11ea-835f-8894b8970363.png)

präziser:
- Part und Master Volume/Tune sind in BOLED und WebUI modulierbar, haben aber keine Indikatoren
- Part Split Point ist (wie dargestellt) nur über BOLED erreichbar (da er in der WebUI bisher nur im Sound Tab auftaucht - über das BOLED kann man im Parameter Tab die entsprechende Bauchbinde zwar erreichen, es fehlt jedoch die Anbindung an die Modulation)
- Output Mixer To FX ist nur über BOLED modulierbar
- Feedback Mixer A/B sowie From sind in BOLED und WebUI modulierbar (haben in der WebUI aber noch keine Indikatoren)
