### ISSUE TITLE
LPC update

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#1736]
lpc_update.sh relies on /nonlinear/scripst/mxli. @KlausStrohhaecker suggests it should be part of the update.tar stashed under /LPC/.

I can change the path, in the lpc_update.sh script. However, I would not know how to deploy the mxli with cmake into the right directory.

**Comment by hhoegelo** [comment]
@AntonSchmied Currently, you can grab the mxli tool from the rootfs.tar.gz as you do for all the other tools. The location is /nonlinear/scripts/mxli. This is about to change, but for now, it can be found there.

**Comment by hhoegelo** [comment]
@AntonSchmied can this ticket be closed?

**Comment by AntonSchmied** [comment]
@hhoegelo 

> @AntonSchmied Currently, you can grab the mxli tool from the rootfs.tar.gz as you do for all the other tools. The location is /nonlinear/scripts/mxli. This is about to change, but for now, it can be found there.

@hhoegelo Has it changed? I must admit, I have not followed the latest LPC changes ...

**Comment by KlausStrohhaecker** [comment]
The MXLI tool sources, likewise to the AVRdude tool, should be part of the top-level projects and be part of the bbb-rootfs target, and they should be collected from there and injected into the update package, like preferably any other specific tool we have there, text2soled, sshpass etc.

They would reside in the BBB platform section of the source tree, for now. Both will move to ePC in a future to come, without BBB.

**Comment by AntonSchmied** [comment]
Suggestion:

- in `create-c15-update.sh -> get_tools_from_rootfs()` we pull the mxli from rootfs and deploy it in the update.tar under `/utilities/`
- in `lpc_update.sh` we change https://github.com/nonlinear-labs-dev/C15/blob/e26d4909ebe136879bb3a7cfaf7c9b8fc740df6e/build-tools/create-c15-update/update_scripts/lpc_update.sh#L56 to `/update/utilities/mxli`
