### ISSUE TITLE
BOLED: Finalisierung der Typ/Part-Symbole und der Symbole für Mute und To Part

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1745]
![BOLED_part-symbole ssc mute](https://user-images.githubusercontent.com/33938408/80583229-3f0abe80-8a10-11ea-8f86-a3fc3123d555.png)

- [x] Das Typ/Part-Symbol, das links im Parameter- und Preset-Screen stehen kann, wurde leicht überarbeitet: Aussenmasse 12 x 12 px, zwei Balken à 5 x 12 px bzw. 12 x 5 px, dazwischen eine 2 px breite Lücke. Position: links 2 px vom Rand, oben 2 px vom Group-Label (15 px vom Rand).

- [x] Wenn "To Part" an ist, sollte ein kleines helles Dreieck (3 x 5 px) von rechts bzw. unten auf den Part zeigen. Abstand: 1 px.

- [x] Das "Mute"-Symbol (Lautsprecher mit "x") am Typ/Part-Symbol wird ersetzt durch ein "x", das über das Typ/Part-Symbol gezeichnet wird. Damit kann nun auch der Mute-Zustand des nicht selektierten Parts indiziert werden. (Im Layer Sound Screen verwenden wir weiter das Mute-Symbol mit dem Lautsprecher jund "x")

- [x] Die Typ/Part-(Quellen)-Symbole, die bei "To Part" in den Zeilen der Presetliste gezeigt werden, wurden auch überarbeitet: Aussenmasse 10 x 10 px, bei Split/Layer zwei Balken à 4 x 10 px bzw. 10 x 4 px, dazwischen eine 2 px breite Lücke. Position: 2 px vom linken/rechten Rand, 2 bzw. 3 px vom oberen/unteren Rand.

- [x] Die bei "To Part" in den Typ/Part-Quellen-Symbolen verwendeten Farben: dunkelgrau für die nicht geladene Quellen, hellgrau für die geladene Quelle, weiss für den Selektions-Rahmen.

**Comment by MatthiasSeeber** [comment]
- [x] Part Selector Triangles seem okay
- [ ] it seems to be intended to highlight the Part Mute indicator ("x"), when the Part is not selected:
![Boled-Thu-Apr-30-15:44:26-2020
](https://user-images.githubusercontent.com/37212609/80718069-f4657100-8af9-11ea-9ddc-e1ff767705b6.png)
- [ ] it seems to be intended to display the Part indicator in the Master Screen:
![Boled-Thu-Apr-30-15:46:29-2020
](https://user-images.githubusercontent.com/37212609/80718121-09420480-8afa-11ea-989a-d5c7a50b22f8.png)

**Comment by schlenkibus** [comment]
> * [ ]  it seems to be intended to display the Part indicator in the Master Screen:
>   ![Boled-Thu-Apr-30-15:46:29-2020 ](https://user-images.githubusercontent.com/37212609/80718121-09420480-8afa-11ea-989a-d5c7a50b22f8.png)

Why should a global parameter have the voice group indication?

**Comment by MatthiasSeeber** [comment]
The remaining Question of whether the Master Parameter Screen should display a Part Selector or not is hereby delegated to a separate issue.
