### ISSUE TITLE
Convert-To-Single + Init + Editieren + Convert-To-Layer: Editierungen gehen verloren

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1774]
- ein Layer-Preset laden
- in einen Single-Sound konvertieren
- diesen mit "Init" zurücksetzen
- den initialisierten Sound editieren
- den editierten Single-Sound in einen Layer-Sound konvertieren
-> der entstandene Layer-Sound ist ein Layer von Init-Parts
-> die Editierungen des Single-Sounds wurden "vergessen"

**Comment by schlenkibus** [comment]
Ich kann in diesem Zusammenhang einen bug sehen der das beobachtete verhalten erklaeren kann: Wenn Part 2 eines Layer/Split presets ueber die WebUI konvertiert wird, bleibt die Selektion auf VG II -> folgende Changes an parametern gehen in den falschen part, so wird auch beim konvertieren des single-sounds in dual part I kopiert.
