### ISSUE TITLE
Boled: Load to Part Single Name not loaded to dual voice group label

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1776]

**Comment by MatthiasSeeber** [comment]
> ![1762](https://user-images.githubusercontent.com/37212609/80956848-524bce80-8e02-11ea-9a4d-53ca8af97e7d.png)
> 
>     * [x]  converting (single) "Adam" to (split) "Adam 2", then converting "Adam 2" Part back to single yields "Adam conv." (as expected, and not "Adam 2 conv.")
> 
>     * [ ]  however, taking "Split empty", and then loading "Adam" and "Eva" into each Part, doesn't change the Part labels of "Split empty" (separately formulated in #1776 )
