### ISSUE TITLE
feature request:  Recall via 'shift' + 'default'

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#1802]
Hi,
would like to see the Parameter-Recall function mapped to the key combinations "SHIFT" + "DEFAULT" in addition to the "SHIFT" + "Softbutton-2"-combo

That would make it even quicker to mute e.g.  levels of the output mixer and jumping back to the original value without moving the left hand so much while testing the sound with the right hand.

**Comment by schlenkibus** [comment]
@majjam what do you think about the "default" button acting as a toggle? While the Recall Layout is open a press on "default" either loads the default value or last non default value, instead of only going one way?

**Comment by nonlinear-labs** [comment]
Danke für die Anregung, Max! Bevor wir die Shift-Taste mit weiteren Buttons kombinieren, würde ich gründlich nachdenken wollen. Aber Justus' Vorschlag erinnert mich an etwas, das ich schon länger vorhatte: s. #1823

**Comment by majjam** [comment]
@schlenkibus : another interesting idea using 'default' as a toggle button  - could convince me..
@nonlinear-labs :  Keine Eile keine Hast , ich dachte mir bei dem großen Update was ihr vorhabt , ist ein Idee kein Fehler. Soll Euch aber auch nicht vom Wesentlichen abhalten !

**Comment by majjam** [comment]
Ich denke wenn #1823 umgesetz wird, kann das diese Anfrage ersetzen.
Deswegen schliese ich das Ticket erstmal
