### ISSUE TITLE
WebUI: Oscillator A/B - Phase ist jetzt MC-modulierbar. Das Symbol des assignten MCs fehlt aber, und der rote Rahmen, wenn man den MC selektiert.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1809]
Das MC-Symbol kann rechts oben neben dem Label eingeblendet werden.

In der HWUI fehlt auch das Blinken der "Phase"-LED, wenn der betreffende MC selektiert ist. 

![Phase - MC Symbol fehlt](https://user-images.githubusercontent.com/33938408/81727212-e7953580-9488-11ea-8580-0b12f660e353.PNG)

**Comment by schlenkibus** [comment]
Das nicht blinken der LED kann ich nicht reproduzieren auf master (965179bd8f1bf823a0cc47815eaba56c1d21e3a0)

**Comment by nonlinear-labs** [comment]
Ich kann das Nichtblinken gerade auch nicht nachvollziehen. Aber ich schwöre: es war da!
