### ISSUE TITLE
WebUI: Fine-Einstellung für Pitches über direktes Anfassen der rechten Hälfte des Controls.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1826]
Es geht um drei Pitch-Zahlenfelder: die der beiden Oszillatoren und das des Comb Filters.

- [x] Wir teilen das Control in zwei Hälften. In der linken Hälfte wirkt ein Draggen (wie bisher ohne Shift-Taste) in Schritten von 1.0 Semitones. In der rechten Hälfte wirkt das Draggen als Feineinstellung (wie bisher mit gedrückter Shift-Taste), in Schritten von 0.01 Semitones.

- [x] Der Doppelklick sollte links (wie bisher) auf Default = 60.00 stellen, In der rechten Hälfte sollte er ein Auf- bzw. Abrunden auf den nächsten ganzzahligen Wert bewirken.
xx.01 ... xx.49 - wird auf xx.00 abgerundet
xx.50 ... xx.99 - wird auf (xx.00 + 1.00) aufgerundet

Das Runden hat gegenüber dem Abschneiden doch erhebliche Vorteile: Wenn ich 71.97 eingestellt habe, um Schwebungen zu bekommen, will ich danach viel eher auf 72.00 als auf 71.00.

- [x] Die Shift-Taste wird für die drei Pitches nun unwirksam.

**Comment by schlenkibus** [comment]
closed in #1828
