### ISSUE TITLE
Crash: HWUI - Preset-Screen öffnen, Info-Button drücken

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1832]

**Comment by schlenkibus** [comment]
I cant reproduce this issue on the current master (6f353c30cf2a4803a46a8251dddf5ed5a151728e)
@nonlinear-labs Can you provide steps to reproduce?

**Comment by nonlinear-labs** [comment]
Maybe it depends on the type of preset. If you select a new dual preset, it doesn't happen. Select an old single preset and it will happen reproducable.
