### ISSUE TITLE
Bitte die aktuelle HTML-Help einbinden (die aktuell eingebundene Version ist halb kaputt).

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1834]
Das zip-Archiv "HTML-Manual-2020-05-18.zip" kann hier heruntergeladen werden:
https://www.nonlinear-labs.de/support/help/help.html
oder per FTP hier:
/nonlinear-labs/support/help/docs

**Comment by nonlinear-labs** [comment]
Im Build mit HEAD = ebd58dd73 sind einige Kapitel der HTML-Hilfe nicht ladbar

**Comment by schlenkibus** [comment]
@nonlinear-labs Welche kapitel sind nicht da? Ich habe den gesamten online-help ordner durch den Inhalt der Zip ersetzt, war diese an sich vollstaendig?

**Comment by nonlinear-labs** [comment]
Diese fehlen z.B.:

/introduction/introduction.html
/interface/interface.html
/synth-engine/synth-engine.html
/synth-engine/parameter-ref/parameter-ref.html
/interface/shortcuts.html
/about.html
