### ISSUE TITLE
BOLED: Das Typ/Part-Icon hat manchmal zwei graue Flächen

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1836]
Lässt sich wahrscheinlich so reproduzieren:
- Gleich nach dem Start ein Single-Preset laden und in einen Dual-Sound konvertieren
  (Vielleicht muss beim Start schon ein Single-Preset im Editbuffer sein...)
- Preset-Screen öffnen
=> Das Typ/Part-Icon hat zwei graue Felder

Wenn man einmal im Parameter-Screen  des Dual-Sounds gewesen ist, tritt das Problem nicht mehr auf.

**Comment by schlenkibus** [comment]
@nonlinear-labs ist dieses Problem nochmal aufgetreten?

**Comment by nonlinear-labs** [comment]
Ja, besonders am Anfang oder nach "To Part". Aber es gibt noch einige weitere Phänomene, wo das Typ/Part-Icon etwas Falsches anzeigt. Ich versuche, etwas reproduzierbares aufzuschreiben, ist aber noch recht verwirrend.

**Comment by nonlinear-labs** [comment]
Ist wahrscheinlich mit anderen Fixes behoben worden.
