### ISSUE TITLE
WebUI: Preset-Tab: Bei Direct Load ist die Animation der Preset-Liste ist langsam, stockend und flackernd. (s.u.) 

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1840]
Es wird erst eine graue und dann die blaue Hinterlegung eingeblendet. Bitte vereinfachen: 
Beim Betätigen der Inc/Dec-Taste das ausgewählte Preset blau einfärben und die damit entstandene Liste verschieben, bis das geladene Preset im Selektionsrahmen ist.

Wenn Direct Load aus ist, ist der Übergang - mit der grauen Hinterlegung - ok.
Also bei Direct Load = an bitte genauso machen - nur blau.

Ausserdem sollte bei Direct Load der Load-Button nicht aufblitzen, wenn ein unverändertes Preset durch ein anderes Preset ersetzt wird. Er sollte nur angehen, wenn ein Preset editiert wird.

**Comment by KlausStrohhaecker** [comment]
Ich persönlich empfinde solche Animationen (zB auch beim Einblenden/Ausblenden von "Setup") als störenden bis zT richtig nervenden Firlefanz, genauso wie das Nachlaufen des Schirms beim Scrollen (was nur bei "Wischgeräten" am Browser Sinn macht).

Würde ich alles rausschmeissen oder evtl. halt abschaltbar machen (Setup->GUI-Settings). Bei Profi-Equipemnt braucht man mE so ein Zeugs nicht, vor allem wenn es eben Ressourcen/Performance frißt ohne echte Nutzwert.
