### ISSUE TITLE
USB sticks contain .not-mounted file after update

### ISSUE THREAD

**Issue by hhoegelo** [nonlinear-labs-dev/C15#1859]

**Comment by schlenkibus** [comment]
Was ist der stand dieses Tickets? Ist das Problem erneut aufgetreten (@nonlinear-labs) / lies es sich repoduzieren (@hhoegelo)?

**Comment by nonlinear-labs** [comment]
Das File fand sich bei jedem der letzten Updates auf dem Stick. Das letzte hatte ich immer weggelöscht. Das Problem scheint also reproduzierbar.

**Comment by schlenkibus** [comment]
fixed in nonlinux repo
