### ISSUE TITLE
CRASH: beim An- und Ausschalten von WiFi in den Device Settings im BOLED-Setup.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1878]

**Comment by schlenkibus** [comment]
Ich habe mehr log output auf dem master hinzugefuegt, ich schaue morgen ob ich mehr herausfinde!

**Comment by hhoegelo** [comment]
Kann ich nicht reproduzieren - funktioniert auf meinem Geraet, wie es soll.

**Comment by nonlinear-labs** [comment]
Ich kriege es auch nicht mehr hin - dann schliessen wir den Issue.
