### ISSUE TITLE
BOLED: Presetscreen: Das Typ/Part-Icon am linken Rand hat manchmal zwei graue Flächen und den Pfeil auf den falschen Part. s.u.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1880]
Lässt sich (hoffentlich) so reproduzieren:

- Bank mit mehreren Layer-Presets, eines davon laden
- "Direct Ld" = an, "To Part" = aus
- Mit "I / II" den oberen Part auswählen.
- Nächstes Layer-Preset laden
- "To Part" einschalten
  => Beide Symbolhälften sind grau, der Pfeil zeigt auf die falsche (untere) Hälfte.

- Mit "I / II" wieder den oberen Part auswählen
- "To Part" wieder ausschalten
  => Beide Teile des Symbols sind wieder grau.
- "To Part" wieder einschalten
  => Der Pfeil zeigt wieder auf den falschen (unteren) Part.

**Comment by nonlinear-labs** [comment]
Kleines Video (Jetzt habe ich die Webcam im Griff ;-) )

[WIN_20200526_15_51_07_Pro.zip](https://github.com/nonlinear-labs-dev/C15/files/4682670/WIN_20200526_15_51_07_Pro.zip)

**Comment by schlenkibus** [comment]
Das Problem tritt auf dem aktuellen Master (9ad9079003ea) nicht auf, bzw laesst sich nicht wie oben erklaert reproduzieren.

**Comment by nonlinear-labs** [comment]
Ist mit anderen Fixes wahrscheinlich behoben worden.
