### ISSUE TITLE
HWUI: Nach dem Hochfahren wird die MC-Position nicht in den Ribbon-LEDs angezeigt.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1897]
Alle LEDs sind aus. Nach der ersten Änderung eines MCs werden die LEDs dann korrekt upgedatet

**Comment by KlausStrohhaecker** [comment]
Bug kann ich bestätigen

**Comment by KlausStrohhaecker** [comment]
Problem is still persistent in latest nigthly build:
The upper ribbon display typically is correctly displayed after PG startup, the lower remains typically at zero or a too-low value and either needs a parameter/MC change or a preset load to update.

**Comment by KlausStrohhaecker** [comment]
fixed with https://github.com/nonlinear-labs-dev/C15/commit/66902bc5e3b30493f1630038df6bacd23b4e8f4b
