### ISSUE TITLE
Reconsider Envelope Sequencers and Env C Rate

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1962]
Weitere Untersuchungen und Beispiel-Presets folgen...

**Comment by nonlinear-labs** [comment]
[Bug Pitch Env.zip](https://github.com/nonlinear-labs-dev/C15/files/4763904/Bug.Pitch.Env.zip)

Attack und Decay 1 = 0.000 ms, Breakpoint = 3 %
Sobald eine der beiden Zeiten nicht Null ist, verschwindet das Problem.

Der Fehler sind die hörbaren Pitch-Ramps, weil dort der Breakpoint übersprungen wird und die Decay 2 Phase schon beim Peak beginnt.

**Comment by MatthiasSeeber** [comment]
The constant "Slow" rate for Envelope C controlling Pitches (at least) is way too low for an accurate representation of curves using very short Attack, Decay 1 times.

**Comment by MatthiasSeeber** [comment]
- [x] primary envelope bug is fixed
- [x] further env-c on pitch processing is covered via #2250
