### ISSUE TITLE
WebUI - Kosmetik (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1968]
- [x] Unison - Voices: Das Feld sollte oben nicht abgerundet sein (s. Mono - Enable)
- [x] Mono - Legato: Das Feld sollte unten abgerundet sein (s. Unison - Pan)
- [x] (Layer) Part - Fade Range: Das Feld sollte unten abgerundet sein (s. Master - Tune)
- [x] Flanger - Envelope: bitte als großen Knob mit grau hinterlegtem Label (nur, wenn's schnell zu machen ist)

**Comment by MatthiasSeeber** [comment]
>     * [ ]  Unison - Voices: Das Feld sollte oben nicht abgerundet sein (s. Mono - Enable)
> 
>     * [ ]  Mono - Legato: Das Feld sollte unten abgerundet sein (s. Unison - Pan)
> 
>     * [ ]  (Layer) Part - Fade Range: Das Feld sollte unten abgerundet sein (s. Master - Tune)

Unison und Mono sollten bereits gefixed sein, siehe https://github.com/nonlinear-labs-dev/C15/pull/1956
