### ISSUE TITLE
WebUI: Unison Voices wird manchmal nicht auf 12 geclippt, wenn man ein Preset (24v unison) in den Part eines Split-Sounds lädt. (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1984]
Als Beispiel ADDONIS2 aus Mikes Bank laden.

Der Parameter auf der WebUI ist dann um Faktor 2 (+Rundungsfehler) größer als im BOLED. Das BOLED ist korrekt.

Das Problem lässt sich nur reproduzieren, wenn in denselben Part vorher ein älteres Preset geladen wurde. (ein Preset aus der Zeit vor Split/Layer/Mono)

**Comment by hhoegelo** [comment]
Ich kann das hier gar nicht reproduzieren. Ich habe aber Grund zur Annahme, dass das Problem durch https://github.com/nonlinear-labs-dev/C15/pull/1987 und/oder https://github.com/nonlinear-labs-dev/C15/pull/1983 gefixt ist. Daher schliesse ich das issue und hoffe, dass es nicht wieder aufgeht.
