### ISSUE TITLE
BOLED: new Layer FB Signal-indication 

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2004]
Layer-Sound: Cross-Part-Feedback Indikatoren (2 Pfeile links vom Layer-Block)
(4 From x FB-Parameter prüfen ob größer NUll)

rough mockup / sketch needed!

**Comment by schlenkibus** [comment]
@schlenkibus add utils to Descriptive Layouts: binary or for events / groups of events? rather or in event sinkage

**Comment by majjam** [comment]
Hi here are my two cents for the indication :

Layered mode :
just found out that arrows are misaligned by a small amount of pixels (right side)  :
![grafik](https://user-images.githubusercontent.com/4758563/88562542-1905b200-d031-11ea-87dd-a114dee190ec.png)


Another thing is that cross mod indicators (left side) are active if FBMixer[A-B] have a value but FBMixer[A/B I] is zero.
Is this intended ?
these settings 
![grafik](https://user-images.githubusercontent.com/4758563/88563119-e14b3a00-d031-11ea-8c87-a94fee873b43.png)  
![grafik](https://user-images.githubusercontent.com/4758563/88563239-0a6bca80-d032-11ea-84ed-5432c69c5fc2.png)
results in this indication : 
![grafik](https://user-images.githubusercontent.com/4758563/88563192-f58f3700-d031-11ea-8553-89f08c977012.png)
