### ISSUE TITLE
cannot build epc-nonlinux-iso

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2013]
make epc-nonlinux-iso fails (for my setup)
Hi since a couple of month im not able to build the epc image anymore. The process isnt able to acces the internal filesystem.  I will post a logfile  later today.

my setup

Linux mint 19.3 inside virtual box

- gcc8 is installed propoperly
- cloned repo to ~/C15 ,checked out RELEASE-2020-06
- cleaned all existing docker images
- user is in docker group and docker is started
- cmake from ~/builds/C15 with all options =On despite of DEV_PC which is =Off.
- "make epc-nonlinux-iso" from ~/builds/C15

After  downloading nonlinux.tar.gz and AP-linux.iso build process tells me trouble with accessing the files (something like : cannot find internal/ap-linux.iso )

building bbb-rootfs is working

as i wrote i will attach more detailed info later.

**Comment by hhoegelo** [comment]
This is a server side issue: I provide some of the files needed to build on my personal server (hoegelow.com). The included traffic is 100GB a month. I was informed by the provider on June, 22th that this quota for June is exceeded.

**Comment by hhoegelo** [comment]
I will still let the ticket opened, so that after talking to @nonlinear-labs we can maybe move the files to NL servers, which would solve the problem and additionally not bind the build process to the availability of a freelancers infrastructure.

**Comment by majjam** [comment]
oh - sorry for helping to killi your qouta ! Din't have an eye to the source addresses.
Just for making sure it is not anything else as mentioned above the output log.
The big downloads worked fine afterwards 
**mount: /internal/AP-Linux-mnt: failed to setup loop device for /workdir/AP-Linux-V.4.0.iso.** happend

[Compile output.pdf](https://github.com/nonlinear-labs-dev/C15/files/4826068/Compile.output.pdf)

**Comment by hhoegelo** [comment]
Indeed, something else seems to be broken, too. Will have a look tomorrow.

**Comment by majjam** [comment]
Would really apreciate that.
Wanted to test the new system since a long time, but not being able to build it myself kept me stay quietly.
I didn't want to disturb the developing process by asking stupid question caused by wrong configurations or faults at my side. 
But now I could not hold it any more ;)
Thanks for having a look into it.

**Comment by hhoegelo** [comment]
@majjam BTW, for using the iso image, you will have to open the housing. I am not sure about the software version of your C15, but if the device is not too old, we could probably upgrade it "over the air".

**Comment by majjam** [comment]
[out of topic] 
i know but I think i have to do the update manually and not via wlan as my serial is 00033. I have an I3-5th gen - system.
But that should not be the problem,  I already had taken an image of my win sytem by using a live linux some time ago.
I can simply connect an Usb hub to the board (for Keyboard ,boot stick and usb-network if necessary ) Also a monitor cable is connected and safely stored. I need only to open left side panel and can take out the wires.

[a bit back into topic]
if possible with my unit and desired by your team I'm happy to help testing the 'user-side' update for the 'old' units.

**Comment by majjam** [comment]
Close Issue :
build system works 
new server integrated
