### ISSUE TITLE
MacroControl Fehlerhafter Ruecksprung bei Bereichsüberschreitung

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2023]
Beta 20-25 RC03
branch       RELEASE-2020-06
commits     4524
head          2fe0d1733
rt version   2.06

Wenn ein Macrocontrol auf 50% in Verbindung mit Pitchbender steht, führen Zuordnungen von HW_Sources mit höheren Grenzen zu Verschiebungen des Returnwertes.

**Beispiel 1 :** 

Init Preset mit Pitch auf +/-2 auf MC-C geroutet 
- MC-C HW Pos steht auf **50**%
- Hw sources 
         Pitchbender mit **50**% amount
         Aftertouch mit **100**% amount

Bei Benutzung :

         1. Taste anschlagen und halten, (oder release auf inf)
         2. Pitchbender links -> pitch = -2 -> OK
         3. PB loslassen -> pitch =  0 -> OK
         4. PB nach rechts -> pitch = +2 -> OK
         5. PB loslassen -> 0 -> OK
         6. Aftertouch komlpett drücken -> pitch = +2 ->OK
         7. AT loslassen -> pitch = -2 -> fail , sollte auf 0 gehen
         8. AT drücken -> pitch = +2 -> ok 

Beispiel 2 : 

Init Preset mit Pitch auf +/-2 auf MC-C geroutet 
- MC-C HW Pos steht auf **50**%
- Hw sources 
         Pitchbender mit **100**% amount

Auch hier bekommt man keine saubere Möglichkeit mehr den Pitchbender einzusetzen. 

Ich denke was passiert ist folgendes:
Bei 100 % Auslenkung der HW source bei nur 50% 'Platz' in der Modulation  wird zwar das Modulationsergebnis geclippt, was richjtig ist, jedoch wird beim Loslassen bzw Rückstellen der HW Source Gesamte Wert wieder abgezogen und liefert somit einen falschen Returnwert.

Zum Ausprobieren ein Preset für Beipiel 1 im Anhang
[test modulations.xml.zip](https://github.com/nonlinear-labs-dev/C15/files/4840265/test.modulations.xml.zip)

Ich denke das ist ein Effekt der bei allen Return-To-Center-HW-Sources auftreten kann.

p.s. : ;Man kann die im Beispiel gewählten Einstellungen evtl. als Fehlbedienung interpretieren, aber das Verhalten zur 1.5/ Reaktor unterscheidet sich. Einge Presets sind selbst nach Adaption der Einstellungen von mir  nicht mehr gleichwertig benutzbar- oder ich bin zu blöd ;)

**Comment by MatthiasSeeber** [comment]
Die MC Positionen in den Displays werden richtig angezeigt. Die inkrementelle Modulation innerhalb der AudioEngine ist offensichtlich nicht imstande, adäquat mit Clipping umzugehen und damit verantwortlich für dieses Fehlverhalten.
**Beispiel 1** reproduziert den Bug auch, wenn der Bender nicht zugewiesen ist.

**Comment by majjam** [comment]
Korrekt Bsp1 ohn PB =>
MC-C 50% +100% AT  = 100% Modulation,
Bei release AT werden dann 0% Modulation daraus.

**Comment by MatthiasSeeber** [comment]
> p.s. : ;Man kann die im Beispiel gewählten Einstellungen evtl. als Fehlbedienung interpretieren, aber das Verhalten zur 1.5/ Reaktor unterscheidet sich. Einge Presets sind selbst nach Adaption der Einstellungen von mir nicht mehr gleichwertig benutzbar- oder ich bin zu blöd ;)

Das ist definitiv ein Bug. Es stimmt schon dass es nicht unbedingt ratsam ist, HW Amounts so hoch einzustellen, dass der Macro ins Clipping fährt - damit verschenkt man quasi Dynamik. Dennoch sollte das Clipping-Verhalten analog zum Reaktor Prototypen funktionieren. So ist das mit Inkrementen, die machen einem nur Probleme ;)

**Comment by majjam** [comment]
Für dieses Beipiel 1 meine Wunschbedienung :
Pitch-OscA mc-amount spielt hier keine rolle Beipielsweise +/-2
MC-C auf pos 50%
PB auf 50%
AT auf 100%
1. PB mittig + AT Voll => +2 (hier hat AT halbe dynamik bzw Sättigungsschwelle ligt bei 50 % )
2. PB links  + AT Voll => +2 (und hier hat at jetzt die komplette dynamik)
2. PB links + AT 0 => -2

**Comment by MatthiasSeeber** [comment]
@majjam ja, genau so sollte die Modulation funktionieren.

> Aber wegen der Anzeige ...
> Bitte mal die Bauchbinde im Oled betrachen, in der WEBUI wird korrekt geclippt, im Oled sieht das anders aus.
> am besten im meine Beipiel preset mal den Pitch-A-mc-amount von +/-2 auf +/- 12 stellen, dann sieht man es besser.
> dann nur AT bedienen.
> altenativ AT drücken und dann parallel Bender benutzen.

Ich kann weder in der WebUI noch in BOLED oder SOLED eine falsche Anzeige von moduliertem Macro bzw. Parameter finden. Der Macro wandert immer schön zurück auf 50% im Return-Fall, der Pitch immer schön zurück auf 60.00 st - so wie es sein sollte. Nur der Klang ist falsch.

**Comment by majjam** [comment]
Bei mir empfinde ich die Darstellung im BOLED als ungewöhnlich, sich da die _Modulationsbereichsindikatoren_ bei AT Vollausschlag nach links verschieben. 
Hier 2 schlechte Fotos, worauf man es vielleicht erkennen kann:
1. Foto einstellung Bsp1  (amount auf 24 => +/1-12
2. Foto AT gedrückt . Unterer Wert verschiebt sich auch auf -24 (36) anstelle von -12 (48)

![MVIMG_20200627_141850](https://user-images.githubusercontent.com/4758563/85922128-423ff080-b881-11ea-9595-21cb300bbaf9.jpg)
![MVIMG_20200627_141854](https://user-images.githubusercontent.com/4758563/85922135-4a982b80-b881-11ea-816b-3e2e98d7a641.jpg)

Aber bei der Darstellungsinterpretation bin ich mir niocht sicher.

**Comment by MatthiasSeeber** [comment]
Oha, danke für die Mühe! Das ist ebenfalls ein Bug..

**Comment by majjam** [comment]
Kein Ding, 
ich profitiere ja davon und Ihr habt die Arbeit ;)
Ich bin nicht sicher, aber ich glaube ich habe solche Effekte auch vorher schon gesehen, aber nie hinterfragt, da der Sound ja passte.

**Comment by MatthiasSeeber** [comment]
Ja, das Problem ist nicht wirklich neu und hat sich offenbar hartnäckig gehalten.. Ich hab dafür ein neues Ticket aufgesetzt.

**Comment by MatthiasSeeber** [comment]
The corresponding PR #2028 was merged git-only (due to server-down), see https://github.com/nonlinear-labs-dev/C15/commit/a10dc852752a5e062b76b9fb337cabbb1a5348da
(both master and RELEASE-2020-06 are up-to-date)
Therefore, this ticket will be manually closed.
