### ISSUE TITLE
Boled: "Only available with Layer Sounds" bugs

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2040]
- [x] weird black pixel in 'd' of Sounds
- [x] align texts centered
- [x] 2 lines: "Only available with" and "Layer Sounds"

**Comment by nonlinear-labs** [comment]
Bitte noch verbessern:
- am unteren bitte vier leere Button-Felder einfügen
- den Parameter-Namen verwenden, sonst denkt man dass der "FB Mixer" "Only available..." ist.
  Vorschlag: wir schreiben in drei (horizontal zentrierte) Zeilen:

             A/B x
is only available with
      Layer Sounds

- Die Schriftfarbe sollte hell sein.
