### ISSUE TITLE
BOLED: Undo für Dual-Sounds: wechselnde Part-Selektion wird bei Undo/Redo nicht sichtbar gemacht (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2045]
Beispiel:
- Part I selektieren, Parameter X selektieren und editieren
- Part II selektieren und Parameter X auch dort editieren
- Undo der letzten Schritte:
  => Der Part-Wechsel wird im BOLED nicht nachvollzogen und die Änderung von Parameter X in Part I bleibt unsichtbar.

**Comment by davidm2894** [comment]
Das passiert weiterhin. Getestet auf 21-22
