### ISSUE TITLE
Boled: HW Source Screen - HW Behavior obscures HW Display Value

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#2052]
![Boled-Tue-Jul--7-11:16:23-2020
](https://user-images.githubusercontent.com/37212609/86761837-8b90fc80-c046-11ea-99ba-6c7b905f2f41.png)

(using RELEASE-2020-06 commit https://github.com/nonlinear-labs-dev/C15/commit/95b569af572538a12410e8b98f3f6428e13e6a7b)

**Comment by schlenkibus** [comment]
Correct me if i am wrong, but the behavior value should not be displayed correct?

**Comment by MatthiasSeeber** [comment]
Yes, it should not be displayed.
Btw, pressing **Soft Button 2** focusses on Behavior, pressing SB 2 again leads to the correct screen.

**Comment by MatthiasSeeber** [comment]
Due to merge in RELEASE-2020-06, this issue can be closed.
