### ISSUE TITLE
WebUI: Echo-Send und Reverb-Send sind hier nicht MC-modulierbar 

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2055]
Die beiden neuen Parameter wurden hier wohl unvollständig implementiert. Im BOLED sind sie ok.

**Comment by MatthiasSeeber** [comment]
Due to merge in RELEASE-2020-06, this issue can be closed.
Also, I double checked all other Parameters in the WebUI for this issue.
