### ISSUE TITLE
Preset Drag&Drop - vertical mouse position flaw

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#2069]
Consider wanting to select Preset 001 for a drag&drop action. If the mouse position while clicking is in the (roughly indicated) red area, the dragged Preset will be 002 (blue).

A simple selection in the red area (a mouse up follows the click, without any drag&drop), Preset 001 will be correctly selected. Even then, a subsequent drag and drop process does not evaluate the vertical mouse position precisely enough and seems to quantize to the next preset.

![vertical-position](https://user-images.githubusercontent.com/37212609/87033968-6982b000-c1e7-11ea-8d59-c6a2587db02b.png)

The Zoom Level seems to play a role in this. The more zoomed in, the smaller the potential of hitting a flawed (red) area.

**Comment by schlenkibus** [comment]
Might be fixed by: https://github.com/nonlinear-labs-dev/C15/pull/2085

**Comment by MatthiasSeeber** [comment]
> Might be fixed by: #2085

Looking good to me.

**Comment by schlenkibus** [comment]
@MatthiasSeeber Thanks for checking / verifying!
