### ISSUE TITLE
PR #2064 double-check

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2071]
#2064 is now part of branches RELEASE-2020-06 and 20-28 and is meant to close the following Issues: 
#2070, #2060, #2014, #2001 

However, it is to be checked, whether the solution is satisfactory or needs rework.

**Comment by MatthiasSeeber** [comment]
For total transparency, there has been another recent (minor) change to the WebUI - see #2076.
