### ISSUE TITLE
"CTRL+H" does not open Online Help 

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2075]
Seems to lead to a wrong online-help address:

[key shortcut](https://github.com/nonlinear-labs-dev/C15/blob/4bd9998c71b029a6e8c450b3a3e2c3d9052f989c/projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/maps/presets/PresetManager.java#L676) -> "/NonMaps/war/online-help/index.html"
vs. 
[mouse click](https://github.com/nonlinear-labs-dev/C15/blob/6f353c30cf2a4803a46a8251dddf5ed5a151728e/projects/NonMaps/src/main/java/com/nonlinearlabs/client/world/overlay/menu/GlobalMenu.java#L194) -> "/NonMaps/MCView/index.html"

**Comment by MatthiasSeeber** [comment]
After successful testing of PR #2076 - which was merged into RELEASE-2020-06 as part of the 20-29 package - this issue can be closed.
