### ISSUE TITLE
[Split] leaving Sound Screen vs Part selector

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#2096]
Consider a Split Sound. When a parameter is selected, **Soft Button 1** will operate as the Part selector.
It also operates the same way when in the Sound Screen.
When changing the Part Selector in the Sound Screen and then leaving the Sound Screen, different behaviors occur:
- using a Parameter Button, the parameter is focussed for the corresponding Part (everything okay here)
- pressing the Sound Button again can bring you back to the last selected Parameter. In this case, the Part Selector indicates the corresponding Part rightly, but the shown parameter slider is from the other Part

Example:
- Make a Split Sound and set Env A Attack in Part 1 to min, in Part 2 to max. Use Soft Button 1 to select a specific Part.
- Then press the Sound Button (the last selected Part is reflected in the Sound Screen). Press Soft Button 1 to select the other Part
- Press the Sound Button again, redirecting to the Env A Attack parameter. The Part indicator is correct, the slider is wrong (from the other part)

**Comment by schlenkibus** [comment]
I will fix this to be put into the next hotfixed release @MatthiasSeeber
