### ISSUE TITLE
HWUI [Shift] on changed Parameter

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#2099]
Consider a freshly loaded Init Sound. Now, select a modulateable Parameter and change its MC Selector. Go back to focus on the Parameter position (which hasn't changed) and press the Shift button in order to revert changes. I think we should consider showing the following only, when the element in focus was in fact changed:

![boled-205800388366](https://user-images.githubusercontent.com/37212609/89285956-a066ad00-d651-11ea-9567-47300c04b800.png)

There is no purpose in wanting to revert to anything when there hasn't been a change, right?

**Comment by MatthiasSeeber** [comment]
While we're at it: When focussing on the position, Soft Button 1 would be available for a possible Part Selector. When focussing on any modulation aspect, this is not possible.

Further, when focussing on Mod Aspects, the caroussel over Soft Button 4 suggests that there is some functionality, but there isn't really. When focussing on the caroussel and pressing Shift, the standard position is shown instead of a changed upper/lower limit:

![boled-802355571318](https://user-images.githubusercontent.com/37212609/89286520-a741ef80-d652-11ea-802d-bf669a94e4ed.png)

**Comment by schlenkibus** [comment]
@MatthiasSeeber regarding your first point in the comment: what do you suggest? I don't see an way to enable part toggling in modulation aspect details.

Regarding the second point: I could disable pressing shift on the modulation limit Carousel or display MC Amount recall. What do you think?

**Comment by majjam** [comment]
@ schlenkibus
is there a way to call the mc (lower or upper ) limit recall ?
MC Amount Recall could end up in irritating people:
example : Preset saved with 
MC Amount = 30 
lower limit = 10 
upper limit = 40.

lower limit is set to 20 by user .
In crousel the upper limit is selected by user and adjusted.
Now he wants to undo this selected value to preset default, which could end up in two scenarios:
1. : Reset MC amount do default  =>  upper limit = 50 (probabl unintended by the user)
2 : Or reset upper limit to 40  => Mc Amount = 20 now

i would prefer second option.

**Comment by MatthiasSeeber** [comment]
@schlenkibus 

> regarding your first point in the comment: what do you suggest? I don't see an way to enable part toggling in modulation aspect details.

As I wrote, this could be implemented when the screen shows a _param position_ slider, on mod aspectst _this is not possible_.

Regarding the upper/lower limit of the caroussel:
Changing a limit means in fact that the param position and the mod amount will change. **If** it is possible to trigger reverting such a change by reverting both aspecct changes, we can keep the caroussel in the screen (when Shift is pressed on a mod aspect) and provide revert actions for the limits. If this is too complicated, we should not provide the caroussel when pressing shift on a mod aspect. The User then has to revert changes to limits by reverting both position and amount separately (as it is currently the case).

**Comment by MatthiasSeeber** [comment]
Update: the core issue (no Shift functionality when aspect hasn't changed) has been implemented. Further possible enhancements have been redirected to #2107, #2108, #2109, rendering this ticket void after merge into release.
