### ISSUE TITLE
BOLED: Das Part-Icon hat nach dem Start oder einem Backup-Restore oft zwei graue Hälften

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2102]
![boled-2505249503269](https://user-images.githubusercontent.com/33938408/89392726-33fbb480-d70a-11ea-95ac-cff967b1ce7c.png)

**Comment by MatthiasSeeber** [comment]
Using Release-2020-06 KW 32 RC2 (https://github.com/nonlinear-labs-dev/C15/commit/29649b851cb2db40ec503edd58525c1ed3f4ebc4), I observed that the Part Indicator always shows a selected Part, even when the currently selected Parameter is a global one - as opposed to previous versions, producing the boled above. We can consider closing this issue.
