### ISSUE TITLE
PanelUnit : "Enable/Disable WiFi" is extremely slow and even crashes the PG sometimes

### ISSUE THREAD

**Issue by KlausStrohhaecker** [nonlinear-labs-dev/C15#2115]
PanelUnit : when changing "Enable/Disable WiFi" the reaction is really slow, C15 UI blocked for several seconds. When trying to toggle the setting the PG completely stalls, then may come up with corrupted/fragmented display and finally crashes and restarts.

Separate topic : After an update to 20-31 I found that WiFi was turned off even though it was on before and a panel unit was required to change that setting.
==> The update process should force WiFi to ON in all cases.

**Comment by KlausStrohhaecker** [comment]
Looks like any update process now automatically disables WiFi. Checked with various updates like 20-32 and 20-33 and the current 2020.06 branch.

If anything, system update should enable WiFi when it was disabled before, but sure not vice versa ;-(

Btw, why is the WiFi setting not found in /persistent/settings.xml ?

**Comment by hhoegelo** [comment]
@KlausStrohhaecker @MatthiasSeeber @nonlinear-labs I think, this one can be closed - what do you think?

**Comment by hhoegelo** [comment]
> Btw, why is the WiFi setting not found in /persistent/settings.xml ?

@KlausStrohhaecker It was a matter of data duplication. The 'real' setting is actually stored in the BBB filesystem by setting symbolic links to systemd-services, controlled by systemd.
Storing the same setting in the xml file on ePC duplicates it and forces us to sync both settings. As asynchronous syncing in a multi-processor system is not trivial, I decided to remove the dispensable setting.
