### ISSUE TITLE
Lower Ribbon: no initial LED display after update to 20-32-RC3

### ISSUE THREAD

**Issue by KlausStrohhaecker** [nonlinear-labs-dev/C15#2116]
After an update from Windows or MS1.7 20-29, 20-32 or 20-31-RC2 to 20-32-RC3 the lower ribbon's LED display is not working, but otherwise the ribbon works correctly (LPC sending values, AE and PG using them -- visible in WebUI).
When one presses any of the buttons on any of the selection panels, the display is updated correctly from then on and that "fix" is persistent, even after a restart.

Interestingly, when re-doing the update (20-32-RC2 --> 20-32-RC3) the bug does not appear.

Double checking with an update from 20-29 to 20-31-RC2 shows no problem as well, so it seems to be something specific to 20-32-RC3.

**Comment by majjam** [comment]
Had the same issue:
After update no lower ribbon indication , modulation was working though
Restart ->  Same issue
Then I selected MC B and switched ribbon 2  off and on again.
Now indication was working correctly. -> OK
Restart -> OK
