### ISSUE TITLE
RT version sometimes not fetched/displayed (never works in 20-32-RC3)

### ISSUE THREAD

**Issue by KlausStrohhaecker** [nonlinear-labs-dev/C15#2117]
In earlier versions than 20-32-RC3, we see that the RT version number sometimes is not fetched and then displays "0" (which is still a bug, btw, it should display "-" or "n/a").

In 20-32-RC3, the LPC version number is never fetched. Fetching the version number manually with the LPC tools works as expected, so it seems to be purely PG-related. Another hint is that restarting the PG, which should initiate the fetch, also just does not do that.

**Comment by AntonSchmied** [comment]
I have 20-23-RC3 currently running and it shows the RT version. Haven't done anything but start up the C15.
Maybe this is rather a general problem?

**Comment by KlausStrohhaecker** [comment]
OK, I see sample size is too low for reliable speculations ;-)
