### ISSUE TITLE
Keyboard shortcut for 'Open MC View' - WebUI

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2127]
I feel like there's a keyboard shortcut missing for opening a new tab with 'MC View' in the WebUI.
Maybe something like 'Ctrl+M'. 
What do you think @nonlinear-labs, @MatthiasSeeber and the rest?

**Comment by MatthiasSeeber** [comment]
Sure, this would be useful and consistent. `Ctrl + M` should also be still available as a shortcut. I just don't see this as a hotfix, but yes.

**Comment by AntonSchmied** [comment]
Yeah, probably not a hotfix ... I changed the milestone, but feel free to move it around, depending on the necessity :)

**Comment by AntonSchmied** [comment]
I just noticed that I can use Ctrl+M and Ctrl+K to increase and decrease the value of the selected Parameter (20-33 Release, using Opera Browser). Should this be reopened, @schlenkibus, @hhoegelo

**Comment by nonlinear-labs** [comment]
"M" and "K" work as decrement/increment for the selected parameter - without "Ctrl".
Therefore "Ctrl + M" and "Ctrl + K" can be used for other purposes.

**Comment by AntonSchmied** [comment]
It was just pointed out to me that you do not need "Ctrl" for incremeting/decrementin with K and M.
So, if "Ctrl+M" opens up the MC View without any abnormal behaviour (f.e. decrementing the selected value AND opening MC View), I think we should be good

**Comment by schlenkibus** [comment]
@AntonSchmied on my machine (Ubuntu 20  tested on Chrome and Firefox) Ctrl + M will not change the Parameter Value and only open the MC View in a new Tab
