### ISSUE TITLE
BOLED: Preset selection animation: Encoder Push != "Enter" button

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2140]
When confirming a preset selection with the enconder push, the animation differs from when using the "enter" button (Release 20-33). Only if the "enter" button is used firstly, does the encoder push provoke the same animation.

**Comment by schlenkibus** [comment]
@KlausStrohhaecker If I remember correctly the missing first animation is a feature and not a bug. Meant to streamline and make the preset switching faster.

**Comment by KlausStrohhaecker** [comment]
> Meant to streamline and make the preset switching faster.

This is definitely a good idea. If that animation is (quasi-)blocking then we should try to avoid when it is clear that it would could stall other tasks. And making it a fully a non-blocking background job or the like is probably not worth the effort...

**Comment by schlenkibus** [comment]
Yes, Stephan said it was enough that the borders / color indicate that the preset is loaded. And reloading the current preset will still trigger the animation to give feedback that a reload has happened.

**Comment by schlenkibus** [comment]
@KlausStrohhaecker the bouncing button is an different issue and should be handled as such, do you have it in your backlog?
@nonlinear-labs can you confirm my interpretation of this issue and close / state what has to be changed for this ticket accordingly?

**Comment by KlausStrohhaecker** [comment]
> @KlausStrohhaecker the bouncing button is an different issue and should be handled as such, do you have it in your backlog?

Intermittent contact of the encoder button this is a pure hardware issue, no way to deal with it (other than using the button on a regular basis to keep contacts clean).
The lesson to be learned from that is that we should continue to never have any features that are encoder-button only and cannot be reached with other buttons. The encoder button is way less reliable and will die sooner than the other push-buttons.

**Comment by schlenkibus** [comment]
@KlausStrohhaecker then the current implementation makes sense: encoder push will be propagated like a enter push. Maybe we should prevent further usage of `Buttons::BUTTON_ENCODER`?

HWUI::onButtonPressed :
```  
if(buttonID == Buttons::BUTTON_ENCODER)
    buttonID = Buttons::BUTTON_ENTER; 

cont...

**Comment by nonlinear-labs** [comment]
There was a misunderstanding. Loading a preset for the first time should not have an animation (to avoid blocking delays), re-loading should have the animation (to create a visible reaction in the display). This is independent from the use of the encoder button or the Enter button.
The current software (20-33) behaves correctly. There is nothing to do.
