### ISSUE TITLE
WiFi war nach dem Start überraschenderweise disabled (hat sich also von allein ausgeschaltet)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2147]
Version 20-33 (Head c1aa7a..)

Hatten wir nicht gerade in dem Bereich etwas umgebaut?

**Comment by KlausStrohhaecker** [comment]
Nun auch auch jedem Neustart auftretend...

**Comment by hhoegelo** [comment]
@nonlinear-labs Please retest with 20-35 or later - I strongly believe, this one is fixed - (hopefully).

**Comment by KlausStrohhaecker** [comment]
@hhoegelo, ^ Tested 20-35 RC1 and first impression is good, WiFi stays enabled after update / reboot.

**Comment by hhoegelo** [comment]
@KlausStrohhaecker @MatthiasSeeber @nonlinear-labs Do you think we can close this one?

**Comment by nonlinear-labs** [comment]
geschlossen - s.#2269
