### ISSUE TITLE
WebUI: Steigender MC Amount kann (bei expon. Scaling, z.B. Env Times) zu negativen Lower Limits führen. Hier fehlt ein Clipping.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#216]
Bei quadratischer Skalierung (z.B. Echo Time) steigt Lower Limit beim Überschreiten der unteren Grenze auf positive (quadrierte?) Werte.

**Comment by schlenkibus** [comment]
Ist das noch aktuell? Das Lower Limit ist zwar im negativen Bereich, aber es wird explizit darauf hingewiesen dort geclipt wird.

**Comment by nonlinear-labs** [comment]
Das Problem tritt nur noch in der WebUI/Bauchbinde auf.
Erst (z.B. bei Attack Time) MC Amount erhöhen, bis unten ein Clipping auftritt, dann Lower Limit anschauen.
