### ISSUE TITLE
sscl User apparently has no power over /persistent 

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2170]
When trying to scp files from BBB to ePC:/persistent, it results in failure due to the lack of permissions.
Example: 
`sshpass -p 'sscl' scp /internalstorage/foo sscl@192.168.10.10:/persistent`
`Warning: Permanently added '192.168.10.10' (ECDSA) to the list of known hosts.`
`scp: /persistent/foo: Permission denied`

`ls -lah /` on the ePC shows that only the SU has the appropriate rights for this:
`drwxr-xr-x   4 root root 4.0K Sep  4 11:59 persistent`

Can we allow sscl to have more power, please? Could make it a bit easier here and there.

**Comment by hhoegelo** [comment]
@AntonSchmied So far, we just added a 'sudo' in front of the according command.
Let me know, if that already fixes your problem. If not, I will fix the permissions for the 'persistent' mount point, so sscl will be allowed to write it.

**Comment by AntonSchmied** [comment]
So since this seems to be a minor obstacle, effecting only moving files (settings.xml, preset-manager, calibration) from BBB to ePC, and we don't see any further need for 'sscl' to receive further rights on the ePC, we will keep this in mind but close the Issue for now.
