### ISSUE TITLE
WebUI: new order for Bank Edit Menu Items

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2191]
Sort Bank Edit Menus like this: 
![image](https://user-images.githubusercontent.com/15381257/93312450-84852800-f807-11ea-8f41-c5e85e019d18.png)
![image](https://user-images.githubusercontent.com/15381257/93312461-87801880-f807-11ea-8988-38e7cb4e3044.png)

**Comment by schlenkibus** [comment]
Tino suggested to add an "Export Selected Bank as File" Item to the Background-Right-Click-Menu. @nonlinear-labs @MatthiasSeeber what are your thoughts about adding that?

**Comment by MatthiasSeeber** [comment]
I don't see any problem with that.

Just a suggestion: maybe indicate the Bank name in (brackets), for at least the background menu?
`Export Bank (2 - Keys) to File...`
