### ISSUE TITLE
WebUI: Add To FX and FB Indicators to Sound Belt

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2202]
Mockups:
![image](https://user-images.githubusercontent.com/15381257/94034606-8419fd80-fdc2-11ea-8640-00bcaedce7f5.png)
![image](https://user-images.githubusercontent.com/15381257/94034623-88deb180-fdc2-11ea-8878-8754d36e28da.png)
![image](https://user-images.githubusercontent.com/15381257/94034633-8aa87500-fdc2-11ea-869b-f99e4431e1e0.png)
![image](https://user-images.githubusercontent.com/15381257/94034645-8e3bfc00-fdc2-11ea-8b64-5db19ca0ca74.png)

TODO:
- [ ] Get SVGs

**Comment by majjam** [comment]
Nice one!
