### ISSUE TITLE
Audio-Engine: "Comb FIlter - PM" ungleich Null kann DC-Verschiebungen verursachen. Bei polyphonem Spiel kann das Ausgangssignal im Clipper verschwinden.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2206]
Es gibt viele Beispiele in der Arovane-Bank. Referenz ist "Carbon Pad". Härter anschlagen und mindestens 3-stimmig spielen.

Comb Test.zip](https://github.com/nonlinear-labs-dev/C15/files/5277616/Comb.Test.zip)

Die hier attachte "Comb Test"-Bank enthält vereinfachte Versionen. Für "Carbon Pad tst 5" gilt:
kein Unison, keine Effekte, nur Comb im Output Mixer, nur Osc A verwendet, Env A als Plateau, ohne Velocity, kürzeres Attack, keine Wirkung von Env C, Comb AP und Hi Cut unwirksam, Comb Pitch höher, Comb Decay kürzer

Das Problem wächst mit höherem positiven Decay (Feedback). Vom Pitch scheint es relativ unabhängig zu sein.

Wenn man den SVF als Hochpass hinter den Comb Filter schaltet, ist das Problem weg, was die These mit dem DC-Offset unterstützt.

**Comment by MatthiasSeeber** [comment]
@AntonSchmied , @nonlinear-labs 
So far I can confirm that the "AP Eco" in the R5 Prototype does NOT produce offsets. So, the basis for the AE code seems alright. Concludingly, the bug has to be somewhere in the implementation (most likely since Milestone 1.5).

**Comment by MatthiasSeeber** [comment]
With the KW-40 RC 1 update, this issue is fixed.
