### ISSUE TITLE
[Playground] Crash when setting MC Sel to [-]

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2212]
Issue:
If MC Sel is decreased from A to [-] Playground crashes and restarts.
(A Parameter which has no MC connected shows [-] without any problems)

Version:
![grafik](https://user-images.githubusercontent.com/4758563/94369092-0d457300-00e8-11eb-90c1-e0e3cbec0edf.png)

Example setting :
![grafik](https://user-images.githubusercontent.com/4758563/94369159-5d243a00-00e8-11eb-85cd-d0f3052dd063.png)
Press Dec(-) button and Playgound crashes

**Comment by schlenkibus** [comment]
Thanks for the report, I will fix this asap!
