### ISSUE TITLE
Falsche (nicht ausgefüllte) Kreis-Symbole für A, B, C, D der MCs

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#222]

**Comment by hhoegelo** [comment]
development done, but waiting for BOLED font containing the symbols at the same positions as in the web font.

**Comment by nonlinear-labs** [comment]
[BOLED-Fonts-2018-08-16.zip](https://github.com/nonlinear-labs-dev/C15/files/2293450/BOLED-Fonts-2018-08-16.zip)

**Comment by hhoegelo** [comment]
fixed by #247
