### ISSUE TITLE
update procedure: fails if no epc update wanted/required

### ISSUE THREAD

**Issue by KlausStrohhaecker** [nonlinear-labs-dev/C15#2224]
In the main update script **run.sh** we have the follwoing lines, allowing to enable/disable the various component of the update:
`ASPECTS="playcontroller bbb epc"`
Removing an item from that string is supposed to leave the component as is, not updating.
This is checked to work with **playcontroller** (formerly **lpc**). I haven't checked **bbb**.
Disabling **epc** causes a failure as ePC is still accessed in various places

**Comment by AntonSchmied** [comment]
Allow me to reopen the issue. The introduced fix does the job, but i feel there can be a more smoother way to deal with this matter.

**Comment by KlausStrohhaecker** [comment]
Yeah, this is more a hack than a smooth fixup, things definitely could be done nicer and with wider scope, for a stable behavior with **any** combination of the "aspects".

**Comment by AntonSchmied** [comment]
I encountered something that needs to be discussed concerning epc2. So this Issue will not be part of the December Release.
