### ISSUE TITLE
WebUI: Fade Point/Fade Range Editor

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2238]
![Layer-Split-Editor-test-b](https://user-images.githubusercontent.com/15381257/95440819-aa5ea200-0959-11eb-941f-1c93110f91b5.png)
![Fade-Editor-Btn-test-a](https://user-images.githubusercontent.com/15381257/95440875-bcd8db80-0959-11eb-867e-4f22c3aaacd7.png)

**Comment by MatthiasSeeber** [comment]
I think, the Sound Belt mockup lacks the icon for the editor, see:

![fade-editor-btn-test-c](https://user-images.githubusercontent.com/37212609/95449261-cddb1a00-0964-11eb-8b7a-f180f430d66f.png)

**Comment by schlenkibus** [comment]
Okay, i see, so the icon in the middle is some kind of indicator, and the button on the right hand side opens the fade editor?

**Comment by MatthiasSeeber** [comment]
Correct. In the middle, the icon (per Part) just indicates if a Fade occurs (lower example) or not (upper example). A Fade will occur when the corresponding Fade From differs from the default position (which is on the edge - C1 for Part I and C6 for Part II).
The icon on the right should redirect to the Fade Editor.

**Comment by MatthiasSeeber** [comment]
> Correct. In the middle, the icon (per Part) just indicates if a Fade occurs (lower example) or not (upper example). A Fade will occur when the corresponding Fade From differs from the default position (which is on the edge - C1 for Part I and C6 for Part II).
> The icon on the right should redirect to the Fade Editor.

Correction: Default Fade From positions correspond to full sliders, so it's the other way around:
- Part I : C6 (slider is filled from left to right)
- Part II : C1 (slider is filled from right to left)

The "Fade Info" Icons per Part, if a fade occurs:
- Part I : Icon should look like a highpass
- Part II : Icon should look like a lowpass (as shwon in the mockup for Part II)
