### ISSUE TITLE
Split Point UI Iteration

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2241]
prerequisite: new icons from tino

- [x]  boled Split Sound Layout overhaul -> 2 points if not synced
- [x] new symbols for overlap and sync for webui and boled

**Comment by schlenkibus** [comment]
First mockups: 
![image](https://user-images.githubusercontent.com/15381257/96558355-d82dda00-12bb-11eb-9c13-2ee06afa45f2.png)
![image](https://user-images.githubusercontent.com/15381257/96558369-dc59f780-12bb-11eb-812b-5d358d2935e3.png)

**Comment by nonlinear-labs** [comment]
The Splitpoint UI can have only 3 states:
- Synced
- Unsynced without overlap
- Unsynced with overlap

For this we need only one new control element:
- WebUI: a button that can be activated to "unsync" the splitpoints, it should be available in the Sound Tab and in the Parameter Tab of the Splitpoint (on the button I would use the "overlap" icon with the rectangles)
- BOLED: a new entry "Sync/Unsync" in the Edit menu of the Splitpoint Parameter Screen and "Sync/Unsync Splitpoints" in the Edit menu of the Split Sound Screen

The "Unsynced" mode is indicated by showing both Splitpoint values:
- in the Splitpoint Tab/Screen they are in one line, connected by a dash, the one of the non-selected Part in a gray font
- in the Split Sound Tab/Screen they are vertically aligned, the left on top of the right, with short lines to the left resp. right block, the one of the non-selected Part in a gray font

**Comment by schlenkibus** [comment]
Boled:
- [ ] Sound Edit Menu Sync Enable Disable
- [ ] Overlap Indicator next to Parameter Values
WebUI:
- [ ] replace temp Button with proper Sync/Unsync Button
- [ ] add Overlap Indicator next to Parameter Values
