### ISSUE TITLE
[Layer] Part Muting still affects Output Mix "To FX I / II"

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#2266]
@nonlinear-labs this is still not as intended, right?

In a special uses case (when having a Part's "To FX" on 100%), Muting the Part might not make any difference.

- [x] if considered as a bug: remove Part Muting from Out Mix Send (presumably as a hotfix)

**Comment by nonlinear-labs** [comment]
As discussed today, we agreed that the Part Muting should affect the Part Volume only, and not have any "side"-effects.

**Comment by MatthiasSeeber** [comment]
Fix was successfully merged into `staging` via #2280 and `unstable` via #2281 - closing this ticket.
