### ISSUE TITLE
WebUI: Multiple Selection nach dem Ausführen einer Aktion auf die selektierte Gruppe von Presets bitte disablen.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2267]
Wenn man mehrere Presets selektiert hat und sie per Drag+Drop verschiebt oder kopiert, wird die multiple Selektion danach ausgeschaltet. Das sollte auch bei Delete, Color Tag und Copy passieren.

**Comment by schlenkibus** [comment]
Ich kann das Problem auf meinem aktuellen Stand nicht nachvollziehen: Ich selektiere mehrere Presets mit einem Auswahl Rechteck oder Shift + Klick und folgende Aktionen beenden die Multiple Selektion: 
- copy
- color tag
- drag + drop auf die Welt
- drag + drop in den belt
- drag + drop in eine bestehende Bank
- drag + drop auf ein preset
(og. drag und drop actions mit und ohne direct load)
- delete

**Comment by hhoegelo** [comment]
@nonlinear-labs Is there any other action that you have in mind and that @schlenkibus did not test and that behaves differently?

**Comment by nonlinear-labs** [comment]
Bei "Delete" auf multiple Presets lässt es sich mit der Version 20-49 zuverlässig reproduzieren, dass danach die Multiple Selection nicht wieder ausgeschaltet wird.
