### ISSUE TITLE
Es kann passieren, das WiFi nach dem Start  fälschlicherweise disabled ist.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2269]
Das ist einmal beim Kunden passiert, einmal hier. Vielleicht können wir noch besser sicher stellen, dass das nicht falsch initialisiert wird.

**Comment by KlausStrohhaecker** [comment]
Passiert bei meinem auch immer wieder mal, besonders nach einen Update (speziell wenn während des Updates keine Antenne dran ist).

**Comment by KlausStrohhaecker** [comment]
also see https://github.com/nonlinear-labs-dev/C15/issues/2147

**Comment by nonlinear-labs** [comment]
Ist wahrscheinlich gefixt worden. Bei fertigen Geräten nicht mehr beobachtet worden.
