### ISSUE TITLE
WebUI: Neue Option in GUI Settings: "Link Part Selection to Hardware UI" (On/Off)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2270]
User haben zurecht darauf hingewiesen, dass es verwirrend sein kann, wenn in der WebUI und die Hardware-UI verschiedene Parts selektiert sind.

Wenn "Link ..." = On ist, sollte die Part-Selektion in beiden Richtungen synchronisiert werden.

Wenn das neue Setting Browser-lokal gespeichert würde, könnte man auf einem zweiten Gerät oder Browser immer noch den anderen Part öffnen. Das ist aber nicht so wichtig.

**Comment by schlenkibus** [comment]
Das Feature existiert seit einer weile schon: 
![Screenshot from 2020-11-03 06-21-03](https://user-images.githubusercontent.com/15381257/97952232-f48e4400-1d9c-11eb-9e81-02d669f48bdf.png)

Einen Umbau auf ein Lokales Setting koennen wir uns vornehmen.
