### ISSUE TITLE
WebUI - oft schlechte Grafik-Qualität durch fehlende Subpixel (ungeglättete Kanten)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2278]
Die Schrift sieht "angefressen" aus, aber auch unsere Grafikelemente haben unsaubere Kanten.

Nach einem Verschieben oder Resizen des Browser-Fensters wird der Canvas-Inhalt wieder mit Kantenglättung gezeichnet.

Browser: Chrome unter Windows. Das Problem tritt seit 2-3 Wochen auf. Kann sein, dass es mit einem Browser-Update zusammenhängt.

![WebUI ungeglättet](https://user-images.githubusercontent.com/33938408/97983147-1efbf380-1dd5-11eb-91bc-16e7dac1fd6c.png)

**Comment by hhoegelo** [comment]
Gibt's das Problem noch immer mit Chrome 87.0.4280? Ich kann es weder auf Linux noch auf Windows reproduzieren in der genannten Chrome Version. @nonlinear-labs

**Comment by nonlinear-labs** [comment]
Habe gerade auf Chrome 87 upgedatet. Das Problem ist jetzt nicht reproduzierbar, ist aber vorher auch nicht jeden Tag auf jedem Computer aufgetreten. Hoffen wir mal, dass es eine temporäre Unverträglichkeit war. Ich schliesse den Issue und mache einen neuen, wenn's wieder auftritt.
