### ISSUE TITLE
Fade Range Editor - einige Issues

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2282]
- [ ] In Chrome unter Windows ist der Editor kürzer als die Tastatur-Grafik (Screenshot unten). In Firefox gibt es das Problem nicht.

![Fade Editor in Chrome](https://user-images.githubusercontent.com/33938408/98015382-01db1b00-1dfd-11eb-9875-7d5b7b555481.PNG)

- [x] Mit dem Zahlenfeld lassen sich bei schnellen Bewegungen nach links in der Grafik auch negative Fade-Ranges einstellen.

![inverse fade ranges](https://user-images.githubusercontent.com/33938408/98040842-45478080-1e21-11eb-8295-9841121fc6b2.PNG)

- [x] Die unteren Anfasser für die Fade Ranges sollten normalerweise in Schritten von ganzen Semitones einrasten. Nur, wenn Shift gedrückt wird, in Schritten von 0.1 Semitones. Das ist konsistenter mit den Zahlen-Editfeldern und dem Verhalten im Parameter-Tab.

**Comment by MatthiasSeeber** [comment]
Punkt eins ist auch in #2277 beschrieben.

**Comment by schlenkibus** [comment]
@MatthiasSeeber bezueglich des Namings dieses Editors: ich stimme dir zu das in Richtung der Kunden entweder ein generischer Name oder deine Beiden Vorschlaege kommuniziert werden sollten. Aktuell wird der 'Fade Range Editor' aber nirgends textlich erwaehnt.
