### ISSUE TITLE
MIDI Implementierung: Preset-Bank, die als Ziel/Quelle für Program-Changes dient, auswählbar machen

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2284]
- [x] Die betreffende Bank bekommt in der UI im/am Header eine Markierung (vielleicht ein kleines Dreieck).
- [x] Die Auswahl erfolgt über einen neuen Eintrag im Bank-Kontextmenü. (Bessere Lösung als im Bank-Info-Dialog)
- [x] Die zuletzt ausgewählte Bank ist die einzige. Wenn man ihre Auswahl zurücksetzt, gibt es keine "Bank for MIDI PC". Ankommende MIDI-PC-Events werden dann ignoriert, und über MIDI-Out werden keine PC-Events verschickt.
- [ ] Weil die Bank vielleicht schwer zu finden ist, in den Device-Settings/MIDI ein Eintrag: "Bank for MIDI PC:" <Nummer_der_Bank>
oder "none".
- [x] Wenn die ausgewählte Bank gelöscht wird, gibt es erst einmal keine "Bank for MIDI PC".
- [x] Die Eigenschaft wird in der XML-Datei gespeichert.

**Comment by schlenkibus** [comment]
@nonlinear-labs wenn die Midi-Bank nicht in das XML abgespeichert werden soll, ist damit das Bank XML gemeint, oder gemeint das ein Neustart die selektierte Midi-Bank resettet?

**Comment by nonlinear-labs** [comment]
Ich meinte das XML-File für den Bank-Export. Die Auswahl sollte nach einem Neustart erhalten bleiben und auch in einem Gesamt-Backup gespeichert werden.
