### ISSUE TITLE
Unsynced Split Points - Rest-Todos

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2290]
- [x] Bug: Bei alten Split-Presets werden die Splitpoints bei disableten Sync fälschlicherweise so dargestellt, als wenn sie identisch sind, sich also um einen Semitone überlappen.
- [x] Der Sync-Status sollte beim Laden eines Preset gesetzt werden, bei (SP_II > SP_I, Overlap=Null) auf On (enabled) und bei (SP_II <= SP_I, Overlap>Null)  auf Off (disabled). Wir brauchen dafür also keinen eigenen Parameter.
- [x] Wenn Sync disabled war und der Overlap auf Null gestellt wurde, wird Sync beim Speichern des Presets enabled. Das gleiche passiert beim Laden eines Presets mit Null Overlap.
- [x] Der Overlap-Indikator ("!") kann entfallen, denn es reicht völlig, wenn im Sync ein Splitpoint gezeigt wird und ohne Sync zwei Splitpoints (unterschieden durch die Verwendung von "|" und "-").
- [x] remove overlap indicator for WebUI
- [x] Beim Editieren mit Sync=Off sollte im Splitpoint-Parameter-Screen/Tab immer ein Wertepaar zu sehen sein. Allerdings sollte es by Overlap=Null durch einen *senkrechten" Strich statt Bindestrich getrennt werden. Im Sound-Screen/Tab soll in diesem Fall eine senkrechte Linie zwischen den beiden Splitpoint-Werten gezeichnet werden, weil sie jetzt nicht mehr unabhängig sind.
- [x] Bei Sync=Off und Overlap > Null sind im Splitpoint-Parameter-Screen/Tab die beiden Werte durch einen Bindestrich verbunden. Anders als bisher sollte der größere Wert aber rechts stehen.
- [x] BOLED Splitpoint-Parameter-Screen: die graue Farbe des Splitpoint-Wertes des nicht selektierten Parts sollte etwas dunkler sein (wie von "Volume" im Karussell).
- [x] Bei Overlap=Null und Sync=On im Sound-Screen auch wieder die zwei senkrechten Linien über und unter dem Splitpoint-Wert zeichnen.
- [x] BOLED: Die Sync Enable/Disable-Funktion sollte nicht nur im Menü des Splitpoint-Parameters, sondern auch im Split-Sound-Edit-Menü angeboten werden. Dort ist sie schneller zu finden und von der Logik her auch gut aufgehoben.

**Comment by nonlinear-labs** [comment]
Zum ersten Häkchen: Wenn man Sync=disabled hat, werden beim Laden eines alten Split-Presets die zwei Splitpoints im Soundscreen als identisch (= 1 st überlappend) dargestellt.

Zum zweiten Häkchen: Der Sync-Mode sollte beim Laden eines Presets ohne Overlap wieder auf "Enabled" wechseln. Er ist also quasi mit dem Preset (Overlap ?= 0) gespeichert.

**Comment by schlenkibus** [comment]
Kann es sein das dein Kommentar sich auf diesen Release bezieht: https://github.com/nonlinear-labs-dev/C15/releases/tag/KW46 ? Falls das der Fall sein sollte, muss ich darauf hinweisen das dieser PR noch nicht in dem Build enthalten war/ ist.

**Comment by nonlinear-labs** [comment]
Ja, das wird so sein. Etwas neueres als KW46 habe ich ja hier nicht...
