### ISSUE TITLE
MIDI-Out: Aftertouch wird nicht korrekt gesendet. Nach jedem neuen Wert wird immer noch einmal eine Null gesendet.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2291]
Das kommt vielleicht von der 14-Bit-Lösung für die CCs.
Für die normalen Channel-Aftertouch-Messages gibt es aber keine LSBs.

![MIDI AT Out](https://user-images.githubusercontent.com/33938408/98742116-252e3900-23ae-11eb-89d4-c4d881371b3d.PNG)

**Comment by MatthiasSeeber** [comment]
Since the introduction of explicit 2-byte MIDI messages, Program Change and Aftertouch messages work properly, without an additional message with zero in it.
