### ISSUE TITLE
WebUI: Preset-Bauchbinde: Loadbutton, Preset-Nummer, Sternchen, Lock-Symbol bitte statisch und mit ausreichendem Abstand layouten 

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#233]

**Comment by hhoegelo** [comment]
fixed by #252

**Comment by nonlinear-labs** [comment]
Wenn man das Fenster Stück für Stück schmaler macht, springt irgendwann (kurz bevor der Block mit den Menü-Buttons verschwindet) der Abstand zwischen der Presetliste und den Up/Down Buttons auf die doppelte Breite. Das ist nicht so schön.
