### ISSUE TITLE
/build-tools and its structure is nested under /playcontroller again when building a C15-update.tar 

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2339]
Sowohl /build-tools als auch die Struktur werden beim Bauen eines Updates anscheinend doppelt angelegt, unter anderem halt auch in dem /playcontroller Ordner. Muss das so?

**Comment by hhoegelo** [comment]
Ja das ist kein Bug: Fuer die Cross-Builds wird je Maschine (ePC, BBB, Playcontroller) ein eigenes Build-Directory angelegt (build-tools/[maschine]. In diesen Directories wird dann jeweils mit cmake und den fuer die Zielplattform benoetigten Settings ein Build-System fuer die Zielplattform gebaut. Daher finden sich dort alle Files eines Build-Systems erneut - aber eben anders konfiguriert als in dem 'Macro'-Build-System. Was Du da gefunden hast, sind also nested-Build-Systems fuer die jeweiligen Ziel-Plattformen. 
Um die Verwirrung etwas zu lindern, habe ich einen PR aufgemacht, der innerhalb der nested build systems die ungenutzten Projekte ausspart.
