### ISSUE TITLE
WebUI - Developer Options: "Enable External Midi" bitte ersetzen durch "Enable USB Communication"

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2373]
Ein bisschen weniger verräterisch... ;-)

**Comment by hhoegelo** [comment]
> Ein bisschen weniger verräterisch... ;-)
Jetzt haben es ehh alle in GitHub gesehen.

**Comment by nonlinear-labs** [comment]
Die meisten unserer Kunden sind nicht in GitHub unterwegs. Wenn sie nach dem Update in der UI etwas von MIDI lesen, weckt das zu frühe Erwartungen.

**Comment by schlenkibus** [comment]
> Die meisten unserer Kunden sind nicht in GitHub unterwegs. Wenn sie nach dem Update in der UI etwas von MIDI lesen, weckt das zu frühe Erwartungen.

Sofern der User die Developer Optionen in der WebUI angestellt haben. Nur in den Dev. Options gibt es ja diesen Schalter.
