### ISSUE TITLE
Performance-Einbruch/WiFi-Ausfall/Einfrieren mit MIDI-Schachtel am USB-Anschluss

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2376]
Wenn ich Klaus' MIDI-Schachtel (V1.0) zwischen Computer und C15-USB-Buchse stecke, bricht die Performance der HW-UI ein. Vieles wird träge, einige Eingaben werden ignoriert. Einmal ist die UI komplett eingefroren. Die WebUI kann nicht dargestellt werden, weil das C15-WiFi abbricht.

Es ist dabei egal, ob "External MIDI" vorher enabled oder disabled wurde.

Version: KW 50 beta

**Comment by hhoegelo** [comment]
Problem ist auch ohne midi-over-ip beobachtbar. 

dmesg sagt Folgendes:

[  308.007241] usb 1-1.2: new high-speed USB device number 5 using musb-hdrc
[  308.157206] ieee80211 phy0: rt2x00usb_vendor_request: Error - Vendor Request 0x07 failed for offset 0x0438 with error -71
[  308.200703] usb 1-1-port2: cannot reset (err = -71)
[  308.206500] usb 1-1-port2: cannot reset (err = -71)
[  308.220835] usb 1-1-port2: cannot reset (err = -71)
[  308.240097] usb 1-1-port2: cannot reset (err = -71)
[  308.246482] usb 1-1-port2: cannot reset (err = -71)
[  308.258198] usb 1-1-port2: Cannot enable. Maybe the USB cable is bad?
[  308.267607] usb 1-1-port2: cannot reset (err = -71)
[  308.277598] usb 1-1-port2: cannot reset (err = -71)
[  308.288963] usb 1-1-port2: cannot reset (err = -71)
[  308.295335] usb 1-1-port2: cannot reset (err = -71)
[  308.307108] ieee80211 phy0: rt2x00usb_vendor_request: Error - Vendor Request 0x07 failed for offset 0x0438 with error -71
[  308.318736] usb 1-1-port2: cannot reset (err = -71)
[  308.323851] usb 1-1-port2: Cannot enable. Maybe the USB cable is bad?
[  308.347355] usb 1-1-port2: cannot reset (err = -71)
[  308.357963] usb 1-1-port2: cannot reset (err = -71)
[  308.368512] usb 1-1-port2: cannot reset (err = -71)
[  308.387371] usb 1-1-port2: cannot reset (err = -71)
[  308.392906] usb 1-1-port2: cannot reset (err = -71)
[  308.408180] usb 1-1-port2: Cannot enable. Maybe the USB cable is bad?
[  308.427588] usb 1-1-port2: cannot reset (err = -71)
[  308.433213] usb 1-1-port2: cannot reset (err = -71)
[  308.447392] usb 1-1-port2: cannot reset (err = -71)
[  308.458055] usb 1-1-port2: cannot reset (err = -71)
[  308.467819] usb 1-1-port2: cannot reset (err = -71)
[  308.473277] usb 1-1-port2: Cannot enable. Maybe the USB cable is bad?
[  308.497490] usb 1-1-port2: unable to enumerate USB device
[  308.503641] usb 1-1.1: USB disconnect, device number 3
[  308.558292] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[  308.582422] ftdi_sio 1-1.1:1.0: device disconnected
[  308.642638] usb 1-1.3: USB disconnect, device number 4
[  309.007512] usb 1-1: reset high-speed USB device number 2 using musb-hdrc
[  309.476867] usb 1-1.1: new full-speed USB device number 9 using musb-hdrc
[  309.583604] usb 1-1.1: New USB device found, idVendor=0403, idProduct=6001
[  309.590910] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  309.601435] usb 1-1.1: Product: FT232R USB UART
[  309.606209] usb 1-1.1: Manufacturer: FTDI
[  309.611838] usb 1-1.1: SerialNumber: AB0JDXIU
[  309.624204] ftdi_sio 1-1.1:1.0: FTDI USB Serial Device converter detected
[  309.636684] usb 1-1.1: Detected FT232RL
[  309.649066] usb 1-1.1: FTDI USB Serial Device converter now attached to ttyUSB0
[  309.746894] usb 1-1.2: new high-speed USB device number 10 using musb-hdrc
[  309.754407] usb 1-1-port2: cannot reset (err = -71)
[  309.761395] usb 1-1-port2: cannot reset (err = -71)
[  309.766605] usb 1-1-port2: cannot reset (err = -71)
[  309.772712] usb 1-1-port2: cannot reset (err = -71)
[  309.778355] usb 1-1-port2: cannot reset (err = -71)
[  309.783475] usb 1-1-port2: Cannot enable. Maybe the USB cable is bad?
[  309.791040] usb 1-1-port2: cannot disable (err = -71)
[  309.796505] usb 1-1-port2: cannot reset (err = -71)
[  309.802520] usb 1-1-port2: cannot reset (err = -71)
[  309.808111] usb 1-1-port2: cannot reset (err = -71)
[  309.813453] usb 1-1-port2: cannot reset (err = -71)
[  309.819550] usb 1-1-port2: cannot reset (err = -71)
[  309.824672] usb 1-1-port2: Cannot enable. Maybe the USB cable is bad?
[  309.832302] usb 1-1-port2: cannot disable (err = -71)
[  309.838162] usb 1-1-port2: cannot reset (err = -71)
[  309.843354] usb 1-1-port2: cannot reset (err = -71)
[  309.849262] usb 1-1-port2: cannot reset (err = -71)
[  309.854458] usb 1-1-port2: cannot reset (err = -71)
[  309.860301] usb 1-1-port2: cannot reset (err = -71)
[  309.865419] usb 1-1-port2: Cannot enable. Maybe the USB cable is bad?
[  309.872933] usb 1-1-port2: cannot disable (err = -71)
[  309.878724] usb 1-1-port2: cannot reset (err = -71)
[  309.883915] usb 1-1-port2: cannot reset (err = -71)
[  309.889759] usb 1-1-port2: cannot reset (err = -71)
[  309.894954] usb 1-1-port2: cannot reset (err = -71)
[  309.900893] usb 1-1-port2: cannot reset (err = -71)
[  309.906014] usb 1-1-port2: Cannot enable. Maybe the USB cable is bad?
[  309.913898] usb 1-1-port2: cannot disable (err = -71)
[  309.920363] usb 1-1-port2: unable to enumerate USB device
[  309.926537] usb 1-1-port2: cannot disable (err = -71)
[  309.933756] hub 1-1:1.0: hub_port_status failed (err = -71)
[  309.946251] usb 1-1.1: USB disconnect, device number 9
[  309.958700] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0

**Comment by KlausStrohhaecker** [comment]
I could recreate the error locally, it looks like a simple USB timing issue, the LPC chip must be run at a higher clock frequency for a stable detection by the BBB's linux/kernel which is obviously different in timing than that of the ePC, general purpose laptops etc.
The tradeoff is increased power consumption.

**Comment by nonlinear-labs** [comment]
Wurde mit der neuen LPC-Firmware behoben.
