### ISSUE TITLE
HW-UI sehr buggy (s.u.) - leider schwer reproduzierbar

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2387]
Folgende Probleme sind bei der KW 51 staging beta (nach einigen Tests mit Screen Saver und Split-Sounds) aufgetreten. Nach Neustart sind sie leider nicht reproduzierbar:
- [ ] Activity Overview defekt
- [ ] Parameter-Screen: Balken des Karussells "tot"
- [ ] MC-Target-LEDs: zeigen falsche Zustände
- [ ] Signal Flow Indication für Envelopes defekt
- [ ] Presetwechsel öffnet Parameter-Screen

**Comment by MatthiasSeeber** [comment]
- [ ] Menus bleiben nach Abschluss offen: Store, Rename
