### ISSUE TITLE
Splitpoints: Das Umschalten von Unlinked/overlapping Mode in Linked Mode wird nicht an die Audio-Engine weitergegeben.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2391]
Die Audio-Engine assignt weiterhin den bisherigen überlappenden Bereich, bis man einmal den Splitpoint-Parameter verstellt.

**Comment by MatthiasSeeber** [comment]
Tested on https://github.com/nonlinear-labs-dev/C15/releases/tag/Staging-Beta-51, could locate bug
- [ ] _HWUI Sound Edit Menu_: AudioEngine still has potential overlap (see description)
- [x] HWUI Parameter Edit Menu: ok - AudioEngine behaves as expected
- [x] WebUI Sound Tab Menu: ok
- [x] WebUI Split Editor Icon: ok
- [x] WebUI Parameter Icon: ok
