### ISSUE TITLE
Preset-Screen/Tab: Der Status des "To Part"-Buttons wird zwischen HW-UI und WebUI nicht synchronisiert

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2393]
("Direct Load" = On)

Wenn man "To Part" auf der WebUI einschaltet, bleibt "To Part" im BOLED aus. Wenn man dann in der HW-UI ein anderes Preset selektiert, passieren merkwürdige Dinge und spätestens beim zweiten Increment wird "To Part" in der WebUI wieder ausgeschaltet.

Wenn man "To Part" auf der HW-UI einschaltet, bleibt "To Part" in der WebUI aus. Sie verhält sich aber, als wenn "To Part" an ist. Wenn man z.B. auf ein Preset klickt, lädt man es in den selektierten Part. Dabei bleibt "To Part" in der HW-UI aktiv.

Ich glaube, wir müssen einfach nur den Status von "To Part" in allen UIs synchronisieren.

**Comment by nonlinear-labs** [comment]
("Direct Load" = On)

Wenn man "To Part" auf der WebUI einschaltet, bleibt "To Part" im BOLED aus. Wenn man dann in der HW-UI ein anderes Preset selektiert, passieren merkwürdige Dinge und spätestens beim zweiten Increment wird "To Part" in der WebUI wieder ausgeschaltet.

Wenn man "To Part" auf der HW-UI einschaltet, bleibt "To Part" in der WebUI aus. Sie verhält sich aber als wenn "To Part" an ist. Wenn man z.B. auf ein Preset klickt, lädt man es in den selektierten Part. Dabei bleibt "To Part" in der HW-UI aktiv.

Ich glaube, wir müssen einfach den Status von "To Part" in allen UIs synchronisieren.

**Comment by schlenkibus** [comment]
> ("Direct Load" = On)
> 
> Wenn man "To Part" auf der WebUI einschaltet, bleibt "To Part" im BOLED aus. Wenn man dann in der HW-UI ein anderes Preset selektiert, passieren merkwürdige Dinge und spätestens beim zweiten Increment wird "To Part" in der WebUI wieder ausgeschaltet.
> 
Da "Direct Load", global, An und "Load to Part" ,auf der HWUI, Aus sind wird beim Preset Selektieren auf der HWUI das ganze Preset geladen. Das die WebUI damit nicht klar kommt konnte ich nachvollziehen. Mein Vorschlag: der Load to Part modus Stellt sich auf jeder UI aus wenn ein Preset geladen wird, was schon bei Sound Typ wechseln der Fall war.

> Wenn man "To Part" auf der HW-UI einschaltet, bleibt "To Part" in der WebUI aus. Sie verhält sich aber als wenn "To Part" an ist. Wenn man z.B. auf ein Preset klickt, lädt man es in den selektierten Part. Dabei bleibt "To Part" in der HW-UI aktiv.
> 

Auch hier wuerde ich den Fix vorschlagen das Overlay ueber den Presetmanager wegzuschmeissen, das heisst den Load to Part modus zu beenden wenn ein Preset geladen wird.
