### ISSUE TITLE
MC-Modulation auf Unlinked Split-Points: der angezeigte Overlap schwankt um einen Halbton, die Split-Ranges der Audio-Engine sind um einen Halbton größer oder kleiner als in der UI

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2394]
Wahrscheinlich ein Rundungs-Probleme:
- verschiedene Rundungsgrenzen für die Werte von SP I und SP II
- verschiedene Rundungsgrenzen in der UI und in der Audio Engine

**Comment by MatthiasSeeber** [comment]
**Specific Values**:

MC (center value: `50%`) on _linked_ SplitPoint (default: `F#3 - G3`), ModAmt = `1ST` (ModRange: `pos - 0.5 ST` - `pos + 0.5 ST`):

| MC | 0% | 50%| 100% |
| --- | --- | --- | --- |
| UI | (ok) `F3 - G3` (!) | (ok) `F#3 - G3` (ok) | (!!) `F#3 - G#3` (ok) |
| AE | (ok) F3 - F#3 (ok) | (ok) `F#3 - G3` (ok) | (!!) `F#3 - G3` (!!) |

**Comment by MatthiasSeeber** [comment]
I would like to point out that a good strategy for modulating the Split Point would be to start with the Macro Ctrl at _min_ or _max_, before setting the Mod Amount of the Split Point. As the observations show, the 0% and 100% cases work reliably when doing so - as opposed to starting with the default center MC position, currently leading to buggy/inconsistent behavior.

Nevertheless, we seem to require a good and consistent quantization strategy for the Split Point, shared by UI and AE.
- linked Split Points always have to be `1ST` apart (as well as unlinked Split Points with no overlap)
- overlapping Split Points always have to be `1 + overlapping ST` apart

A good thing might be to produce and quantize a modulated Split Point first for Part I, before using this value for adding the integral `1 + overlapping ST` for the other Part (always maintaining the distance of the two Split Points) ?

**Comment by nonlinear-labs** [comment]
(( Auf späteren Milestone verschoben, weil wir einen gründlicheren Lösungsansatz finden müssen. ))

**Comment by schlenkibus** [comment]
Another one:

Als Bug tritt ein Overlap im Linked Mode auf.
Split auf default pos stellen.
MC A auf 0% stellen
Assign A auf Split
Set Mod Amt auf 1 st
Set MC A auf 95%
Auf G3 erklingen beide Parts

**Comment by MatthiasSeeber** [comment]
zwei generelle Ansätze (müssten in UI und Synth implementiert werden):

1. Sonderfall Split Point Parameter: obwohl in beiden Parts vorhanden hat er nur EINE Control Position, welche moduliert und dann quantisiert wird. Für die Part-spezifischen Werte werden dann integralle Offsets draufgerechnet (wie oben beschrieben).
2. möglicherweise kein Sonderfall sondern generell: wenn ein Parameter moduliert wird, sollte (ModAmount * MacroPos) auf die Parameter Resolution quantisiert werden, bevor die Control Position sich bewegt. Modulationen unterhalb einer Parameter Resolution verschwinden quasi in der Quantisierung.

**Comment by schlenkibus** [comment]
current implementation of issue-2394:

|0% init|	0 |	50 |	100
| --- | --- | --- | --- |
ui |		F#3-G3 |	F#3-G3 |	G3-G#3
ae |		F#3-G3 |	G3-G#3 |	G3-G#3

| 50% init | 0 | 50 | 100
| --- | --- | --- | --- |		
ui |		F#3-G3 |	F#3-G3 |	G3-G#3
ae |		F3-F#3 |	F#3-G3 |	F#3-G3

| 100% init | 0 | 50 | 100
| --- | --- | --- | --- |	
ui |		F3-F#3 | 	F#3-G3 |	F#3-G3
ae |		F3-F#3 |	F#3-G3 |	F#3-G3

**Comment by MatthiasSeeber** [comment]
Nach bisherigen Umbauten bleibt nur noch ein Problem beim Split Point übrig, die Range Restriktionen (CP insgesamt: 0 ... 60 --> ModAmt -60 ... 60, CP I allerdings: 0 ... 59, II 1 ... 60).

Bei einem voll modulierten Split Point kommt derzeit Part I auch hoch bis C6 (60), man kann also anders modulieren als einstellen. Gleichermaßen kommt Part II auch runter bis C1 (0).

Mit den weiteren vorhandenen Plänen (duale Modulation des Split Points über unabhängige MCs und Amounts) weichen sich die Restriktionen eh auf, sodass wir der Einfachheit halber die vorhandenen Restriktionen wegnehmen können und sinnvolle Einstellungen komplett dem User überlassen.

Das harmoniert allerdings nicht besonders mit der Verlinkung beider Parts (II = I + 1). Die beiden Rand-Positionen sind quasi nicht mit einer Verlkinkung kompatibel. Bei einem verlinkten Split Point müsste die Verlinkung deaktivieren, wenn man CP I auf 60 hochdreht bzw. CP II auf 0 runterdreht.

Alternativ könnte die Range um die Zustände -1 und 61 erweitert werden. Diese Zustände bedeuten dann Clipping, bzw. das effektive Verschwinden eines Parts aus dem Key-Bereich. Es sollte nicht möglich sein, einen Slider explizit auf diese Positionen zu stellen, allerdings sollten indirekt (durch Modulation oder Verlinkung) diese Zustände erreichbar sein. An der Auflösung (0 ... 60) und der Mod Range (-60 ... 60) sollte sich nichts ändern.
