### ISSUE TITLE
HWUI :No reactions on buttons after screensaver

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2407]
After a time I am not able to change the HWUI by button presses any more.
If i switch anyting in the WEBUI , BOLED menu entries are following.
Ribbin indicators are fine, too

I had this behaviour twice:
first time : after update  +  some minutes to play
second time : I made a restart then played for some minutes = > again.
third restart : all seems to be ok

![grafik](https://user-images.githubusercontent.com/4758563/103007117-2321d300-4533-11eb-9e8d-4cded59600be.png)

**Comment by nonlinear-labs** [comment]
I have the same issue after installation of the 20-52 and the first start.

**Comment by majjam** [comment]
i changed the title : it seems to happen after bringing the hwui back to life after the screensaver.
Screensaver time is 1 minute here

**Comment by majjam** [comment]
testet with latest staging (5381 commits)
Works for me so i close this.
thanks !
