### ISSUE TITLE
Nebenwirkung des Updates 20-52 (oder des Update-Installers): Ribbon Relative Factor in der Wirkung auf 1 zurückgesetzt.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2413]
Unser Kunde Till Kopper:
> Nach dem Update war allerdings die Beschleunigung der relativen
> Ribbonbewegungen wie bei einem Wert von 1 in den Settings. Mein
> üblicher Wert von 5.5 war aber in den Settings eingetragen. Nachdem
> ich den aber dann verstellt und wieder auf 5.5 zurückgestellt habe
> ging es wieder wie gewohnt. War also nur ein kleines
> Initialisierungsproblem.

**Comment by schlenkibus** [comment]
@nonlinear-labs Ist dieses Ticket noch aktuell und ein eventueller Show-Stopper?

**Comment by nonlinear-labs** [comment]
Ich würde das Ticket schliessen und hoffen, dass es ein seltener Fall in einer bestimmten Update-Konstellation ist.
