### ISSUE TITLE
MIDI - Settings, Part 1 

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2428]
**Globale Optionen / Settings:**

Setup > MIDI:     (neue Page, an erster Stelle, über Dev-Option sichtbar geschaltet)

**"Receive":**

"Channel":                 Omni, 1...16, Off
"Channel II (Split)":   "Follow I", Omni, 1...16, Off

"Program Changes":   On/Off
"Notes":                      On/Off
"Controllers":              On/Off

"Velocity Curve":          ...
"Aftertouch Curve":      ...

**"Send":**

"Channel":                  1...16, Off
"Channel II (Split)":     "Follow I", 1...16, Off

"Program Changes":    On/Off
"Notes":                       On/Off
"Controllers":               On/Off

"Velocity Curve":          ..., intern
"Aftertouch Curve":      ..., intern

**"Local":**

"Program Changes":    On/Off
"Notes":                       On/Off
"Controllers":               On/Off

"PC = Off" isoliert die MIDI-PC-Bank von der Audio-Engine und den übrigen Bänken. Das heisst: Ein Aufruf in der MIDI-PC-Bank hat keine Wirkung auf die Bank-Selektion. Vielleicht nehmen wir eine andere Selektions-Farbe/Markierung für Bank-Header und Preset. Die übrigen Bänke funktionieren normal. "Direct Load" wird bei der MIDI-PC-Bank nicht angeboten.

**Comment by MatthiasSeeber** [comment]
Anmerkungen/Fragen:
1. Sind **Receive**, **Send**, **Local** als _Operations-Modi_ (von denen einer gelten kann) zu verstehen oder eher als _Aspekt-Gruppen_ (oder Reiter)?
2. Wenn der optionale Zweit-Channel bei _Split Sounds_ separat laufen soll, wie ist dann die Wirkung des Split Points gedacht? Hebelt ein "Channel Split" den Split Point nicht aus?
3. Der Split Point (und die Fade From/Range) Parameter und Editoren sollten auf 128er Ranges erweitert werden, um MIDI voll auszuschöpfen. (Vielleicht besser via separatem Ticket?)

**Comment by nonlinear-labs** [comment]
1.) "Receive", "Send", "Local" sind keine Modi, sondern "Reiter"/Zwischenüberschriften für drei Gruppen von Settings. Sie behandeln drei möglichen Kommunikationswege, die ggf. gleichzeitig genutzt werden - zwei über MIDI In/Out und die interne Kopplung zwischen Spiel-Oberfläche und der Audio-Engine. Letztere muss man auch unterbrechen können, wenn man in den Sequencer spielt, während dieser den C15 ansteuert, oder wenn man den C15 als Masterkeyboard für andere Synths verwendet.
2.) Für MIDI Send: die Keys, die Part I ansteuern, schicken MIDI-Noten über den ersten der beiden MIDI-Kanäle raus, die Keys von Part II gehen über den zweiten MIDI-Kanal (falls separiert, sonst über den ersten). Die Splitpoints legen die Grenzen auch für die gesendeten Noten fest.
Für MIDI-Receive: Falls die Kanäle separiert sind (Follow I = Off), kann Part I über den ersten MIDI-Kanal gespielt werden, Part II über den zweiten. Die Splitpoints werden dabei ignoriert. Wenn alles über den ersten MIDI-Kanal läuft, wirken die Splitpoints wie bei der internen Tastatur.
