### ISSUE TITLE
WebUI: Layer Sound Tab: Der Fade-Indikator von Part II ist immer an

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2436]
![Fade Range Indikator Bug](https://user-images.githubusercontent.com/33938408/105746694-0ddc0200-5f40-11eb-9f63-9427cbe60093.PNG)

**Comment by schlenkibus** [comment]
@nonlinear-labs Ist dieses Ticket noch aktuell und ein eventueller Show-Stopper?

**Comment by nonlinear-labs** [comment]
Bei mir war es reproduzierbar. Ich hatte kein Update, um zu überprüfen, ob's noch aktuell ist.
Wir können das Ticket erstmal schliessen. Wenn's wieder auftritt, wird es mir beim Test sofort auffallen.

**Comment by nonlinear-labs** [comment]
Wenn es noch da ist, ist es ein Showstopper.. ;-)

**Comment by nonlinear-labs** [comment]
Das Problem ist in der 21-06 staging leider noch da

**Comment by nonlinear-labs** [comment]
Wenn die Bedingungen für den State im Browser-Java-Code bestimmt wird: Vergleich von Floats ? Lieber noch was Kleines drauf addieren vor dem Vergleich.

Mein Browser: Chrome 88 unter Windows 10.
