### ISSUE TITLE
WebUI: Docking: Wenn in der letzten Spalte zwei Bänke übereinander sind, lässt sich eine längere Bank nicht an der oberen andocken

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#245]
Wenn die anzudockende Bank länger ist als die obere Bank, berührt sie beim Heranschieben auch die untere, und es wird nur ein Docking mit der unteren Bank angeboten.

**Comment by schlenkibus** [comment]
Necessary information needed to fix:
Rule which determines the order of docking priorities. Which bank should be docked to if 2 Tapes are available for docking?

**Comment by nonlinear-labs** [comment]
Also: (ich schreib's in Deutsch): Den vertikalen Abstand der beiden nächstliegenden Header zum Header der anzudockenden Bank bestimmen. Die Bank, deren Header den kürzeren Abstand hat, sollte die Docking-Priorität bekommen.
