### ISSUE TITLE
Die Hardware Source "Aftertouch" wird nicht als MIDI-Aftertouch rausgeschickt

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2454]
Soweit ich mich erinnere, lief das früher schon einmal.

**Comment by MatthiasSeeber** [comment]
Auf **unstable** beobachte ich: von der WebUI ausgehend kommen MIDI Out Messages mit Status `0xD0`. (LPC-Verhalten kann ich leider nicht testen, gehe aber laut Code davon aus, dass das auch klappen sollte).

Unstable entspricht aber sicher nicht der Version um die es geht?

Auffällig ist noch, dass der derzeit auf 7 Bit reduzierte AT von der WebUI aus wegen des Auto-Return smoothings viele MIDI Messages mit Wert Null erzeugt (was wir wohl besser wegfiltern sollten...).
