### ISSUE TITLE
 midi-over-ip.service hat Probleme mit zuviel zu schnell empfangenen Daten, und/oder großen SysEx-Daten, stallt den BBB

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2462]
Beim Flashen der MIDI-Bridge klicken die Relais des C15, der gleichzeitig am anderen Port angeschlossen ist.

Klaus: Das ist keine erlaubte Betriebsart für das FW-Update der Bridge ;-)
Was da wohl passiert: die Bridge ist zwar noch als USB-Device da, reagiert aber nicht mehr auf irgendwas. Vermutlich bringt das den C15 durcheinander und zwar so dass die Audio-Engine abstürzt. Das wiederum veranlasst den Playcontroller-LPC dass er dem Supervisor sagt er soll muten.

Vielleicht liegt das Problem nicht in der Audio-Engine sondern im MIDI-Proxy.

**Comment by KlausStrohhaecker** [comment]
Was ich schon mal sicher sagen kann, die AE mag offenbar keine SysEx Daten (in dem Fall über 20kBytes am Stück), dann kommt es zu dem Aussetzer -- aber nur beim ersten mal. Und dann beim Abstecken der MIDI-Bridge wieder.
AE meldet: http://192.168.10.11:40108  ->  The server did not accept the WebSocket handshake.

Und der BBB meldet per dmesg sched: RT throttling activated
Irgendwas überfährt ihn da...

Schritte zum Reproduzieren des "zuviele Daten" und/oder SysEx Phänomen.
- C15 anschalten, ohne Bridge
- Bridge anstecken am C15
- Bridge anstecken am PC
- Einmal am Bender wackeln oder sonstwie MIDI-Daten generieren, egal auf welcher Seite (damit verlässt die Bridge die Scharfstellung auf etwaiges programmiert werden, das muss in der ersten Message nach Power-Up geschehen)
- Vom Rechner aus das Update-SysEx senden oder etwas anderes großes. Die Bridge versucht das durchzustellen. --> Relais klappert.
- Nochmal Senden --> klappert nicht, Daten kommen durch (sagen die LEDs).
- MIDI-Bridge am C15 abstecken --> klappert

**Comment by KlausStrohhaecker** [comment]
Nach dem "RT throttling activated" sagt top auf dem BBB:
461     1 root     S    51596  10%  96% /usr/C15/midi-over-ip/midi-over-ip -i hw:0,0,0 -o hw:0,0,0 -a 192.168.10.10

**Comment by KlausStrohhaecker** [comment]
Beim Brennen kann ich keine Probleme feststellen, der BBB merkt dass das USB-Device nicht mehr reagiert und meldet es ab. Danach abstecken (auf beiden Seiten, also Power-Down der Bridge), wieder anstecken, und alles geht wieder.

**Comment by KlausStrohhaecker** [comment]
Testen mit https://github.com/nonlinear-labs-dev/C15/pull/2497 bringt keine Änderung....

**Comment by schlenkibus** [comment]
Kurze Info: ich habe den BBB befragen koennen was er von einem midi-bridge update haelt. Folgende infos konnte ich der midi-over-ip-exe entlocken: Bytes kommen an und sind im inputhandle "available", nach N reads gibt snd_rawmidi_read einen errorcode -11  zuerueck -> "Resource temporarily unavailable". So richtig schlau bin ich daraus nicht geworden. Ausserdem habe ich folgende .syx dateien verschickt: 
-rw-r--r-- 1 justus justus  24K Mär  4 10:53 big.syx
-rw-r--r-- 1 justus justus  127 Mär  4 10:53 test127.syx
-rw-r--r-- 1 justus justus  128 Mär  4 10:53 test128.syx
-rw-r--r-- 1 justus justus  129 Mär  4 10:53 test129.syx
-rw-r--r-- 1 justus justus  107 Mär  4 10:53 test.syx
 nur bei dem big.syx konnte ich ein stallen des BBBs beobachten. Das verschicken von dem 'updates' von port zu port auf einem PC auf dem die mid-over-ip-bridge lief fuehrten zu keinem stalling.

**Comment by KlausStrohhaecker** [comment]
OK, d.h. es ist BBB-spezifisch offenbar. Ich mache mal Tests ab welcher SysEx-Größe es kritisch wird.

"Resource temporarily unavailable"... ja, k.A. was er uns damit sagen will. Die Bridge wartet auf das der BBB ein Packerl zu (max) 64 Bytes abnimmt bis er auf der anderen Seite wieder hinhört, was also somit den Sender bremst (wird sein nächstes Paket kurz nicht los). Solange der nicht vor Wut abbricht weil es zu langsam geht kann auf BBB Seite der Zustand des unavailable-seins von seiten der LowLevel-Hardware bzw unteren USB-Protokollebenen ja eigentlich nicht vorkommen. Man kann dem raw_midi_* Gedöns größere Puffer zuweisen mit `snd_rawmidi_params_set_buffer_size()` (mache ich auch im perf-test tool) aber so richtig klar ob das was hilft (oder überhaupt was macht) ist mir nicht....

**Comment by KlausStrohhaecker** [comment]
Ab (nicht) zufällig genau 4096+128 (also 4224) Bytes an empfangenen SysEx-Daten stallt midi-over-ip.
Ich probier mal den erwähnten buffer größer zu setzen...
