### ISSUE TITLE
WebUI: Developer Options: Die Schaltfelder können in Safari nicht bedient werden

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2490]

**Comment by schlenkibus** [comment]
Um welche Safari- und OS-Version handelt es sich?

**Comment by nonlinear-labs** [comment]
Kann ich leider nicht sagen. Es war ein Kunde, dem wir eine MIDI-Box geschickt haben. Ich hatte ihn im Video-Chat. Er hat es nicht geschafft, die "USB-Communication"-Option von Off nach On zu stellen. Erst mit dem Chrome-Browser ging es.

**Comment by schlenkibus** [comment]
Ich kann den Bug leider nicht bearbeiten, da mein (veraltetes) IPad sich weigert in Safari die WebUI anzuzeigen. Und Apple kein Safari fuer Windows oder Linux anbietet. Ich leite das Ticket weiter an @hhoegelo

**Comment by hhoegelo** [comment]
@nonlinear-labs Das Ticket kann wohl auch zu: Die Option "USB-Communication" gibt's ja gar nicht mehr. Andere Optionen kann ich mit Mac OS 11.4 und Safari 14.1.1 ohne Probleme auf meinem MacBook nutzen.

**Comment by nonlinear-labs** [comment]
Wir haben das hier auch getestet. Wir können den Issue schliessen.
