### ISSUE TITLE
Input Event Stage (MIDI/TCD refactoring)

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2495]
![inputstage](https://user-images.githubusercontent.com/15381257/109171657-490d6300-7782-11eb-909f-8830fe9f869e.png)

**Comment by MatthiasSeeber** [comment]
Sorry for the delay, here is a more detailed desccription, which maybe shall be further discussed.
[C15 Midi & Ctrl Flow - v2.pdf](https://github.com/nonlinear-labs-dev/C15/files/6075233/C15.Midi.Ctrl.Flow.-.v2.pdf)

**Comment by MatthiasSeeber** [comment]
At this point, the InputEventStage is developed and tested. Required features are established, so I think this general ticket has no more need to be open.
