### ISSUE TITLE
Screensaver: Das Timeout wird durch eine Betätigung des "Setup"-Buttons nicht zurückgesetzt.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2501]
Bitte prüfen, ob es noch mehr User-Aktionen gibt, die den Timeout nicht zurücksetzen.

**Comment by schlenkibus** [comment]
Ich brauche mehr Infos um diesen Bug einzuschaetzen, Setup Knopf druecken, beendet und setzt den Screensaver timeout wie ich es erwarten wuerde. Steps to reproduce waeren super! @nonlinear-labs

**Comment by nonlinear-labs** [comment]
Also, meine Beweislage war mager... Ich hatte es einmal erlebt, dass kurz nach dem Drücken der Setup-Taste der Screensaver angesprungen ist. Aber ich kann es jetzt noch einmal nachzuvollziehen:
- Screensaver auf 1 Minute stellen
- "Preset"-Taste drücken und dabei die Stopuhr o. ä. starten
- nach 50 Sekunden die "Setup"-Taste drücken
=> 10 Sekunden später geht der Screensaver an (das sollte erst nach 60 Sekunden passieren)

**Comment by schlenkibus** [comment]
Das kann ich reproduzieren, danke!
