### ISSUE TITLE
Flac Recorder : Klicking noise while playing 

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2510]
Depends on the sound 

1. Record some chords with **Bank 03 -Program 018 Tilly2** 
2. On recorder page : select recorded chords and press play. (let record button on ON)
3. while playing recorded snippet : additionally play melody on keyboard with the same sound selected.
=> the mixed sound output gives clicking noises (while both recorded snippets are clean !)
so i think this happens in the mixing not in synthesis.

(have in mind that i use i3-5 and it could be a performance issue, too .)

**Comment by hhoegelo** [comment]
fixed in flac-3 branch
