### ISSUE TITLE
WebUI : Flac recorder page becomes unresponsive on zoom 

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2511]
I f you zoom out too much - 16 clicks and more to (-) Symbol - the recorder page becomes unresponsive.
Closing an reopening works fine !
Probably the maximum zoom can be regulated to 3 hours or so.( Or not all waveforms shall be calcaluted for the Preview.)

**Comment by hhoegelo** [comment]
fixed in flac3 branch
