### ISSUE TITLE
Erweiterte MIDI Settings für Hardware Sources und Notes (s. u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2512]
- [ ] Das MIDI-Menü wird um den Eintrag "Mapping" erweitert:
- Receive
- Send
- Local
- Mapping

- [ ] Die bisherigen "Enable xxx"-Zeilen der Receive/Send/Local-Pages werden durch eine detailliertere Liste ersetzt:
[MIDI Channels+Enable.pdf](https://github.com/nonlinear-labs-dev/C15/files/6108035/MIDI.Channels%2BEnable.pdf)
Bis auf die Channels sind die möglichen Werte für alle Einträge "On/Off" (Default: On). In der Send-Page kann nun auch das Senden des Notes-LSB (CC 88) abschalten. Beim Empfang wird es immer ausgewertet.
Das bisherige "Enable" würde ich weglassen. Es ergibt sich aus den Namen des Menüs, z.B.: "MIDI > Send" "Pedal 1"
Auf der  Local-Page entfällt die Zeile für Program Change (wurde schon früher beschlossen).

- [ ] Die neue "Mapping" Page enthält 8 Zeilen für die Hardware Sources mit jeweils einem längeren Menü zur Auswahl der benutzten MIDI-Events/CCs:
[MIDI Mapping.pdf](https://github.com/nonlinear-labs-dev/C15/files/6108069/MIDI.Mapping.pdf)
Diese Auswahl wird für Send und Receive verwendet.
Bitte beachten, dass für Pedal auf CC 64...69 eine Reduktion auf 1 Bit ( ?> 50 %) erfolgt und nur dann Events verschickt werden sollen, wenn die 50%-Grenze über/unterschritten wird. Beim Empfang wird 0...63 auf 0 % und 64...127 auf 100 % gemappt.
Ein zweiter Spezialfall ist das Mapping von Aftertouch auf die positive (up) bzw, negative (down) Hälfte von MIDI Pitchbend. Ansonsten ist alles wie bisher, nur mit der freien Wahl der CCs zwischen 01 und 31 (mit zugehörigen LSBs) und der Option, auch Bender und Aftertouch auf solche CCs zu mappen.

**Comment by MatthiasSeeber** [comment]
Ebenfalls zu beachten:
- wenn der Bender als Pitchbend versandt wird, muss die volle 14-Bit Breite [_0...16383_] ausgeschöpft werden (wie bisher)
- wenn der Bender als CC LSB/MSB versandt wird, müssen stattdessen geclippte Werte [_0...16256_] genutzt werden, damit das LSB optional bleibt (wie bisher die Pedale und Ribbons)
- Aftertouch muss je nach Setting sowohl im bisherigen 7-Bit-Format [_0...127_], als auch im geclippten 14-Bit-Format [_0...16256_] gehandhabt werden
