### ISSUE TITLE
ePC2 cannot build install medium / iso creation fails

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2515]
$ **make epc2-create-install-medium**
[100%] Built target epc2-setup-host-os
[100%] Built target epc2-setup-target-os

Scanning dependencies of target epc2-create-install-medium
[100%] Create iso for installing a minimal nonlinux 2021-03-04
/dev/pts/1
warning: config file /etc/pacman.d/mirrorlist, line 1: directive 'Server' in section 'options' not recognized.
warning: config file /etc/pacman.d/mirrorlist, line 1: directive 'Server' in section 'options' not recognized.
warning: config file /etc/pacman.d/mirrorlist, line 1: directive 'Server' in section 'options' not recognized.
:: Synchronizing package databases...
 nonlinux               54.3 KiB  13.3 MiB/s 00:00 [######################] 100%
warning: config file /etc/pacman.d/mirrorlist, line 1: directive 'Server' in section 'options' not recognized.
warning: config file /etc/pacman.d/mirrorlist, line 1: directive 'Server' in section 'options' not recognized.
warning: config file /etc/pacman.d/mirrorlist, line 1: directive 'Server' in section 'options' not recognized.
**error: target not found: archiso**
make[3]: *** [build-tools/epc2/install-medium/CMakeFiles/epc2-create-install-medium.dir/build.make:62: build-tools/epc2/install-medium/nonlinux-2021-03-04.iso] Error 1
make[2]: *** [CMakeFiles/Makefile2:1474: build-tools/epc2/install-medium/CMakeFiles/epc2-create-install-medium.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1481: build-tools/epc2/install-medium/CMakeFiles/epc2-create-install-medium.dir/rule] Error 2
make: *** [Makefile:502: epc2-create-install-medium] Error 2

**Comment by hhoegelo** [comment]
Fixed in unstable, thanks for reporting
