### ISSUE TITLE
Undo History: Time-Stamp pro Eintrag und "Goto Time..."-Funktion

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2521]
In der Anwendung des FLAC-Recorders wäre es sehr nützlich, wenn man zu den Preset/Parameter-Einstellungen zurückspringen könnte, die man in einer Phase des aufgenommenen Spiels verwendet hat. Eine typische Fragestellung wäre also: "Das klingt gut. Ich will es noch einmal spielen. Welches Preset oder welche Editerierung eines Presets war das?"

Eine manuelle Eingabe einer Zeit als Sprungziel in der Undo-Liste wäre ausreichend. Die Zeit würde man von der Recorder-Abspielposition auslesen. Vielleicht ist auch eine Kopplung der Undo-Reproduktion an das Abspielen des Aufnahme denkbar.

Unser einzigartiges Undo-System bekäme damit einen zusätzlichen Nutzen und würde sehr wirkungsvoll demonstriert.

**Comment by hhoegelo** [comment]
Mir faellt nichts ein, warum das prinzipiell nicht moeglich sein sollte: Timestamps an den Undo-Transaktionen zu speichern ist kein Problem. Die Suche nach der richtigen Transaktion koennte - ohne zusaetzliche Optimierungen - bedeuten, dass der gesamte Baum traversiert werden muss, aber das sehe ich nicht als Problem an.
Die sog. ContinuousTransactions fassen viele gleichartige aufeinanderfolgende Aktionen zu einer zusammen - darin ueberlebt nur der erste und der letzte Schritt (Beispiel: Ich drehe langsam an einem Parameter). Hier koennte es in der Reproduktion zu Ungenauigkeiten kommen, wenn die Aufnahme bei einem der mittlerweile verworfenen Schritte gestartet wurde.

**Comment by majjam** [comment]
Alternativ könnte man natürlich auch einen TCD recorder/player implementieren....

**Comment by hhoegelo** [comment]
> Alternativ könnte man natürlich auch einen TCD recorder/player implementieren....

Schon, aber der gesamte System-State (Sound-Typ, Parameter-Stellungen, Sound-relevante Settings) muesste zusaetzlich wiederhergestellt werden, damit auch der selbe Sound wieder rauskommt.

**Comment by nonlinear-labs** [comment]
Wir hatten schon ziemlich früh Pläne für einen "Event-Recorder". Die Umsetzung wäre aber erheblich aufwendiger als der jetzt entwickelte Audio-Recorder. Man käme damit auch in die Nähe von MIDI-Sequencern und müsste mit vielen Feature-Requests z.B. zur Editierbarkeit rechnen. Mit unserer Unterstützung von MIDI kann man Spielvorgänge ausreichend genau (extern) aufnemen und wiedergeben. Die Editierung überlassen wir den Sequencern.
Mit dem FLAC-Recorder reagieren wir u.a. auf die Forderung nach einem Digital-Ausgang und umgehen auf elegante Weise die Clock-Sync-Probleme einer digitalen Audio-Schnittstelle. Er ist auch ein gutes Notizbuch, gerade in Verbindung mit einem Timestamp-fähigen Undo-System. Und er eröffnet die Möglichkeit, menschliches Spiel oder MIDI-getriebene Sequenzen verlustfrei im C15 aufzunehmen und sehr einfach in den Rechner zu importieren. Damit liegt der C15 - bis auf leichte Einschränkungen beim MIDI-Timing - auf dem Qualitätsniveau von Plug-ins.

**Comment by majjam** [comment]
Mein Kommentar zum TCD recorder war auch eher dem Featurewahn unterlegen als Anwendungsbezogen.
Ich finde den Flac recorder in seiner Idee echt richtig gut ! Kurz hatte ich über eine Loopfunktion nachgedacht um sich selbst zu begleiten zu können, aber auch das zieht schnell viel Unheil mit sich (sync usw).

(DIe Midi Implementierung hat mich ehrlich gesagt sehr überrascht.)
