### ISSUE TITLE
MIDI Settings - Mappings: Weitere Einträge für "None" und 7-Bit-Controller (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2548]
Jedes der acht Menüs bekommt am Anfang den Eintrag "None".

Jeden Eintrag der Form "CC nn (LSB: CC mm)" sollten wir ersetzen durch solche zwei Einträge:
  CC nn
  CC nn + CC mm (LSB)

Damit haben User, die bereits viele CCs belegt haben, die Möglichkeit, Konflikte mit unseren LSB-CCs zu vermeiden, haben dann natürlich nur noch eine 7-Bit-Auflösung. Die Einstellungen wirken identisch für Send und Receive.

Die Listen werden ziemlich lang, aber die angezeigte Belegung sieht sauber aus.

**Comment by majjam** [comment]
Idee , um die Liste etwas kürzer zu halten :

![grafik](https://user-images.githubusercontent.com/4758563/113756609-e2c91800-9711-11eb-8571-70f42031491b.png)

**Comment by schlenkibus** [comment]
see #2589
