### ISSUE TITLE
FLAC-Recorder Ergänzungen

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2551]
**Scrollen + Zoomen:**
- [x] Nur noch über die Navigations-Leiste (nicht mehr über Wellenformfläche)
- [x] Die Position des Play Cursors und eine eventuelle Selektion sollten in der Navigationsleiste immer sichtbar sein.

**Abspielen:**
- [x] Der Play-Button soll zwischen Play und Pause toggeln. (Shortcut: die Leertaste des Computers)
- [x] Der Play-Cursor kann unabhängig von der Selektion gesetzt werden.
- [x] Er wird gesetzt, indem man in den äusseren dunklen Bereich der Wellenformfläche klickt.
- [x] Nach dem Initialisieren ist der Play-Cursor unsichtbar.
- [x] Wenn der Play-Cursor unsichtbar ist, ist der Play-Button ausgegraut.
- [x] Wenn der Play-Button auf Play steht, wird beim Versetzen des Cursors an der neuen Stelle weitergespielt. Kleine Lade-Verzögerungen werden akzeptiert.
- [ ] In der Nähe des Play-Buttons zeigt ein neues "23:59:59" Feld die Uhrzeit der Stelle, wo der Play-Cursor steht.

**Undo:**
- [x] Sollte über einen neuen Undo-Button neben dem Play/Pause-Button bedient werden.
- [x] Klick auf den Button ruft den Zustand zum Zeitpunkt des Play-Cursors ab.
- [ ] Solange der aktuelle Zustand des C15 gegenüber dem Zustand an der Play-Cursor-Position unverändert ist, bleibt der Undo-Button ausgegraut.
- [x] Solange kein Play-Cursor gesetzt ist, sollte der Undo-Button grau sein.

**Download:**
- [x] Die Selektion dient zur Festlegung des Download-Abschnittes.
- [x] Selektiert wird durch Draggen im inneren Bereich der Wellenformfläche.
- [x] Wenn man in den inneren Bereich klickt ohne zu draggen, wird die Selektion aufgehoben, es bleibt auch keine Linie.
- [x] Selektionsgrenzen können durch Anfasser verschoben werden.
- [x] Nur wenn ein Bereich selektiert ist, kann der Download-Button gedrückt werden. Sonst ist er ausgegraut.

**Marken:**
- [ ] Werden zur Aufnahmezeit vom Anwender gesetzt (HW-UI-Shortcut finden..!)
- [ ] Werden automatisch chronologisch durchnummeriert.
- [ ] Ihre Funktion: reine visuelle Orientierungshilfen. Erst einmal keine Editierbarkeit

**Comment by KlausStrohhaecker** [comment]
wegen der Issues beim Playback der FLACs nach dem download (keine Duration und kein Scrollen möglich im Player, zB Foobar), es fehlen ein paar Meta-Daten:
Original:
```
kstr@DESKTOP-CAHJ1A8:/mnt/r/Temp/FLAC-Issues$ metaflac --list C15-Recording-Fri-09-23-54-to-Fri-09-24-05.flac
METADATA block #0
  type: 0 (STREAMINFO)
  is last: false
  length: 34
  minimum blocksize: 4096 samples
  maximum blocksize: 4096 samples
  minimum framesize: 0 bytes
  maximum framesize: 0 bytes
  sample_rate: 48000 Hz
  channels: 2
  bits-per-sample: 24
  total samples: 0
  MD5 signature: 00000000000000000000000000000000
METADATA block #1
  type: 4 (VORBIS_COMMENT)
  is last: true
  length: 40
  vendor string: reference libFLAC 1.3.3 20190804
  comments: 0
```

Einmal --> WAV und zurück:
```
kstr@DESKTOP-CAHJ1A8:/mnt/r/Temp/FLAC-Issues$ metaflac --list C15-Recording-Fri-09-23-54-to-Fri-09-24-05-renencoded.flac
METADATA block #0
  type: 0 (STREAMINFO)
  is last: false
  length: 34
  minimum blocksize: 4096 samples
  maximum blocksize: 4096 samples
  minimum framesize: 16 bytes
  maximum framesize: 15765 bytes
  sample_rate: 48000 Hz
  channels: 2
  bits-per-sample: 24
  total samples: 536576
  MD5 signature: 4af3589923aacb27c916e914461c30a8
METADATA block #1
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 40
  vendor string: reference libFLAC 1.3.2 20170101
  comments: 0
METADATA block #2
  type: 1 (PADDING)
  is last: true
  length: 8192
```

Vermutlich reicht die Angabe von `total samples` und alles wird gut.

**Comment by KlausStrohhaecker** [comment]
Ach ja, Datums/Zeit-Format im Filename, da würde ich (wie immer) ISO streng bevorzugen.

**Comment by hhoegelo** [comment]
@nonlinear-labs Koennen wir das Ticket schliessen? Es sind zwar nicht alle Todos erledigt, aber wir haben die Features ja umformuliert.

**Comment by nonlinear-labs** [comment]
Ja, wir können es gerne schliessen..
