### ISSUE TITLE
WebUI: save Preset from EditBuffer inconsistencies

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2558]
- [ ] Question: should macro postions be saved from the EditBuffer into a new Preset?
- [ ] Question: Saving EditBuffer as Presets revisit "Counting"-Rules Eg: Original Preset was Preset X, changing parameters and resaving should yield Preset X 2. Does this rule only apply when saving the preset in the same Bank? Does this rule work as intended on all types of saving? 
- [x] BUG: drag and drop of the save button does not select the new preset (the new bank is selected though)

**Comment by MatthiasSeeber** [comment]
Ich sehe ein Sternchen wenn ich nach Laden eines Presets eine Source verstelle (über UI oder physikalisch) - egal ob die Source auf einen Macro geht oder nicht (etwas merkwürdig, oder?)

Es macht wohl einen Unterschied wo ein Sternchen Buffer abgespeichert wird (selbe Bank, andere Bank per Drag&Drop, neue Bank per Drag&Drop)

Mir ist noch nicht ganz klar wie, aber es gibt einen Weg, immer ein Sternchen zu sehen, auch direkt nach Laden eines Presets??
- wo eine Source beim Abspeichern steht scheint nicht wirklich eine Rolle zu spielen: speicher ein Preset mit Pedal 1 auf 100% ab
- nach Laden des Presets: setze Pedal auf 50% (default) --> Sternchen
- lade Preset neu --> kein Sternchen
- setze Pedal wieder auf 100% (wie beim Speichern) --> Sternchen ?
- lade Preset neu --> kein Sternchen ?

**Comment by KlausStrohhaecker** [comment]
> Ich sehe ein Sternchen wenn ich nach Laden eines Presets eine Source verstelle (über UI oder physikalisch) - egal ob die Source auf einen Macro geht oder nicht (etwas merkwürdig, oder?)

Ich sehe das nur (HWUI) wenn die HW-Source tatsächlich in ein Macro geht und nun anders steht als beim speichern (und gewackelt hat, damit die Änderung ankommt), selbst wenn das Macro dann gar nichts steuert. Was gewissermaßen auch etwas zu scharf ist: wenn es keine Paramter effektiv steuert (weil abgeklemmt oder Gain/Range auf 0), ändert es auch das Preset nicht tatsächlich.
