### ISSUE TITLE
Version 21-07: Audio-Aussetzer für einige Sekunden bei zwei Kunden in USA  --  Hotfix ??

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2561]
Keine Korrelation mit User-Aktionen (= "aus heiterem Himmel")
Eventuell nur bei längerem Betrieb - es könnte sein, dass da etwas vollläuft...
(Anton hat Fehlermeldungen zu MIDI over Ethernet beobachtet.)
Einer der Kunden hat von Relais-Klicken in Verbindung mit den Unterbrechungen berichtet.

**Comment by AntonSchmied** [comment]
Noticed this
```
root@apl /home/sscl # journalctl -b | grep audio-engine
Apr 14 10:06:12 apl audio-engine[895]: Debug:  http://192.168.10.11:40108  ->  The server did not accept the WebSocket handshake.
Apr 14 10:06:12 apl audio-engine[895]: Error:  Alsa Error: Invalid argument
Apr 14 10:06:12 apl audio-engine[895]: Info:  Alsa periods: 3
Apr 14 10:06:12 apl audio-engine[895]: Info:  Alsa frames per period: 49
Apr 14 10:06:12 apl audio-engine[895]: Info:  Alsa ringbuffer size: 147
Apr 14 10:06:15 apl audio-engine[895]: Debug:  http://192.168.10.11:40108  ->  The server did not accept the WebSocket handshake.
Apr 14 10:06:17 apl audio-engine[895]: Debug:  http://192.168.10.11:40108  ->  The server did not accept the WebSocket handshake.
Apr 14 10:06:19 apl audio-engine[895]: Debug:  http://192.168.10.11:40108  ->  The server did not accept the WebSocket handshake.
Apr 14 10:06:21 apl audio-engine[895]: Debug:  http://192.168.10.11:40108  ->  The server did not accept the WebSocket handshake.
Apr 14 10:06:23 apl audio-engine[895]: Debug:  http://192.168.10.11:40108  ->  The server did not accept the WebSocket handshake.
Apr 14 10:06:25 apl audio-engine[895]: Debug:  http://192.168.10.11:40108  ->  The server did not accept the WebSocket handshake.
```
And it goes on forever ... and ever ... until the audio-engine is stopped.
Could be this a dumping or a journal content overflow problem?

**Comment by KlausStrohhaecker** [comment]
Deja vu?
https://github.com/nonlinear-labs-dev/C15/issues/2528

**Comment by KlausStrohhaecker** [comment]
> Einer der Kunden hat von Relais-Klicken in Verbindung mit den Unterbrechungen berichtet.

Das ist ein klares Anzeichen dass die AE kurz aus ist (kein Heartbeat mehr an den Playcontroller --> der sagt dem Supervisor "mute")

**Comment by hhoegelo** [comment]
40108 is the port of the midi-over-ip tool expected to run on the bbb. It is expected behavior for the audio-engine to try to connect to the tool every 2 seconds and report success or failure. So we shouldn't be concerned regarding the according messages on epc, but we should find out why there is no midi-over-ip tool running on bbb.

**Comment by AntonSchmied** [comment]
> Deja vu?
> #2528

In wie fern?

**Comment by KlausStrohhaecker** [comment]
> In wie fern?

Weil eben selbe Fehlermeldung ... deren Usache Henry jetzt erklärt hat...

**Comment by AntonSchmied** [comment]
> > In wie fern?
> 
> Weil eben selbe Fehlermeldung ... deren Usache Henry jetzt erklärt hat...

Ah jetzt! Ich habe deinen Kommentar nicht in Zusammenhang mit der Fehlermeldung, sondern dem Bug an sich in Zusammenhang gebracht. Sorry! :)

**Comment by nonlinear-labs** [comment]
Von Matt Peterson:

The C15 has been running continuously since our call last Friday, but I haven't had much time to use it for a few days. I sat down tonight and started playing and within a couple minutes experienced the audio stopping issue. It was the same as before: four seconds exactly of no sound. I was listening to the headphones but was also recording the output. I've attached a capture of the event.

Timestamp on the event was around 9:30~31PM PDT on 19 April.

I've attached the journal file, compressed.

[journal.zip](https://github.com/nonlinear-labs-dev/C15/files/6342650/journal.zip)

**Comment by hhoegelo** [comment]
(Hopefully) fixed and merged into main and unstable.
