### ISSUE TITLE
Neues Symbol für Bank, die MIDI verbunden ist (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2563]
- Rechteck in Fontfarbe mit "M" in Hintergrundfarbe
- Sitzt am rechten Ende der Label-Fläche.
- Sollte auch im Preset-Tab der WebUI im Bank-Header und im SOLED (Bank-Mode) eingebaut werden.
- Wird von Tino in den Font eingebaut.

![BOLED - MIDI Bank Symbol](https://user-images.githubusercontent.com/33938408/114771687-2dc7d880-9d6d-11eb-9924-6f5b654b54e1.png)

![SOLED - MIDI Bank Symbol](https://user-images.githubusercontent.com/33938408/114772800-85b30f00-9d6e-11eb-94e4-530d3baa14cf.PNG)

![GUI_Midi-Target-Bank ssc 2](https://user-images.githubusercontent.com/33938408/114771493-eb060080-9d6c-11eb-8e1c-89ac54adf901.png)

**Comment by MatthiasSeeber** [comment]
Das ist dann ein weiterer `M` Indikator, neben
- `m` (Mono) Preset Indikator
- `m`, (Mono Glide) `M` (Master Volume/Tune) Macro Target Indikatoren

Vielleicht setzt sich das neue Symbol ja durch die Farb-Invertierung genug von den bereits vorhandenen ab, aber ich würde sagen, das M haben wir dann voll ausgeschöpft.

**Comment by majjam** [comment]
Ich habe auch als erstes direkt an MUTE gedacht bei dem M als Symbol.
Vielleicht etwas an das M des Midi Logos anlehnen ? (rechte abgerundete Ecke )
![grafik](https://user-images.githubusercontent.com/4758563/114875869-05d48580-9dfe-11eb-9b3a-e248899a6eae.png)

https://commons.wikimedia.org/wiki/File:MIDI_LOGO.svg
Wegen copyright müsst ihr mal schauen, aber bei nur dem M....

**Comment by nonlinear-labs** [comment]
Dass das von mir vorgeschlagene inverse M mit anderen Symbolen verwechselt wird oder als "Mute" interpretiert wird, ist nicht sehr wahrscheinlich, weil es im Kontext einer Bank auftritt und die anderen im Kontext von Parametern oder Presets. Aber auszuschliessen ist es nicht.
Ich habe mit Tino besprochen, dass er auch eine stilisierte MIDI-Buchse liefert. Wir können dann beides ausprobieren.

**Comment by majjam** [comment]
Die Assiziation mit den Patchkabeln habe ich auch direkt gedacht ;) Ist eben en vogue .
Das so eine altehrwürdige und standhafte (oder starre) Vereinigung wie Midi auf einmal so umtriebig wird wie im Augenblick, hätte ich nie erwartet.

**Comment by nonlinear-labs** [comment]
Hier die Fonts mit den neuen Zeichen für den MIDI Bank Header (+ Flac-Recorder-Symbole)

[NLL-Fonts-2021-04-15.zip](https://github.com/nonlinear-labs-dev/C15/files/6343662/NLL-Fonts-2021-04-15.zip)

Software/GUI (Source Sans Pro):
ftps://wp1052916.server-he.de/nll-wolke/C15-Grafik-Ressourcen/Fonts/SW-Font_SSP/2021-04-15

Hardware (Emphase):
ftps://wp1052916.server-he.de/nll-wolke/C15-Grafik-Ressourcen/Fonts/HW-Font_EMPHASE/2021-04-15
