### ISSUE TITLE
Voice allocation Fehler: mono anstelle von poly sound

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2565]
**Test-build-April-8**
beim spielen und preset wechseln war auf einmal ein Layersound monophon, der polyphon sein sollte.
Wechseln des Presets auf ein anderes und zurück hat den Fehler behoben

**Test-build-April-13**
nach einer längeren Session mit vielen Events  (Pedale, Preset wechseln usw.) hat sich nach der Auswahl eines Sounds dieser monophon gespielt anstelle von polyphon, wie es im Preset gespeichert war.
Eine Veränderung der unision Voices von 1 auf 2 hat den Sound wieder auf den Erwartungswert gebracht. Eine Reduktion der Voices auf den Ursprung 1 hat den Sound weiterhin normal polyphon spielen lassen.

[Mono-poly.zip](https://github.com/nonlinear-labs-dev/C15/files/6323113/Mono-poly.zip)
Beispiel : vor und nach der Stimmanzahländerung 

Es scheint beim Preset laden ein Datum nicht oder falsch durchgekommen zu sein, so dass der Sound mono alloziert worden ist.
Allgemein habe ich im Augenblick bei den Midi-Releases performance Probleme wenn ich lange mit vielen Events spiele staut sich wohl etwas auf.

**Comment by nonlinear-labs** [comment]
Das ist interessant! Wie machen sich die Performance-Probleme bemerkbar? Welche Phänomene treten auf, oder ist es messbar?

**Comment by MatthiasSeeber** [comment]
@majjam kannst Du bitte mal eine Bank bereitstellen mit Presets, in denen die Mono/Poly/Unison Probleme auftauchen? Und wie genau es dazu kam:
- Preset-Anwahl über C15 UI oder externe Program Changes?
- Nutzung der Pedale über C15 oder externe Control Changes?

**Comment by majjam** [comment]
@nonlinear-labs : die ui kommt verspätet hinterher. Siehe hierzu #2555

@MatthiasSeeber  : alles via Hardware - also Preset Selektion , Pedale , Notes usw. 
Der PC ist im Normalfall zwar physisch verbunden, aber webui oder midi ist nicht offen.
Es ist leider random und hängt nicht an speziellen Presets. Ich schaue mal , ob ich etwas reproduzierbares erfassen kann.

**Comment by MatthiasSeeber** [comment]
Okay, danke.

> die ui kommt verspätet hinterher.

Es gibt auch den sporadischen Effekt, dass ein selektiertes Preset trotz Direct Load einige Zeit zum Laden benötigt, manchmal mehrere zig Sekunden (#2554). Eventuell gibt es da ja einen Zusammenhang?

**Comment by majjam** [comment]
habe heute wieder den mono voice effekt gehabt :
DL is On, midiBridge war dran, C15 war sehr lange angeschaltet (ca. 80+Minuten), aktueller unstable build 7d52828af

1. Sound war ok
2. HWUI setup ->device settings -> transition time ->auf 305ms
=> und Zack der sound war mono
3. Selbst beim Preset wechsel blieb es mono
4. sound voices mono enable ON=> mono
5. Sound voices mono enable OFF=> mono
6. sound voices unision 2 => poly

[monopoly (2).zip](https://github.com/nonlinear-labs-dev/C15/files/6360780/monopoly.2.zip)
Inhalt :
       1 Flac mono 1 
       die Bilder während es mono war
       1 Flac poly nach umschalten des voice counts.
       Fehlerbericht enthalten
edit buffer kann ich leider nicht (mehr) herunterladen

**Comment by MatthiasSeeber** [comment]
Hallo @majjam , danke für die ausführliche Rückmeldung. Die Transition-Time ist vielleicht ein Anhaltspunkt, ich mache da mal ein paar Tests.

Ansonsten gibt es einen neuen MIDI/Flac Preview: https://github.com/nonlinear-labs-dev/C15/releases/tag/MIDI-PR-04-22. Ich vermute, dass das Problem weiterhin besteht, da in die Richtung noch kein konkreter Bug und damit Fix gefunden wurde - kann es aber gerade nur vermuten.

Sollte die Vermutung stimmen und weiterhin unklar sein was hier los ist, gäbe es noch die Möglichkeit, einen extra Installer zu bauen, welcher in der UI und AudioEngine Logs generiert sobald ein Preset geladen wird. Dann hätte man zumindest im Log eine Vergleichsmöglichkeit (z.B. UI schickt Mono OFF, AudioEngine meint MONO On).

**Comment by MatthiasSeeber** [comment]
So, nun habe ich tatsächlich auch mal den Bug gesehen, mit beiliegender Bank mit Preset 012 (ein polyphoner Layer Sound). Beim Durchsteppen (..., 10, 11, 12) ist beschriebener Effekt genau so aufgetreten:

- UI sagt: Mono Enable ist OFF, Unison Voices ist 1
- oft stimmt der Sound in der Audio Engine auch
- aber eben bisher einmal klang der Sound trotzdem monophon

Eventuell liegt es am Preset-Vorgänger: ein Split Sound mit Mono Part II.

[Layer Mono Bug Tests.zip](https://github.com/nonlinear-labs-dev/C15/files/6365031/Layer.Mono.Bug.Tests.zip)

(beobachtet via https://github.com/nonlinear-labs-dev/C15/releases/tag/MIDI-PR-04-22)

**Comment by majjam** [comment]
habe beim Testen mit FIX keine monophonen Artefacte mehre hinbekommen !
