### ISSUE TITLE
Voice Allocation Bugs

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#2567]
Due to recent observations, we need to clarify what exactly goes wrong in the Voice Allocation when specific circumstances apply:

So far ok:
- [x] MONO _Single, Layer_ (internal, external): all Notes are "merged", as only Voice Zero exsists. A specific Key (C3, for example) can only be played once (any following C3 will be ignored and doesn't affect the already pressed key)
- [x] POLY _Single, Layer_ (internal, external): internal and external Notes are separate, a C3 can be played twice. Note Steal only happens when all Voices are exhausted

So far bad:
- [x] MONO/POLY _Split_ (internal, external) - Overlapping or Linked Split - Part II can steal/kill Part I (every `12 / Unison` Voices), the other way round: Part I cannot steal/kill Part II

**Comment by nonlinear-labs** [comment]
In Split mode Tim had artefacts - short high notes - in Part II when playing both Parts. Every time when a high note appears in Part II, the voice played in the left hand (Part I) is stolen.

To restore playability we installed a software version from 27.03. on Tims C15, which does not have the problem.

Here a video showing the high "blibs" and the voice stealing:


https://user-images.githubusercontent.com/33938408/115228805-83580880-a112-11eb-9cdf-2b3e75dca1ab.mp4
