### ISSUE TITLE
Neue Aktion (BOLED-Zeile, GUI-Button) in MIDI Settings für "Set to Defaults" (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2573]
Vielleicht bieten wir auch zwei Aktionen (BOLED-Zeilen, GUI-Buttons) an:
- "Set to High-Res Defaults" (Pedals, Ribbons und AT auf 14-Bit CCs 20...26) 
- "Set to Classic MIDI Defaults" (7-Bit-CCs 01, CC 07, etc., switching CC64, AT auf Channel Pressure)

**Comment by schlenkibus** [comment]
Aktuell habe ich diese Werte fuer die Beiden UseCases:

High Res Defaults:
14BitSupport -> true
14BitVelocity -> true
Pedal1 -> CC20
Pedal2 -> CC21
Pedal3 -> CC22
Pedal4 -> CC23
Ribbon1 -> CC24
Ribbon2 -> CC25
Aftertouch -> CC26
Bender -> Channel Pitchbend

Classic Midi Defaults:
14BitSupport -> false
14BitVelocity -> false
Pedal1 -> CC01
Pedal2 -> CC02
Pedal3 -> CC03
Pedal4 -> CC04
Ribbon1 -> CC05
Ribbon2 -> CC06
Aftertouch -> Channel Pressure
Bender -> Channel Pitchbend

**Comment by schlenkibus** [comment]
Change Classic to CC20 - CC25
