### ISSUE TITLE
Recorder: Sound läuft weiter obwohl Tab geschlossen ist.

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2608]
(kein Bug - aber führt evtl zu Überraschungen .)
Wenn der Recorder abspielt und man den Tab schliesst, bzw den kompletten Browser schliesst, läuft der Sound weiter.
Vielleicht kann man das zeitlich überwachen ?
Es kann ja ein langsames Überwachungsintervall sein. 2,3 oder sogar 5 Sekunden.

**Comment by gua-jostkleigrewe** [comment]
@schlenkibus 
Kannst du dies einmal bewerten/ bewerten lassen und das Ticket zuordnen oder wenn gewünscht schließen ?
Danke
Max

**Comment by majjam** [comment]
@schlenkibus
Kannst du dies einmal bewerten/ bewerten lassen und das Ticket zuordnen oder wenn gewünscht schließen ?
Danke
Max

**Comment by schlenkibus** [comment]
When the recorder is playing and no UIs are connected anymore, the recorder will signal the PG to display an Overlay which will prompt the user: "do you want to stop the recorder-playback?"
additionally a new recorder action "stop replay" will be added at setup->recorder settings
