### ISSUE TITLE
FLAC-Recorder: Tastatur-Shortcuts (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2622]
- Play / Pause (wenn Play-Cursor gesetzt ist): Leertaste

- Restore: "Z" ?
- Record (Start/Stop/Continue): "R" ?
- Download: S" ?

- Zoom In/Out
- Nudge Left/Right

- Jump to Previous/Next Preset Marker

**Comment by davidm2894** [comment]
Z does not restore the parameters, but instead deletes the whole storage.
