### ISSUE TITLE
Buffer-Underruns auch auf meiner Test-Unit (EPC-00001)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2650]
Entgegen früherer Aussagen höre ich doch Glitches (vielleicht 1-2 pro Stunde), die von Buffer-Underruns herrühren könnten.

**Comment by KlausStrohhaecker** [comment]
@hhoegelo , werden Xruns geloggt oder sind sie logbar? Oder gar kurz vor Xruns (also knappe Bufferstände)? Womöglich als Histogramm? Unsere Buffer sind ja mW eher sehr kurz, da wäre so ein Profiling evtl. leicht machbar und mit wenig Overhead.

Da man entweder über MIDI oder über die Playcontroller-Tools Noten (bzw Tasten) abfeuern kann, wäre ein simpler Dauertest möglich.

**Comment by hhoegelo** [comment]
x-runs werden geloggt. Sie sollten numehr (in unstable) nicht mehr auftreten.
