### ISSUE TITLE
FLAC-Recorder: Probleme Download auf iPad - Safari lässt Recorder einfrieren - Chrome Download nicht möglich 

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2661]
2 Probleme:

**1.** Läuft der FLAC-Recorder in Safari auf dem iPad, lässt sich der Download zwar durchführen, allerdings friert der Recorder danach ein, d.h.:

- Aufnahme läuft nicht mehr & lässt sich nicht mehr starten
- Abspielen geht nicht mehr
- Zurückspringen geht nicht mehr 
- restliche Bedienelemente gehen noch

Kann durch Refresh bzw. Löschen der Aufnahme gefixt werden. Einmal trat der Fall auf, dass es nur durch komplettes Neustarten von Safari wieder ging.

**2.** In Chrome (bzw. DuckDuckGo) funktioniert der Download nicht. Öffnet einen Tab mit Fehlersymbol. Download-Ordner ist auch leer. 

**Safari:**

https://user-images.githubusercontent.com/84857645/119956168-181b1500-bfa1-11eb-9b93-b211f883d1de.mov

**Chrome**

https://user-images.githubusercontent.com/84857645/119956282-38e36a80-bfa1-11eb-92ea-8096cdd32ee1.MP4

**Comment by hhoegelo** [comment]
@davidm2894 ist das noch aktuell?

**Comment by davidm2894** [comment]
hab heute mein ipad nicht dabei, würde es morgen mal testen.

**Comment by davidm2894** [comment]
ja ist noch aktuell @hhoegelo

**Comment by hhoegelo** [comment]
Das Problem Nr 2 habe ich nicht in den Griff gekriegt. Im Internet scheint es auch Konsens darueber zu geben, dass Chrome das einfach nicht kann. Ich denke, das ist etwas fuers Handbuch / Release Notes. @nonlinear-labs ? @MatthiasSeeber ?

**Comment by nonlinear-labs** [comment]
Ok, dann schreiben wir das in die Known-Issues-Abteilung der Release Notes (und ins Addendum), empfehlen auf dem iPad Safari und hoffen, dass Chrome später vielleicht auch noch die Option zum Download bekommt.
