### ISSUE TITLE
PC to MIDI: Single Sound empfängt auch CCs über den bei Split Channel (Part II) eingestellten Kanal

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2662]
Situation:
Habe ich in der DAW zwei MIDI-Tracks (MIDI-Channel 1 & 2), empfängt C15 bei Receive Einstellungen "Channel: 1" & "Split Channel (Part II): 2" auch die CCs, die über den Channel 2 aus der DAW geschickt werden. Es ist **kein** Split Sound geladen.

Denke das kommt daher, dass die HW-Sources Split-Channel unabhängig gehandelt werden. 

(Die Channel sind nur beispielhaft gewählt.)

**Comment by MatthiasSeeber** [comment]
Soweit ich mich erinnere, ist das gewollt für Control Changes und Program Changes. Nur Note On/Off Events werden ignoriert, wenn kein Split Sound geladen ist. Wenn man also beide Kanäle bedient, verliert man dadurch nicht die Kontrolle über HW Sources und Presets, nur weil gerade kein Split Sound geladen ist.

**Comment by MatthiasSeeber** [comment]
Nach gemeinsamer Konferenz gilt nun folgender Beschluss:
Control Changes und Program Changes gibt es exklusiv nur auf dem Primary Channel, Secondary kann damit nur noch Noten (und dies dann auch nur noch im Split).
