### ISSUE TITLE
MIDI Send: Wenn der Split Channel nicht auf "None" oder "Common" steht, werden von Single- oder Layer-Sounds die Hardware Sources auf Primary und Secondary Channel gesendet.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2669]
Nur im *Split*-Betrieb wollen wir etwas auf dem Secondary (*Split*) Channel senden.

**Comment by MatthiasSeeber** [comment]
Wir hatten kürzlich in #2662 festgelegt, dass Program Changes und Control Changes nun exklusiv auf Primary liegen. Ich bin der Meinung, dass dies auch die Ausgabeseite betreffen sollte:

Hardware Sources und Program Changes werden nie, **auch nicht im Split**, auf Secondary gesendet. Dies passiert immer auf Primary.

- [ ] @nonlinear-labs: bitte bestätigen

(siehe https://github.com/nonlinear-labs-dev/C15/issues/2662#issuecomment-850300459)

**Comment by nonlinear-labs** [comment]
Wenn wir über den Secondary/Split Channel nur Noten senden und empfangen, ist das am einfachsten zu kommunizieren und zu merken. Das sollte deshalb in diesem Release so umgesetzt werden.

Mir ist inzwischen allerdings der Use Case eingefallen, dass man HW Sources auch (oder nur) an das externe Instrument schicken möchte, das man im rechten Splitbereich spielt. Solche Fälle lassen sich aber wohl nur sinnvoll abdecken, wenn man MIDI-Mappings in Presets speichert. Schaun wir erstmal, was für Feature Requests von den Usern reinkommen.

**Comment by schlenkibus** [comment]
Can we extract this comment and discussion into a new issue?
