### ISSUE TITLE
MIDI Send: Bei Local Enable Notes Off sendet im Split-Betrieb Noten über beide Kanäle 

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2682]
Wenn Local->Enable Notes: **Off** steht, werden Noten im Split-Betrieb über beide Kanäle gesendet. Steht Status auf On, funktioniert es wie gewollt (Split Part 1 -> Channel A, Split Part 2 -> Channel B).

**Comment by MatthiasSeeber** [comment]
`Local -> Enable Notes` legt fest, ob gedrückte Tasten des C15 Keybeds einen Sound erzeugen sollen.  (Also, bei OFF kann man Tasten drücken, der Synth macht aber nix.)

Ob gedrückte Tasten versendet werden oder nicht hängt lediglich von den Send Settings ab. Meine Vermutung: beim Testen von Local Enable waren die Send Settings aktiv, weshalb richtigerweise Noten versendet wurden.

**Comment by MatthiasSeeber** [comment]
Sorry, ich kann den Bug doch bestätigen.
Local Enable off bewirkt im Split Sound, dass beide Kanäle versendet werden, obwohl die gedrückte Taste lediglich einem Part zugehörig war.

**Comment by davidm2894** [comment]
Anbei mal schnell ein Video das die Problematik zeigt. 

https://user-images.githubusercontent.com/84857645/120632265-0e922100-c469-11eb-9a7f-af7788cc3efb.mp4
