### ISSUE TITLE
noten hängen bei split point modulation [bug]

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2698]
Ein letzter vor meinem Urlaub (2 Wochen Ruhe vor mir ) 

1 Split preset wählen
2 Part 1 spielen und halten
3 Split point so modulieren/per Menu legen , dass Wert unter gehaltenen Noten liegt.
4 Tasten loslassen => Sound läuft weiter

**Comment by MatthiasSeeber** [comment]
Oh ja. Ich fürchte, das haben wir uns mit der Einführung von MIDI eingehandelt (ich bin mir ziemlich sicher, dass das vorher funktioniert hatte).

**Proposal**

Wenn eine Note die Split Point Parameter nutzen möchte (bei internem Keybed sowie MIDI mit `SplitCh = Common`), dann sollte die InputEventStage nur bei einem `KeyDown` nach den Parametern schauen und die Part-Zuordnung ermitteln. Bei einem `KeyUp` darf dies nicht passieren, die Information steckt zu diesem Zeitpunkt bereits in der gedrückten Taste bzw.klingenden Stimme.
