### ISSUE TITLE
WebUI: Anzeigefehler Kontextmenü bei Chrome (macOS)

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2703]
System Version: 21-24
Chrome Version 91.0.4472.106

Folgender Anzeigefehler im Preset-Kontextmenü:
![Bildschirmfoto 2021-06-18 um 17 38 27](https://user-images.githubusercontent.com/84857645/122586672-3d111e00-d05d-11eb-8bfb-d622e1bb9ee5.jpg)

Andere Kontextmenüs sind nicht betroffen.

**Comment by nonlinear-labs** [comment]
In einem Video-Training hatte ein User auch Probleme in Chrome auf dem iPad. Wenn er mit Long-Touch ein Menü aufmacht, wird "alles blau". Habe es nicht ganz verstanden, aber es scheint ein Problem mit den Kontextmenüs zu geben.

**Comment by davidm2894** [comment]
Kann mir vorstellen, dass er folgende Situation meint. Wenn man Long-Touch macht, ist das auch die Touch-Geste zum markieren, ersichtlich auch oben über die lokalen Pop-Ups "Kopieren | Nachschlagen". Da es im Video nicht zu sehen ist, die Long-Touch-Geste passiert auf dem Resonance-Parameter.


https://user-images.githubusercontent.com/84857645/122725988-d9ae0880-d275-11eb-88d0-f51cf72fdc5b.mov
