### ISSUE TITLE
Der Screensaver wird nicht mehr durch Spielen auf der Tastatur beendet.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2704]
Wir hatten es schon einmal so implementiert, dass auch das Anschlagen von Noten den Screensaver abschaltet. Das sollte wieder so werden.

**Comment by davidm2894** [comment]
Ich hab den Screensaver auf 20 Minuten eingestellt und komme per Tastaturanschlag raus. Bei 1 Minuten klappt es bei mir allerdings auch nicht.

OS: 21-24

**Comment by schlenkibus** [comment]
Ich kann bestaetigen das ein Tastatur-Anschlag in der Aktuellen Software keinen Screensaver beendet. Was den Screensaver allerdings beendet ist eine geaenderte HW-Source, also auch Aftertouch, es kann sein das der Aftertouch veraendert wurde, was das unterschiedliche Verhalten, das @davidm2894 beschrieben hat, erklaeren koennte. 

Meines Wissens nach haben wir eine Schnittstelle zwischen LPC und BBB ausgemacht ''HW_SOURCE_ID_LAST_KEY" die wir nutzen sollten.

**Comment by davidm2894** [comment]
Kann @schlenkibus Vermutung bestätigen. Hab ich eine falsche Verbindung hergestellt.

**Comment by KlausStrohhaecker** [comment]
> Meines Wissens nach haben wir eine Schnittstelle zwischen LPC und BBB ausgemacht ''HW_SOURCE_ID_LAST_KEY" die wir nutzen sollten.

Ja, das würde gehen. Evtl. sollten wir aber den "Idle-Detector" zentralisiert in die Input-Event-Stage verlegen für die Sachen, welche die UI nicht unter direkter Kontrolle hat (also alles ausser Buttons/Encoder, praktisch).
