### ISSUE TITLE
BOLED: design and implement HW-Source-Options

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2714]
In the WebUI the new settings are displayed as an table. Come up with an solution for the BOLED.
Change WebUI RadioButtons to checkboxes to save some space.

**Comment by schlenkibus** [comment]
![image](https://user-images.githubusercontent.com/15381257/124911730-61717200-dfed-11eb-8f9d-bc0e48fa75e3.png)

**Comment by nonlinear-labs** [comment]
Vorschlag zu einer etwas klareren Beschriftung:
"Channel" kann entfallen
"Direction" kann entfallen
"Primary" -> "Primary Channel"
"Split" -> "Split Channel"
"Both" durch "Local" ersetzen, wodurch das obere "Local" entfällt.

Die Checkboxen bitte zentrieren.

**Comment by nonlinear-labs** [comment]
Hier eine Diskussions-Vorlage für überarbeitete MIDI-Settings. Ziel war eine verständliche und praxisgerechte Bedienung bei gleichzeitiger Integration der neuen Routing-Schalter der Hardware-Sources.

Achtung: aus Konsistenzgründen schlage ich für Notes und Program Changes jeweils vier statt zwei Routing-Schalter vor:
Bisher: Receive On/Off, Send On/Off
Nun: Receive Primary On/Off, Receive Secondary On/Off, Send Primary On/Off, Send Secondary On/Off

Ein Vorschlag zur Umsetzung im BOLED folgt in Kürze.

[MIDI Settings Rework 00.txt](https://github.com/nonlinear-labs-dev/C15/files/6848683/MIDI.Settings.Rework.00.txt)

**Comment by nonlinear-labs** [comment]
Kommentare zum Preview:

- [ ] "Routings"-Screen: "MIDI Routing" wäre als Überschrift besser ("MIDI" verbessert die Orientierung, der Plural ist hier nicht nötig)
- [ ] in der WebUI statt "MidiRoutings" besser "Routings" (hier steht "MIDI" schon im Tab)
- [ ] Routings-Screen: "Rec. Prim." und "Rec. Split" besser "Recv. Prim." und "Recv. Split" (sonst denkt man immer an "Record")
- [ ] Falsche Reihenfolge der HW-Sources in der Routings-Liste: Nach "Pedal 4" sollte "Bender", "Aftertouch", "Ribbon 1" und "Ribbon 2" kommen.
- [ ] Routings-Screen: falsche Reihenfolge mit Pfeiltasten: "Prog Ch" - "Notes" - "Pedal 1" ... ("Notes" bitte vor "Prog Ch")
- [ ] Farben und Symbole für die einzelnen Routing-Switches - tbd...

**Comment by nonlinear-labs** [comment]
**!! Crash !!**
BOLED: MIDI Settings: Prog Ch. Bank 
- Mit Enter rechts die Edit-Liste öffnen
- Mit Encoder eine andere Zeile auswählen
- Mit Softbutton auf linke Hauptliste wechseln
- Nochmal mit Enter rechts die Edit-Liste öffnen
- Nochmal mit Encoder eine andere Zeile auswählen  => Crash/Restart oder Freeze
