### ISSUE TITLE
Ribbon wird beim Wechseln des Behaviour buggy bzw. RtC-Mode immer buggy

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2723]
OS-Version: 21-25 (tritt aber auch in früheren Versionen schon auf)

1. Ribboncontroller steht auf Non-Return
2. Wechsel zu Return to Zero
3. Mittelpunkt wird statt auf 0% auf 50% gestellt, die LEDs markieren den Bereich von 0% bis 50%
4. Drücke ich ganz links auf den Ribbon, steht er auf 0%. Drücke ich zwischen 0% und 50% erhöht sich der Wert und die Ribbon-LEDs sind meinem Finger voraus.
5. Speicher ich nun das Preset, gehe auf ein anderes und lade wieder das vorherige, dann sieht es zunächst nach dem gewünschten Verhalten aus, die Werte, die im HW-Source Menü angezeigt werden, stimmen. Wenn ich mir aber die Werte im Macro Control Menü anschaue, dann erreiche ich 0% bzw. 100% bereits bei 25% bzw. 75%.

1. Ribboncontroller steht auf Return to Zero
2. Wechsel zu Non-Return
3. Bleibt bei 0% bis ich mit dem Finger die Hälfte des Bands überschreite. Bewege ich den Finger weiter Richtung ganz rechts, werden die LEDs schneller als meine Fingerbewegung und holen mich bei knapp 100% schließlich ein.

Smoothing-Werte sind default.

Hier im Video nochmal dargestellt:

https://user-images.githubusercontent.com/84857645/124096941-5ea9d680-da5b-11eb-8f62-92abf454d6d8.mp4

Ein weiteres Verhalten ist, dass ich im RtC-Mode die Modulationstiefe nur noch in eine Richtung einstellen kann. Und wenn ich den Parameter dann per Ribbon moduliere, verschiebt sich auf einer Hälfte der Modulationsbereich, auf der anderen wird der Parameter dann tatsächlich moduliert. Im folgenden Video zu sehen:

https://user-images.githubusercontent.com/84857645/124097309-bea07d00-da5b-11eb-9ba7-52a482bf5d31.mp4

**Comment by MatthiasSeeber** [comment]
gug has been fixed via #2726
