### ISSUE TITLE
WebUI: Übeschneidungen von Parameter- und Preset-Fenstern möglich

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2724]
Parameter- und Preset-Oberflächen können sich überschneiden. Hatte meine Presets in etwas weiterer Draufsicht unterhalb der Parameter angeordnet, als ich dann reinzoomte, fingen beide Oberflächen an sich zu überschneiden.

Video:
https://user-images.githubusercontent.com/84857645/124113420-b6e8d480-da6b-11eb-9d46-e8d962ce93d7.mp4

**Comment by schlenkibus** [comment]
Ich sehe wie sich die UI Verhaelt und erkenne keinen Bug. MMn handelt es sich dabei um das normale Verhalten der UI. Wenn du alle Baenke verschieben willst (etwas nach unten z.B) kannst du ueber das Hintergrund-Context-Menu -> "Move all Banks" ausfuehren.
