### ISSUE TITLE
playcontroller crash 

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2739]
Version : **R-21-25**

beim Spielen war der Sound plötzlich weg.
Ribbons standen still, 
Klaviatur hat keine Klangereignise mehr erzeugt.
Beides hat auch den screen saver nicht beendet, der Knopf 'Preset' aber schon 
(Pedale nicht getestet.)

dmesg BB: keine Auffälligkeiten
dmesg EPC : keine Auffälligkeiten

EPC:
1. audio-engine.service stop, start => keine Veränderung
2. playgound.service stop, start => keine Veränderung

BB:
3. bbb.service stop, start => keine Veränderung
4. midi-over-ip.service stop, start => keine Veränderung

daher glaube ich,m dass der Playcontroller weg war.

[C15-journal.txt](https://github.com/nonlinear-labs-dev/C15/files/6836847/C15-journal.txt)

**Comment by KlausStrohhaecker** [comment]
Der Playcontroller hat einen Watchdog, d.h. sollte er sich aufhängen wird sofort ein Reset ausgelöst. Zudem haben wir eine Heartbeat-Chain, die dafür sorgt, dass in so einem Fall (und anderen) alles wieder richtig initialisiert wird. Auch ansonsten ist das Gebiet um den Playcontroller sehr stabil. Ich würde daher fast ausschließen dass der Playcontroller hart stehengeblieben ist oder dergl. 

Sollte sowas nochmal auftreten, kannst du kontrollieren ob der Playcontroller läuft, auf dem BBB:
- `systemctl stop bbbb`  (BBB-Bridge darf die Playcontroller-Ereignisse nicht abgeifen)
- `playcontroller-read` (empfängt Ereignisse vom Playcontroller -- gibt auch verschiedene Optionen -- und stellt sie dar, zB sieht man immer den Heartbeat laufen).

Will man den Play controller resetten, geht das mit dem `playcontroller` tool:
`playcontroller reset`
(wieder mit deaktivierter Bridge, aus dem gleichen Grund).

**Comment by majjam** [comment]
Schade, dass ich dies nicht vorher wusste, dann hätte man es viel besser eingranzen können !
Wenn der watchdog vom LPC an ist, glaube ich auch nicht, dass es keinen Reset am µc gegeben haben sollte falls er sich aufhängt. 

Ich glaube nicht, dass ich dieses Verhalten schnell reproduziert bekomme, denn so einen 'Crash' hatte ich bis jetzt nur einmal, 
obwohl ich recht viel gespielt habe, auf dieser Version.

Könnte das AudioRelais weg gewesen sein ?
Aber dass passt nicht so gut zur stehengebliebenen Anzeige der Ribbons..

Bitte immer bedenken meine Hardware ist eine relativ frühe Variante.

WEBUI und HWUI OLED,BOLED haben in diesem Zustand funktioniert.

**Comment by KlausStrohhaecker** [comment]
>Könnte das AudioRelais weg gewesen sein ?

Der Playcontroller lässt Audio gemutet solange die Audio-Engine nicht läuft (indem er das Ausbleiben den Heartbeats auswertet). 

Was mir noch unklar ist, musstest du den C15 neustarten oder war der Aussetzer "selbst-heilend"?

**Comment by majjam** [comment]
Nein ich konnte weder die Ribbon-LEDs animieren, noch mittels der Tastatur klang herstellen. Ein Neustart hat es dann gelöst.

Nach auftreten der Fehler habe ich : 
1. WIFI verbunden,
2. per ssh  auf BBB
3. dann auf EPC
4. services EPC wie oben beschrieben neugestartet
5. zurück zu BBB
6. services BBB wie oben beschrieben neugestartet
7. disconnect.

Folgendes lief :
Die Preset Tasten 
OLED und BOLED
WEBUI (WIFI)
Ribbon Anzeige auf Preset state (glaube ich - nicht 100% sicher)

folgendes lief nicht :
klaviatur -> sound
ribbon touch -> ribbon led

ungetestet : 
PEDALE  PB AT
MIDI  (wobei ich glaube , dass die Bridge nur Lila gepulst hat , also PC seitige Verbindung ja , C15  nicht - nicht 100% sicher)

Der Build  war von Euch aus der github Release liste, nicht von mir selbst compiled.

Mehr fällt mir nicht ein. Blöder Fehler , da nicht repoduzierbar.

**Comment by majjam** [comment]
ist glaube ich inzwischen obsolet daher -Close
