### ISSUE TITLE
NL logo for Recorder and Help UI browser tabs have the same color

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2752]
This seems to be inconsistent. If I understood Tino correctly back in the day, the Web UI, Help UI and MC UI were supposed to have different colors for better tab navigation in  browser. Now, I am not able to tell by the color of the Logo, whether I have opened the Help or Recorder UI. 
![image](https://user-images.githubusercontent.com/37212595/127012550-35b511a1-e2b2-4559-973a-9d04c9923660.png)

@MatthiasSeeber suggested the color to be red (like MC view), since it's a tool.
I think it should have a unique color, for better navigation. 
Or set them all to black f.e. and let the user choose the color of the Logo?
 
P.S. I heard this was discussed before, but @nonlinear-labs allowed me to open the issue ;)

**Comment by schlenkibus** [comment]
I would prefer a fixed color instead of allowing the user to set a preferred color.

**Comment by davidm2894** [comment]
On Chrome (at least on Mac) the WebUI Tab has no Logo at all.

<img width="865" alt="Bildschirmfoto 2022-12-08 um 13 54 07" src="https://user-images.githubusercontent.com/84857645/206451758-fe8c6ae8-0090-423a-806b-71f074f058fb.png">

**Comment by schlenkibus** [comment]
@davidm2894 is that happening on the rc-sammelstelle preview?

**Comment by schlenkibus** [comment]
the green recorder icon has been in for a while
