### ISSUE TITLE
Export/Import auf/von USB-Stick - mehrere Probleme

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2757]
- Das Back-Up am C15 auf einen angeschlossenen USB-Stick erzeugen, führt zu einem 0 kB großen File.
- Export Bank to USB schreibt nichts auf den Stick. Interessanterweise wird die Bank aber zunächst in der Liste unter Import angezeigt. Am Rechner und an einem anderen C15 sind die Files nicht zu sehen (auch nicht versteckt). Anton hatte die Vermutung, dass vielleicht nur ins RAM geschrieben wird. Ich hab den C15 mal ausgemacht und hatte die Bänke dann auch nicht mehr in der Liste. 
- Ziehe ich am Rechner ein Bank-File auf den Stick, wird es am C15 im Import-Window nicht erkannt. 
- beim Import-Fenster funktioniert "Cancel" nicht. Drückt man bei 0 angezeigten Files "Select" kommt man so zurück. Hier wäre eine Fehlermeldung wahrscheinlich besser.

**Comment by schlenkibus** [comment]
- [ ] Bank Import "cancel" has no effect, ever
Test:
- [x] Backup export to USB works
- [x] Bank export to USB works
- [x] Import of existing files
- [x] Import of just exported Files
