### ISSUE TITLE
User-editierbares WiFi-Passwort

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2765]
Zu klären:
- Einstellung nur im BOLED?
- Eingabe des alten Passworts erforderlich?
- Setzen wir Mindestanforderungen an Länge oder Inhalt? (mein Vorschlag: nein, der User hat die Verantwortung)
- Welche Zeichen sind erlaubt? Nicht alles, was unser Zeichensatz hergibt, kann der User an seinem browserfähigen Device eingeben. 
- Reset-Button, um wieder "88888888" einzustellen?

**Comment by KlausStrohhaecker** [comment]
M.b.M.n.:
* Reset auf Werks-PW nur (oder zumindest auch) am SOLED mit einem speziellen Affengriff der nur beim Booten gescannt wird. Weil darum geht's im Ernstfall: Auf Tour, Panel-Unit oder -Kabel verschlampt oder defekt, jedoch Rettung möglich weil geht ja auch alles über WebUI, aber nein, ich weiß das Passwort nicht (mehr)... Baam! Im Prinzip reicht auch allein diese Reset-Funktion.
Ein kleines Tool auf dem BBB kann noch bevor die BBBB startet nach dem Affengriff scannen bzw einfach den Zustand der 4 Testen binär codiert (also 0..15) irgendwo hinterlegen. D.h., das kann effektiv in den Startcode der Bridge.
Dann hätte man gleich eine Reihe möglicher Bootcode-Affengriffe (2..4 Tasten gleichzeitig) auch für andere Zwecke. Das kenne ich zB von meinem RME Audiointerface, dort für verschiedene Level an Werks-Resets.
Die Abfrage ist einfach, der Treiber kann auch Polling, nicht nur Events:
https://github.com/nonlinear-labs-dev/C15/blob/unstable/projects/bbb/espi-driver/espi_buttons.c
Und bevor die Bridge später "normale" Events der betr. Tasten durchlässt, wartet man erstmal alle Releases ab, damit es zB keine false-triggers für die Transpose-Tasten gibt.

Eingabe eines eigenen PW ist dagegen mehr eine Komfort-Sache.
Falls wir dies haben wollen, mM:
* Änderungen im Boled (ohne altes PW) und WebUI (mit altem PW)

* Kein Beschränkung, incl kein Passwort

* Nur ASCII bzw sogar nur das Subset "a".."z", "A".."Z", "0".."9", "_" und "-". Das geht immer irgendwie auf jedem System und mit (fast) jeder Tastatur. Das gleiche übrigens für die SSID selbst, bei der Gelegenheit.
