### ISSUE TITLE
ePC NUC10i3: occasional  "Warning:  recovered from x-run" in journalctl

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2788]
Seems to be not dependent on whether or not the audio-engine is started automatically or manually.
Observed with Release 21-33

**Comment by hhoegelo** [comment]
Ideas:
- reduce number of bg threads used by InputEventStage (Justus)
- have developer option for alerting on buffer underruns (Henry)

- Should we try to find out if it happens only on epc2?

- Does it happen without wifi, too? (USB traffic)
-> Try to reproduce buffer underruns with artificial traffic on usb. 

- Too expensive: Should we try to find out when the problem happend first?

- We could just increase buffersize from 49 to e.g. 64 samples and see what happens.
- We could reduce the number of condition_variable::notify() calls by maintaining a boolean flag and fire only after audio callback.

**Comment by hhoegelo** [comment]
BU observed with and without running AP on EPC2

**Comment by hhoegelo** [comment]
BU observed on EPC1 as well

**Comment by hhoegelo** [comment]
Here is a diagram of underruns observed on my ePC2:
https://docs.google.com/spreadsheets/d/1dO7YOGW9bcKq0gVdJtDranYelU4S9UaRU2WgTDTiPsY/edit?usp=sharing

**Comment by hhoegelo** [comment]
Rebased to unstable, containing simplified audio engine background threading -> did not help.

**Comment by hhoegelo** [comment]
Next try:
- [ ] add user land kernel update procedure
- [ ] produce normal update
- [ ] test installation and kernel update
- [ ] test downgrade (new kernel should be kept, old Software has to work with new kernel)

**Comment by schlenkibus** [comment]
@hhoegelo can this issue be closed?
