### ISSUE TITLE
Presetname bleibt bei Store/Overwrite nicht erhalten

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2802]
- Preset über Soundscreen in Single/Split oder Layer konvertieren (Presetname ist automatisch "Converted")
- Das konvertierte Preset (editieren und) mit Append speichern und dabei einen neuen Namen eingeben
- Das Preset noch einmal editieren und mit Overwrite auf demselben Platz speichern
=> der Name ist leider wieder "Converted" 

Das kommt wahrscheinlich daher, dass im Editbuffer immer noch "Converted" steht. Der Editbuffer muss bei der Preset-Benennung also auch upgedatet werden.

**Comment by nonlinear-labs** [comment]
siehe auch #2828

**Comment by schlenkibus** [comment]
Ich habe eine Frage/Anmerkung zu diesem Ticket.

Bezieht sich `(Presetname ist automatisch "Converted")` auf den Text der im Preset-Focus links oben in der Ecke steht? Siehe Screenshot:
![Boled-Thu-Sep-30-09:54:06-2021
](https://user-images.githubusercontent.com/15381257/135411230-fb9af58e-6d3e-4d39-9f4e-731a60bfdfb1.png)

Dieser Text, gleich mit dem Selbigen in der WebUI, zeigt an das der Editbuffer konvertiert wurde, statt an dieser Stelle anzuzeigen welches Preset geladen war, und ob zu diesem eine Veraenderung besteht. 'Converted' erscheint in userem Code nie als 'EditBufferName'.

Soll dieses Ticket als komplette Feature-Beschreibung dienen und Der Editbuffername 'Converted' eingefuehrt und wie beschrieben implementiert werden, oder wollen wir uns nocheinmal ueber diesen Themenkomplex unterhalten? @nonlinear-labs
