### ISSUE TITLE
BOLED flackert mit verschiedenen Inhalten, wenn man ein Pedal betätigt und gleichzeitig bei einem Dual-Sound den "I/II"-Button betätigt

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2803]
Mit "I / II" wird ein neuer Screeninhalt geladen. Durch die Pedal-Aktion wird dabei anscheinend der Inhalt einer größeren Zahl von BOLED-Screens "abgefeuert". Diese Kaskade kann länger dauern als die Pedalbewegung. Könnte das ein Stau in einem Websocket sein? Das Wesentliche ist aber, dass die Bewegung der HW Source überhaupt eine Störung auslösen kann.

**Es tritt auch eine größere Verzögerung ein, wenn man auf der WebUI auf ein anderes Preset klickt, während man ein Pedal bewegt. Auch hier scheint ein Stau zu entstehen.**

**Comment by nonlinear-labs** [comment]
Das Problem ist leider nicht immer reproduzierbar. Ich suche noch nach den notwendigen Randbedingungen.

**Comment by davidm2894** [comment]
Ist für mich auf 22-27 nicht reproduzierbar, deshalb zunächst einmal auf SEU-Nice-to-have verschoben.

**Comment by schlenkibus** [comment]
i cant reproduce this on d099c5866dd6a811d3a7a3aba09b6a80f6e693f6
