### ISSUE TITLE
ePC Absturz - C15 friert ein bei Oled Mirroring

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2804]
OS: die letzte Preview, die @schlenkibus letzte Woche gebaut hatte. 

Mir ist der C15 heute zweimal eingefroren (BOLED/SOLED + LEDS, kein Ton), während ich ihn eigentlich nicht benutzt hatte. War nur in den Settings unterwegs, meistens auf der neuen Routings-Matrix.  
Nachdem ich erst dachte, es liegt an der Matrix, habe ich nach einiger Zeit dann rausgefunden, wie es passiert:
- in WebUI das Oled Mirroring aktivieren
- dann mit dem Rechner aus dem C15-Wifi gehen
- nach ca. 5-10 Minuten knacken die Relais und es kommt zum Absturz

Laut @AntonSchmied stürzt der ePC ab, der C15 lässt sich auch nicht mehr runterfahren (kommt nur zum Shutdown Screen und nicht weiter)

![CPU_Soft_lockup_#2](https://user-images.githubusercontent.com/84857645/133111778-da5bcd3b-d741-4799-baf4-7d7646b25809.jpg)
![IMG_2868](https://user-images.githubusercontent.com/84857645/133111929-b71ccedd-d2d1-48bd-b0a0-996e355601e0.jpg)

**Comment by schlenkibus** [comment]
Apparently this Issue is still happening and Stephan needs to be able to use the Mirror-Oled Feature reliably.

**Comment by AntonSchmied** [comment]
We logged Stephan's C15 before freezing. see #3304. Maybe it will help!
