### ISSUE TITLE
MIDI Enhancements Sammlung

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2817]
Eine Sammlung an offenen Dingen zum Thema MIDI, die teilweise schon an anderer Stelle erwähnt sind, aber zur Übersichtlichkeit hier einmal gesammelt:

- [x] "Global Local Enable" -> "Local Enable"
- [x] Local Enable ist noch unwirksam 
- [x] "Panic" sollte auch "All Notes Off" schicken
- [x] Routing-Einstellungen: "All Notes Off" schicken bzw. VA + Env resetten, wenn Notes off geschaltet wird (Local, Send, Receive)
(- Pitchbender & Aftertouch resetten, wenn Off geschaltet wird (Local, Send, Receive))
(- alle anderen Routingeinstellungen sollen kein "All Notes Off" schicken bzw. die VA resetten)
- [x] "Panic Button" in "Panic" umbennen (HW UI)

**Comment by MatthiasSeeber** [comment]
> (- Pitchbender & Aftertouch resetten, wenn Off geschaltet wird (Local, Send, Receive))

@davidm2894 

Diese Art von Reset soll bedeuten, dass wenn der Bender oder AT (beide immer returnend) aus einem Routing herausgenommen wird, eine Art Ausgangszustand wiederhergestellt wird, richtig? Ein paar Anmerkungen hierzu:
- Die anderen Sources können auch returnen, wenn deren Behavior so eingestellt wurde. Generisch betrachtet würde der beschriebene Reset auch in diesen Fällen Sinn ergeben.
- Local, Send, Receive: Ich glaube, wir sollten diese Settings einzeln betrachten:

| Setting | Reset (bei returnender Source) -> Empfänger (Bedingung) |
| - | - |
| Send = off | MIDI Out (immer) |
| Receive = off | UI (immer), Synth (bei Local = on) |
| Local = off | Synth (immer) |

**Comment by davidm2894** [comment]
> Diese Art von Reset soll bedeuten, dass wenn der Bender oder AT (beide immer returnend) aus einem Routing herausgenommen wird, eine Art Ausgangszustand wiederhergestellt wird, richtig? 

Ja, richtig, da sie durch das Return-Verhalten auch einen sinnvollen Wert haben, auf den resettet werden kann. Das haben die Ribbons im RtC Modus auch - stimmt. Die Pedale haben zwar auch einen RtC-Modus, der bildet sich aber nicht in der haptischen Wahrnehmung ab. 

Die Idee war, dass wir die All Notes Off/AE Reset Events verringern können und auf die nachvollziehbar erscheinenden Momente beschränken. Wenn man Änderungen an den Notes Routings macht, dann ist ein All Notes Off/AE Reset für den User nachvollziehbar und sinnvoll. Wenn man ein Pedal ausschaltet, das nicht direkt Klang erzeugt, waren wir zu dem Schluss gekommen, dass es dann eher störend ist. 
Die natürlich returnenden HW-Sources sollen ja auch nur ihren Wert resetten und kein All Notes Off oder AE Reset machen.

**Comment by MatthiasSeeber** [comment]
> Die Pedale haben zwar auch einen RtC-Modus, der bildet sich aber nicht in der haptischen Wahrnehmung ab.

Sowohl die WebUI als auch die HWUI sind in der Lage, eine returnende Source (WebUI: MouseUp, HWUI: Screen/Focus-Wechsel) zu simulieren und damit ein quasi-haptisches Return-Verhalten abzubilden. Bei Pedalen sind es lediglich die physikalischen Controller, die sich nicht in die Betrachtung integrieren lassen.

**Comment by davidm2894** [comment]
Du würdest es also bevorzugen, wenn wir alle HW-Sources gleich behandeln und nach Send/Receive/Local unterscheiden?
Also:
- Send = Off -> All Notes Off
- Receive = Off -> AE Reset (sofern Local On), HW Sources Reset
- Local = Off -> AE Reset, HW Sources Reset

**Comment by MatthiasSeeber** [comment]
Nein.
- AllNotesOff sollte wie du bereits ausführtest lediglich für Noten-relevante Settings genutzt werden. (Panic, Local Enable = off, Veränderung der Send Channels, Note Send = off)
- Bei HW Sources ist der beschriebene Reset eine "Change" Message, welche die neue Return Position der Source beinhaltet.
- Beide "Reset" Events hängen davon ab, ob es um Send, Receive oder Local geht. Wenn Send auf off gestellt wird, müssen wir MIDI rausschicken. Wenn Receive oder Local auf off gestellt wird, müssen wir es lediglich intern verarbeiten.
