### ISSUE TITLE
MIDI: Single -> Convert to Split -> kein All Notes Off

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2831]
Haben auch auf diesem Weg noch einen Notenhänger, bei gedrückter Note und gleichzeitigem Convert Aktion. Es kommt gar kein Note Off, also weder auf Part 1 noch auf 2.

**Comment by MatthiasSeeber** [comment]
Ich glaube, das liegt am (derzeit noch generellen) Problem, dass Preset-Wechsel noch nicht "Reset"-fähig sind. Für die MIDI-Verwaltung sollte ein Recall und ein Convert im selben Ereignis enden:

| Preset-Vorgänger | Preset-Nachfolger | Reset |
| --- | --- | --- |
| Single, Layer | Split | VoiceAlloc + Envelopes, AllNotesOff (primary) |
| Split | Single, Layer | VoiceAlloc + Envelopes, AllNotesOff (primary, secondary) |

**Comment by MatthiasSeeber** [comment]
Nachtrag: Nach Convert müsste (theoretisch) kein Program Change gesendet werden.

**Comment by davidm2894** [comment]
Leider ist der Bug wieder da.

**Comment by MatthiasSeeber** [comment]
Ich kann mit [6deeea1](https://github.com/nonlinear-labs-dev/C15/commit/6deeea1bb2c60861ab0d13feec4a8785b06799c7) den Bug nicht reproduzieren. Ich habe einen Single Sound, halte eine Note, converte auf Split und sehe ein Primary All Notes Off

**Comment by davidm2894** [comment]
> Ich kann mit [6deeea1](https://github.com/nonlinear-labs-dev/C15/commit/6deeea1bb2c60861ab0d13feec4a8785b06799c7) den Bug nicht reproduzieren. Ich habe einen Single Sound, halte eine Note, converte auf Split und sehe ein Primary All Notes Off. Danach auf Layer converten mit einer geh. Taste pro Part erzeugt ANO auf Primary und Secondary.

Da war ich etwas nachlässig. Es passiert auch nur bei Local Off. Gib mir bitte Rückmeldung, ob du es bestätigen kannst, dann öffne ich das Ticket wieder.

**Comment by MatthiasSeeber** [comment]
Hm, ja :/ bei Local Off fehlt der AllNotesOff...
