### ISSUE TITLE
MIDI: Panic-Affengriff schickt im Preset-Modus kein All Notes Off

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2835]
Wenn man im SOLED Preset-Modus ist, schickt der Affengriff kein "All Notes Off" raus. Intern kann ich nicht genau sagen, weil der Affengriff in dem Modus immer auch einen Presetwechsel auslöst.

**Comment by nonlinear-labs** [comment]
Wir müssen den Panikgriff besser gegen Nebenwirkungen absichern:
- [ ] Wenn eine der "-" und "+" Tasten gehalten wird, sollte die andere erst mit Button-Up den Transpose-Wert incrementieren oder dekrementieren. Bei erkanntem Panikgriff gar nicht. Im Moment ist nach den Panikgriff alles um einen Halbton verstimmt.
- [ ] Der "Mode"-Button wirkt eigentlich erst bei Button-Up. Trotzdem ist nach dem Panikgriff der Mode (z.B. in den Edit-Mode) umgeschaltet. Bei längerem Halten der Panikgriffs wird auch in den Preset-Mode umgeschaltet. Das ist störend und vermeidbar.

**Comment by KlausStrohhaecker** [comment]
@nonlinear-labs , full ack, der AllNotesOff-Affengriff muss komplett nebenwirkungsfrei sein, habe ich schon früher mal gefordert (finde es nicht mehr...)

Das erfordert einige Maßnahmen im Button-Eventgenerator oder Statemachine (oder was auch immer die Jungs da haben):
- Sobald die erste der vier PlayPanel-Buttons schließt, startet ein Timer (sagen wir 100ms, besten Wert wird die Erfahrung zeigen).
- Sobald innerhalb dieser Zeit alle vier Buttons gedrückt sind, wird beim Press der vierten Buttons das AllNotesOff ausgelöst und, wichtig, die Button-Statemachine wartet bis alle vier Buttons wieder released sind, egal was sonst passiert.
- Anderfalls, sobald der Timer abgelaufen ist oder alle Buttons released sind, werden die PlayPanel-Buttons wie bisher ausgewertet und zwar unter Miteinbeziehung der währenddessen gepufferten etwaigen Zustandswechsel samt ihrer Zeitbeziehungen, quasi rückwirkend. Wenn zB "Mode" also nur 50ms lang gedrückt war schaltet das wie gehabt dem Mode beim Loslassen sofort um. Drückt man dagegen "Funct", so wird der Event erst erzeugt wenn losgelassen wurde oder der Timer abgelaufen ist, also leicht verzögert.

D.h., der PanicEvent wird nur erzeugt wenn vorher kein Button gedrückt ist und dann alle vier innerhalb der 100ms gedrückt werden. Kommt er nicht zustande, werden die Buttons zuerst _nachträglich_ und dann weitergehend ganz normal ausgewertet, inclusive der Zeiten.

**Comment by nonlinear-labs** [comment]
Die Vermeidung von Nebenwirkungen wird in #2917 behandelt
