### ISSUE TITLE
MIDI: Performance-Einbruch

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2836]
Der C15 kann überlastet werden, indem man CCs mit unterschiedlichen Werten an gekoppelte HW-Sources (Pedal & Ribbon) schickt. Macht sich v.a. dadurch bemerkbar, dass die Ribbon-LEDS auch beim Stoppen des MIDI-Clips noch weiter laufen (bildet sich wohl ein Stau irgendwo). 

Lässt sich auch erreichen, wenn man einen Split-Sound hat und auf beiden Kanälen CCs an die HW Sources schickt - in diesem Fall braucht es keine gekoppelten HW-Sources. 

Je nachdem, wie lange man den Clip abspielt, bleibt auch die UI stehen und es wird nicht mehr auf Tastendrücke reagiert. AE läuft weiter. Im Splitsound-Fall wird der C15 schneller schwach.
[performance_midiclip.mid.zip](https://github.com/nonlinear-labs-dev/C15/files/7260507/performance_midiclip.mid.zip)

**Comment by MatthiasSeeber** [comment]
Durch die bisherige Premisse, dass der Secondary-Kanal nur in Split Sounds existiert, und dementsprechend Noten, HW Changes (Ctrl Chg, PB, AT) sowie Program Changes nur über Secondary empfangren werden können wenn man gerade einen Split Sound geladen hat, haben wir die Primar/Secondary Häkchen eingeführt.

Damit kann man also additiv Primary und Secondary zusammenfügen und von beiden Kanälen gleichzeitig empfangen bzw. senden. Für Noten ist dies auch definitiv sinnvoll. Bei HW oder Program Changes jedoch erscheint mir ein (exklusives) entweder/oder sinnvoller, deshalb hier ein Vorschlag:

Bei den Routings für HW Sources und Program Changes statt den Check-boxes für Primary/Secondary lieber Radio-boxes (Receive und Send). Und in der Logik dann den Sound-Typen für HW/Prog Changes einfach ignorieren. Intern sind die Sources eh immer global (also nicht an einen Split Part gebunden).

Unterm Strich dürfte sowohl die Logik der MIDI-Verarbeitung etwas schrumpfen als auch ein Schutz vor Fluten von Control Changes entstehen. Die Hoffnung wäre, dadurch Performance Peaks zu vermeiden. Es ist doch auch nicht wirklich sinnvoll ein HW Source gleichzeitig über zwei MIDI-Kanäle anzusteuern, oder?

**Comment by davidm2894** [comment]
Finde ich einen guten Vorschlag - allerdings würde ich die entweder/oder-Auswahl auf den Empfang beschränken. Beim Senden fallen mir doch sinnvolle Anwendungsszenarien für das Senden über zwei Kanäle ein. Und das reine Senden sollte ja auch zu keinen Performance-Problemen führen, oder?

**Comment by MatthiasSeeber** [comment]
Nun.. die Problembeschreibung deutet auf die Eingabe-Seite hin und eine exklusive Eingabe-Belegung der HW Sources sollte das Problem umgehbar machen.

Theoretisch könnte die Ausgabe-Seite weiterhin nicht-exklusiv bleiben, allerdings habe hier Vorbehalte:
- Dinge möglichst generisch und simpel halten: Eingabe-Routings und Ausgabe-Routings mit identischen Optionen (also bei HW Sources: Radio Buttons für Primary/Secondary bei Receive und Send)
- Datenverarbeitung/Logik möglichst einfach halten: Mit Radio Buttons für HW Sources und Program Changes für Send und Receive kann man den Sound Type komplett aus der Event-Verarbeitung herausnehmen (wenn Send allerdings weiter Checkboxes hat, wäre dies für die HW Sources weiterhin vom Sound Type abhängig)
- Redundanzen möglichst vermeiden: Wozu identische Daten gleichzeitig auf zwei Kanälen rausschicken?

**Comment by nonlinear-labs** [comment]
Eine minimal-invasive Lösung: bei Program Change und den 8 HW-Sources die Receive-Häkchen von Primary und Split Channel gegenseitig auslösen lassen. Es gibt also drei mögliche Zustände (ähnlich wie beim Part-Muting):
Primary:   Split:
  On           Off
  Off           On
  Off           Off

**Comment by schlenkibus** [comment]
I suppose the defaults for the new exclusive routing (cleanup for existing settings) would be enabled for primary and disabled for split?
