### ISSUE TITLE
Recorder: Shortcut Ctrl + R not working

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2860]

**Comment by nonlinear-labs** [comment]
Still a problem with the MC View shortcut (Ctrl+M): it tries to open http://192.168.8.2:8080/MCView/index.html
The correct address would be: http://192.168.8.2:8080/mc-view/index.html

**Comment by davidm2894** [comment]
Just a thought: 
Will the URL change be repeated in the future? If so, we might consider a redirect mechanism or notification, as bookmarks are out of date too.
