### ISSUE TITLE
MIDI UI Anzeigefehler

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2877]
Setup:
Local Enable Off
MIDI: C15 -> DAW -> C15

Schicke ich HW-Sources über MIDI (MSB + LSB) raus an eine DAW und dann wieder zurück, kommt es zu Anzeigefehlern. 

- [ ] Die Extrema in der MC-Ansicht werden nicht erreicht, es bleibt (wie stark hängt von der DAW ab) oberhalb von 0 bzw unterhalb von 100. Das setzt sich dann auch in der Parameteransicht fort.
- [ ] Es gibt starke Delays bzw. Aussetzer in der Anzeige. Der Sound reagiert direkt, die Anzeige bleibt entweder auf einem Wert stehen oder braucht merklich Zeit um den Wert zu updaten. Hier gibt es Unterschiede bei den DAWs. Logic verursacht die größten Probleme, Ableton folgt danach und mit Reaper ist es noch am schnellsten. Wenn ich mir den MIDI Output von der DAW monitore (an der Schnittstelle zur Bridge) nehme ich aber keine Zeitverzögerungen wahr. 
- [ ] der Pitchbender macht die größten Probleme. Hier ist er bei Reaper bspw. invertiert in der MC Anzeige, bei Logic und Ableton fällt er meistens einfach auf 0 und bleibt dann auch da stehen.

Das passiert alles nur bei MSB + LSB (bis auf der Bender, der ja eh die höhere Auflösung hat). Wenn ich auf MSB begrenze, spricht alles gut an. 

Wenn ich das aufgenommene MIDI dann wiedergebe, funktioniert alles wieder wie erwartet.

**Comment by davidm2894** [comment]
> Abgesehen davon erschließt sich mir kein wirklicher Sinn eines solchen Setups. HW Sources über Local Disable und DAW zurück an Receive zu schicken bewirkt aus meiner Sicht lediglich eine Verzögerung der Modulation und unnötige Komplexität.

Also das ist nichts ungewöhnliches und eine völlig normale Arbeitsweise. 
Zwei Beispiele:
Einmal aus dem Logic Manual ([Link](https://support.apple.com/de-de/guide/logicpro/lgcpebe6ceab/mac))

und aus dem KORG Wavestate Manual ([S. 80](https://cdn.korg.com/us/support/download/files/8f3b2b64a5cf6240cf028c4591d18515.pdf?response-content-disposition=inline%3Bfilename%3Dwavestate_OM_G1.pdf&response-content-type=application%2Fpdf%3B)):
`Local Control
[Off, On]
On: Dies ist die Vorgabe. Die internen Sounds des wavestate werden von der eingebauten Tastatur und den Spielhilfen
angesteuert. Wenn Sie den wavestate als eigenständiges Instrument verwenden, muss dieser Parameter aktiv sein.
Off: Die Tastatur und die Bedienelemente des wavestate (darunter auch die Mod-Regler) sind nicht mehr mit der
internen Klangerzeugung verbunden. Es werden aber weiterhin MIDI-Befehle gesendet und empfangen. Wählen Sie
diese Einstellung, wenn Sie mit einem Sequenzer arbeiten, der alle empfangenen Daten sofort wieder ausgibt.`


Hier nochmal ein Video zu dem Thema, ich hoffe man versteht was:
https://user-images.githubusercontent.com/84857645/141988113-811df361-b83d-4a87-a99a-17076d6b6ddc.mp4

Man sieht, dass der MC C, der an den Bender gekoppelt ist, sich völlig entgegen der Erwartung verhält. Er geht in die entgegengesetzte Richtung, er bleibt stehen. Weiter bleibt natürlich auch der an den MC gekoppelte Parameter (Pitch in diesem Fall) an den Stellen stehen. Wie gesagt, es ist nur visuell. Aber es kann gerade dadurch dazu führen, dass man das gar nicht mitbekommt, das Preset dann so abspeichert und dort Werte angezeigt werden, die nicht im Zusammenhang mit dem Klang stehen.

In früheren OS Versionen hatten wir den Bug nicht. Ich hatte nochmal auf den ersten MIDI Release gedowngradet und hier funktioniert es noch.

**Comment by MatthiasSeeber** [comment]
Ich habe in dem Video auch bei Fullscreen-Wiedergabe das Display kaum lesen können. Du bewegst den PB zuerst nach rechts und der Pitch zeigt 58, oder sehe ich da was falsch?

Es ist halt problematisch, wenn ein HW Param in der UI nur einmal da ist und auf alle Editierungen, Receive und internal Sources gleichzeitig reagiert. Deswegen sollten wir dieses Problem m.M.n. genauer betrachten, wenn #2853 erledigt ist.

**Comment by davidm2894** [comment]
Okay, das Video wurde wohl ziemlich runter komprimiert. Nein, ich bewege den Bender nach links, der Pitch geht hoch - und umgekehrt.
