### ISSUE TITLE
Restore Backup: Warum wird erst "writing" für die bisherigen Bänke und dann "reading" für die Bänke aus dem Backup durchgeführt?

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2884]
Ein Sichern der alten Bänke in ein File ist eigentlich nicht erforderlich. Ein Undo würde ggf. aus dem RAM kommen.

**Comment by KlausStrohhaecker** [comment]
Wenn es 100% fail-safe sein soll (niemals ein korrupter/unvollständiger Stand der Bänke möglich egal was passsiert, power-fail etc), dann ist ein des Backup des Iststandes Pflicht, zusammen mit anderen Maßnahmen natürlich.

**Comment by nonlinear-labs** [comment]
Soweit ich weiß, ist auch das Einspielen eines Backups Undo-fähig. Das heißt, es liegt noch eine Kopie des alten Standes im RAM. Als Sicherheit für den User reicht mir das aus.
Übrigens: wenn ein "writing"-Vorgang ausgeführt wird, nehme ich an, dass es um das Erzeugen einer Datei geht. Da wäre dann die Frage, ob diese Datei auf die Festplatte geschrieben wird und ob sie als Absicherung gedacht ist.

**Comment by nonlinear-labs** [comment]
Es sieht so aus, als wenn die "writing"-Zeilen einfach nicht mehr angezeigt werden. Das hat zur Folge, dass im Display eine ganze Weile gar nichts mehr passiert, bis es dann plötzlich doch noch losgeht mit den "reading"-Zeilen.
Es entsteht der Eindruck, dass die angestossene Aktion nicht funktioniert.
Wenn das "Writing" wirklich notwendig ist (als Fallback? fürs Undo?), dann zeigen wir es lieber auch. Oder einen anderen Fortschritts-Indikator...

**Comment by davidm2894** [comment]
"Writing" ist wieder da.
