### ISSUE TITLE
HWUI : button press '-' (Encoder CCW) on preset 1 jumps to last preset of selected bank [BUG]

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2885]
Current unstable :
![image](https://user-images.githubusercontent.com/4758563/139590725-69df3e9a-0e7a-44e1-9e20-546801ba16f1.png)

if  you navigate through the presets by decreasing (pressing minus or turning encoder CCW)  at selected preset 1, menu jumps to the highest preset in bank . in the other direction there is a stop.

1. Should be the same in both directions
2. should stop at the minimum and maximum preset number.

**Comment by KlausStrohhaecker** [comment]
Not reproducible here.
