### ISSUE TITLE
HWUI: Preset selection screen: HOME and END function by holding Shift while inc/dec [ENHANCEMENT]

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2886]
could be handy in preset menu : 
jump to **first** preset by holding  [ **'SHIFT' and 'Dec(-)'** ]  or [ **'SHIFT' and Encoder-CCW** ] (HOME or POS1 function)
jump to **last** preset by holding  [ **'SHIFT'  and 'Inc(+)'** ] or [**'SHIFT'  and Encoder-CW** ] (END function)

**Comment by KlausStrohhaecker** [comment]
👍

**Comment by majjam** [comment]
additionally it is consistent to the parameter behavior
