### ISSUE TITLE
Wenn das selektierte Preset bereits geladen ist, sollte das Einschalten von "Direct Load" es nicht noch einmal laden.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2894]

**Comment by KlausStrohhaecker** [comment]
Hhm, DirectLoad tut mE zwei Sachen:
- Es schaltet den Mode um, sodass ein Preset Scroll zukünftig das Preset auch sofort lädt
- Aber beim Einschaltvorgang des DirectLoad-Modes. also beim ersten Mal lädt auch es das Preset unter dem Cursor sofort, ohne dass es Scroll vorlag... selbst wenn es das gleiche Preset ist (und ein verändertes solches wieder resetted).

M.E ist das voll konsistent.

**Comment by schlenkibus** [comment]
Ich habe dieses Ticket gefunden: https://github.com/nonlinear-labs-dev/C15/issues/1710 
Was jetzt aber korrekter ist kann ich nicht einschaetzen.

**Comment by KlausStrohhaecker** [comment]
Ich denke man kann man es so rum oder so rum als logisch/sinnvoll erachten, aber nur ein Weg davon ist möglich.... damit also Stephan's, der Nebeneffekte stärker bewertet als Inkonsistenz. ;-)

Die Problematik besteht darin dass DirectLoad sowohl eine Betriebsart global ändert als auch (aber nur manchmal) gleich eine Aktion startet... das Laden welches normerweise erst mit Enter passiert.
