### ISSUE TITLE
BOLED: Preset Screen: Wenn man auf dem ersten Preset ist und decrementiert, wird das letzte Preset selektiert.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2896]
Bitte wie bisher - mit "Anschlag" an beiden Enden der Liste.

**Comment by KlausStrohhaecker** [comment]
Ist im tagesaktuellen `unstable` gefixt, seit gestern: https://github.com/nonlinear-labs-dev/C15/pull/2888
