### ISSUE TITLE
Recorder (Settings): "Auto-Start Recorder" sollte nach der Installation "Off" sein. Beim Öffnen des Recorders darauf hinweisen.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2900]
Solange Auto-Start Off ist und der Recorder noch nicht per Hand gestartet wurde, sollte beim Öffnen des Recorder-Fensters diese Meldung kommen:

"To start the recording please use the Record button. You can enable Auto-Start in the Recorder Settings in the Setup."

Darunter ein "Ok"-Button.

**Comment by hhoegelo** [comment]
@nonlinear-labs "Solange ... und der Recorder noch nicht per Hand gestartet wurde ..."

Wo soll gespeichert werden, ob schon einmal per Hand auf Record gedrueckt wurde?

- in dieser Instanz (Speichern im RAM)
- in diesem Browser (Speichern im WebStorage)
- auf diesem Geraet (Speichern auf SSD)

**Comment by nonlinear-labs** [comment]
Bitte auf dem Gerät speichern.

**Comment by nonlinear-labs** [comment]
David fragt: "Ist es gewollt, dass wenn AutoStart = Off und ich einmal den Recorder manuell gestartet habe, er auch nach Aus- und Anschalten wieder aufnimmt?"

Nein, AutoStart sollte aus bleiben, bis der User AutoStart es explizit (manuell) einschaltet. Bis dahin sollte er in jeder Session beim ersten Öffnen des Recorders wieder den Hinweis bekommen.

**Comment by hhoegelo** [comment]
> "Ist es gewollt, dass wenn AutoStart = Off und ich einmal den Recorder manuell gestartet habe, er auch nach Aus- und Anschalten wieder aufnimmt?"

@nonlinear-labs @davidm2894 David konnte das geschilderte Verhalten nicht mehr reproduzieren und durch den Code ist es ebenfalls nicht zu erklaeren, so dass wir davon ausgehen, dass der Bug nicht existiert und eine Fata Morgana war.

**Comment by hhoegelo** [comment]
> David fragt: "Ist es gewollt, dass wenn AutoStart = Off und ich einmal den Recorder manuell gestartet habe, er auch nach Aus- und Anschalten wieder aufnimmt?"
> 

@nonlinear-labs  Hier bitte ich um Klarstellung: 

"AutoStart sollte aus bleiben ... Bis dahin sollte er in jeder Session beim ersten Öffnen des Recorders wieder den Hinweis bekommen."

unterscheidet sich von der urspruenglichen Anforderung:

"Solange Auto-Start Off ist und der Recorder noch nicht per Hand gestartet wurde, sollte beim Öffnen des Recorder-Fensters diese Meldung kommen"

Implementiert ist die urspruengliche Anforderung, die also den Dialog nie wieder zeigt, wenn jemals auf Record gedrueckt wurde.

**Comment by nonlinear-labs** [comment]
> "AutoStart sollte aus bleiben ... Bis dahin sollte er in jeder Session beim ersten Öffnen des Recorders wieder den Hinweis bekommen."
> 
> unterscheidet sich von der urspruenglichen Anforderung:
> 
> "Solange Auto-Start Off ist und der Recorder noch nicht per Hand gestartet wurde, sollte beim Öffnen des Recorder-Fensters diese Meldung kommen"
> 
> Implementiert ist die urspruengliche Anforderung, die also den Dialog nie wieder zeigt, wenn jemals auf Record gedrueckt wurde.
Ok - lassen wir es so, wie es implementiert ist. Meine neue Variante ist wahrscheinlich zu aufdringlich.
