### ISSUE TITLE
Presetwechsel mit Bender != Null führt zu bleibenden Offsets der modulierten Parameter (gilt für alle "returning" HW-Sources)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2915]
Wahrscheinlich nur zu vermeiden, wenn wir auf Modulation durch Absolutwerte statt durch Incremente umsteigen

**Comment by majjam** [comment]
Ich vermute issue #724 hängt hier an einem ähnlichem Effekt.

Off-topic: Ist es beschlossene Sache, dass die Modulation eines Tages von inkrementell auf absolut umgeändert wird ?

(Ich glaube bei mir würde das einige Presets durchwürfeln, ich muss aber mal prüfen, ob diese Art der MC verschaltung musikalisch überhaupt genutzt wird)

**Comment by nonlinear-labs** [comment]
Hi Majjam, soweit ich es bisher durchdacht habe, sollte eine Umstellung auf die Modulation durch Absolutwerte statt durch Incremente für den User kein verändertes Verhalten bringen. Die Verbesserung läge im Bereich der zuverlässigeren Initialisierung z.B. bei Presetwechseln und der Vermeidung potentieller Rechen-Ungenauigkeiten. Aber wenn Du potentielle Nebenwirkungen auf Presets von Dir siehst, wäre ich für Hinweise dankbar.

**Comment by majjam** [comment]
Ich prüfe das mal genauer und mache dann ggfs ein Beispiel fertig.

Aber aus meinem Gedankenprotokoll heraus : Ein Preset mit Ribbon und Bender-zuordung auf den gleichen MC.
Über das Ribbon stellt man Basis Wert ein, und der Bender kann davon ausgehend den MC inkrementieren und dekrementieren. (sofern and den Seitenrändern noch Platz dazu ist.)
Also Ribbon absolut und PB relativ dazu.

**Comment by nonlinear-labs** [comment]
Das ist kein so exotischer Case. Ich würde es eher "additive" Modulation nennen. Die kann man auch aus den Absolutwerten der beteiligten HW-Sources errechnen.

**Comment by majjam** [comment]
Soweit ich es durchgespielt habe ist diese additive Modulation, der Fall , den ich bei absolut vs inkrementell als gefährdet angesehen habe. Vielleicht eine Fehlinterpretation meinerseits.

**Comment by MatthiasSeeber** [comment]
Issue #3035 ist etwas umfassender, beinhaltet aber die hier beschriebene Problematik (die auch bei Preset Store besteht). Da bereits einige Test diesbezüglich erfolgreich waren, gibt es keinen Grund, dieses Ticket weiterzuführen.
