### ISSUE TITLE
[Local: Off] Provide Info Texts for secondary HW Source Parameters

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#2919]
### Attention
We have to be careful about the order of changing the ParameterList.ods, so #2874 and #2916 need to be merged first. *(the file is binary and parallel, branch-based changes cannot be merged by gh)*

### Goal
When in MIDI Mode Local OFF, the secondary HW Parameters should be visible. As they are displayed as ordinary Parameters, we require Info Texts for them.

### Proposition
~~~
When the MIDI Local Setting is disabled, this control is the
parameter representation of the "Pedal 1" Hardware Source.
It reflects changes that will be sent when the MIDI Channels
Settings allow for MIDI to be sent without affecting the Synth.

This parameter will be visible next to the internal representation
of "Pedal 1" (which reflects changes from the User Interface or
MIDI Input, only affecting the Synth).
~~~

@nonlinear-labs, @davidm2894 please discuss further in the comments.

**Comment by davidm2894** [comment]
> `When the MIDI Local Setting is disabled,`

MIDI Local ist hier eigentlich die falsche Bezeichnung, weil Local ja gerade kein MIDI ist. Auf der anderen Seite ist es natürlich eine Einstellung aus dem MIDI-Kontext und in dieser Formulierung im Text deutlich leichter zu verstehen.
Alternativer Vorschlag wäre:
`When Local is disabled in the MIDI Settings, ...`

Man könnte vielleicht noch einbringen, dass der Encoder bzw. -/+ auf den "Send" Parameter Einfluss hat, aber nicht auf den "Receive".

**Comment by MatthiasSeeber** [comment]
> weil Local ja gerade kein MIDI ist
Verstehe ich nicht ganz. Weder Local OFF noch Local ON bewirken "kein MIDI", habe aber gegen den Vorschlag nichts einzuwenden.

**Comment by MatthiasSeeber** [comment]
```
When Local is disabled in the MIDI Settings, this control is the
parameter representation of the "Pedal 1" Hardware Source.
It reflects changes that will be sent when the MIDI Channels
Settings allow for MIDI to be sent without affecting the Synth.

This parameter will be visible next to the internal representation
of "Pedal 1" (which reflects changes from the User Interface or
MIDI Input, only affecting the Synth).

```

**Comment by davidm2894** [comment]
> > weil Local ja gerade kein MIDI ist
> 
> Verstehe ich nicht ganz. Weder Local OFF noch Local ON bewirken "kein MIDI", habe aber gegen den Vorschlag nichts einzuwenden.

Ja genau das habe ich gemeint. Es bezieht sich ja auf die interne Verarbeitung und nicht auf MIDI.
Finde den Text jetzt gut.

**Comment by nonlinear-labs** [comment]
"It reflects changes that will be sent when the MIDI Channels Settings allow for MIDI to be sent without affecting the Synth."
lässt sich vereinfachen:
"It reflects changes that will be sent via MIDI without affecting the Synth."
Das die Channel Settings noch einen Einfluss haben können, muss man hier nicht erklären.
