### ISSUE TITLE
Erweiterte Bereiche für einige Key Trackings, Key Panning, einige Velocities, Unison Detune

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2920]
- [x] Output Mixer - Key Pan: -100.0 ... 100.0 % (auch in #2756)
- [x] Oscillator A - Pitch - Key Trk: 0.00 ... 200.00 %
- [x] Oscillator B - Pitch - Key Trk: 0.00 ... 200.00 %
- [x] Comb Filter - Pitch - Key Trk: 0.00 ... 200.00 %
- [x] Comb Filter - AP Tune - Key Trk: 0.0 ... 200.0 %
- [x] Comb Filter - Hi Cut - Key Trk: 0.0 ... 200.0 %
- [x] SV Filter - Cutoff - Key Trk: 0.0 ... 200.0 %
- [x] Unison - Detune: 0.00 ... 24.00 st
- [x] Envelope A - Attack Velocity: -100.0 ... 100.0 %
- [x] Envelope B - Attack Velocity: -100.0 ... 100.0 %
- [x] Envelope C - Attack Velocity: -100.0 ... 100.0 %
- [x] Envelope A - Time Key Trk: -100.0 ... 100.0 % ~~(intuitiver, wenn man die bisherigen 0...100% auf 0...-100% mappt?)~~ 
- [x] Envelope B - Time Key Trk: -100.0 ... 100.0 %
- [x] Envelope C - Time Key Trk: -100.0 ... 100.0 %

Envelope X Attack - Velocity -> DB_t instead of %

**Comment by majjam** [comment]
zwei Fragen hierzu:
1. sollte Unsion-Pan dann nicht auch analog dazu von -100 bis 100 % gehen ?
2. (unabhängig von 1) was passiert bei Output-Mixer-Pan =100% und Unision-Pan = 100% ?

**Comment by MatthiasSeeber** [comment]
@majjam 

1. Unison Pan bestimmt, wie weit der Unison Cluster ins Stereobild gespreizt wird. Bei 100% gibt es dann eine der Stimmen mit 100% L und eine mit 100% R. Hier beispielhaft die Spreizungen für 5 Unison Voices: -4/4, -2/4, 0/4, 2/4, 4/4. Theoretisch könnte man auch negatives Unison Pan erlauben, was die Spreizung dann invertieren würde. Ich bin mir allerdings nicht sicher, wie nützlich dies wäre bzw. ob das ein Zugewinn ist.
2. Aus den Pannings (Unison Pan, Key Pan, Mixer-Channel Pan) errechnen wir dann durch Addition und anschließendes Clipping Faktoren für jeweils L und R eines Mixer-Channels (z.B. Out Mix A). Key Pan (und Mixer-Channel Pan) verschieben also die Spreizungen eines Unison Clusters, bis sie ins Clipping gehen.

**Comment by nonlinear-labs** [comment]
Wegen der Kopplung der Detune-, Pan- und Phase-Offsets an den Index der Voice würde bei einem negativen Pan-Amount die höchste Stimme nicht rechts sondern links zu hören sein. Das könnte also schon eine kreative Option sein. Ob es bei negativem Phase-Amount hörbare Unterschiede gibt, wenn die Phasen mit steigendem Pitch nicht nach vorn sondern nach hinten verschoben werden, kann ich nicht vorhersagen.
Man könnte also - zumindest für eine experimentelle Version - Unison Pan und Phase einmal bipolar auslegen.

**Comment by majjam** [comment]
Hallo zusammen, 
danke für die Erläuterungen! Trotzdem musste ich mir das mir das noch einmal verbildlichen und habe den mileston-syntengine-update angetestet.
Dazu habe ich ei paar Sweeps von C1 zu F#3 zu C6 aufgenommen
Sound -
1. Mono 
2. Unision 
3. Sound detune auf 24st
4. key pan und unision pan variiert

[pantest.zip](https://github.com/nonlinear-labs-dev/C15/files/8541845/pantest.zip)

Keypan 100 unision pan 0
https://user-images.githubusercontent.com/4758563/164737232-a1c289db-596f-494a-a6d7-84f2e2d34f09.mp4

Keypan 100 unision pan 100
https://user-images.githubusercontent.com/4758563/164737242-ba6bf866-d65c-45da-9a1d-8517b2948ed9.mp4

Keypan 100 unision pan 50
https://user-images.githubusercontent.com/4758563/164737251-e060fb75-1251-4885-873f-929497923330.mp4

Keypan -100 unision pan 50
https://user-images.githubusercontent.com/4758563/164737260-a4697087-8274-4112-b6af-dd07923feb39.mp4

Keypan -100 unision pan 100
https://user-images.githubusercontent.com/4758563/164737269-343ddef8-0fe4-40fd-bd6a-dc347d509fbf.mp4


(ps. habe das gefühl das unision detune bei diesm zweig direkt am keytracking hängt . evtl ein Bug ?)
.

**Comment by MatthiasSeeber** [comment]
> (ps. Ich habe das Gefühl das unision-detune bei diesem Zweig direkt am Keytracking hängt . evtl ein Bug ? keytrackig = 0 unision detune = 0)

In der Tat: die durch Unison Detune entstandenen Pitch Offsets addieren sich auf die Key Position, welche dann durch Key Trackings gewichtet wird. Das ist (bisher jedenfalls) kein Bug und war quasi schon immer so.

Dies zu ändern hieße auch, dass Presets mit Key Trackings ungleich 100% plötzlich anders klingen würden.

**Comment by MatthiasSeeber** [comment]
Überlegungen in Richtung bipolarer Unison Pan und Phase habe ich auf #3126 umgelagert. Dieses Ticket hier ist quasi schon behandelt.

**Comment by majjam** [comment]
Hallo Matthias, danke für das Schaubild.

> n der Tat: die durch Unison Detune entstandenen Pitch Offsets addieren sich auf die Key Position, welche dann durch Key Trackings gewichtet wird. Das ist (bisher jedenfalls) kein Bug und war quasi schon immer so.
Dies zu ändern hieße auch, dass Presets mit Key Trackings ungleich 100% plötzlich anders klingen würden.

Das ist auch ok. Es ist mir vorher nicht aufgefallen, da ich bei den Oszis meistens Key Tracking auf 100% hatte - zumindest bei den "Ganzton-Verstimmten-Unision-Detune-Sounds"(tm). Unabhängig davon ist die Kompatibilität zu alten SW- Ständen schon ein wichtiger Faktor.

**Comment by davidm2894** [comment]
KeyPan in Preview nur von 0-100% anstatt -100-100%.
