### ISSUE TITLE
Shaper A/B - FB - Env C: Bereich auf -100 % ...100 % erweitern. Negativer Teil dient zum Bypassen des Gates

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2921]
100 % : Envelope C voll wirksam
0% : Gate voll wirksam
-100 %: Gate unwirksam, Signalweg permanent offen (Multiplikation mit 1)

Im positiven Bereich crossfaden wir - wie bisher - zwischen dem Gate-Signal und dem Envelope-Signal. Im negativen Bereich zwischen dem Gate-Signal und der konstanten 1.

Das Gate hilft, ein Dauer-Feedback (Durchpfeifen) beim Loslassen der Taste zu vermeiden. Es ist in Physical-Modeling-Strukturen aber oft störend, weil die Töne nach dem Loslassen der Taste nicht natürlich abklingen. Mit dem Envelope C mit langer Release-Zeit kann man das zwar umgehen, damit ist aber der Envelope für nicht anderes mehr verfügbar. Ausserdem ist er dafür "überqualifiziert".
Der neue negative Range eignet sich auch gut für die Anwendung eines Sustain/Damper-Pedals.

Der Parameter könnte vielleicht umbenannt werden in "FB - Gate/Env C".

**Comment by majjam** [comment]
danke: ich hab immer überlegt, wie man das gate für fb austricksen kann. bzw wie man ein ticket dazu formulieren kann ! (Gerade wenn Fb Futter für den comb filter ist habe ich einige male gewünscht das gate per pedal wegschalten zu können )

**Comment by MatthiasSeeber** [comment]
The import of Parameter Shaper A/B > Feedback Mix - Gate - Env C does not work correctly (100% become 50%). The bug originates here: https://github.com/nonlinear-labs-dev/C15/commit/c21c83a0f6dcb26c03f6bec52e8172ffc06da126#r92160271 (and the following line).
