### ISSUE TITLE
BOLED: Settings u.ä.: mit "Enter" getriggerte Aktionen bitte nicht erst am Ende der Balken-Animation ausführen.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2922]
Die Animation abzuwarten führt zu einer unnötigen Verzögerung z.B. beim "Panic"-All-Notes-Off in den MIDI-Settings.

**Comment by schlenkibus** [comment]
Soll das fuer alle Items gelten?
Also auch fuer Store Init Sound, Reset Init Sound, Set MIDI Defaults?

**Comment by nonlinear-labs** [comment]
Sorry für die späte Antwort. Bitte alle Aktionen vor der Animation auslösen.
