### ISSUE TITLE
EPC2: iso-installer corrupt

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2923]
The current unstable epc2 iso-installer (https://github.com/nonlinear-labs-dev/C15/tree/unstable/build-tools/epc2/install-medium) does not work properly. I assume it is because `/update-scratch` and `/os-overlay` are missing on `/dev/sda3` after installation. Both are needed for our C15 update installer [here](https://github.com/nonlinear-labs-dev/C15/blob/42fe83c1ede9e977b05f713699cfbcd0ea4aad0b/build-tools/create-c15-update/update_scripts/epc_push_update.sh#L45)

Not sure how this effects the current RC [21-45](https://github.com/nonlinear-labs-dev/C15/releases/tag/21-45-fix)

**Comment by schlenkibus** [comment]
@AntonSchmied The current Preview for 21-45 is broken as well. I reverted the merge of build-tools-2 into staging, the resulting preview can be found here: https://github.com/nonlinear-labs-dev/C15/releases/tag/21-45-fix

**Comment by AntonSchmied** [comment]
This currently works on #3036 (milestone-sp-a3). soi'll close it.
