### ISSUE TITLE
BOLED: Store: Wenn man ein unverändertes Preset mit Append/Insert speichert, wird der "Store"-Mode danach nicht ausgeschaltet.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2924]
Bei den übrigen Store-Aktionen ist der Store-Mode korrekterweise danach wieder deaktiviert.

**Comment by schlenkibus** [comment]
I can only reproduce this bug with the 'Append' option. 'Insert' does end the Store mode after the animation is finished.

**Comment by nonlinear-labs** [comment]
Ok. Probably I tried it only with Append.
