### ISSUE TITLE
Es fehlt noch "All Notes Off" für Local = Off, wenn man bei gehaltener Note den Send-Kanal wechselt.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2939]
Das gilt für das globale Local Off und für das Local Off für Notes.

Wahrscheinlich orientieren wir uns zur Zeit nur an internen VA-Resets...?

**Comment by davidm2894** [comment]
Kleine Ergänzung dazu: 
Ich kann das Verhalten bis auf eine Ausnahme bestätigen. Bei Split Sounds ist das Verhalten wie gewünscht.

**Comment by davidm2894** [comment]
Auch bei MIDI-relevanten Änderungen in der Routings-Matrix fehlt das AllNotesOff bei gehaltener Note und Local Off (auch globales Local Off). Hat wahrscheinlich die gleiche Ursache.

Auch hier ist es so, dass es bei SplitSounds funktioniert, bei Single/Layer aber nicht.
