### ISSUE TITLE
WebUI: Die Browser-Adresszeile zeigt jetzt wieder :8080

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2941]
Wie ist das reingekommen, und werden wir das wieder los?

**Comment by hhoegelo** [comment]
Der Grund ist: Auf PC darf man als normaler User keinen Port 80 anbieten. Daher bietet Playground seine Services auf 8080 an. Auf dem Geraet gibt es zusaetzlich den Service auf Port 80, der aber direkt auf 8080 umleitet.

**Wie ist das reingekommen?**
Frueher hatten wir cmake switches, die beim Bauen fuer Dev-PC Port 8080 verwendeten und beim Bauen fuer das Geraet Port 80. Das hat aber beim Entwickeln manchmal fuer Probleme gesorgt, daher habe ich das wir oben beschrieben umgebaut.

 **Wie werden wir das wieder los?**
Ich denke die Umleitung ist keine gute Idee gewesen, stattdessen kann der auf dem Geraet laufenden Port-80-Service einfach genau das gleiche anbieten, wie der 8080 Service. Ich muss mir das nochmal anschauen.

**Comment by nonlinear-labs** [comment]
Ich würde daraus auch kein Drama machen wollen. Die Adresszeile sieht halt ein bisschen unsauberer aus, und in der Dokumentation ist es bisher ohne :8080 angegeben oder abgebildet.
