### ISSUE TITLE
WebUI: Setup - Kosmetik

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2946]
![Device Settings](https://user-images.githubusercontent.com/33938408/143439631-6e4e065b-0d46-4c1c-ad1f-ecdb1de0b94d.PNG)

- [ ] Device Settings: hier gibt es einen senkrechten Scrollbar, weil die untersten 3 mm des Fensters nicht sichtbar sind. Bitte das Fenster entsprechend vergrößern, dass dieser Scrollbar überflüssig wird.

![MIDI Settings](https://user-images.githubusercontent.com/33938408/143439614-7ca863ad-a515-437d-9af7-dcb311b1cfc6.PNG)

- [ ] Scrollbars: Wenn es einen senkrechten Scrollbar gibt, wird im Chrome-Browser nach dem Wechsel in einen anderen Tab der senkrechte Scrollbar breiter und es kommt noch ein horizontaler Srollbar hinzu und ein hässliches weißes Rechteck. Da wir in den MIDI Settings nicht ohne senkrechten Scrollbar auskommen, müssen wir am rechten Rand genug Platz dafür lassen und das Fenster-Verhalten so konfigurieren, dass kein horizontaler Scrollbar erscheint, und erst recht nicht so ein weißer Fleck...

![System Info](https://user-images.githubusercontent.com/33938408/143439559-a7419df3-f803-4484-8e2a-cebed3458510.PNG)

- [x] System Info: die "Save"-Buttons sitzen zu dicht an den Textfeldern. Zwischen den drei Buttons der Passphrase können die Abstände etwas kleiner sein, und alle bitte gleich. Also z. B. so: Textfeld - 2 mm - "Save" - 2 mm - "Dice" - 2 mm - "Default"

- [x] Die Funktion "Dice" heisst im BOLED "Randomize". Ich denke, wenn wir in beiden UIs "Random" verwenden, passt es auch hier rein.

- [x] System Info: in der Zeile "Upload Software Update" gibt es einen weißen Button, der in Browsersprache (also z.B. auch in Deutsch) beschriftet wird. In Englisch ist es "Choose File". So etwas machen wir sonst nicht und weiße Buttons auch nicht. Bitte einen unserer grauen Buttons nehmen und fest mit "File" beschriften.

- [x] Tabs: Der aktive Tab ist schwer von den anderen zu unterscheiden. Ich schlage vor, die Schriftfarbe der nicht aktiven Tabs leicht grau abzutönen.

**Comment by MatthiasSeeber** [comment]
Anmerkungen:
- Passphrase:  in der WebUI gibt es die Buttons Save, Dice, Default. In der HWUI gibt es Cancel, Edit, Randomize, Default. Der Rename Screen für die Passphrase besitzt auch einen Cancel Button. Ginge das nicht simpler und konsistenter zw. beiden UIs?
- HWUI: Free Internal Memory vs WebUI: Free Disk Space
- HWUI: Ram Usage vor Software Version, WebUI: Ram usage nach Commit Date
- HWUI: Software Version ist ein Submenu und Commit Date fehlt, WebUI: alle Version und HWID Infos untereinander, RT Version fehlt

**Comment by nonlinear-labs** [comment]
System Info - "Upload Software Update" - Hier würde ich einen Standard-Button mit "Choose File"-Beschriftung einsetzen. "No file chosen" würde ich weglassen. Während des Uploadvorgangs könnte man den Button durch ein reines Text-Label ersetzen: "Uploading <Filename>".

**Comment by schlenkibus** [comment]
- [ ] Dialoge (Confirm Backup + Delete Bank): Layout Buttons with Space-Around and evenly size buttons.
- [ ] Match all Dialog Buttons to have new Stup-Button CSS

**Comment by schlenkibus** [comment]
Remaining Issues were moved to #2977
