### ISSUE TITLE
[Layer] Part Volume: Shift Button doesn't lead to Part Mute Screen anymore

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#2962]
In the 2020 Update, Part Muting was possible by focussing on Part Volume and then pressing the **Shift** Button, leading to this screen:

![boled-snd-layer-vol-shift](https://user-images.githubusercontent.com/37212609/145590728-eccb9fee-c806-408e-9455-87747a054566.png)

With 21-49, this is not possible anymore. Did we get rid of the feature or is this a bug? (Maybe this collided with the Shift Button functionality to revert parameter changes?)

**Comment by davidm2894** [comment]
Should be clarified as it is part of the manual at the moment.

**Comment by davidm2894** [comment]
Okay Edit: It is still possible if you change the part volume, because then shift enables the functionality to revert the paramter. So it clearly collides with the revert functionality.

**Comment by MatthiasSeeber** [comment]
In the Parameter Screen, Part Muting via the Shift Button doesn't work because the Shift Button is already reserved for handling Parameter Changes. In order to avoid this collision, it seems appropriate to move the Part Muting feature into the Edit Menu of the Part Volume Parameter. Pressing Edit on the Part Volume would then provide Mute/Unmute (similar to Link/Unlink with the Split Point).

Further (this may be put in a separate issue): The Part Muting feature can be extended for Split Sounds as well, as Parts can overlap. So, Layer and Split Part Volumes could implement the Muting Feature. In the Split/Layer Sound Screen, the Part Muting feature can be implemented with help of the Shift Button as well, so setting the Split Point in the Split Sound Screen would still be possible, as muting would require pressing the Shift Button.

@nonlinear-labs please set priority

**Comment by nonlinear-labs** [comment]
We should remove the description from the manual. I will close this issue and open a new one with the suggestion to use Shift + Encoder/Dec/Inc in the Split Sound screen.
