### ISSUE TITLE
Keine ANO-Messages wenn Local Off und Änderungen in den MIDI Settings

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2966]
RC 1 KW 49

Bei gehaltener Taste, Local Off (Global oder Local) und Änderungen in den relevanten MIDI Settings (Routings oder Channels) haben wir wieder Notenhänger, weil keine ANO-Message geschickt wird.

**Comment by schlenkibus** [comment]
Kannst du bitte den genauen Commit Hash  schicken von der Software die bei dir die Notenhaenger Produziert? Und im Besten Fall auch die den Hash der Version bei der keine Probleme aufgetreten sind.

**Comment by davidm2894** [comment]
Hier schon mal für ersteres:
6533
d403365f5

**Comment by MatthiasSeeber** [comment]
Ich kann folgendes bestätigen:

Beim Halten von Tasten (intern oder extern spielt eine Rolle) und Ändern eines bestimmten Settings (z.B. Send oder Receive CH):

| Commit | interne gehaltene Noten | externe gehaltene Noten |
| - | - | - |
| [Issue 2853 - KW 47](https://github.com/nonlinear-labs-dev/C15/pull/2874/commits/354f4f103ccffbbae8426e07979a5c61b1b2e416) | Reset, AllNotesOff | Reset, AllNotesOff |
| [KW 49](https://github.com/nonlinear-labs-dev/C15/commit/d403365f52aa1241ca4584e66d456ccc1292a296) | Reset, :warning: <s>AllNotesOff</s>| Reset, AllNotesOff |

**Comment by davidm2894** [comment]
already fixed, just not merged yet. closed and linked to #2939 as it is basically the same topic.
