### ISSUE TITLE
Kosmetik: Getrennte HW-Sources, CC-Nummern + Undo-Pfeile 

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#2973]
Problem:
![boled-dummy3](https://user-images.githubusercontent.com/84857645/146742809-65880c40-4c96-48b3-b089-829c64125312.png)

Mein Vorschlag wäre, die Schriftgröße der CC-Nummern an die der Parameter-Werte anzupassen (7 Pixel Höhe, Emphase-8) und 5 Pixel unterhalb des Pfeils anordnen, dann schließt der CC Text an den Parameter-Wert ab (1 Pixel Überlappung). Das sähe auch ohne Pfeil in Ordnung aus:
![Slide 16_9 - 3](https://user-images.githubusercontent.com/84857645/146743381-309a0e64-1bdb-41c7-9cd7-e528502ada08.png)
![Slide 16_9 - 6](https://user-images.githubusercontent.com/84857645/146743384-35fb3c44-fade-4a43-ac53-9c51795f7922.png)

**Comment by nonlinear-labs** [comment]
Wir haben das noch einmal diskutiert und sind zu dem Ergebnis gekommen, dass "CC xx" auf die gleiche Höhe gerückt wird wie die Values, im gleichen Font wie die Values. Der Punktlinien-Pfeil (bei selektiertem linken Slider) sollte entfallen.

**Comment by MatthiasSeeber** [comment]
See https://github.com/nonlinear-labs-dev/C15/pull/3040#issuecomment-1040094696
