### ISSUE TITLE
Nachbesserungen für getrennte HW-Sources [s.u.]

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2977]
Grafik-Fehler in WebUI (Preview vom 17.12., Chrome unter Windows 10):

![schwarzer Rand](https://user-images.githubusercontent.com/33938408/147510638-9c05239d-9df0-4ac8-8617-0dabc02644a1.PNG)
![R2 Send nicht ausgeblendet](https://user-images.githubusercontent.com/33938408/147510640-a8cdc3d8-62ca-4b3a-a089-446bc2195147.PNG)
![R2 Send nach oben versetzt](https://user-images.githubusercontent.com/33938408/147510642-fd3d29a1-d894-4182-898a-5725c88a4d9e.PNG)
![R1 Send nicht eingeblendet + weite Felder](https://user-images.githubusercontent.com/33938408/147510644-108bacfb-02b4-4d22-b589-a0186fe5952f.PNG)
![R1 Send nach unten versetzt](https://user-images.githubusercontent.com/33938408/147510645-2836d884-4f9e-4b2c-ae03-d80b11c40a66.PNG)
![R2 Send nicht eingeblendet](https://user-images.githubusercontent.com/33938408/147510647-22d29a08-63c0-41ae-ad5b-045ad157d66a.PNG)
![R2 Send nach unten versetzt](https://user-images.githubusercontent.com/33938408/147510648-b42017b7-f9cf-4853-9d71-640031ac8646.PNG)

**Comment by schlenkibus** [comment]
- [ ] Dialoge (Confirm Backup + Delete Bank): Layout Buttons with Space-Around and evenly size buttons.
- [ ] Match all Dialog Buttons to have new Setup-Button CSS
![Device Settings](https://user-images.githubusercontent.com/33938408/143439631-6e4e065b-0d46-4c1c-ad1f-ecdb1de0b94d.PNG)

- [ ] Device Settings: hier gibt es einen senkrechten Scrollbar, weil die untersten 3 mm des Fensters nicht sichtbar sind. Bitte das Fenster entsprechend vergrößern, dass dieser Scrollbar überflüssig wird.

![MIDI Settings](https://user-images.githubusercontent.com/33938408/143439614-7ca863ad-a515-437d-9af7-dcb311b1cfc6.PNG)

- [ ] Scrollbars: Wenn es einen senkrechten Scrollbar gibt, wird im Chrome-Browser nach dem Wechsel in einen anderen Tab der senkrechte Scrollbar breiter und es kommt noch ein horizontaler Srollbar hinzu und ein hässliches weißes Rechteck. Da wir in den MIDI Settings nicht ohne senkrechten Scrollbar auskommen, müssen wir am rechten Rand genug Platz dafür lassen und das Fenster-Verhalten so konfigurieren, dass kein horizontaler Scrollbar erscheint, und erst recht nicht so ein weißer Fleck...

**Comment by davidm2894** [comment]
Wir haben noch immer die horizontale Scrollbar auf der MIDI Settings Seite.
