### ISSUE TITLE
Create Selftest Script for C15

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2985]
Selftest script should be on the ePC (/persistent?) - prime should either be installed or run from stick

- [x] ePC Heattest - run prime and check if temperature exceeds 80° (30 minuten test)
`./mprime -t &; kill $(pidof mprime);` and `while true; do sensors; sleep 5; done &`  and `rm results.txt prime.txt local.txt`
- [x] check journalctl `journalctl -b -p "emerg".."warning"` / dmesg `dmesg --level=err,warn` (BBB/ePC) for warnings, print these out
- [x] check mount (BBB/ePC), ckeck if everything is mounted rw
`mount | grep '(ro'`
- [x] communication BBB <-> ePC - Ping, simple sshpass command?
- [x] check if everything is present on /persistent (settings.xml, calibration)
`ls /persistent/calibration/*.cal calibration.bin calibration.ini`, 
`ls /persistent/settings.xml`
- [x] check if alsa is running on 100%
`amixer -D hw:PCH sget 'Master'`
- [x] check for buffer underruns (30 minutes?)
- [x] check communication with lpc
- [x] BBB blkid (might be outdated ...)
- [x] BBB sshpass, date+time, /etc/network/interfaces, /etc/hostapd.conf check
`command -v sshpass`, `cat /usr/C15/scripts/install-update.sh | grep version`
- [ ] check if default C15 Settings are set (settings.xml)
- [ ] Tastendrücke simulieren (LEDs)

**Comment by KlausStrohhaecker** [comment]
> prime should either be installed or run from stick

Maybe we could use the "stress" utility that might available already in the Distro we use. I'm having good success using it on the rPi and it's well suited for automation
https://linux.die.net/man/1/stress
