### ISSUE TITLE
WebUI - HW Sources - kleine Verbesserungen [s.u.]

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2993]
- [x] Wenn in den Assignments "None" ausgewählt ist, nicht "None" in die HW-Source-Felder schreiben. Einfach nix schreiben.
- [x] Die gekürzten (#2982) CC-Nummern u.ä. in einem etwas größeren Font (ca. 60 % der Höhe des Wertes) darstellen. Ein bisschen mehr vom Rand wegrücken, sodass sie durch einen gelben Rahmen oder einen Selektionsrahmen nicht überdeckt werden können.
- [x] Labels wie "Ribbon 2 Snd" sind eigentlich nicht zu lang für den Slider. Bitte die beschreibbare Fläche so vergrößern, dass keine Kürzung (wie z.B. "Ribbon..Snd") auftritt.
- [x] Parameter-Tab: Der grau hinterlegte Originalwert lässt sich bei den "Send"-HW-Sources korrekt benutzen. Bei den ursprünglichen HW-Sources bewirkt ein Mausklick leider nichts.
- [x]  Es wäre gut, wenn man den assignten CC u.ä. auch im Parameter-Tab einer HW-Source auslesen könnte. Ich schlage vor, wir schreiben ihn linksbündig über den Anfang des Sliders, in der Höhe alignt zum Value, in dem gleichen grauen kleineren Font den wir für dem Original-Value nutzen.

Screenshot des Status Quo:
![Screenshot 2022-01-05 224648](https://user-images.githubusercontent.com/33938408/148295302-a90c1db9-206c-4c3b-8a16-41186a5a113d.png)

**Comment by davidm2894** [comment]
![IMG_0DD46688A7FB-1](https://user-images.githubusercontent.com/84857645/150514820-578a9cd8-bd4d-4824-aa53-afb8e3460152.jpeg)

Sieht so aus, als wäre die Textfläche für den CC Wert im Parameter Tab nicht groß genug für MSB/LSB Values. Würde die Issue dafür nochmal öffnen.

**Comment by schlenkibus** [comment]
![image](https://user-images.githubusercontent.com/15381257/153437026-171ae03b-4376-48e7-9013-06f8fc49b773.png)
I cant reproduce this bug on either an 4k display nor an standart 1920x1080px monitor.

@davidm2894 Is this bug still reproducible for you?
