### ISSUE TITLE
Reihenschaltung von zwei Effektgruppen für Dual-Sounds

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2996]
Zwei neue Parameter erlauben die kreuzweise Einspeisung der Ausgangs-Signale von FX II in den Eingang von FX I und von FX I in den Eingang von FX II. Damit wird eine Reihenschaltung der beiden Effektgruppen möglich. Hier ein schönes Blockschaltbild:

![S  4 Dual Sound](https://user-images.githubusercontent.com/33938408/148845972-99dc4129-360b-43d7-b8d9-633761921d76.PNG)

- [ ] **Output Mixer - FX II to I (oder "From FX II")**  // vierter Parameter des Level-Parameter-Screens von Part I
- [ ] **Output Mixer - FX I to II (oder "From FX I")**  // vierter Parameter des Level-Parameter-Screens von Part II

Alle Signalwege sind stereo. Ausnahme: die hier nicht gezeigten Wege zum FB Mixer.

**Comment by MatthiasSeeber** [comment]
__neue Spec__
- ein bipolarer Parameter statt zwei
- 0...-100 % für den Signalweg "FX II to I" = 0...1 ("FX I to II" = 0)
- 0...+100 % für "FX I to II" = 0...1 ("FX I to II" = 0)
