### ISSUE TITLE
Neuer Parameter "Separation" zur Trennung von Part I und II in den linken und rechten Kanal

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3003]
Es besteht der Bedarf, die beiden Parts im Stereobild zu trennen. Dazu werden beide Stereo-Kanäle eines Parts auf einen der Stereo-Kanäle der Master-Summe gemischt. Parameterbereich:
-100 %: Part I nach rechts, Part II nach links
0 %: keine Trennung
100 %: Part I nach links, Part II nach rechts
 
Wieder eine schöne Zeichnung zur Umsetzung in einer 4-in-2-Mixer-Stufe, die auch für Part-Level/Mute und Master-Volume genutzt werden kann:

![S  5 Separation](https://user-images.githubusercontent.com/33938408/149163344-716d1c47-06d6-4fd1-8dec-a42a65868bac.PNG)

**Comment by nonlinear-labs** [comment]
Das Parameter-Label ist wohl besser "Part Pan" für Dual-Sounds und "FX Pan" für Single-Sounds.

**Comment by MatthiasSeeber** [comment]
In Layer Sounds haben wir Part Muting, was auch für Split Sounds (aufgrund des mögl. Overlaps) angedacht ist. Dem Ansatz folgend käme für Single Sounds ein FX Muting infrage?
- [ ] ja
- [ ] nein

**Comment by nonlinear-labs** [comment]
Für eine solche FX-Mute-Funktion würde ich aber keine neuen Parameter einführen und keine extra UI-Fläche freischaufeln.
Meistens reicht es, den Parameter "Mix I-II" auf Minimum oder Maximum zu stellen (Shift + Dec/Inc) und durch Undo wieder auf den Originalwert. 
Wir sollten erst einmal schauen, welche Lösung wir für (Bedienung und Anzeige eines) Split-Part-Mute finden. Dann kann man das vielleicht auf das FX-Muting übertragen
