### ISSUE TITLE
Alternative ByeBye Screen

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#3007]
Consider requesting to allow the C15 to shut down completely before pulling the plug on the displays.
Hope is to sensitize our users in taking greater care of the instrument.  
Have to come up with a friendly, yet determining and short message.  Ideas welcome!

**Comment by MatthiasSeeber** [comment]
Shutting down.
Do not cut power!

**Comment by nonlinear-labs** [comment]
BOLED:
"Shutting down...
Please do not cut the power!"

SOLED:
"Shutting down..."

**Comment by MatthiasSeeber** [comment]
Es dürfte zwar eng werden, aber ich halte es für eine gute Idee, auch im SOLED den Hinweis zu haben, da die Base Unit allein ja auch genutzt werden kann.

**Comment by AntonSchmied** [comment]
Danke! bin dran und schau, ob im SOLED genug Platz ist!

**Comment by davidm2894** [comment]
Wäre es möglich den Text im SOLED mittig anzuordnen, damit oben und unten genauso viel Abstand ist?

**Comment by KlausStrohhaecker** [comment]
Ja, erfordert aber einen Haufen neuen/überarbeiteten Code, wäre Fleißarbeit.
