### ISSUE TITLE
Hängende MIDI Note bei Wechsel zwischen SplitPresets mit verschiedenen Voice-Eigenschaften

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3009]
Ziemlicher Corner-Case.

Wenn **Local = On**, man eine Note hält und von einen Split Preset auf ein anderes Split Preset, das sich aber in den Voice-Eigenschaften unterscheidet (Mono, Unison (auch relevant wie viele Stimmen), Poly), wechselt, bleibt die Note hängen. 
Wenn die Voice-Eigenschaften gleich sind, bleibt sie nicht hängen.

**Comment by MatthiasSeeber** [comment]
We had a discussion about this and decided that it is indeed a corner case that can be solved later, not as a hotfix.
