### ISSUE TITLE
HWUI: Pedal Preset-Wechsel führt zu Absturz

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3015]
Wenn ich das Preset unter Setup -> Device Settings -> Pedals ändere, wird die Änderung (meist) nicht vom C15 anerkannt, sondern bleibt auf der vorherigen Auswahl stehen. Nach jeder Änderung crasht der C15 und liest die Bänke neu ein, die Presetauswahl bleibt aber unverändert. Auch wenn ich neustarte, bleibt die Auswahl bestehen. Nach mehrmaligen Versuchen klappt es manchmal, kann da bisher aber kein Muster herauslesen.

Bitte um Rückmeldung, ob das jemand auf seinem Gerät so reproduzieren kann.

**Comment by MatthiasSeeber** [comment]
Wenn er die Bänke neu lädt, deutet dies auf einen Absturz hin würde ich sagen. Ich kann dies über Boled reproduzieren. Über WebUI scheint es normal zu funktionieren. (Habe derzeit einen inoffiziellen Test Build zu issue 3000 auf dem Gerät)

**Comment by schlenkibus** [comment]
@davidm2894 kannst du bitte noch sagen auf welcher Version du den Bug beobachtet hast?

**Comment by davidm2894** [comment]
Kann es neben der 22-03 auch für die 22-02 bestätigen.
