### ISSUE TITLE
BOLED + WebUI: An den vier Pedal-Parametern sollte im Zustand "Off" eine kleine Markierung gezeigt werden.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3023]
"Off" kann in den Menüs der Pedal-Settings eingestellt werden. Die Signale an den Pedalbuchsen werden dann ignoriert.
Die Bedienung der Parameter über die UI und über MIDI sollte trotzdem möglich bleiben.

Wir müssen uns ein kleines Zeichen (Pedalsymbol (?) mit "X" oder "Off") überlegen, dass neben dem Parameter-Slider eingeblendet wird.

**Comment by davidm2894** [comment]
Evtl. sowas in der Art für die WebUI?

![Pedals](https://user-images.githubusercontent.com/84857645/151538470-28027570-b0a1-43b8-a189-f13b169a2097.png)

**Comment by KlausStrohhaecker** [comment]
Einfach Text `Pedal N(off)` , das versteht jeder und sticht sofort hervor.
Icons kann kein Mensch a) erkennen was das Icon sein soll, erst recht bei der Größe, und b) dann was es bedeuten soll.

**K**eep **I**t **S**imple and **S**tupid ;-)

**Comment by nonlinear-labs** [comment]
Naja, mal schauen, was uns da noch einfällt. Ich brauche auch ein Pedal-Symbol (oder Buchstaben) für eine neue Lösung im SOLED. Die Belegung und Beschriftung der Ribbons soll flexibler und aussagekräftiger werden. U.a. mit Hinweisen auf parallel verbundene Pedale.
