### ISSUE TITLE
Hardware controls not always translated to numeric representations of the UI

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#3026]
Occasionally, once the C15 is up and running, the effects of using the pitch bender, after touch or the ribbons are only heard. The values in the WebUI and the Macro Control Screen do not change and neither do the ribbon LEDs. 

However, when using the WebUI or the Panel Unit to set parameters assigned to the ribbons, the LEDs follow the lead of the parameter. 
The behavior recovers once the audio-engine ist restarted manually.

Observed on 21-49. So far it was not observed with the current unstable.
journalctl on the ePC does not show anything dodgy.

**Comment by MatthiasSeeber** [comment]
In unstable, this might already be solved via #3011. _(The AudioEngine to Playground synchronization of LPC/MIDI HW Source Events has changed - compared to 21-49)_

Further tests on unstable are needed. Apparently, the described behavior was observed without using MIDI at all (and using standard MIDI settings with Local enabled).

**Comment by schlenkibus** [comment]
As this nor similar behavior has been reported in close to 6 months I assume that this is no longer an Issue.

**Comment by AntonSchmied** [comment]
> As this nor similar behavior has been reported in close to 6 months I assume that this is no longer an Issue.

well, not quite ...  Release 22-16 (1ede50a), two days ago:
1. The C15 was running, then froze. Displays nor PU or Ribbon LEDs did not react to any button pushing. Sound was on AND the Ribbons and the Pitch Bender effected the audio engine. Soft  Shutdown did not work, not sure if it was ePC realted. On the UniBoard, the LED 'LE' was blinking red.
2. After rebooting, Ribbon LEDs frozen, but the Ribbons did work. Displays and buttons were working again. Soft shutdown (ePC) did not work
3. After new reboot, everything was working again, soft shutdown too.

@davidm2894 did say, that Thomas observed similar behavior a week or two ago.
sooo do we reopen?
