### ISSUE TITLE
BOLED: die kleinen Slider in den Parameter-Karussell werden falsch gezeichnet, wenn sie (als Crossfader) einen Punkt darstellen sollen.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3027]
Hier ist es der kleine "A-B"-Slider:

![Slider Draw Bug](https://user-images.githubusercontent.com/33938408/151818298-c1ca49b1-8723-48a3-ba71-062a25e59305.PNG)

Die Fläche des Sliders ist fast vollständig weiss gefüllt. Der Punkt ist nur erkennbar, weil links und rechts davon zwei graue Linien gezeichnet werden.

**Comment by MatthiasSeeber** [comment]
Appearance seems to be fixed, see https://github.com/nonlinear-labs-dev/C15/pull/3038#pullrequestreview-880198239
