### ISSUE TITLE
WebUI - Recorder lässt sich auf iPad nicht öffnen und funktioniert auf MacOS nicht vollständig

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3029]
[21-49]
Ein Kunde berichtet, dass er auf einem 3 Jahre alten iPad (OS 15.1, Safari) den Recorder nicht öffnen kann. Auf seinem Mac (wahrscheinlich auch Safari) ließ sich der Play-Button des Recorders nicht bedienen.

**Comment by davidm2894** [comment]
> [21-49] Ein Kunde berichtet, dass er auf einem 3 Jahre alten iPad (OS 15.1, Safari) den Recorder nicht öffnen kann. Auf seinem Mac (wahrscheinlich auch Safari) ließ sich der Play-Button des Recorders nicht bedienen.

Zum 1. Fall.: Auf dem iPad: Settings -> Safari -> Disable "Block Pop-Ups"

Zum 2. Fall.: Für mich nicht reproduzierbar, auf macOS BigSur + Safari/Chrome/Firefox lässt sich der Recorder normal benutzen.

**Comment by nonlinear-labs** [comment]
Lässt sich nicht durch SW-Update lösen
