### ISSUE TITLE
CC Tag "Channel-Pressure" wird im BOLED falsch angezeigt 

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3032]
OS: 22-3b

![boled-19118934251932](https://user-images.githubusercontent.com/84857645/153213485-dd6e3e3c-a352-4917-806b-9c8ce4f57722.png)

**Comment by MatthiasSeeber** [comment]
Was solved in #3040 (see https://github.com/nonlinear-labs-dev/C15/pull/3040#pullrequestreview-880237382)
