### ISSUE TITLE
Bitte alle HW-Sources und ihre "Snd"-Controls vom Presetsystem abkoppeln

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3035]
Die vier Pedale sind bereits vom Presetsystem abgekoppelt. Das sollte für alle HW-Sources einheitlich so sein.
- [ ] Die Ribbons und die (bei Local=Off bereitgestellten) "Snd"-Controls aller HW-Sources werden mit Presets gespeichert/recallt. Das ist nicht sinnvoll.
- [ ] Damit sollten auch bei keiner der HW-Sources oder ihren "Snd"-Controls
       - in der WebUI bei Veränderung ein Originalwert angezeigt werden
       - im BOLED eine Recall-Möglichkeit über den Shift-Button angeboten werden

**Comment by nonlinear-labs** [comment]
Das Soft-Takeover wird auf der Position der Makro-Controls basieren. Eine Hardware-Position zu speichern, ist damit nicht nötig. Für Non-Returning-Sources haben wir die 1:1-Übertragung auf die MCs und bei diesem Vorgang vergleichen wir HW-Pos mit MC-Pos und wenden "Takeover"-Funktionen an. Returning Sources sollen im Preset sowieso Null sein.

**Comment by MatthiasSeeber** [comment]
Wie gehen wir mit dem Return Behavior um?

Mein erster Gedanke war, dass das Return Behavior ebenfalls beim Recall ignoriert werden sollte. Das hieße aber, ein Preset wird evtl. mit anderem Return Behavior recalled, als es abgespeichert wurde. Das Return Behavior beeinflusst die HW Amounts, sodass ein Recall ggf. die HW Amounts anders lädt als sie abgespeichert wurden. Wäre das tolerierbar?

**Comment by MatthiasSeeber** [comment]
Was soll der initiale Zustand einer HW Source sein?

1. **Return Bevahior**: vermutlich *persistent* wie ein Setting? (außer Bender, Aftertouch mit immutable ReturnToZero)
2. **Control Position**:
  2.1. *physikalischer Zustand*: erster ADC Wert im PlayController?
  2.2 *persistent*: letzte HW Pos vor Shutdown wird gespeichert und bestimmt Initialzustand

**Comment by nonlinear-labs** [comment]
- Das Return Behaviour bitte mit Preset speichern und aufrufen. Es gehört sozusagen zu der HW-Amount-Matrix.
- Local=On: Die Control Position kann vom physikalischen Zustand (letzten ADC-Wert) des HW-Elements übernommen werden. 
- Local=Off: Die Control Position der "Snd"-Source kann vom physikalischen Zustand (letzten ADC-Wert) des HW-Elements übernommen werden. Interne HW-Source-Controls im Non-Returning Mode sollten persistent dort stehen bleiben, wo man sie zuletzt hingestellt hat. Interne HW-Source-Controls im Returning-Mode laufen nach jeder Veränderung automatisch in ihre Return-Position und werden damit auch so initialisiert.

**Comment by nonlinear-labs** [comment]
Wenn eine HW-Source bei einem Preset-Recall vom Non-Return in den Return-Mode umgeschaltet wird, sollte sie physikalisch auch in der Return-Position stehen. Wenn das nicht der Fall ist, entsteht beim Bewegen der Source im MC ein unerwünschter Offset. Das lässt sich folgendermaßen verhindern:
- Direkt nach dem Setzen aller Parameter auf ihre Preset-Position wird ein Sprung des HW-Controls von seiner Return-Position auf die momentane physikalische Position angewandt. D.h. die betreffenden MCs und Targets machen einen entsprechenden Sprung und befinden sich dann in der Position, die dem physikalischen Zustand der Returning-Source entspricht.

**Comment by nonlinear-labs** [comment]
Ein zweites (altes) Problem: Beim Preset-Store steht eine Returning-Source nicht auf ihrer Return-Position. Damit werden die betroffenen MCs/Targets mit einem Offset gespeichert, der später nicht wieder korrigiert werden kann. Das kann folgendermaßen vermieden werden:
- Vor dem Auslesen der Parameter für das Preset werden die Returning-Sources "für einen Moment" (oder in einem parallelen Datensatz) auf ihrer Return-Position (Null) gesetzt. Die dabei entstehenden Parameter-Positionen werden in das Preset geschrieben.

**Comment by nonlinear-labs** [comment]
Wenn Local für einen Ribbon Off war und auf On geschaltet wird, sollten die Ribbon-LEDs wieder auf die MC-Position gesetzt werden. In der Version "22-03/issue-3035" ist das nicht der Fall. Die LED-Kette bleibt auf der Position des Local-Off-Snd-Controls stehen, bis man den Ribbon oder den MC bewegt.

**Comment by schlenkibus** [comment]
https://docs.google.com/spreadsheets/d/1NCD79gSQztknE5oleewIP549Wg61XoNUxY15fb1nLkM
