### ISSUE TITLE
WebUI Kosmetik: Rote Markierung der MC-Ziele uneinheitlich

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3058]
Parameter, die nicht auf der obersten Stufe des Parameter-Stacks sind, scheinen kein rotes Buchstabensymbol zu bekommen.

Hier richtig:
![Bildschirmfoto 2022-03-03 um 11 42 19](https://user-images.githubusercontent.com/84857645/156549138-ba74d2e3-4def-4332-817f-96f035b4cec9.jpg)

Hier falsch:
![Bildschirmfoto 2022-03-03 um 11 42 47](https://user-images.githubusercontent.com/84857645/156549130-caa6909d-fd21-4722-9341-c8c67b38976a.jpg)

Hier falsch:
![Bildschirmfoto 2022-03-03 um 11 42 33](https://user-images.githubusercontent.com/84857645/156549135-dc2e3e86-708b-4074-81ef-a058bc46e8ed.jpg)

Wird in Zukunft sichtbarer, wenn dann mehr 2. und 3.-Parameter modulierbar sind.

**Comment by schlenkibus** [comment]
![image](https://user-images.githubusercontent.com/15381257/171684442-e2d133e4-0533-4f74-85ff-5c72655692e2.png)
This will definitly be closed wiht #3169
