### ISSUE TITLE
Es sollte kein MIDI beim Booten des C15 gesendet werden

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3068]
Es wird verschickt:

- Werte der angeschlossenen Pedale
- Aftertouch Wert

**Comment by MatthiasSeeber** [comment]
Ich habe auch den Bender öfters beobachtet.

**Comment by davidm2894** [comment]
Stimmt, hatte den Bender jetzt auch einmal dabei.

**Comment by MatthiasSeeber** [comment]
Derzeit deutet vieles auf folgende Ursache hin:

Beim Booten pollen wir den PlayController auf seine HW Sources. Wenn die Source vorhanden ist (eingesteckte Pedale), wird der erste ADC-Wert (nun nicht mehr über BBB sondern) über "TCD" (PlayCtrlr --> Synth) an die EventStage verschickt, um dann dem PlayGround über die HW Positions bescheid zu geben.

Idealerweise wäre der Prozess so: wir erhalten die Positions im PlayGround und können DANN den EditBuffer das erste Mal laden und diesen Initial-Sound an den Synth verschicken. (Es gibt also eine wohldefinierte Abfolge von Schritten, präzises Timing spielt eine Rolle.)

Derzeit hat der Polling-Prozess folgende Einschränkungen und Konsequenzen:
- Timing: es gibt keinen wirklichen Abschluss für das Polling (entweder kommt ein HW Event oder eben nicht, mit entsprechender Latency), dadurch existiert kein Zeitpunkt bei dem alle HW Positions bekannt sind. Der EditBuffer wird also "irgendwann" geladen, möglicherweise bevor alle Polling-Ergebnisse da sind. Das wäre eine Erklärung für das derzeit undefinierte Verhalten
- Protokoll: die EventStage kann nicht zwischen initialen und nachfolgenden HW Events unterscheiden. Hier vermute ich den Kern dieses Tickets: wenn noch keine Settings beim Synth angekommen sind, wird möglicherweise nichts verschickt. Andernfalls könnte initiales MIDI verschickt werden.

Durch Logging von relevanten Ereignissen wollen wir die beschriebene Problematik näher untersuchen.

Zudem fiele mir aus dem Stand eine naive Lösung ein, die vielleicht minimal-intensiv ist:
1. Prozess-Start: Der PlayGround pollt den PlayController auf HW Sources. Editbuffer und Settings werden noch nicht angerührt. Die EventStage initialisiert autonom mit "disabled" MIDI Settings und verschickt dadurch kein MIDI.
2. Prozess-Data: Der PlayController versendet alle verfügbaren HW Sources an die EventStage (... sodass die HW Sources in Ruhe gesammelt und an den PlayGround weitergereicht werden können ohne dass MIDI verschickt wird ...)
3. Prozess-Ende: Der PlayController versendet zum Abschluss diese neue (wertelose) Message an die EventStage, diese leitet sie an den PlayGround weiter
4. Transmission: Der PlayGround hat nun alle verfügbaren HW Positions und weiß, dass der Editbuffer nun geladen werden darf. Die Settings und der Initial-Sound werden geladen bzw. an den Synth übertragen.

@schlenkibus @KlausStrohhaecker - was meint ihr?

**Comment by KlausStrohhaecker** [comment]
> Timing: es gibt keinen wirklichen Abschluss für das Polling (entweder kommt ein HW Event oder eben nicht, mit entsprechender Latency), dadurch existiert kein Zeitpunkt bei dem alle HW Positions bekannt sind.

Mit dem kürzlich eingeführten Polling-Kommando für den LPC gibt es diesen Zeitpunkt zu dem alle Daten (falls gültig)  vorliegen, das ist eben genau kurz nachdem die Bestätigung kommt dass das Kommando angenommen und bearbeitet wurde. Typisch nach 12.5ms (interne Zeitscheibe für das Bearbeiten der HW-Sources). Wenn's länger dauert als 100ms dann ist was kaputt (zB der BBB ist kurz überlastet). Man sollte aber mindestens 2 Retries in ebenfalls ca. 100ms Abstand machen bevor man aufgibt.
Ob der Playcontroller lebt weiß man ja aber eh schon, über dessen Heartbeat alle 10ms bzw Ausbleiben desselben.


Es werden verschickt:
- Pitchbender
- Aftertouch (ist noch leicht buggy im poll-hw-sources -Branch), aber die Null stimmt ;-)
- Pedal 1..4, wenn dafür ein zuverlässig gültigen Wert ermittelt wurde (also Pedal angeschlossen und fertig mit dem Auto-Ranging und seitdem nicht mehr umgesteckt worden).
Ribbons werden NICHT verschickt, da unnötig (schicken sich selber weil sie eh niemals einen stabilen Wert annehmen ausser Null)

Jedoch: Der Playcontroller verschickt uU auch schon vorher "unaufgefordert" HW-Werte (und Key-Events) wenn er welche hat, da wir keine Freischaltung des Messaging machen (ausser dass der Playcontroller frühestends etwas über MIDI schickt nachdem ein Heartbeat von der Audio-Engine empfangen wurde).

Diese Daten müsste man also discarden wenn man sie nicht haben will bis zum Zeipunkt X. Man muss sie auch nicht loggen weil nun ja mit Polling immer Werte bekommt wenn man sie initial braucht.

**Comment by MatthiasSeeber** [comment]
Es sieht nach Rücksprache danach aus, als wäre eine Erweiterung des "TCD" Protokolls sinnvoll. Es würde ein bzw. zwei neue Messages geben, z.b. `AE_CMD_POLL_DATA_START/STOP`. Der Polling-Prozess wäre dann mit dem Event-Fluss LPC --> Synth --> PlayGround eindeutig definiert.

Wird in separatem Ticket behandelt: #3051
