### ISSUE TITLE
Aftertouch does not return in its idle position

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3076]
Pressing different keys, no MIDI.

I'd ask others to test it on their devices to exclude that it is a hardware defect.

https://user-images.githubusercontent.com/84857645/160108047-536dbde0-dbb1-451b-901d-7c004df959f8.mp4

OS: [cf4d8e580](https://github.com/nonlinear-labs-dev/C15/pull/3071/commits/cf4d8e5802fd5874cf5ed3a9e73b95ed5800a5cb)

**Comment by MatthiasSeeber** [comment]
Ich beobachte das auch mit selbigem Commit beim nutzen des internen ATs über das Keybed. Je höher die Release Velocity, umso weniger kommt der AT zurück. Über MIDI tritt das bei mir nicht auf.

**Comment by KlausStrohhaecker** [comment]
Copy&Paste bug ;-)
Fill fix

**Comment by MatthiasSeeber** [comment]
After commit [176644e](https://github.com/nonlinear-labs-dev/C15/commit/176644e95324fd542309bef46d1ebac5b54ff0ad) Aftertouch (and Bender) both return without issues.
