### ISSUE TITLE
11i3 NUC: shutdown fail

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#3089]
Currently not all 11i3 NUCs running on ePC2 seem to shutdown reliably (2 out of 7). The ePC seems to be stuck somewhere between OS logout and physical shutdown, thus there is nothing to see in Journalctl or dmesg...
 
Only way to provoke a correct ePC shut down, is to keep a HDMI+Monitor attached. (Freaky, but it's true! i have witnesses) 

If current Ubuntu LTS is installed the ePC can be shutdown with `shutdown now` via ssh on every try.
But once our tailored arch latest build-tools is installed, it does not work.

'reboot' works!

**Comment by majjam** [comment]
ich glaube ich habe hier auch Effekte:
Manchmal  startet der C15 , aber ich bekommen keinen Sound. Ein Neustart behebt das Problem.
Ich denke der EPC hängt dann immer noch beim alten herunterfahr Befehl.

**Comment by AntonSchmied** [comment]
> ich glaube ich habe hier auch Effekte: Manchmal startet der C15 , aber ich bekommen keinen Sound. Ein Neustart behebt das Problem. Ich denke der EPC hängt dann immer noch beim alten herunterfahr Befehl.

hmmmm ... Würde der ePC nicht runterfahren, müsste der C15 als ganzen nicht runterfahren und der "Goodbye" Screen müsste hängen bleiben ... Hast du das beobachtet?

**Comment by majjam** [comment]
Nein ,dies konnte ich nicht beobachten.. Alles war aus. Und wenn man drüber nachdenkt auch die LED des boards waren aus. (man kann sie im dunkeln unter der Tastatur sehen) Hätte ich also auch drauf kommen können, dass es sich hier um was anderes handelt.

Ich werde das noch einmal genauer beobachten und dann evtl ein neues Ticket eröffnen ? "epc Sound engine not starting" oder so.

ich hatte das verhalten ca 3,4 mal bei vielen (mindesten 1x täglichen) Einschaltvorgängen.

**Comment by AntonSchmied** [comment]
ja das hört sich leider nach einem eigenen Ticket an ... danke dir!!

**Comment by majjam** [comment]
ich bekomme leider kein vernünftiges Ticket erstellt, da ich nichts seriös reproduzieren kann.
Ich habe vereinzelt komsche effekte beim ein und ausschalten.
Letztens hatte ihc eine bootloop, die ich nur durch Steckerziehen stoppen konnte. Ob der taster hing kann ich nicht sagen.
Aber es war ein komplettes hochfahren, dann 30 40 Sekunden spielbereit und dann fuhr die Kiste automatisch herunter.
Und wieder von vorne.

Aber es kann natürlich auch alles an meiner historisch gewachsenene Hardwarestruktur liegen. Wenn Ihr also keine schwächen mehr feststellt, dann bitte meine vorkommnisse einfach ignorieren.
