### ISSUE TITLE
Split-Sounds: Im Feedback Mixer für Effects "From I/II" anbieten

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3111]
Da der FB-Effects-Zweig ein monophones Signal führt, kann es auch sinnvoll in den anderen Part eines Split-Sounds geroutet werden.

**Comment by schlenkibus** [comment]
Current Info still says: "Crossfades to the Effects signal of the other Part. (Only available when using Layer mode.)"
