### ISSUE TITLE
BBB - install-update-from-epc.sh deletes /update on boot

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#3112]
not a show stopper, but the script and so the service should only be called from ePC and should not independently start on boot.

**Comment by KlausStrohhaecker** [comment]
Enabling the service in question (`install-update-from-epc.service`) happens in `/projects/bbb/bridge/CMakeLists.txt`, lines 54pp.
==> it would clutter the code if we introduce enabling exceptions there ==> service is the wrong means.

**Comment by KlausStrohhaecker** [comment]
I think fixing this is more important than it may appear because the situation is completely uncontrolled.
Also it defeats our policy of keeping the update for support /debug /evidence tracking.
