### ISSUE TITLE
Undo System deckt Preset Store nicht korrekt ab

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3117]
Steps to reproduce:

1. Veränderung an einem Preset.
2. Abspeichern des veränderten Presets (Overwrite)
3. Über Undo soweit zurück gehen, dass man sich vor dem Abspeicher-Punkt befindet
4. Parameter gehen mit zurück und das Preset sieht so aus, wie es vor Edit und Overwrite aussah
5. Nun das Preset neuladen
6. Preset ist so, wie es zuletzt abgespeichert wurde (also vor Undo)

Das Preset sollte aber den Zustand haben wie vor (1.).

Soweit ich das beurteilen kann, betrifft das nicht Append und Insert, da dort gänzlich neue Presets abgespeichert werden, die durch Undo auch wieder entfernt/gelöscht werden können.

**Comment by schlenkibus** [comment]
closed with #3119
