### ISSUE TITLE
Loop Funktion für Envelope C

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3158]
Es wird ein neues Feature eingeführt, welches Envelope C für die Phase zwischen Breakpoint und Sustain loop-bar macht. Das bedeutet, dass ein neuer Parameter mit Namen "**Loop**" eingeführt wird. Der Parameter hat einen Wertebereich von 0%-200% und wird in der UI im Stack unter Sustain platziert. Steht der Parameter auf 0% ist Loop ausgeschaltet und der Envelope verhält sich wie gewohnt. Steht der Parameter auf 100%, wird der Envelope zwischen Breakpoint und Sustain geloopt, d.h. 
- Envelope startet mit der Attackphase und läuft bis zum Erreichen des Sustainlevels ganz normal durch
- sobald das Sustainlevel erreicht ist, geht der Envelope in Decay 1 Zeit zum Breakpoint und von dort in Decay 2 Zeit zum Sustain Level usw. 

Hierfür muss Decay 2 linear werden. Das passiert, sobald Loop > 0.

Loop ist ein Faktor, deshalb auch der Wertebereich von 0% - 200% (bzw. 0-2). 
Es wird zunächst der Betrag aus der Differenz von Breakpoint und Sustain gebildet. Mit dem ersten Loop, d.h. nach dem ersten regulären Durchlauf des Envelopes zum Sustainlevel, wird dieser Betrag mit dem Loopfaktor multipliziert und im nächsten Loop der erhaltene neue Betrag erneut mit dem Loopfaktor multipliziert usw. Dadurch nähert sich für Loop < 1 der Breakpoint dem Sustain mit jedem Loopdurchlauf an und man erhält einen abkligenden Loop, der in das Sustainlevel übergeht. Für Loop = 1 klingt der Loop dementsprechend nicht ab. 

Für Loop <= 1 wird mit dem NoteOff wie gewohnt die Release Phase des Envelopes getriggert. Bei Loop > 1 bleibt der Envelope auch mit dem NoteOff im Loop. Solange NoteOn, verhält sich der Envelope für Loop > 1 wie für Loop = 1, d.h. Faktor = 1. Sobald NoteOff, ergibt sich der Faktor aus Faktor = Loop - 1. Das bedeutet, dass für Loop < 2, der Loop mit NoteOff langsam abklingt, für Loop = 2 nie abklingt. 

Zusätzlich wird der schon von Attack und Release bekannte Velocity-Parameter auch für Decay 1 und Decay 2 eingeführt. 

Der Loop-Parameter ist modulierbar. 

**Vorschlag für einen Infotext:**
At a setting of 100%, the envelope is looped between the breakpoint and the sustain level. If the value is between 0 and 100%, the loop decays by this factor to the sustain level. If the value is above 100%, the release phase is not triggered when a key is released, but the loop decays to the sustain level by the value minus 100%. If the value is 200%, the loop will never decay. 
When the loop is activated, Decay 2 decays linearly, not exponentially. 

**Zusammenfassung:**
Envelope C wird zwischen BP und Sustain loopfähig. Der Loop kann wahlweise unendlich, zum Sustainlevel abklingend oder mit NoteOff in die Releasephase übergehend sein. Es gibt die drei neuen Parameter Loop (0-200%), Decay 1 und 2 Velocity (-60 bis 60 dB). 

P.S.: Es gibt eine funktionierende Core-Implementierung.

**Comment by MatthiasSeeber** [comment]
@davidm2894 @nonlinear-labs 
Hier ein neuer Vorschlag zur Info für den Loop Parameter (die zusätzl. Anforderung, dass ein Loop auch bei < 100% in Richtung Null statt Sustain abflaut berücksichtigend):
~~~
Determines the presence and decay speed of looped envelope segments (Decay 1 and 2).
0%: no looped segments, normal envelope behavior with an exponential Decay 1 segment.
<= 100%: the loop will repeat and approach zero until a pressed key is released. Smaller Loop values produce a faster loop decay.
At 100%, the loop will repeat indefinetely. After releasing a pressed key, the normal Release segment will start. The Decay 2 segment is linear during loops.
> 100%: the loop will repeat at full presence until a pressed key is released. Then, the loop will still repeat and approach zero.
Smaller Loop values produce produce a faster loop decay. At 200%, the loop will repeat indefinetely.
~~~

**Comment by davidm2894** [comment]
Finde ich gut. Ich würde diesen Satz noch ans Ende setzen:

`The value of the loop parameter is sampled only with every key down and key up event.`
