### ISSUE TITLE
HWUI: Unsion page carousel : Playground crash "after" PAN

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3194]
At Unision page hitting soft-button-4  four times  leads to playground crash. 
Any entries missing ?

![image](https://user-images.githubusercontent.com/4758563/171473075-128d6f6d-1245-400e-abf5-157ebce8e212.png)

![image](https://user-images.githubusercontent.com/4758563/171473112-6cb23d4e-c0a7-4f6d-b610-c8704107576e.png)

**Comment by MatthiasSeeber** [comment]
also observed with
- Voices / Mono (selected Mono Enable via SB4)
- (Split Sounds) Part / Split Point
- (Layer Sounds) Part / Fade Range
