### ISSUE TITLE
HWUI: Sound (Sub) Screen navigation - proposal

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#3198]
The Sound Screen has several Sub Screens: (Part), Voices, Master (Scale).
Currently, only the Mono Sub Screen has a consistent implementation of back-navigation via SB3 (back...). The Unison Sub Screen only implements SB3 for the first two parameters.
The back-navigation could also be extended to the Part/Master Sub Screens.

**Comment by majjam** [comment]
> The back-navigation could also be extended to the Part/Master Sub Screens.

+1 from me

**Comment by MatthiasSeeber** [comment]
We decided to re-implement the Scale Sub Screen with Soft Button 1, switching between Master and Scale, whereas the other (Part/Voices) Sub Screens are using Soft Button 3 (which shows `back ...` when in a Sub Screen). This could also be reduced down to one consistent method?
