### ISSUE TITLE
Update WebUI: when aborting choose file procedure it still says "Uploading..."

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3238]
The choose file box disappears and instead it says "Uploading" although no file has been selected. The "choose file" button should appear instead.

**Comment by KlausStrohhaecker** [comment]
see also https://github.com/nonlinear-labs-dev/C15/pull/3121
Looks like ithis has been addressed and will be part of the next major update.

**Comment by davidm2894** [comment]
indeed, only checked opened issues.
so issue closed as is already fixed in https://github.com/nonlinear-labs-dev/C15/pull/3121.
