### ISSUE TITLE
Remote Update Upload does not notify the user (and cannot be aborted)

### ISSUE THREAD

**Issue by KlausStrohhaecker** [nonlinear-labs-dev/C15#3242]
When an update upload has been started from WebUI's upload panel, the hardware UI does in no way signal it.
It should stop/pause the playground after emitting an "uploading" message.

Sidenote: Ideally, there should be a way to cancel the update at that time (until uploading, copying to BBB and unpacking has finished), using the 4 play-panel buttons in a special combintion, together and some messaging. The tools for this are available.

It looks like that the update can be aborted by quitting the WebUI (or closing the System Pane of it) while the upload is still running, but it is unclear what is happening and there is no documentation or user info.

Further, the file selected is not checked for correctness, neither in name nor in content.

Goes hand in hand with #3231

**Comment by davidm2894** [comment]
Feature in #3290 formuliert, diese Issue wird hiermit geschlossen.
