### ISSUE TITLE
WebUI Update not starting (Windows + Firefox)

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#3246]
Der failende Host war Windows +  Firefox + Update liegt auf einem angesteckten USB-Stick. Und der Fail selbst war das nach der Meldung "Uploading" der WebUI nichts mehr passiert ist, über 10 minuten lang. Weder am Gerät noch an der WebUI. Wir haben auch nachgesehen ob das Update, bzw ein Teil davon, schon auf epc /tmp angekommen ist, ist es nicht.

**Comment by KlausStrohhaecker** [comment]
I now tried two more times with the same constellation but it did work both times.
So, a single islolated glitch, might have nothing to do with C15 at all...
