### ISSUE TITLE
epc3 freezes after several hours

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#3259]
i have turned on the C15 with the epc3 draft (#3211) twice today and both times the ePC froze after running for several hours .
I was not able to do anything remotely or directly ... hard to debug, as the JC does not keep the history ...
Will have to "record" it on Monday for a while ...

**Comment by schlenkibus** [comment]
@AntonSchmied This seems resolved too, can we close this Issue?
