### ISSUE TITLE
Update media error on every boot

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3262]
Since a time I get an update media error message on every boot.
No USB is attached nor is the update manually started through WEBUI

1. "unpacking C15 update"
2. "update Media error"

Afterwards it boots and starts normally

If i enter BBB via ssh i cannot find any update.tar lying around in the filesystem
Same goes for EPC via ssh .

Assumption :
Is there a rest of an update in the read only file system which is deleted on start up ?
How could I track that behavior?

photo love story :
1 
![grafik](https://user-images.githubusercontent.com/4758563/184605446-1de44f65-d0fb-4997-8e95-0206487d524b.png)
2
![grafik](https://user-images.githubusercontent.com/4758563/184605477-2cdf3964-6c55-49d5-9466-d2b8256e6ccb.png)
3
![grafik](https://user-images.githubusercontent.com/4758563/184605545-5a8191a5-7fc0-4450-82c4-1574b5973ae1.png)
4
![grafik](https://user-images.githubusercontent.com/4758563/184605571-162fd158-fd4b-4bd5-b143-4ebaa80219fa.png)
5
![grafik](https://user-images.githubusercontent.com/4758563/184605621-dcbea923-a294-4a6f-a93a-f27cb4017470.png)
6
![grafik](https://user-images.githubusercontent.com/4758563/184605691-18685de7-56f9-403c-be79-3e40f190c103.png)

Additionally a small enhancement : the scroll bar in the bank loading screen (pic 5) can be hidden (if possible )

**Comment by davidm2894** [comment]
On what OS version does this occur?

**Comment by AntonSchmied** [comment]
we have the same issue here ... but the branch you mention is wip ... there's still a lot to be done!
Luckily we do not seem to have the same problem on the main release branch.

**Comment by majjam** [comment]
".. but the branch you mention is wip ... "
i know - and im not complaining. 
i felt it is a file system bug somehow

**Comment by majjam** [comment]
Thanks for the info, i will give it a try and let you know.

**Comment by majjam** [comment]
@schlenkibus You were right !  The build system was dirty.  After a clean build the startup works as expected.
So the fault was on my side . Thanks a lot for helping out.
Shall i close the issue, or should it be left open due to the "wontfix" label ?
