### ISSUE TITLE
Parameter-Belt: "F"-Togglebutton zur Umschaltung auf feine Auflösung (Parameter-übergreifend)

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3267]
aus #516:

Es gibt in der WebUI keine Entsprechung zum Fine Button der HWUI. Der Fine Button (Toggle) soll so funktionieren wie in der Shift+Fine in HWUI, also Parameter-übergreifend.

**Comment by schlenkibus** [comment]
Wir brauchen noch ein Fine-Button SVG um diesen Button Implementieren zu koennen.

**Comment by davidm2894** [comment]
Den Finebutton bitte nochmal umpositionieren, auf 3/4 der Parameterwertanzeige. 

In etwa so:
![Mockup_Finebutton](https://user-images.githubusercontent.com/84857645/189916303-4d399041-5e5d-4313-9d25-5e65aec8820b.png)

**Comment by davidm2894** [comment]
Und den Fine-Button an folgenden Stellen weglassen:

- Osc Phase Reset
- Mono Enable
- Unison Voices
- Priority
- Legato
- Split Point
- Scale Base Key
- Fade From
