### ISSUE TITLE
SVF - Reson KT has improper Scaling Unit (and Polarity?)

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#3272]
![SVF-Res-Bug](https://user-images.githubusercontent.com/37212609/186888616-208c0947-50ac-4cea-bc22-c9f6d472734e.png)

The Parameter Info describes Percentages, but the parameter is bipolar and shows 0 ... +/- Semitones instead of percent. I backtracked this and found that this problem was present on https://github.com/nonlinear-labs-dev/C15/releases/tag/20-29-xy and maybe even earlier versions.

This issue is closely connected to #3271

**Comment by MatthiasSeeber** [comment]
It is likely, that just the Unit and Parameter Info are wrong.

**Comment by davidm2894** [comment]
> It is likely, that just the Unit and Parameter Info are wrong.

Confirmed. Unit is %, Info is outdated.
