### ISSUE TITLE
MC-Amt Auflösung von Pitch Parametern erhöhen

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3273]
Auflösung für die Fine Auflösung der MC-Amts für die Pitch Parameter erhöhen.

Pitch A/B: 15000 steps
Pitch Comb: 12000 steps

**Comment by schlenkibus** [comment]
@davidm2894 
Are we talking about the Pitch Parameter of the Oscillator A/B Groups?
If yes: then this ticket is already done. Pitch A/B MC-Amt is set to 15000 steps, and Pitch of the CombFilter is set to 12000 steps

**Comment by davidm2894** [comment]
Yes, Osc A/B.

**Comment by davidm2894** [comment]
Closed as completed.
