### ISSUE TITLE
Return to Center Ribbon Symbol im SOLED entfernen

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3280]
Folgendes Symbol, das im SOLED anzeigt, auf wie viele und wie stark ein RtC-Ribbon auf die MCs wirkt, soll entfernt werden. Verbunden mit #3279.

![soled-7571215232829](https://user-images.githubusercontent.com/84857645/187688109-2d14e1fd-75d0-48e0-ab00-277f895f8255.png)

**Comment by schlenkibus** [comment]
We did not remove it, but rather extend it to work with the new ribbons 3 and 4 as well.
