### ISSUE TITLE
Emphase-8-TXT-Regular.ttf missing letter-spacings

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#3284]
![Boled-Tue-Sep--6-18:17:20-2022
](https://user-images.githubusercontent.com/15381257/188686325-9e192db8-5b00-4dbd-84ab-eda6c93e2674.png)

the small letter 'l' does not have proper spacing after the letter. 
This issue is only present for the small L in the font: `Emphase-8-TXT-Regular.ttf` all other fonts do not have the tick on the bottom and therefore have one pixel space.

**Comment by davidm2894** [comment]
Small "L" with one pixel space for font `Emphase-8-TXT-Regular.ttf` has been added to the font and replaces the old small "L".

**Comment by schlenkibus** [comment]
This will be fixed with the 2 extra ribbons.
