### ISSUE TITLE
Ribbon im RtC-Mode springt bei erster Berührung nach Umschalten von Absolute in Relative Mode

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3287]
Der Ribbon ist im Return-To-Center und Absolute Mode, schaltet man dann in Relative Mode und berührt den Ribbon an arbiträrer Stelle, springt er zum -100% Punkt. Danach funktioniert er wieder normal.

**Comment by schlenkibus** [comment]
This was closed in combination with the set of extra ribbons.
