### ISSUE TITLE
Playcontroller :  Aftertouch calibration  question

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3292]
@KlausStrohhaecker 
I wanted to make use of the aftertouch calibration possibilities.
I have some questions  about that :

1. software tools
which tool shall i use for reading the ad values ? 
lpc req at-test-data 
or 
lpc-read s  ?
Where do i get the sensors serial numbers ?
A brief advise would be perfekt

2. Pressure point
Where must I apply the force at the keys ? At the tipps of the keys (red) ? In the middle of the key (blue)
![grafik](https://user-images.githubusercontent.com/4758563/189344125-bb988fa6-a822-4ebf-9f3b-3dbd6d734b10.png)

3. Spring
should the force (10N ) be applied with the keybed springs assembled, or should they be disassembled ?
(i guess assembled)

4. hw tools
i want to use such a Forcemeter for applying the pressure.
is this suffictiant  ?
![grafik](https://user-images.githubusercontent.com/4758563/189345506-95cd33bf-3b46-44a9-bcbe-dee848708fa2.png)

thanks you for your  help 
best regards 
majjam

**Comment by KlausStrohhaecker** [comment]
The whole process is too complicated to do it yourself.
If you want your keybed calibrated then please turn in the C15 for service.

**Comment by majjam** [comment]
ok  thanks for answering
