### ISSUE TITLE
Neue Presetsuche für die WebUI

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3295]
Es soll eine neue Presetsuche für die WebUI geben.

Alles Weitere im angehängten Dokument.

[Preset Search V2 (Limitiert).pdf](https://github.com/nonlinear-labs-dev/C15/files/9557382/Preset.Search.V2.Limitiert.pdf)

**Comment by davidm2894** [comment]
[ssp_2022-10-10.zip](https://github.com/nonlinear-labs-dev/C15/files/9763055/ssp_2022-10-10.zip)

Upgedatete Fonts für die WebUI mit den neuen Zeichen für Zahnrad (Options) und Uhr (Clock). Auch die Lupe (Unicode: E180) ist enthalten.

**Comment by davidm2894** [comment]
Beim Steuern per Pfeiltasten sollte die Liste mitscrollen.

**Comment by davidm2894** [comment]
### Touch-Bedienung für die Preset Suche:

**Scrollen**
Touch + vertikale Bewegung innerhalb (kleiner als) von Kontextmenü-Zeit.

**Kontextmenü**
Touch + Halten über Zeit.

**Drag & Drop**
Touch + horizontale Bewegung innerhalb (kleiner als) von Kontextmenü-Zeit.

**Select**
Touch + Loslassen innerhalb (kleiner als) von Kontextmenü-Zeit.

**Comment by hhoegelo** [comment]
- [ ] preset info noch nicht angeschlossen
- [ ] Auf Touch devices kommen sich DragDrop der Presets und Scrolling der Liste in die Quere
- [ ] Touch Devices sind generell schlecht getestet bisher
- [ ] show in bank schiebt das preset manchmal auch unter die Suche
- [ ] drag/drop hat 2 images
- [ ] das gewollte image (das wir schon von den anderen Presets kennen) haengt nicht sehr praezise an der Maus
- [ ] Tinos Design ist noch nicht uebernommen
- [ ] beim schnellen Scrollen ist das Nachladen der Liste manchmal sichtbar, wirkt nicht sehr edel
- [ ] manchmal ist die Liste bei "All Banks" bzw "None" leer - erst die Auswahl von Baenken bringt Suchergebnisse !?
- [ ] manchmal, wenn man sehr schnell, direkt nach dem Laden der WebUI die Suche aufklappt, gibt es keinen Sync zum Playground und daher weder Baenke noch Presets

**Comment by davidm2894** [comment]
- [ ] Ich komm nur über das normale Wifi auf die Suche, nicht über das BBB. Da lädt sie nicht die Suchergebnisse, auch nach etwas Warten nicht.
- [ ] bei Show in Bank wäre es gut, wenn das Ergebnis zentral im Bildschirm steht. So kann es aktuell sein, dass die Suche davor steht und die Bank verdeckt (schreibst du ja auch selbst).
- [ ] manchmal reagiert die Maus-Selection in der Liste nicht, manchmal selektiert sie nur in grau (obwohl Preset geladen wird)
- [ ] Wäre gut, wenn "Result" vor der Anzahl der Ergebnisse steht in der Fußleiste
- [ ] Multiple Selection über Shift geht noch nicht
- [ ] nach einer Weile reagiert die UI nicht mehr, Refresh geht auch nicht. Passiert vor allem dann, wenn die Suche zugeklappt wird. Da bleibt es dann in der Animation hängen. Tab schließen und neu öffnen hilft.

**Comment by davidm2894** [comment]
Hier das letzte Design von Tino:
- neue Rahmenfarbe
- neue Farbe des Suchfelds (entspricht dem Hintergrund der Textfelder aus dem Setup (#111111)
- Suchfeld kriegt Fokus, wenn geklickt und inaktiven Rahmen, wenn nicht geklickt
- Zahnrad hat auch aktiven wie inaktiven Status (entspricht dem Style bei den Sortier-Tabs)
- nicht wie im Mockup, verkürzt oder verlängert sich nicht der gesamte Rahmen der Presetsuche, sondern die Liste der Suchergebnisse

![Mockup-22-11-24-tm_a](https://user-images.githubusercontent.com/84857645/203785483-27e9ddd1-e48a-4503-bd54-00f4a054f11d.png)


![checkbox-f-hr-sw](https://user-images.githubusercontent.com/84857645/203786226-f0716373-c23d-44f7-af03-4fe2e7a8cd55.png)

**Comment by davidm2894** [comment]
Prio 1:
- [ ] NonWorld-Context Menus hidden by preset search
- [ ] schnelles "scrollen" über Pfeiltasten führt dazu, dass die Selektion außerhalb des Listenausschnitts gerät. könnte man so lösen, dass es beim Loslassen der Pfeiltaste dann zum Ausschnitt mit dem selektieren Preset wechselt
- [ ] Fokus als weißer Stroke um Presetsuchfenster -> Suchfeld immer im Fokus, wenn PS-Fenster im Fokus
- [ ] Bewegung der NonWorld-Bänke in der "rechten" Bildschirmhälfte funktioniert nicht mehr. Bänke verschwinden oder bleiben in Zoomstufe kleben und werden dann unscharf -> Known Issues (?)
- [ ] Touch/iOS: Rahmen der Presetsuche passt sich nicht dynamisch an die Größe der Liste an
- [ ] Select All im Kontextmenü (Deselect über Neuauswahl ohne MS)
- [ ] Drop Down Pfeil und Links/Rechts-Pfeile bei Baenken ist auf MacOS nicht zu sehen
- [ ] Comment per Default aktiviert in Settings
- [ ] Shortcuts abfangen nur bei aktiven Suchfeld


Prio 2:
- [ ] Wenn Bankauswahl offen, sollen Scrollevents der Presetliste aufgefangen werden. Bank-Dropdown schließt nicht.
- [ ] Wenn Bank Selektion geöffnet wird, sollte die letzte Scrollposition restored werden
- [ ] Touch: Was es noch "edler" machen könnte, wäre, wenn das Scrollen beim Wischen nicht abrupt abbricht sondern etwas ausläuft - so wie es beim Bank-Auswahl DropDown schon passiert
- [ ] Touch: gefühlt ist die Zeit zum Öffnen eines Kontextmenüs in der Suche länger als in der nonworld
- [ ] wenn alle Bänke ausgewählt sind (Bankselektion) und dann eine Auswahl der Ergebnisse per Drag+Drop zur Erstellung einer neuen Bank verwendet wird, springt die Selektion zu "Multiple Banks" um. Das ist logisch korrekt, aber es wäre dennoch besser, wenn die neue Bank dann automatisch mit drin wäre. Ich kann mir allerdings vorstellen, dass es hier Bedenken geben könnte.

**Comment by hhoegelo** [comment]
[ssp_2022-12-07.zip](https://github.com/nonlinear-labs-dev/C15/files/10175960/ssp_2022-12-07.zip)

**Comment by davidm2894** [comment]
![Mockup-22-12-07-tm_d](https://user-images.githubusercontent.com/84857645/206405532-847fbf33-0052-4efe-a2ab-c611d0ea8404.png)

Hier das Design für die Bankselection. Der Highlight-Balken ist für Maus-Hovering. Das Ausklappmenü der Einstellung ist noch der alte Entwurf, das bleibt aber wie es jetzt umgesetzt ist.

**Comment by davidm2894** [comment]
Prio 2 Tasks sind in eine neue Issue (#3428) und auf den SEU Nice-To-Have Milestone verschoben worden.

**Comment by schlenkibus** [comment]
Da die verbleibenden Probleme in ein neues Ticket ueberfuehrt wurden, und das feature im milestone-maintanence angekommen ist, wuerde ich dieses Ticket nun schliessen.
