### ISSUE TITLE
Wrong ssid submitted

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3308]
at Milestone-Maintenance. 
in bbb etc/hostapd.conf : 
**ssid=NL-C15-Unit-00033_BBB**

in epc2 persistent/settings.xml : 
 **<setting id="SSID">NL-C15-Unit-00033</setting>**

transmitted SSID : **NL-C15-Unit-00000**

![image](https://user-images.githubusercontent.com/4758563/191222942-438d5cd5-69e3-4fb0-b014-85344b14b523.png)

![image](https://user-images.githubusercontent.com/4758563/191223897-9eeb6960-db39-47bc-80ca-e0add61db25c.png)

**Comment by KlausStrohhaecker** [comment]
The prefix NL-C15 is automatically inserted during SSID generation, that is NL-C15-xxxx is the _technical SSID_ whereas xxxx is the user-modifiable _Device Name_ the SSID is derived from.
The suffix _BBB is automatically added to the BBB SSID (only relevant when a WiFi-antenna is attached to the BBB -- internal or external) to tell it apart for the case that ePC also has attached antenna (the primary connection to be used).

There is a known syncing issue (ussually it it only de-syncs when replacing hardware)
Setting a new device name it in the WebUI or on the PanelUnit fixes the broken syncing.

Issue already addressed in https://github.com/nonlinear-labs-dev/C15/issues/3139

**Comment by majjam** [comment]
Unfortunately changing the device name does not help.
all frum HWUI
1. change device name from "Unit-00033" to  "Unit-00033q"
2. disable wifi
3. enable wifi
4.  transmitted SSID "NL-C15-Unit-00000"

second attempt :
1. change device name from "Unit-00033" to  "Unit-00033q"
2. shutdown C15
3. start C15
4. transmitted SSID remains "NL-C15-Unit-00000"

**Comment by majjam** [comment]
Could this somehow be connected to the persistence of the overlay-fs ?

**Comment by AntonSchmied** [comment]
When the ePC starts the Wifi-transmission, it starts the network with default settings -> "NL-C15-Unit-00000". 
When the playground is up and running, only then the information from /persistent/settings.xml is forwarded to the network manager. 

So it usually takes a while for the correct SSID to show up, but eventually it should, say within a minute after starting the C15. Some computers are a bit slower clearing their network connection lists. I work on Ubuntu and every now and then I have to turn wifi off and then on again. The the correct SSID shows up.

Could you tell me the branch and the commit you observed this on?
Are you nevertheless able to connect to the C15?

**Comment by AntonSchmied** [comment]
And depending on the system you are running, could you run `nmcli connection` or similar in a terminal to check which network you are connected to? to check whether the network UI is behaving sluggish or not. 

![image](https://user-images.githubusercontent.com/37212595/191931055-84599e9f-c348-4bd6-8164-de6c79f64e4b.png)

**Comment by majjam** [comment]
It was under milestone-maintenance at 58bfc3e (before epc3 merge)

1 .I can connect to the "wrong" SSID  "...unit-00000" sucessfully

2. the client is a windows10 machine.
I did restart wifi on that machine and even plugged the wifi dongle of that machine out an in again.
  
3. i changed the config under the hood of the  overlay-fs at etc/NetworkManager/system-connections/C15.nmconnection
For that I mounted the partion, changed the file, unmounted the partition and restarted the system afterwards.
That change has been seen by the Windows machine immediately. The edited SSID was transmitted
So i thought it has nothing to do with any caching mechanisms.


I will do some more checks on Sunday and let you know afterwards.
If I produce false alarms please excuse me !!

**Comment by majjam** [comment]
Seems to be a bug or a device specific thing:

Started C15 with device name "Unit-00033q"
Waited 3 minutes.
plugged Wifi Dongle into another (linux) machine
Wrong transmitted SSID :

![image](https://user-images.githubusercontent.com/4758563/192023141-28a33c31-6dc9-45d3-b23f-84a1c6b75a41.png)

**Comment by AntonSchmied** [comment]
interesting ... is it the latest milestone-maintenance (2fb60adfbab5e2fe72249395fa1992e649efe7a6)?

we will try to reproduce it here!

**Comment by majjam** [comment]
was on :
![image](https://user-images.githubusercontent.com/4758563/192315429-9a9564fd-dddf-41cc-8b7d-5aa8fe3d0f50.png)

**Comment by AntonSchmied** [comment]
It does look like the latest build ... For our record, majjams device is running a epc2 OS with the milestone-maintenance update.

**Comment by majjam** [comment]
Hi everybody , I used a fresh and clean build(2fb60adfb) and now i cannot reproduce it anymore. 
The SSID is transmitted correctly every time i change the device ID.
Therefore i close the issue now. I'm sorry for creating chaos here.
