### ISSUE TITLE
Modulation Issues Load Preset With Bender on 1

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#3310]
[bank.zip](https://github.com/nonlinear-labs-dev/C15/files/9608576/bank.zip)
preset xml:
MacroControl C = 0.5
Pitchbender CP = 1.0  
  
after load:
Pitchbender CP = 0.0
MacroControl C CP = 0.0

and changed-indication is showing up for MacroControl

**Comment by MatthiasSeeber** [comment]
When using a Build that contains the implementations for #3037, I cannot save a Preset in which the Bender CP is set to 1.0 (it alwas is 0), regardless of where I put the Bender (internally or by MIDI).

It is still odd, that a Bender CP stored in the Preset XML would have any effect on the Macro Control during Recall, as it should be ignored (but it isn't).

**Comment by MatthiasSeeber** [comment]
Ich habe Grund zur Vermutung, dass der Store und Recall -Mechanismus bugfrei ist, returnende Sources verhalten sich definitionsgemäß.

Wenn ich der obigen Beschreibung vollständig folge und das recallte neue Preset höre/sehe, ist der Macro bewegt, weil die returnende Source weiterhin nicht genullt ist. Nach dem Aufrufen eines Parameter Screens ist dann wieder alles in Ordnung.

Wenn ich der obigen Beschreibung nur bis Store folge und dann einen Parameter Screen anwähle und dann das Preset lade, ist alles in Ordnung. Wenn ich vor Store einen Parameter Screen anwähle, ist sowieso alles in Ordnung.
