### ISSUE TITLE
EPC3 build: file permission problem on building

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3311]
I had permission problems with the epc3 build.
1. I started a clean build
2. after a while i got file permission errors at some .js files.

files were owned by root at following folder :
**src/projects/shared/configuration/lib**

After changing the file ownership to current user , build worked .

**Comment by AntonSchmied** [comment]
please check if you encounter the same problems on the milestone-maintenance branch. 
we encountered similar problems, which we were able to fix yesterday. epc3 was updated and merged.

if the build runs through, please close the issue, thx

**Comment by majjam** [comment]
That was a misunderstanding i had this behaviour yesterday at milestone-maintenance with  7,452 commits  . (after merge)

But my source initially came from branch "issue-3158" - perhaps thats why ?

i went to milestone-maintenance by :
1. git pull
2. git checkout milestone-maintenance
3. git pull

4. cmake .... xyz
5 make c15-update
=> error ... permissions

i will give it another try on sunday and close it if build runs through.

best regards

**Comment by majjam** [comment]
As you said. The problem seemed to be based on an old artifact.
Thanks for helping out
