### ISSUE TITLE
Parameter Buttons not responding and Crash

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3331]
I had a crash with the Preview Build from this PR. Error Journal is attached and was downloaded just right after the crash. Banks were reloaded and sound was gone for a moment. 

_Originally posted by @davidm2894 in https://github.com/nonlinear-labs-dev/C15/issues/3314#issuecomment-1271361044_

I have two problems that correlate with each other and may also be causally related. 

It happens that C15 does not respond to the parameter selection, but stays in the last screen. Some selections respond, like "Preset", "Sound" or "Store", also MCs respond. In one case - when a Single Sound was loaded - C15 crashed shortly after. In another case, a Dual Sound was loaded, but no part was selected (both line indicators were gray). In this case, pressing the part selector fixed the problem (one indicator was then white) and a crash could be avoided.

In the case of the comment quoted above, I am not 100% sure that the parameter selector was not working before the crash (I think I was playing on the keys at that moment).

The attached error report is from after the first crash that is mentioned in the quoted comment and the first crash I mention in this comment. It's file size is massive when not compressed (41,8 MB), so it seems that it is flooded by error messages.

[C15-journal.txt.zip](https://github.com/nonlinear-labs-dev/C15/files/9732952/C15-journal.txt.zip)

**Comment by MatthiasSeeber** [comment]
I also had a crash that seemed pretty similar when testing #3314 for the first time. I couldn't find a way to reproduce it, though.

**Comment by davidm2894** [comment]
> I also had a crash that seemed pretty similar when testing #3314 for the first time. I couldn't find a way to reproduce it, though.

Yes, I also couldn't find a way to reproduce it. However, the amount of crashes may should lead to some investigation.
