### ISSUE TITLE
build system : uboot not found [bug]

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3334]
milestone-maintenance  current head
fresh build  : pruned old docker containers, source freshly checked out, build dir was empty

problem link is not reachable : 
https://h2949050.stratoserver.net/buildroot//uboot-nonlinear_v2021.47.tar.gz

===================================================================
build messages : 
>>> uboot nonlinear_v2021.47 Downloading
--2022-10-10 17:13:08--  http://h2949050.stratoserver.net/buildroot//uboot-nonlinear_v2021.47.tar.gz
Resolving h2949050.stratoserver.net (h2949050.stratoserver.net)... 85.214.132.78
Connecting to h2949050.stratoserver.net (h2949050.stratoserver.net)|85.214.132.78|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://h2949050.stratoserver.net/buildroot//uboot-nonlinear_v2021.47.tar.gz [following]
--2022-10-10 17:13:08--  https://h2949050.stratoserver.net/buildroot//uboot-nonlinear_v2021.47.tar.gz
Connecting to h2949050.stratoserver.net (h2949050.stratoserver.net)|85.214.132.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5 [text/html]
Saving to: '/workdir/fs/nonlinux/output/build/.uboot-nonlinear_v2021.47.tar.gz.b5hoCv/output'

**/workdir/fs/nonlinu 100%[===================>]       5  --.-KB/s    in 0s**      

2022-10-10 17:13:08 (75.3 KB/s) - '/workdir/fs/nonlinux/output/build/.uboot-nonlinear_v2021.47.tar.gz.b5hoCv/output' saved [5/5]

>>> uboot nonlinear_v2021.47 Extracting
gzip -d -c /workdir/fs/nonlinux/dl/uboot-nonlinear_v2021.47.tar.gz | tar --strip-components=1 -C /workdir/fs/nonlinux/output/build/uboot-nonlinear_v2021.47   -xf -

**gzip: /workdir/fs/nonlinux/dl/uboot-nonlinear_v2021.47.tar.gz: not in gzip format
tar: This does not look like a tar archive**
tar: Exiting with failure status due to previous errors

**Comment by hhoegelo** [comment]
I uploaded the missing file, don't know why it was missing... ¯\_(ツ)_/¯

**Comment by majjam** [comment]
THX ;)
