### ISSUE TITLE
[developer] are gassy test logs still necessary?

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#3366]
Consider the current output of test applications (acceptance-tests, playground-test, ..?), producing long logs similar to:

~~~
...
Error:  Test leaks filedescriptors, before: 189 , now: 190 
Warning:  Application::Application(int, char**) 131 
...
~~~

I am aware that we recently put efforts into memory management and as far as I am informed, no more issues remain (it is ok for the Recorder to consume memory). So my **question** is if there still is a need to log filedescriptors? (smaller Logs are easier to share/inspect etc.) If so, is there a way to specify a Log Level when starting test applications?

**Comment by schlenkibus** [comment]
We can set the current loglevel in the constructor of ApplicationFixture in TestHelper.h , I don't see a reason to not set the level to something more applicable, like error or warning. Gassy is intended to be used for debugging purposes.

**Comment by MatthiasSeeber** [comment]
Well, the Log Level on my branch is `nltools::Log::Error`, but erroring the filedescriptors bloats the generated output (seems more like gassy to me).
