### ISSUE TITLE
HWUI: minor fixups for soled ribbon displays and scale offsets

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#3385]
- [x] reduce distance between the blocks of 4 scale-offsets by one pixel (bottom y position of the whole block should not change) 
- [x] remove the pedal symbol from the Macro-String in the SOLED play-mode, left align the standalone pedal-indication
- [x] remove the pedal symbol from the Macro-String in the SOLED edit-mode, left align the standalone pedal-indication
- [x] remove the space between the Circled Macro Symbol and the given name (if there is any) -> undo
- [ ] move the new ribbon selector one more pixel to the right
- [x] remove undocumented (and supposedly unused) display feature that showed which other MCs the selected ribbon is modulating (for returning ribbons only)

**Comment by majjam** [comment]
"remove the pedal symbol from the Macro-String in the SOLED play-mode, left align the standalone pedal-indication"
+1 from me for that ;)
