### ISSUE TITLE
Boled: introduce workflow to convert- and init-Sounds faster 

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#3417]
maybe introduce a `default`-button action on the preset-screen which prompts for the sound-type of the desired init-preset and then converts + inits the editbuffer

**Comment by MatthiasSeeber** [comment]
Proposal for a generic Init/Convert solution using the Shift Button for alternative Soft Buttons:

![image_2022-12-07_123315833](https://user-images.githubusercontent.com/37212609/206168838-d02f8059-18a3-42e3-9cf4-8bd0cc4d3080.png)

**Comment by davidm2894** [comment]
I had also made a draft last weeek following @schlenkibus suggestion to use the default button as init button in the preset and sound screen.

![Frame 8](https://user-images.githubusercontent.com/84857645/206174100-c88cb68f-7846-470c-99cf-b7d66fa02a74.png)
