### ISSUE TITLE
build system broken ? 

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3421]
perhaps i use wrong cmake settings  ?

tested on 
issue2995-ui
milestone-maintenance
rc-48-sammelstelle
building works fine, packing update fails

1. removed all docker images
2. deleted all old cmake artifacts
3. source freshly checked out at ~\C15

Folder structure 
~\C15  source
~\builddev cmake starting point

CMAKE Settings :
cmake \
-DTARGET_PLATFORM=EPC3 \
-DBUILD_BRIDGE=On \
-DBUILD_ESPI_DRIVER=On \
-DBUILD_PLAYCONTROLLER_DRIVER=On \
-DBUILD_TEXT2SOLED=On \
-DBUILD_BBB_SCRIPTS=On \
-DBUILD_ACCEPTANCE_TESTS=Off\
-DBUILD_AUDIOENGINE=On \
-DBUILD_PLAYGROUND=On \
-DBUILD_WEB=On \
-DBUILD_EPC_SCRIPTS=On \
-DBUILD_PLAYCONTROLLER=On \
-DBUILD_PLAYCONTROLLER_TOOLS=On \
-DCMAKE_BUILD_TYPE=Release \
 ~/C15

**"make c15-update"**

+ echo 'Getting tools from rootfs done.'
Getting tools from rootfs done.
+ return 0
+ create_update_tar
+ echo 'Creating /home/q/builddev/nonlinear-c15-update.tar...'
Creating /home/q/builddev/nonlinear-c15-update.tar...
+ rm -rf /home/q/builddev/nonlinear-c15-update/../nonlinear-c15-update.tar
+ cd /home/q/builddev/nonlinear-c15-update/
+ tar -cf /home/q/builddev/nonlinear-c15-update.tar at-least-version-22-42.stamp BBB EPC playcontroller run.sh run_v2.sh run_v3.sh utilities
+ echo 'Creating /home/q/builddev/nonlinear-c15-update.tar done.'
Creating /home/q/builddev/nonlinear-c15-update.tar done.
+ return 0
+ print_C15_version_strings
+ echo 'Getting version strings...'
Getting version strings...
+ '[' 1 = 1 ']'
+ FILE=/home/q/builddev/build-tools/epc/tmp/usr/local/C15/playground/playground
+ rm -f /home/q/builddev/build-tools/epc/tmp/usr/local/C15/playground/playground
+ mkdir -p /home/q/builddev/build-tools/epc/tmp
+ tar -C /home/q/builddev/build-tools/epc/tmp --extract --file=/home/q/builddev/build-tools/epc/update.tar update/c15-rootfs.tar.xz
+ tar -C /home/q/builddev/build-tools/epc/tmp --extract --file=/home/q/builddev/build-tools/epc/tmp/update/c15-rootfs.tar.xz ./usr/local/C15/playground/playground
tar: ./usr/local/C15/playground/playground: Not found in archive
tar: Exiting with failure status due to previous errors
make[3]: *** [build-tools/CMakeFiles/c15-update.dir/build.make:121: nonlinear-c15-update.tar] Error 2
make[3]: *** Deleting file 'nonlinear-c15-update.tar'
make[2]: *** [CMakeFiles/Makefile2:2557: build-tools/CMakeFiles/c15-update.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2564: build-tools/CMakeFiles/c15-update.dir/rule] Error 2
make: *** [Makefile:940: c15-update] Error 2

**Comment by hhoegelo** [comment]
Yes, the build system is quite rotten, I am currently working on fixing it.
For building updates, it is enough to set "BUILD_WEB", All other flags are not needed for the update target.
The problem with your setup is probably TARGET_PLATFORM, which should be unset or devpc.

**Comment by majjam** [comment]
you shouldn't work on Sundays ! ;)
But thanks for answering. I will give it  try and will let you know.
Next week I'm on a business trip so it is unlikely that i will check here ?
shall i close the ticket after the check ?

**Comment by majjam** [comment]
cmake -DBUILD_WEB=On
seems to be the same problem (tested rc-22-48-sammelstelle)

so I leave the ticket open.

ends up with :
**tar -C /home/q/builddev/build-tools/epc/tmp --extract --file=/home/q/builddev/build-tools/epc/tmp/update/c15-rootfs.tar.xz ./usr/local/C15/playground/playground
tar: ./usr/local/C15/playground/playground: Not found in archive
tar: Exiting with failure status due to previous errors**

within /home/q/builddev/build-tools/epc/tmp/update/c15-rootfs.tar.xz  the complete **/usr** directory is missing

**Comment by majjam** [comment]
made a small test :
merged d4d4220d677fd43f14569c9a4b2b42ae23763dc3 (build-fix) into  rc-22-48-sammelstelle and the build worked fine.

**Comment by majjam** [comment]
same goes for issue 2995-ui so i think its done
