### ISSUE TITLE
HWUI: Im MC-Screen führt Edit u.U. zum falschen Screen

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3427]
Wenn man im MC Screen auf HW-Select geht und die HW-Source ändert, dann Edit drückt, erscheint ein Screen, den es nicht mehr geben sollte:

![image](https://user-images.githubusercontent.com/84857645/206499834-ef760ab0-9b12-4d48-bc79-5c2692c6be34.png)

Wenn die Source nicht verändert wird, bleibt man mit Edit im richtigen Screen.

**Comment by MatthiasSeeber** [comment]
Der (eigentlich nicht mehr existente) Screen kommt auch, wenn man im MC Screen auf SB4 drückt, oder/bzw. solange SB3 im "HW Amt" Modus ist - und dann auf Edit drückt.
