### ISSUE TITLE
BOLED: Preset-Screen: Für alle Soundtypen über dem Softbutton 1 nur noch das "Bank"-Feld einblenden ("I/II" nur noch bei "To Part" hier schaltbar)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3430]
Der Bank-Button soll bei *allen* Soundtypen wieder unten sitzen. Zwischen den Parts/FXs wechselt man ab jetzt nur noch im Sound-Screen oder im Parameter-Screen. Das Interesse an einer leichten Erreichbarkeit des Bank-Fokus überwiegt gegenüber der I/II-Auswahl.

Besonders in Verbindung mit den neuen Dual-Effekten für Single-Sounds wurde die Doppelbelegung des Softbuttons mit "I/II" und "Bank" mehr störend als nützlich, war aber auch schon früher nervig. "Direct Load" und "To Part" für Softbutton 4 bleiben erst einmal wie bisher (bei Split und Layer).

Den FX-Indikator für Single-Sounds sollten wir auch in diesem Screen anzeigen, weil man wissen muss, für welche Effektgruppe die Activity-LEDs leuchten. Dadurch, dass das "I/II"-Buttonfeld wegfällt, wird der Screen optisch wieder entlastet und verkraftet das für Single-Sounds hinzugefügte Symbol.

**Comment by MatthiasSeeber** [comment]
## Update

- [ ] Single Indicator links im Preset Screen hinzufügen (wie bei Split/Layer Sounds)
- [ ] Soft Button 1 `I / II`-Doppelbelegung entfernen/verstecken: generell bei Single Sounds, bei Dual Sounds verstecken solange "Load To Part" aus ist. Im Normalfall ist SB1 dann exklusiv der Bank Mode switch.
