### ISSUE TITLE
Details zu den Pfeilen im Sound-Screen bzw. Sound-Tab

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3438]
**Für alle  Soundtypen:**

BOLED: 

Die beiden Effektgruppen werden durch die folgenden beiden Symbole (in je 2 Varianten) dargestellt. Wenn Part/FX I selektiert ist, nehmen wir die invertierte Variante, ansonsten ist das Symbol von Part/FX II invertiert.

![FX Symbole](https://user-images.githubusercontent.com/33938408/207876781-8042ef28-7555-4179-afbe-ddd8752b5f57.png)

**Single Sound:**

Alles sichtbar (FX I selektiert, Serial > 0):
![Single Soundscreen ssc 04](https://user-images.githubusercontent.com/33938408/207890410-afd48c81-b210-4a11-9469-e87d19babc97.png)

Alles sichtbar (FX II selektiert, Serial > 0):
![Single Soundscreen ssc 05](https://user-images.githubusercontent.com/33938408/207890441-70b864ef-fe1d-4a99-b73f-a21e33fe9c55.png)

Die verwendeten Pfeile:
![Single Pfeile](https://user-images.githubusercontent.com/33938408/207889615-c720ea4b-ad70-4a4a-88f1-9fee291a5719.png)

Die Objekte mit Nummern:
![Single mit Nummern](https://user-images.githubusercontent.com/33938408/207894086-c70838a5-e397-4696-8c87-96be08c0957b.PNG)

Bedingungen für die Sichtbarkeit der Objekte:

1 ("FB"): (FB_Mixer_Effects != 0 %) AND (FB_Mixer_Level > -inf) AND 
   ( (OSC_A_PM_FB != 0 %) OR (OSC_B_PM_FB != 0 %) OR (SHAPER_A_FB_Mix > 0 %) OR (SHAPER_B_FB_Mix > 0 %) )

2 ("FX I"): (Objekt 1 sichtbar)

3 ("FX II"): (Objekt 1 sichtbar)

4_A (Serial-Pfeil nach unten): (Objekt 1 sichtbar) AND (Master_Serial_FX > 0%)
4_B (Serial-Pfeil nach oben): (Objekt 1 sichtbar) AND (Master_Serial_FX < 0%)

5_A (Pfeile von beiden FX):  (Objekt 1 sichtbar) AND (FB_Mixer_Effects_From_II > 0 %) AND (FB_Mixer_Effects_From_II < 100 %)
5_B (Pfeil nur von FX I): (Objekt 1 sichtbar) AND (FB_Mixer_Effects_From_II = 0 %)
5_C (Pfeil nur von FX II): (Objekt 1 sichtbar) AND (FB_Mixer_Effects_From_II = 100 %)

6_A (Pfeile zu beiden FX): (Output_Mixer_To_FX > 0 %) AND (Output_Mixer_To_FX < 100 %)
6_B (Pfeil nur zu FX I): (Output_Mixer_To_FX = 0 %)
6_C (Pfeil nur zu FX II): (Output_Mixer_To_FX = 100 %)

7 ("FX I"): immer sichtbar (auch zur I/II-Selektions-Anzeige)

8 ("FX II"): immer sichtbar (auch zur I/II-Selektions-Anzeige)

9_A (Serial-Pfeil nach unten): (Master_Serial_FX > 0%)
9_B (Serial-Pfeil nach oben): (Master_Serial_FX < 0%)

10_A (Pfeile von beiden FX): (Master_FX_Mix > 0 %) AND (Master_FX_Mix < 100 %)
10_B (Pfeil nur von FX I): (Master_FX_Mix = 0 %)
10_C (Pfeil nur von FX II): (Master_FX_Mix = 100 %)

**Layer Sound:**

Alles sichtbar (Part II selektiert, Serial FX > 0):
![Layer mit Nummern](https://user-images.githubusercontent.com/33938408/208716145-486efa55-5acb-49d8-a76c-c8962a5a1ad4.png)

Die Pfeile vor den Effektgruppen:
![Layer to FX Pfeile 01](https://user-images.githubusercontent.com/33938408/208735318-cc41c78a-c89e-4607-b2a3-c368314a62a3.png)

Die Pfeile hinter den Effektgruppen (auch im Split benutzt):
![Layer+Split Part Mix Pfeile R](https://user-images.githubusercontent.com/33938408/208529545-5e7470bd-d6be-4149-9414-9b565edddd53.png)

Bedingungen für die Sichtbarkeit der Objekte:

1_A: (I_To_FX_II == 0 %) AND (I_OutMixer_Level > -inf) AND (II_OutMixer_Level == -inf)
1_B: (II_To_FX_I == 0 %) AND (I_OutMixer_Level == -inf) AND (II_OutMixer_Level > -inf)
1_C: (I_To_FX_II == 100 %) AND (I_OutMixer_Level > -inf) AND (II_OutMixer_Level == -inf)  
1_D: (II_To_FX_I == 100 %) AND (I_OutMixer_Level == -inf) AND (II_OutMixer_Level > -inf) 
1_E: (I_To_FX_II > 0 %) AND (I_To_FX_II < 100 %) AND (I_OutMixer_Level > -inf) AND (II_OutMixer_Level == -inf) 
1_F: (II_To_FX_I > 0 %) AND (II_To_FX_I < 100 %) AND (I_OutMixer_Level == -inf) AND (II_OutMixer_Level > -inf) 
1_G: (I_To_FX_II == 0 %) AND (II_To_FX_I == 0 %) AND (I_OutMixer_Level > -inf) AND (II_OutMixer_Level > -inf)
1_H: (I_To_FX_II == 100 %) AND (II_To_FX_I == 100 %) AND (I_OutMixer_Level > -inf) AND (II_OutMixer_Level > -inf)
1_I: (I_To_FX_II > 0 %) AND (I_To_FX_II < 100 %) AND (II_To_FX_I == 0 %) AND (I_OutMixer_Level > -inf) AND (II_OutMixer_Level > -inf)
1_J: (I_To_FX_II == 0 %) AND (II_To_FX_I > 0 %) AND (II_To_FX_I < 100 %) AND (I_OutMixer_Level > -inf) AND (II_OutMixer_Level > -inf)
1_K:  (I_To_FX_II > 0 %) AND (I_To_FX_II < 100 %) AND (II_To_FX_I == 100 %) AND (I_OutMixer_Level > -inf) AND (II_OutMixer_Level > -inf)  
1_L: (I_To_FX_II == 100 %) AND (II_To_FX_I > 0 %) AND (II_To_FX_I < 100 %) AND (I_OutMixer_Level > -inf) AND (II_OutMixer_Level > -inf)
1_M: (I_To_FX_II > 0 %) AND (I_To_FX_II < 100 %) AND (II_To_FX_I > 0 %) AND (II_To_FX_I < 100 %) AND (I_OutMixer_Level > -inf) AND (II_OutMixer_Level > -inf)
1 leer: (I_OutMixer_Level == -inf) AND (II_OutMixer_Level == -inf)

2 ("FX I"): immer sichtbar (auch zur I/II-Selektions-Anzeige)

3_A (Serial-Pfeil nach unten): (Master_Serial_FX > 0%)
3_B (Serial-Pfeil nach oben): (Master_Serial_FX < 0%)

4 ("FX II"): immer sichtbar (auch zur I/II-Selektions-Anzeige)

5_A (Pfeil nur von FX I): (Part_I_Volume > -inf) AND ( (Part_II_Volume == -inf) OR (Part_II_Muted == TRUE) )
5_B (Pfeil nur von FX II): (Part_II_Volume > -inf) AND ( (Part_I_Volume == -inf) OR (Part_I_Muted == TRUE) )
5_C (Pfeile von beiden FX): (Part_I_Volume > -inf) AND (Part_II_Volume > -inf)
5 leer:  (Part_I_Volume == -inf) AND (Part_II_Volume == -inf)

**Split Sound:**

Alles sichtbar (Part I selektiert, Serial FX > 0):
![Split mit Nummern](https://user-images.githubusercontent.com/33938408/208716057-9124b4aa-d88c-4b0d-9a7d-1ff296048e32.png)

Die Pfeile hinter den linken Effektgruppen:
![Split Part Mix Pfeile L](https://user-images.githubusercontent.com/33938408/208529663-5b199e56-7b2f-4eba-9f22-a669528ca436.png)

Die Pfeile zu den Effektgruppen und die FB-Pfeile:
![Split to-FX + FB](https://user-images.githubusercontent.com/33938408/208532115-d166a436-5cee-4849-a1d7-b65805632c68.png)

Bedingungen für die Sichtbarkeit der Objekte auf der linken Seite (Part I):

1_A (Pfeil nur von FX I): (Part_I_Volume > -inf) AND (Part_II_Volume == -inf)
1_B (Pfeil nur von FX II): (Part_II_Volume > -inf) AND (Part_I_Volume == -inf)
1_C (Pfeile von beiden FX): (Part_I_Volume > -inf) AND (Part_II_Volume > -inf)
1 leer:  (Part_I_Volume == -inf) AND (Part_II_Volume == -inf)

2 ("FX I"): immer sichtbar (auch zur I/II-Selektions-Anzeige)

3_A (Serial-Pfeil nach unten): (Master_Serial_FX > 0%)
3_B (Serial-Pfeil nach oben): (Master_Serial_FX < 0%)

4 ("FX II"): immer sichtbar (auch zur I/II-Selektions-Anzeige)

5_A (Pfeil nur zu FX I): (I_To_FX_II == 0 %) AND (I_OutMixer_Level > -inf)
5_B (Pfeil nur zu FX II): (I_To_FX_II == 100 %) AND (I_OutMixer_Level > -inf)
5_C (Pfeile zu beiden FX): (I_To_FX_II > 0 %) AND (I_To_FX_II < 100 %) AND (I_OutMixer_Level > -inf)
5 leer: (I_OutMixer_Level == -inf)

6 (oberer FB-Pfeil, von FX I): 
     (I_FB_Mixer_Effects_From_II < 100 %) AND
     (I_FB_Mixer_Effects != 0 %) AND (I_FB_Mixer_Level > -inf) AND 
     ( (I_OSC_A_PM_FB != 0 %) OR (I_OSC_B_PM_FB != 0 %) OR (I_SHAPER_A_FB_Mix > 0 %) OR (I_SHAPER_B_FB_Mix > 0 %) )

7 (unterer FB-Pfeil, von FX II): 
     (I_FB_Mixer_Effects_From_II > 0 %) AND
     (I_FB_Mixer_Effects != 0 %) AND (I_FB_Mixer_Level > -inf) AND 
     ( (I_OSC_A_PM_FB != 0 %) OR (I_OSC_B_PM_FB != 0 %) OR (I_SHAPER_A_FB_Mix > 0 %) OR (I_SHAPER_B_FB_Mix > 0 %) )

Bedingungen für die Sichtbarkeit der Objekte auf der rechten Seite (Part II):
(Nummerierung wie bei Part I, horizontal gespiegelt)

1_A (Pfeil nur von FX I): (Part_I_Volume > -inf) AND (Part_II_Volume == -inf)
1_B (Pfeil nur von FX II): (Part_II_Volume > -inf) AND (Part_I_Volume == -inf)
1_C (Pfeile von beiden FX): (Part_I_Volume > -inf) AND (Part_II_Volume > -inf)
1 leer:  (Part_I_Volume == -inf) AND (Part_II_Volume == -inf)

2 ("FX I"): immer sichtbar (auch zur I/II-Selektions-Anzeige)

3_A (Serial-Pfeil nach unten): (Master_Serial_FX > 0%)
3_B (Serial-Pfeil nach oben): (Master_Serial_FX < 0%)

4 ("FX II"): immer sichtbar (auch zur I/II-Selektions-Anzeige)

5_A (Pfeil nur zu FX I): (II_To_FX_II == 0 %) AND (II_OutMixer_Level > -inf)
5_B (Pfeil nur zu FX II): (II_To_FX_II == 100 %) AND (II_OutMixer_Level > -inf)
5_C (Pfeile zu beiden FX): (II_To_FX_II > 0 %) AND (II_To_FX_II < 100 %) AND (II_OutMixer_Level > -inf)
5 leer: (II_OutMixer_Level == -inf)

6 (oberer FB-Pfeil, von FX I): 
     (II_FB_Mixer_Effects_From_II < 100 %) AND
     (II_FB_Mixer_Effects != 0 %) AND (II_FB_Mixer_Level > -inf) AND 
     ( (II_OSC_A_PM_FB != 0 %) OR (II_OSC_B_PM_FB != 0 %) OR (II_SHAPER_A_FB_Mix > 0 %) OR (II_SHAPER_B_FB_Mix > 0 %) )

7 (unterer FB-Pfeil, von FX II): 
     (II_FB_Mixer_Effects_From_II > 0 %) AND
     (II_FB_Mixer_Effects != 0 %) AND (II_FB_Mixer_Level > -inf) AND 
     ( (II_OSC_A_PM_FB != 0 %) OR (II_OSC_B_PM_FB != 0 %) OR (II_SHAPER_A_FB_Mix > 0 %) OR (II_SHAPER_B_FB_Mix > 0 %) )

**Comment by nonlinear-labs** [comment]
- Die beiden anderen Screen kommen natürlich noch! Musste auch erst einmal eine Methode finden für die Beschreibung
- "FX Pan" war Quatsch (werde ich gleich korrigieren)

**Comment by schlenkibus** [comment]
fixup:
N: outmix_I_open && outmix_II_open && FX_I_TO_I_ONLY && FX_II_TO_I_ONLY
O: outmix_I_open && outmix_II_open && FX_II_TO_II_ONLY && FX_I_TO_II_ONLY
