### ISSUE TITLE
BOLED: Preset Info: Preset-Namen in den Titel schreiben, automatisch generierte Hashtags für Type etc. in die erste Zeile

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3448]
Automatische Hashtags: #Layer, #Split, #mono, #unison, #scale

Der Preset-Name wäre im Header dann wieder ohne "u" und "m".

// Damit ist der Header konsistent mit der Parameter Info, wo im Header der Parameter Name steht.

// Die Suche müssen wir so erweitern, dass nach Auto-Hashtags gesucht werden kann.
// Möglichkeit für Negierung bei Sucheingabe wäre schön. (z.B. "Flute NOT #mono")
// oder die Suche auch nach #poly (= NOT #mono), #Single (= NOT(#Layer OR #Split))

**Comment by davidm2894** [comment]
Schließe dafür #3408, weil Duplikat.

**Comment by davidm2894** [comment]
Würde mich für den Vorschlag aussprechen noch #Poly und #Single mit aufzunehmen und dafür auf "NOT" zu verzichten. Man könnte die Verwendung der Hashtags noch unterstützen, indem man die sechs automatischen Hashtags vorschlägt, sobald ein Hash eingegeben wurde. Das könnte etwa so aussehen:

https://user-images.githubusercontent.com/84857645/208858528-149e4231-c24f-4589-bd44-219199e679e4.mov
