### ISSUE TITLE
HWUI : Single Sound : Copy FX I to II [enhancement]

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3457]
Would be nice to have an option to copy the FX I to FX II part with a simple command.

**Comment by schlenkibus** [comment]
@majjam this feature is implemented here: 249daa620aa3b0594866d413003a5a0d52388f14
and can be found in the sound-edit-menu on the hwui

**Comment by majjam** [comment]
Hi @schlenkibus ,
thank you very much that is super fast ! Christmas present for 2023 already given ;)
I will check that out

**Comment by majjam** [comment]
looks good to me !
thanks
