### ISSUE TITLE
Boled: add indication for 'unused FX' (cross in fx-part of preset-symbol)

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#3465]
FX I unused:
(FX_Mix == 1) && !( ( (Serial_FX > 0) || ( (FB_Mixer_Effects_From_I_II < 1) && (FB_Mixer_Effects != 0) ) ) && (To_FX_I_II < 1) )
   
FX II unused:
(FX_Mix == 0) && !( ( (Serial_FX < 0) || ( (FB_Mixer_Effects_From_I_II > 0) && (FB_Mixer_Effects != 0) ) ) && (To_FX_I_II > 0) )

**Comment by MatthiasSeeber** [comment]
I thought we'd discuss this before creating a ticket..

1. FX_Mix is only available in Single Sounds. In Dual Sounds, such indications would be useful as well (when Part Mute is active or when Part Volumes are -inf)
2. FX_From (Feedback Mixer) also plays a role in this.

**Comment by schlenkibus** [comment]
I extracted the request for comparable functionality, but for dual sounds into #3475 
And @nonlinear-labs  supplied the ruleset for FX_From which I already implemented.

**Comment by davidm2894** [comment]
I refer to the software version 23-01-rc1. If the rules have changed in the meantime (and it sounds like they have, but I can't find anything related), please let me know. 

When FX Mix > 0 AND To FX I-II == 0 AND Serial FX == 0, there's no cross indicator for FX II, although nothing is sent to FX II. Is this intended? In my opinion, there should be a cross in this case.

**Comment by nonlinear-labs** [comment]
FX I: unused if 
      ( ( (FX_Mix == 1) && (FB_Mixer_Effects_From_I_II = 1) && (Serial_FX <= 0) )
      || ( (Output_Mixer_To_FX_I_II = 1) && (Serial_FX >= 0) ) )

FX II: unused if 
       ( ( (FX_Mix == 0) && (FB_Mixer_Effects_From_I_II = 0) && (Serial_FX >= 0) )
       || ( (Output_Mixer_To_FX_I_II = 0) && (Serial_FX <= 0) ) )

(zum Feedback können noch weitere Parameter ausgewertet werden.
