### ISSUE TITLE
Boled: add indication for 'unused Part' (cross in part of dual-preset-symbol)

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#3475]
Successor to #3465
In Dual Sounds, such indications would be useful as well (when Part Mute is active or when Part Volumes are -inf)

**Comment by davidm2894** [comment]
I think we use the cross indications too much now. If I have muted the part itself in a layer sound, but the part still sounds via serial connection of the effects, then there should be no cross. The cross implies that the part is not active, which is not the case. Maybe you should only use the crosses when a part really has no influence at all. 

Maybe you don't need the crosses at all with dual sounds.
