### ISSUE TITLE
After Restore Init: Sound initializes with Mono Note Priority "Lowest" instead of "Latest"

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3479]
Observed on d39f767d3 and 160370f56, but has probably been this way for some time.

**Comment by MatthiasSeeber** [comment]
I also think this is a long existing bug.

In the deprecated ParameterList spreadsheet and in the Yaml configuration, the Factory initial value is defined as 0.0f (which translates to `lowest`).

@schlenkibus 
I suspect, the initial value should rather be 0.5f?
