### ISSUE TITLE
Nach Initialisierung über Default halten führt Drücken des Sound/Preset-Buttons zurück auf den Init Screen

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3494]
Denke, das sollte unterbunden werden, da das kein persistenter Screen ist. Würde sagen, nach Tastendruck sollte dann der Screen nicht wechseln und bei Sound bzw. Preset bleiben. Was denkt ihr?

**Comment by MatthiasSeeber** [comment]
Ich kann die Beobachtung bestätigen. Der Initialization Screen sollte sich m.M.n. nicht in die "Screen History" einreihen [^1]. Nach Initialisierung erneut den Preset/Sound Button drücken sollte auf den letzten z.B. Parameter-Screen wechseln.

[^1]: der Undo History Screen z.B. reiht sich nicht ein. Einige andere Screens könnten auch aus der "Einreihung" entfernt werden: Setup, Store, (Preset) Info, (Preset/Sound) Edit

**Comment by davidm2894** [comment]
> Einige andere Screens könnten auch aus der "Einreihung" entfernt werden: Setup, Store, (Preset) Info, (Preset/Sound) Edit [↩](https://github.com/nonlinear-labs-dev/C15/issues/3494#user-content-fnref-1-22b97636addfac6d86325c2cc79919aa)

Hab mit Stephan gesprochen und die Screens sollen ebenso aus der History fliegen.
