### ISSUE TITLE
Bei Convert und Init sollte Layer vor Split sein

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3499]
In der Reihenfolge sollte Layer vor Split angeboten werden, da Layer öfters verwendet wird.

**Comment by MatthiasSeeber** [comment]
@davidm2894
Diese Reihenfolge ist mmN nicht nur in der Hardware UI relevant. In der WebUI ist im SoundTab das Convert Dropdown bereits in der gewünschten Reihenfolge. Im User Manual hingegen werden Split Sounds üblicherweise vor Layer Sounds genannt. Hälst Du dort eine Anpassung für notwendig?

**Comment by davidm2894** [comment]
@MatthiasSeeber 
Interessant, dass es in der WebUI schon anders herum war, dann ist es ja gut, dass das jetzt angeglichen wurde.
Zum Manual: Glaube, das ist nicht unbedingt notwendig. Wenn sich durch Änderungen der Reihenfolge Kapitelnummerierungen ändern und dadurch Querverweise angepasst werden müssten, dann ist das den Aufwand wahrscheinlich nicht wert. Wenn es mit ein, zwei Anpassungen gemacht ist, dann ist es natürlich runder (bleibt aber ein Detail).
