### ISSUE TITLE
Einstellung von Upper/Lower-Limits in Coarse-Schritten sollte auf die gleichen Stufen runden, wie der Parameter selbst.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3522]
Zur Zeit bleibt der aktuelle Nachkommawert bei Coarse-Einstellungen stehen.

**Comment by schlenkibus** [comment]
closed in https://github.com/nonlinear-labs-dev/C15/pull/3565
