### ISSUE TITLE
Convert-to-Layer und Convert-to-Split für alte Single-Presets "with FX I only"

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#3538]
Siehe Spalte E und F von
https://docs.google.com/spreadsheets/d/1JyMu0EROOBc1nT2WSHSTPJ9n2QGi8fkrHgzSsLcdYoU/edit#gid=289602573

Es werden zwei zusätzliche Zeilen im Sound-Edit-Menü des Single-Sounds (BOLED) und im Convert-Menü des Soundtabs (WebUI) gebraucht. Die ersten vier Einträge sehen dann so aus:

Convert to Layer (FX I only)
Convert to Layer (both FX)
Convert to Split (FX I only)
Convert to Split (both FX)

**Comment by MatthiasSeeber** [comment]
Zwei Anmerkungen:

1. WebUI: der Vollständigkeit halber wäre auch hier eine Auswahl im Sound Tab nicht verkehrt.
2. Die Dual-zu-Single Konvertierungen gehören der "both FX" Gruppe an. Die Labels der "Convert to Single"-Einträge könnten ebenfalls um "(both FX)" erweitert werden.

**Comment by nonlinear-labs** [comment]
Danke für die Anmerkungen. Du hast völlig recht. Ich editiere die obige Beschreibung und mache einen zweiten Issue auf für to-Single-Konvertierungen, der eine etwas niedrigere Priorität bekommt.
