### ISSUE TITLE
MC Destinations werden nicht angezeigt; Envelope LEDs blinken zufällig

### ISSUE THREAD

**Issue by Oni030** [nonlinear-labs-dev/C15#3541]
Macro Destinations werden plötzlich nicht mehr angezeigt, wenn MCs ausgewählt wird. Dafür blinken die Envelope-LEDs wie verrückt (siehe beigefügtes video).
Bug trat plötzlich nach ca. 5h Benutzung auf, konnte bisher nicht reproduziert werden. Zuletzt wurden Macro Einstellungen geändert und zwischen Macros hin und her gewechselt.

Version: 23-02-rc1 (ae2f2cae8)

https://user-images.githubusercontent.com/51912581/213726886-1f9bb98f-1e94-44ee-a220-d6c3fa174799.mp4

**Comment by Oni030** [comment]
Bug trat bei diesem Preset auf. Wenn MC F bewegt wird, blinken die Envelope LEDs kurze Zeit unregelmäßig. Nach ein paar Sekunden blinken sie aber wieder alle synchron.

[MC Dest. Bug.zip](https://github.com/nonlinear-labs-dev/C15/files/10467341/MC.Dest.Bug.zip)

**Comment by davidm2894** [comment]
Closed as non-reproducible. If the problem occurs again, we will investigate it further.
