### ISSUE TITLE
Wenn nach einer Convert Aktion, der Convert über Undo rückgängig gemacht wird, updatet sich der Screen nicht korrekt

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3566]
Erst wenn man den Screen verlässt und wieder auf den Soundscreen geht, wird alles richtig angezeigt.

**Comment by schlenkibus** [comment]
This seems to be a side-effect of the broken PR #3561

**Comment by schlenkibus** [comment]
does not seem like the explanation above was correct
