### ISSUE TITLE
New Name for the "Ribbon Mode" in HW-Source Screen

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3613]
@MatthiasSeeber suggested that we should change the name for the ribbon touch behavior (absoulte/relative) since we already use the word "mode" for various functions in the Base Unit section. Also, we have a "Mode" button in the Base Unit that has nothing to do with "Ribbon Mode". This could also confuse the user. @MatthiasSeeber suggested to call the button "Touch" instead of "Mode", because it is the touch behavior that can be set.

In the manual we call it "Behavior". 

Thoughts @nonlinear-labs @schlenkibus?

**Comment by majjam** [comment]
my favourites :
 'touch'
 'sense'
 'input'

**Comment by schlenkibus** [comment]
@davidm2894 and I thought about this, and we would suggest "R. Behavior" and "T. Behavior" corresponding to `Return Behavior` and `Touch Behavior`

**Comment by nonlinear-labs** [comment]
"R." und "T." sagen dem User leider garnichts.

Ich plädiere dafür für den ersten der beiden Buttons das bisherige "Behaviour" beizubehalten, da es sich um ein Rücklauf-"Verhalten" handelt, also um ein gewisses Eigenleben. Ausserdem gibt's das auch noch bei den Pedalen.

Statt des momentanen "Mode" können wir an den zweiten Button gern "Touch" dran schreiben. Das gibt es nur bei den Touch-fähigen Elementen, den Ribbons.

**Comment by davidm2894** [comment]
We're going to call it "Touch".
