### ISSUE TITLE
C15 - Default Settings

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#3663]
When Setting up a C15 unit for the first time, it would spare time, if all Settings found in Setup were set to default. 
Some differ from and have to set by hand.

Also it would be helpful, if the settings can be set back to default after being changed.

I assume the current values can be found here [../projects/epc/playground/src/device-settings](https://github.com/nonlinear-labs-dev/C15/tree/be860edaea3686601a225e8435a14d6d1ab16a6d/projects/epc/playground/src/device-settings)

Would it be helpful to create a list of some sort, where all default values are defined?

- [x] Create a list of default Value for all Settings
- [x] Implement a "Set to default" option (global or explicit for every setting?)

**Comment by MatthiasSeeber** [comment]
Proposal: include settings and their defaults in the yaml configuration?

**Comment by AntonSchmied** [comment]
> https://docs.google.com/spreadsheets/d/1IREs_uU4dCT1iar2fBBLZ7-cVHILBrPvfwJR0V2Rx1Y/edit#gid=0
I would edit the document from i understand should be the defaults

**Comment by schlenkibus** [comment]
also add a default button action for selected setup-entries to allow single default..

**Comment by MatthiasSeeber** [comment]
In #3667, a basic mechanism for yaml-based Setting Descriptors is implemented and already covers "primitive" (boolean, numeric, string) and nltools-based types (MIDI Channels, CC Assignments, Vel/AT Curves, ...).

However, I'd like to point a few things out:

1. We should be aware of our nomenclature, "setting" leaves room for interpretation. Crudely, anything available within HWUI / WebUI Setup, or within WebUI Developer Settings and some additional stuff for HW Sources within corresponding Boleds/Soleds (for example `ParameterEditModeRibbonBehaviour`) can be considered a setting. If a setting property is only for displaying purposes (like `TotalRAM` or `UsedRAM`), there is nothing to default to.

2. There may be some settings where defaults are tricky to realize or counter-productive:
- Device Name (Default differs for every C15 Unit and can't simply be expressed in yaml - could be possible if the Unit name is somehow known at compile time?)
- Date/Time (can be adjusted in HWUI only - and as I understand it, you can overwrite the timestamp completely - a sensible default would be `now()`, but it wouldn't be helpful to set the timestamp to default to zero, meaning 1977 or whatever..?)
- AlsaFramesPerPeriod: zero also doesn't seem to be a sensible default value?

3. How to default?
- individual defaults for every setting seem nice but would likely mean ui overkill and big ui workload
- one global default seems simple and easy to implement, but I am not sure if defaulting everything at once is helpful for the user (for the developer it is without question)
- a group based approach (Developer/Device/GUI/MIDI/Recorder/System) seems more user-oriented, but would also result in a considerable workload

I think, the global default as a developer option should be the way to go now, to cover this ticket's premise. A user-oriented solution appears to be a bigger task (to me at least). "Tricky" defaults (2.) should be subject of further discussion.

**Comment by AntonSchmied** [comment]
Updated the document, new column is **defaults (Production)**
https://docs.google.com/spreadsheets/d/1IREs_uU4dCT1iar2fBBLZ7-cVHILBrPvfwJR0V2Rx1Y/edit?pli=1#gid=0

While most settings (my comprehension of settings are values that can be changed, unlike RAM, ALSA and such) seem to correspond with neighboring column, not all values are set correctly, when the C15 is initially set up. 

Red Values are set manually (such as SSID, Time, etc.) and don't have to be included into the defaults list, I think.
And I must admit, my input does not yet include webUI Settings.

However/ Additionally:
_Sync Parts Across UIs - On_ is missing??
Enter _Set to High-Res. Defaults_
Enter _Set all Routings to On_ 

We can discuss further values and the approach

**Comment by MatthiasSeeber** [comment]
> Sync Parts Across UIs - On is missing??

I think this is covered in row 39 (SyncVoiceGroups).

> Enter Set to High-Res. Defaults
> Enter Set all Routings to On

These are buttons that overwrite several other settings at once. It would consider these actions (not possesing any owned value to default to), not settings.

**Comment by AntonSchmied** [comment]
> These are buttons that overwrite several other settings at once. It would consider these actions (not possesing any owned value to default to), not settings.

yes, this was more of a note, that when a C15 is set up, these two actions take place.

**Comment by MatthiasSeeber** [comment]
Most of the Settings appear to be reliably defaultable now, but unfortunately there are some issues remaining _(proposed default values are marked __bold__)_:

Setup: Device Settings
- [ ] Edit Smoothing Time has wrong default (0ms ... __20ms__ .. 200ms, default should be 0.1f)

Setup: GUI Settings (Web UI only) are missing
- [ ] Selection Auto Scroll? (Off, Parameter, Preset, Parameter and Preset)
- [ ] Edit Parameter? (Always, If Selected, Never)
- [ ] Show Context Menus, Preset Drag and Drop? (BooleanSettings: __On__, Off)
- [ ] Display Scaling Factor? (50%, 75%, __100%__, 125%, 150%)
- [ ] Stripe Brightness (Off, 10%, 25%, 50%)
- [ ] BitmapCache, Show Developer Options (BooleanSettings: __On__, Off)

Setup: MIDI Settings
- [ ] Routings
  - display problem: set all routings off, load factory defaults and observe that nothing seems to have changed, then click on a checkbox and observe that now all checkboxes are in actual default state (see below)
  - actual default is: all on except Prog. Change and HW Sources with exclusive Receive (either __Primary Receive On, Secondary Receive Off__ or Primary Receive Off, Secondary Receive On) _(and Prog. Change is `n.a.` for Local and can be considered permanently Local On)_
  - does the wrong default cause display problems or is it an update issue?

Developer Options
- [ ] Alsa Frames per Period
  - doesn't show a value unless clicking on `set`, opening an input dialog (raw text input with no validation: no errors seems to appear when entering non-numerical text)
    - the text says `Frames per Period (0 = default, 1...512)`, which is wrong (16 is new default, and zero is not considered a valid value)
    - there are better input types to consider, like `number` or `range` (with min/max attributes and some validation out of the box)
    - the setting is declared as `persistent: TRUE`, but no value persists (the text input always shows `0` after clicking set, no matter what was entered before)
