### ISSUE TITLE
Doku: Mobile Version nicht zu verwenden auf Smartphones

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3694]
Die Dokumentation ist auf Smartphones nicht zu verwenden, weil die meisten Features nicht auswählbar sind. Was funktioniert ist, die einzelnen Manuals auszuwählen, danach gelangt man aber nur auf Seiten, wo meist nur das Bild des Manuals angezeigt wird. Navigation etc. sind nicht sichtbar und dementsprechend auch nicht bedienbar. Beim Anwählen der Manuals blitzt kurz ein Menu-Icon oben rechts auf, der dann aber direkt wieder verschwindet. Auf Android und iOS beobachtet.

![image](https://user-images.githubusercontent.com/84857645/227203365-4ec7d00f-f732-4025-ba25-354e883d403d.png)
![image](https://user-images.githubusercontent.com/84857645/227203383-e03bf05c-d355-45cd-a005-18afd6341416.png)
![image](https://user-images.githubusercontent.com/84857645/227203395-733506d4-de3e-46a2-8b28-776dd6e90462.png)

**Comment by schlenkibus** [comment]
![Screenshot_20230323-150523.png](https://user-images.githubusercontent.com/15381257/227229051-f8c1d0b9-2e71-4825-92bd-cd20f12a5652.png)

Auf Android funktioniert bei mir das Hamburger Menü auf dem Index. Aber wenn ich z.B. auf die midi-bridge klicke sieht es genau so aus wie auf den Screenshots von David.

**Comment by MatthiasSeeber** [comment]
Das ist natürlich ärgerlich - und seltsam. In den Browser Dev-Tools (Chromium, Firefox, Opera - Linux/Windows) ist immer ein Hamburger oben links zu sehen. Ist Javascript aktiviert bei euch?

Ich möchte auch anmerken, dass das Manual im Portrait View auf einem Smartphone die wohl schwierigsten Anforderungen hat und am unansehnlichsten ist. Im Landscape View z.B. ist idR noch platz für die Navigation.

Dass die Titelseiten der Manuals nur Bilder besitzen ist vielleicht nicht ideal, aber derzeit so gesetzt.

**Comment by MatthiasSeeber** [comment]
Anbei zwei Screenshots (via Chromium Dev-Tools), die das Layout so aufzeigen wie gedacht.

1. mobile - portrait (wie obige Screenshots)
![man-mobile-portrait](https://user-images.githubusercontent.com/37212609/227497524-b90a881b-ddeb-435e-9fee-33bbda194dac.png)


2. mobile - landscape (klappt auch nicht?)
![man-mobile-landscape](https://user-images.githubusercontent.com/37212609/227497556-950ebdc2-5f05-4510-9699-345532e1c608.png)
