### ISSUE TITLE
Soundrecorder direct disc streaming [feature request]

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3699]
Da der C15 ja mit m.2 "Platten" betrieben wird habe ich mir die Frage gestellt, ob es nicht möglich ist, den Soundrecorder direkt auf die m.2 streamen zu lassen - anstelle eines reservierten Ram bereichs. Daraus würden sich zwei neue Möglichkeiten ergeben :
1. größere Aufzeichnungsdauer ohne den Ram zu erweitern zu müssen.
2. nach einem Shutdown kann die Aufzeichnung wieder hervorgeholt werden. 
    (die Preset-Events wären dann wahrscheinlich weg aber zumindest die Auzeichung besteht noch.)

Da der C15 ja ansonsten relativ wenig platten Zugriffe hat könnte das funktionieren.

Vorteil : Was hatte ich gestern noch mal gespielt ? ach ja ich starte den alten stream gerade noch mal vom handy aus. (ohne eine dediziert abgespeicherte datei laden zu müssen.

**Comment by davidm2894** [comment]
Das wurde - soweit ich weiß - schon in der Vergangenheit mal diskutiert und die Entscheidung dagegen begründet sich glaube ich darauf, dass man so wenige Schreibvorgänge wie möglich auf der SSD haben möchte und damit die Lebensdauer verlängert.
