### ISSUE TITLE
[WebUI] Preset Search - Hashtag mechanism

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#3708]
Before the latest features, we already encouraged the user that custom hashtags in the comment field of a preset could be helpful when searching for them (and we also provided some, like `#Piano`). With the new auto-generated hashtags, we step more in this direction. However, the current implementation does not distinguish hashtags in any way, leading to:

- typing the pound character `#` is optional (`Poly` and `#Poly` will lead to the same results)
- matches include substrings (searching for `#P` will match all `#Poly` presets)

I don't mind this implementation in regards to ordinary text search, but I would prefer a more strict approach for hashtags:

- if a word of the search input starts with `#`, it will be considered a hashtag
- hashtags should only match the full word (including the `#`), not a substring (maybe?)
- at leats, the properties and comment fields should be able to search for hashtags, for the other fields (name, device name) this may not be necessary

Opinions?
@nonlinear-labs @davidm2894

**Comment by nonlinear-labs** [comment]
The current implementation seems simple and effective to me. The "#" is not handled differently from other characters. We recommend its use for preset attributes and make use of it when we automatically create the eight built-in Properties. The concept relies on the assumption that words starting with "#" are normally not used in comments or names.
Searching Properties with "#p" or "#m" gives me the polyphonic or monophonic presets. If I enable Comments for search it would also give me presets categorized like "#plucked" or "#membrane", which is fine. I just have to be a little clearer - like "#pl" or "#mem"

**Comment by davidm2894** [comment]
> * if a word of the search input starts with `#`, it will be considered a hashtag

I also feel like that it would be better to distinguish between hashtags and normal text.
> * hashtags should only match the full word (including the `#`), not a substring (maybe?)

I don't think that's needed when we distinguish between hashtags and normal text.
> * at leats, the properties and comment fields should be able to search for hashtags, for the other fields (name, device name) this may not be necessary

yes. but then we should not allow hashtags in preset names.

**Comment by nonlinear-labs** [comment]
I agree with David. Trying to be a little more precise: Properties-based search results are only shown, if the first character of a search string is "#", followed by at least one normal character (not space). The string does not need to be complete.

**Comment by MatthiasSeeber** [comment]
**proposed algorithm**

- the search query string is split into a sequence of words
- for each word (if search options allow for it)
  - check if Preset or Device Name fields include this word (no hashtag distinction here, same as before)
  - if the word starts with `#` and has at least two characters it is considered a hashtag
    - check if Comment or Properties include this hashtag
  - otherwise the word is considered ordinary
    - check if Comment includes this word (hashtags in the comment are ignored)
- depending on the and/or option, either *every* or *any* item of the search sequence has to match

**notes**
- following the definition, the word "#" is not considered a hashtag and will only match if the preset name or device name contain this character (properties and comment will not match in this case)
