### ISSUE TITLE
Build System 23 :  cmake error

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3747]
build system, (linux mint 21, vanessa)

CMake Error at cmake/crossbuild.cmake:22 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  update/c16/web/CMakeLists.txt:1 (crossBuild)

https://github.com/nonlinear-labs-dev/C15/blob/04c5d06e5c6993a2ee948938840dca2744abce08/cmake/crossbuild.cmake#L22

**my hotfix:** - adding qoutes
 **string(STRIP "${CCACHE_DIR}" CCACHE_DIR)** 

are there empty lines in "${CCACHE_DIR} ?

@hhoegelo 

![image](https://user-images.githubusercontent.com/4758563/234965077-1a638d8f-86e1-4d60-a4e5-4a8fcf456a08.png)

**Comment by hhoegelo** [comment]
Thank you for reporting, this is already fixed in branch c16-ui.
I didn't have the chance to port the fix back to next-milestone today.

**Comment by majjam** [comment]
Thanks for the info i will close it then.

27.04.2023 21:28:05 Henry Hoegelow ***@***.***>:
