### ISSUE TITLE
Change compressed file format of backup file from tar.gz to .gz

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3749]
On an Apple computer, it is not possible to properly unzip the zipped (.zip) factory backup file from our website because the built-in archiver program attempts to unzip both the .zip and tar.gz files. When trying to unzip the tar.gz file, the application fails. The reason for this could be that the tar.gz file is actually a "fake" tar.gz file. The reason for zipping the tar.gz file for the website is that the browser would otherwise consider it a "suspicious" file. The reason could be that it is not a "real" tar.gz file. 

Therefore, we want to change the file format for backup files from tar.gz to .gz. The first step now is to check if we can upload and download .gz files from our website.

If this works correctly and we then change the file format, we have to make sure that it will still work with the old backup file format (read only).

**Comment by schlenkibus** [comment]
we implemented a change to `.nlbackup` on main
