### ISSUE TITLE
[Dual Sounds] - Swap Parts

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#3760]
_This reflects on remarks from a user during the SB._

**Description**

Consider having designed a Layer Sound. You started with Part I and built a _primary_ lead-like component. Then you added a _secondary_ bass-like component for Part II. You then realize that this could be a nice Split Sound as well and convert it. You will end up with a Split Sound with the lead-like Part on the left and the bass-like Part on the right - which is probably the opposite of your intention.

**Proposal**

Similar to our Copy FX options, it would be nice to be able to swap Parts in Dual Sounds (replace I with II and vice versa). This could be another option in the Dual Sound Edit menu. It could also be realized for Dual Sound conversions (Layer --> Split, Split --> Layer) by using the selected Part (I means no swap, II means swap) - but this would change legacy behavior (selected Part has no influence on dual conversions) - unless wrapped into another setting.

In Split Sounds, almost everything dual (poly: Env A ... Mix, mono: FX) is swappable (including Unison/Mono) - except for the Split Point. In Layer Sounds, Unison and Mono and Part Fade From/Range are not swappable.

**Comment by schlenkibus** [comment]
Tim also proposed this idea some time ago: https://github.com/nonlinear-labs-dev/C15/issues/3321
I think this is a useful feature aswell.

**Comment by MatthiasSeeber** [comment]
I added the proposal to the original ticket.
