### ISSUE TITLE
Artefakte bei Elevate T-A

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3835]
**Describe the bug**
Wenn man schnell den Parameter Elevate verändert, hört man Artefakte. Am stärksten hört man die, wenn man über einen Ribbon den Parameter steuert und dann sprunghaft moduliert.

**C15 Software Version as found in systeminfo**
Ist test build von next-milestone. nehme an, das ist auf main auch so.
branch: test-build-next
head: 0af7f1781

**To Reproduce**
1. simple Osc A Sound
2. Elevate schnell verstellen (wie gesagt am besten über Ribbon sprunghaft modulieren)

**Comment by MatthiasSeeber** [comment]
Die Artefakte hängen zum Einen mit der MC Smoothing Time zusammen. Je kürzer die Zeit, umso stärker die Artefakte. Die Default Zeit (12.1ms) verursacht bereits deutlich hörbare Artefakte, besonders bei Werte-Sprüngen. Wenn die Zeit extrem kurz oder exakt 0 ms ist, dann ist ein "Knackser" bei Werte-Änderungen streng genommen kein Bug.

Im Code habe ich diesbezüglich aber einen Bug gefunden. Die Elevate Parameter Smoother selbst werden per "fast" clock (9600 Hz) gerendert, allerdings werden die Envelopes per "slow" clock (400 Hz) mit den Smoother Werten upgedated.

Streng genommen sind auch mit 9600 Hz abgetastete Segmente als Artefakte hörbar (besonders bei tiefen Sinüssen), wenn auch weit weniger prägnant. Und bisher tolerieren wir das, bzw. nehmen den Kompromiss in Kauf. Nur ganz wenige Parameter rendern wir tatsächlich in Audio-Rate (Unison und Osc Phases). Wir müssten dann mal schauen, ob uns hier die "fast" clock reicht.
