### ISSUE TITLE
build error at NL.cmake cmake version ?

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3840]
branch next-milestone at: 80b3df5c79675ab415fc6f0f75a3e7bfa4b5a9fc
for update c15

[16%] X-Building text2soled for beaglebone on 259c0b166f1004d0c34d4997a0f40b67f562ea7f
CMake Error at /build/cmake/NL.cmake:137 (target_link_options):
  **Unknown CMake command "target_link_options".**
Call Stack (most recent call first):
  CMakeLists.txt:16 (addNLExecutable)

 - Browser [e.g. chrome, safari, firefox]

**Comment by schlenkibus** [comment]
should be fixed with: 063138e7c3a8c25444191e32ccf18bd30c989bb2

**Comment by majjam** [comment]
will hopefully check that today
