### ISSUE TITLE
c15 crashes on boot and restarts

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3864]
**C15 Software Version as found in systeminfo**
[issue-3774-next](https://github.com/nonlinear-labs-dev/C15/tree/issue-3774-next)

[C15-journal.tar.gz.txt](https://github.com/nonlinear-labs-dev/C15/files/12359665/C15-journal.tar.gz.txt)

**Comment by schlenkibus** [comment]
it seems like a crash but i suspect the 2 instantiated HWUI's to look like a crash. As the journal also reports no crash, so this ticket will be closed with #3866
