### ISSUE TITLE
Beim Import einer Bank sollte der bisherige Editbuffer nicht verändert werden

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#394]
Aus der neuen Bank wird nichts geladen. Das war gefordert. Aber das zuletzt geladene Preset wird neu geladen, wodurch der Editbuffer verloren geht.

**Comment by schlenkibus** [comment]
Lokal kann ich den Bug schonwieder nicht nachvollziehen.
