### ISSUE TITLE
[C15]-[HWUI]  Parameter selection ignored when in preset screen  [BUG] 

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3946]
![image](https://github.com/nonlinear-labs-dev/C15/assets/4758563/c4a56e7d-d52d-404c-b75e-89ce5cf282d3)

(and older versions , too)
Occurs on all (96) hwui-parameter keys :

example to reproduce :
1. Select Macro control A via key press => MC A Menu is shown , OK
2. goto Preset screen by Preset button
3. select another  preset via + or - button
4. Select Macro control A via key press => nothing happens [BUG]
5. Select Macro control B via key press =>  works

The last shown parameter menu is ignored after loading a preset via + -  at direct load=On

**Comment by schlenkibus** [comment]
I can reproduce this on the latest next-milestone, but not on main, so it's not super urgent, but should be fixed before the next update.

**Comment by majjam** [comment]
Agreed :)

15.11.2023 11:51:44 Justus Scheil ***@***.***>:
