### ISSUE TITLE
NonMaps remove 'selected xy parameter' in undo tree 

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#395]
NonMaps undo tree can be probably clearer if the selected xy parameter entries are not shown.
+label:enhancement 
e.g. 
if you change PM of OSCA:
       Set 'SV Filter - Parallel'
          |
      **Select 'Oscillator a-PM Self'**
           |
        Set 'Oscillator A-PM Self'
           |
        Set 'Oscillator A-PM Self'

shortens to : 
        Set 'SV Filter - Parallel'
           |
        Set 'Oscillator A-PM Self'
           |
        Set 'Oscillator A-PM Self'

**Comment by nonlinear-labs** [comment]
Hi Majjam, thanks for your input! We are planning to offer a user preference to enable/disable the display and replay of selection steps. They are useful if you want to see the parameter value before and after the change.

**Comment by majjam** [comment]
Entschuldigung Sie bitte ich habe zu spät bemerkt, dass hier auch auf Deutsch geschrieben wird. 

Hieraus eine Option zu machen find ich gut, denn den vorhergehenden Parameterwert kann ich auch zurückbekommen wenn ich einen Schritt 'über' select gehe.

**Comment by nonlinear-labs** [comment]
Wow - thanks for writing in perfect German! May I ask where you have tested the C15?
(We found a musician from Guinea with the name "Majjam", currently living in Dakar, where one of our instruments is being used by Ibou Mbaye.)

**Comment by majjam** [comment]
Hallo - ein Mißverständnis, ich bin deutsch.
Ich habe den C15 auf der Superbooth 18 getestet, und bin immer noch begeistert.
Dann habe ich durch Zufall dass Repo hier gefunden, und bei mir zu Hause eine Vbox eingerichtet, auf der ich den Playground compiled und getestet habe, dabei ist mir dieser Umstand aufgefallen.
Ich musste zwar ein par Hürden nehmen, aber mein Lob gilt Ihren Entwicklern: Das meiste ist selbsterklärend und es gibt gute Kommentare und cmake scripts!

Ich hatte Ihnen schon per Mail geschrieben, dass ich Sie gerne im Herbst besuchen möchte, was ich auch gerne weiterhin tun möchte : (max@j****we.net) dazu kontaktiere ich Sie gerne noch einmal. Bis dahin lese ich in Vorfreude die Commits ;)

Weiter so ,liebe Grüße aus OWL
Max
