### ISSUE TITLE
Preset Search: bad performance when first open 

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3979]
observed on branch: 40@96khz

We have a regression in the preset search performance. When you open the search for the first time, it takes a considerable amount of time (around 20 seconds) until the list shows the results. It seems like the time depends on the amount of presets.

On main, the performance is flawless.

**Comment by majjam** [comment]
had a test with 
next-milestone as base 
merged : #3981 
(merged:  #3982 ,too)

preset search is instantly loaded.before i had enormous load times at next-milestone .
So works great here !
