### ISSUE TITLE
Krasser Bug: Ribbon-Labels im SOLED werden oft erst beim Berühren eines Ribbons aktualisiert

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#409]

**Comment by nonlinear-labs** [comment]
Evtl. in Verbindung mit dem Problem, dass die HWUI nicht aktualisiert wird, wenn man bei offenem Parameter-Screen (von der WebUI) ein neues Preset lädt.

**Comment by hhoegelo** [comment]
ich kann es mit dem aktuellen Release-2018--8 nicht reproduzieren und bin ebenfalls der Meinung, es handelt sich um eine weiteres Symptom des bereits gefixten Bugs im Throttler, der ein Update der HWUI verzoegerte.
