### ISSUE TITLE
Nach dem Booten werden Änderungen einiger Parameter (s.u.) nicht an die Audio-Engine übertragen. Nach dem Laden eines Presets geht's dann.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#411]
Mindestens betroffen: beide PM SELF, PM A,B, beide PM FB.
Viele andere Parameter lassen sich bedienen.

**Comment by schlenkibus** [comment]
Kann ich nicht reproduzieren auf lokalem RELEASE-2018-08
