### ISSUE TITLE
WebUI: Änderungen in Preset/Bank-Info-Feldern sollten beim Wechsel des/der Presets/Bank genauso wirksam werden wie beim Wechsel des Fokus.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#428]

**Comment by nonlinear-labs** [comment]
Undo auf Änderung des Comments führt zu einer Dauer-Undo/Redo-Schleife.

**Comment by schlenkibus** [comment]
Kann ich nicht Reproduzieren, Undo+ Redo in normalen Funktionsweise ist funktioniert wie Erwartet.
