### ISSUE TITLE
WebUI: Zoom-in per Touch-Pinch-Geste erzeugt unscharfes Bild, die Randelemente verschwinden (nach aussen).

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#456]
Es ist aber kein Browser-eigener-Zoom, denn dessen Zoomfaktor bleibt 100 %.

**Mist! Einmal aufgetreten, dann noch einmal reproduziert, danach nicht mehr reproduzierbar...**

**Comment by majjam** [comment]
Soweit ich mich erinner kann war es :
1. Browser auf auf secondary Monitor  in Fullscreen-mode
2. Zoom und Navigations-Aktionen in Browser durch Maus
3. Fenstergröße wurde wiederhergestellt (verkleinert)
4. verschoben auf primary Monitor
5. Fullscreen Mode
6. Touch-Pinch-Geste
unscharfes Bild und keine Randelemente mehr.

**Comment by schlenkibus** [comment]
Problemumgehung besteht darin in jedem Browser die Einstellungen so zu ändern das die Touchevents erzwungenermaßen an die Seite gesenden werden bzw die Pinchgeste keinen Browserzoom auslöst.
Anleitung für die "großen 3 Browser" (Google Chrome, Mozilla Firefox, Microsoft Edge) folgen.

**Comment by schlenkibus** [comment]
MS Edge:
about:flags in Adresszeile
Einstellung "Touchereignisse aktivieren" von "Immer Deaktiviert" auf "nur Aktivieren, wenn ein Touchscreen erkannt wurde" oder "Immer Aktivieren"


Mozilla Firefox:
about:config in Adresszeile
bei den Einstellungen "browser.gesture.pinch.in" und "browser.gesture.pinch.out" den Wert aus der letzten Spalte löschen. 

Google Chrome:
chrome://flags/#touch-events in Adresszeile
oberste Option: "Touch Events API" von "Automatic" auf "Enabled" setzten

**Comment by nonlinear-labs** [comment]
Nur durch Browser-Settings zu lösen. Wir haben ein PDF mit Hinweisen für die User erstellt.
