### ISSUE TITLE
WebUI-Feinschliff (Tinos Liste)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#465]
Siehe Text und Bilder im Attachment.

[Todos.txt](https://github.com/nonlinear-labs-dev/C15/files/2484458/Todos.txt)
![clipping](https://user-images.githubusercontent.com/33938408/47038783-9c1e8680-d182-11e8-95a9-4e3974bfb6eb.png)
![dl-zentriert](https://user-images.githubusercontent.com/33938408/47038784-9c1e8680-d182-11e8-8aca-c761a8975cdb.png)

![liste-buttons](https://user-images.githubusercontent.com/33938408/47038785-9cb71d00-d182-11e8-8900-ef66eb05c8f9.png)
![marker-fader](https://user-images.githubusercontent.com/33938408/47038786-9cb71d00-d182-11e8-84b3-448109181554.png)
![mod-buttons](https://user-images.githubusercontent.com/33938408/47038787-9cb71d00-d182-11e8-8a84-74d11bcd479f.png)
![pitch-mod](https://user-images.githubusercontent.com/33938408/47038788-9d4fb380-d182-11e8-8079-7f655cc98406.png)
![preset-bank-buttons](https://user-images.githubusercontent.com/33938408/47038789-9d4fb380-d182-11e8-9906-44824a8662b8.png)
![presetliste](https://user-images.githubusercontent.com/33938408/47038791-9d4fb380-d182-11e8-9dc6-04b009659980.png)
![x-fade](https://user-images.githubusercontent.com/33938408/47038792-9d4fb380-d182-11e8-8839-5455a1c91c9e.png)

**Comment by hhoegelo** [comment]
Not yet finished, here is what is missing:

+++ 
View Menu wird sofort nach Anwahl einer Option geschlossen. 
- sollte wie bei den anderen Menüs funktionieren (Hintergrund kurz blinken)
+++
Modulations-Balken bei Pitch zu schmal, sollte so hoch, wie bei normalen Parametern) sein
-> siehe: "Pitch-Mod.png"
+++
Favicon ersetzen -> favicon.ico
- ist jetzt in den Ecken transparent

This is done and can be tested:
+++ Presetliste grafisch aufräumen 
- alter Zustand war gut. 
-> siehe "Presetliste.png".
+++ Cross Fader (A – B) mit breiter Linie (weiß) und schwarzem Indikator
-> siehe: "X-Fade.png"
+++ Clipping Anzeige der Modulation: "!" mit etwas mehr Abstand zu Fader + etwas kleiner 
oder: 
an Enden einfärben (nur BOLED mit "!")
-> siehe: Clipping.png
+++ Parameter Tab: Punkte (Linie) zwischen Modulations-Marker verlängern bzw. Abstand auffüllen
-> siehe "Marker-Fader.png"
+++ Preset Tab: Preset/Bank Buttons: Abstände und Eckenradien kleiner
-> siehe "Preset-Bank-Buttons.png"
+++ MC Adjust Buttons: etwa doppelten Abstand voneinander
-> siehe: "Mod-Buttons.png"
+++ Preset Tab: "DL" Button mit "Load" Button zentrieren, "DL" sitzt etwas zu tief
siehe: "DL-zentriert.png"
+++ zwischen Buttongruppen (rechts/links) und Preset-Liste etwas größer
-> siehe: "Liste-Buttons.png" 
+++ Höhen-Versatz zwischen "Pitch" und "Decay" Parametern ?
-> siehe: "Pitch-Mod.png"

**Comment by nonlinear-labs** [comment]
Hier kommt das gezippte favicon
[favicon.zip](https://github.com/nonlinear-labs-dev/C15/files/2491130/favicon.zip)
