### ISSUE TITLE
WebUI Parameter Tab: Ungenaue Werte für Upper/Lower Limit (!= Werte im BOLED)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#494]
Wirkt irritierend und von fragwürdiger Qualität. Ggf. auch verschiedene Clipping-Zustände.

**Comment by schlenkibus** [comment]
Nicht mehr konsistent reproduzierbar in fix-webui-clipping
-> Aber Vorhanden!
