### ISSUE TITLE
WebUI: Parameter-Feineinstellung nicht ausreichend implementiert

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#516]
1) Parameter-Tab: QWERTY-"Shift" sollte auch für das Mausrad auf feine Schritten umschalten.

2) Parameter-Tab: neuer "F"-Togglebutton zur Umschaltung auf feine Auflösung (wahrscheinlich Parameter-übergreifend)

3) Zahlenfelder für Pitch und Pitch-Keytracking: Das Feld in zwei Teile aufteilen. Im linken Teil: Änderung in ganzzahligen Schritten (setzt Nachkomma-Anteil auf .00). Im rechten Teil: Änderung in Schritten von 0.01.

**Comment by schlenkibus** [comment]
"Parameter-Tab: QWERTY-"Shift" sollte auch für das Mausrad auf feine Schritten umschalten"
Getestet: solange Shift gehalten wird, ist der Fine Modus für Mausrad, Tastatur und Maus-Drag aktiv.

**Comment by schlenkibus** [comment]
Parameter-Tab: neuer "F"-Togglebutton zur Umschaltung auf feine Auflösung (wahrscheinlich Parameter-übergreifend)
 Soll das Togglen nur die Aktuelle WebUI betreffen?

**Comment by schlenkibus** [comment]
@nonlinear-labs Bis auf den 2. Punkt ist dieses Ticket nicht mehr relevant. 
Besteht noch Interesse an einem Shortcut oder Visuellem Button fuer den WebUI-Parameter-Fine-Mode-Toggle?

**Comment by nonlinear-labs** [comment]
Ja, wir sollten im Parameter-Tab einen Fine-Button haben, der so funktioniert wie in der Hardware.

**Comment by nonlinear-labs** [comment]
Nur noch teilweise relevant.
