### ISSUE TITLE
BOLED Parameter Screen mit MC: Upper/Lower Limit bitte mit Leerzeichen vor der Einheit.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#518]
Um das Platzproblem bei "!", langem Wert und "F" zu lösen, wurden alle Leerzeichen rausgenommen. Damit entsteht schlecht lesbares Bild für den Normalfall.  Also bitte möglichst immer ein Leerzeichen hinter dem "!", vor der Einheit und vor dem "F".

Bei Überlänge könnte sollten wir dann das "F" opfern.

Typischer Fall von Überlänge: "! 16000 ms F"

**Comment by hhoegelo** [comment]
fixed by #521
