### ISSUE TITLE
WebUI: EB Name wird bei Override durch Presetname ersetzt

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#535]
Wenn man im "EditBuffer"-Info den Namen geändert hat, wird er beim Speichern im "Overwrite"-Modus wieder durch den alten Namen aus dem "Preset"-Info ersetzt. Bei Comment und Color Tag passiert das nicht.

**Comment by nonlinear-labs** [comment]
Wir haben das EditBuffer Info erst einmal rausgeworfen.
