### ISSUE TITLE
WebUI: Die Pfeile von zwei Hardware-Amounts (R1-MCA, R2-MCB) waren dunkel, obwohl eigentlich an.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#553]
Schlecht reproduzierbar. Nach ein/zwei Bedienschritten war die Anzeige dann korrekt.
---
Heute wieder einmal gesehen: Init-Sound geladen: alle Pfeile sind schwarz, im BOLED ein Preset geladen, Pfeile bleiben schwarz, obwohl einige eingeschaltet sind. Dann wurde durch eine Bedienhandlung (in der WebUI?) das fehlende Grafik-Update ausgelöst.

**Comment by hhoegelo** [comment]
@nonlinear-labs Ich habe in dem Bereich am 3.1.2019 etwas gefixt  - wenn Du das nicht mehr reproduzieren kannst, waere ich dafuer, das issue zu schliessen.

**Comment by nonlinear-labs** [comment]
Ok - wird bis auf weiteres geschlossen.
