### ISSUE TITLE
WebUI: falsche Farben der Preset-Einträge bei Preset Search

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#570]
Muss beim Grafik-Umbau reingekommen sein: die Abdunklung der Presets und die Hervorhebung der Suchergnisse funktioniert nicht mehr. Die Suchergebnisse sind dunkler als der Rest

**Comment by nonlinear-labs** [comment]
Und auch bei der Selektion von Buchstaben im Rename-Dialog

**Comment by majjam** [comment]
RELEASE-19-01 (In VBOX)
Verbesserung:
Zusätzlich wäre es gut wenn der Fokus so gelegt wird, dass man direkt  lostippen kann um zu suchen (wie bei rename):

Zum Testen:
STRG+F und danach "rentier" eintippen führt zum umbenenne des aktuellen Preset zu "entier"
