### ISSUE TITLE
Playground: Description text 81.txt und 111.txt erweiterte Beschreibung

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#576]
RELEASE-19-01
In der Beschreibung für Ringmodulation steht jeweils:
111.txt:Mix amount for the result of the ring modulation between both Oscillators & Shapers.
81.txt:Mix amount for the result of the ring modulation between both Oscillators & Shapers.

Schön wäre noch wenn hier jeweils stehen würde wer Carrier and wer Modulator ist.
z.B.:
Mix amount for the result of the ring modulation between both Oscillators & Shapers.
Carrier : OscA ShpA
Modulator:  OscB ShpB

**Comment by nonlinear-labs** [comment]
Das Ringmodulations-Produkt ist wirklich nur das Ergebnis einer Multiplikation von A und B. Es gibt also keine Unterscheidung zwischen Carrier und Modulator. Wenn es zum A-Zweig gemischt wird, könnte man es als Amplituden-Modulation von A durch B interpretieren, aber spätestens bei einem Mix von 100% sind beide gleichermassen Carrier und Modulator. Ich denke mal über eine entsprechende Formulierung nach.

**Comment by nonlinear-labs** [comment]
81.txt: Crossfades between the signal of branch A and the multiplication (ring modulation) product of branch A and branch B. At lower values the result is an amplitude modulation of signal A (carrier) by signal B (modulator). At 100 % signal A is fully cancelled and the output is the product of signal A x signal B, containing frequencies that are sums and differences of their original frequencies.

111.txt: Crossfades between the signal of branch B and the multiplication (ring modulation) product of branch A and branch B. At lower values the result is an amplitude modulation of signal B (carrier) by signal A (modulator). At 100 % signal B is fully cancelled and the output is the product of signal A x signal B, containing frequencies that are sums and differences of their original frequencies.

**Comment by nonlinear-labs** [comment]
Ja - das ist richtig interpretiert.
In unserem detaillierten Block-Diagramm sind die Crossfader übrigens alle als helle kleine Rechtecke mit 2-3 Eingängen und einem Ausgang dargestellt:
[Block-Diagramm-L-Druck.pdf](https://github.com/nonlinear-labs-dev/C15/files/2720672/Block-Diagramm-L-Druck.pdf)
