### ISSUE TITLE
Änderungen an Attributen eines gerade geladenen Presets auch in den Editbuffer kopieren.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#580]
Ein neuer Versuch, die Divergenz zwischen Editbuffer und Presetmanager zu verringern.

Case:
Preset laden, editieren, speichern, Color Tag ändern: Color Tag ist neu. - schön!
Preset noch ein bisschen editieren, wieder speichern: Color Tag ist wieder alt. - nicht schön!
(Der Grund ist, dass der Editbuffer noch das alte Color Tag enthält. Es müsste bei Veränderungen mit überschrieben werden.)

**Comment by hhoegelo** [comment]
@nonlinear-labs Ich glaube, dieser Bug hat sich erledigt durch das Entfernen des EditBuffer Info, richtig?
