### ISSUE TITLE
WebUI: Design für MC-Touch-Oberfläche

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#663]
Tinos Mock-up:
![mc-touch-oberflache-a-1 0](https://user-images.githubusercontent.com/33938408/50641841-8b073980-0f69-11e9-8a11-ab18c41ba291.png)

- Mausklick wie Touch akzeptieren
- Bidirektionale Kommunikation - aktuellen Wert des MCs darstellen
- "Smoothing"-Einstellung in schmalem Streifen am linken Rand 
  - Call-Rate fest auf 20 ms
  - step = 1.0 / (Smoothing * 0.5 +1.0)   // Smoothing = 0 … 100
- CPU-Last (ca 15 % ohne, 20 % mit Touch) reduzieren

**Comment by schlenkibus** [comment]
![mc-touch-oberflache-1 1](https://user-images.githubusercontent.com/15381257/50834558-9c2ebc80-1354-11e9-838c-20e12829a12a.png)

**Comment by nonlinear-labs** [comment]
Ist erstmal ok so für die Messe
