### ISSUE TITLE
WebUI: Freezes at random Times with over 100% CPU

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#695]
Happened to me frequently now, I can't reproduce it. (But I have the feeling it happens more frequently when the Developer Tools are open)
The Only way to restart the WebUI for me is to kill the tab via Chrome Taskmanager.

![100](https://user-images.githubusercontent.com/15381257/51618145-01c2a180-1f2e-11e9-960b-59f6cee52322.png)

**Comment by hhoegelo** [comment]
found an infinite loop in undo system (with uninitialized members)
