### ISSUE TITLE
Neuer Presetmanager WEBUI : Speichern ; fehlerhafte Zuordnung des Namens

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#704]
RELEASE-2019-02
Speichern INSERT mit Änderung    OK
Speichern INSERT ohne Änderung    OK
Speichern APPEND mit Änderung    OK
Speichern APPEND ohne Änderung   Leerer presetname
Speichern OVERWRITE              OK

**Comment by schlenkibus** [comment]
Ich konnte durch Append ohne Änderunf keinen Leeren Presetnamen reproduzieren.

**Comment by majjam** [comment]
Sorry #704 kann geschlossen werden. War eine Missinterpretation meinerseits:
1 Playground war frisch gestartet nach crash.
2 Direct Load war aus (es wurde also kein Presetname geladen)
Speichern führte zu leerem Presetnamen
