### ISSUE TITLE
HwUI: Crash bei Cut and Paste

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#707]
branch RELEASE-2019-02
(Bank mit 139 Presets)
1. Select Preset (138)
2. EDIT
3. CUT
4. neue Stelle suchen
5. PASTE  => Playground crash (and restart)

**Comment by schlenkibus** [comment]
Ich kann den Crash nicht reproduzieren. Cut und Paste innerhalb der HWUI funktionert bei mir (mit neustem RELEASE-2019-02) einwandfrei, das betrifft paste innerhalb der Quell-Bank und auch Paste in andere Bänke. 

Tritt der Bug bei jedem Cut + Paste auf, egal welche Stelle (Schritt 4.) gewählt ist?

**Comment by majjam** [comment]
branch RELEASE-2019-02 vom 31.11.2019 
Habe gerade noch nen Test gemacht: CUT and PASTE OHNE Schritt 4 löst bei mir das Problem aus:
Also dort einfügen , wo entnommen. => crash.
Wenn gewünscht kann ich die dementsprechnde Bank übermitteln. (Scheint aber immer schief zu gehen.)

**Comment by majjam** [comment]
Habe einen weitern Test mit 
Test-Build 
1553 commits
Head 048d003 gemacht.
gleiches Ergebnis : dort einfügen , wo entnommen. => crash.

**Comment by hhoegelo** [comment]
Hi Majjam,

ich kann den Bug leider ebenfalls nicht reproduzieren.
Hast Du demnaechst mal Zeit, dass wir telefonisch oder per Mail besprechen koennen, wie wir das besser eingrenzen koennen? Logs waeren hilfreich, oder auch Infos darueber, wie Du die Testversionen baust und ob der Crash eventuell an einem fehlerhaften Build liegen koennte.

Gruss, Henry

**Comment by majjam** [comment]
Hallo zusammen,
ich baue mit builddocker allerdings unter Linux (linux Mint )
Es wäre natürlich schlecht, wenn ich hier issues poste und es liegt nur am build, wonach es ja im Augenblick aussieht. 
ich hab mal ein log angehängt, bei dem ich nichts gemacht habe ausser edit cut and paste. 
Morgen früh könnten wir telefonieren, wenn es Euch passt. Stephan hat meine Email adresse , da könnt Ihr mir gerne eine Nummer hin senden auf der ich Euch anrufe.
Gruß
Max
[C15-journal(3).tar.gz](https://github.com/nonlinear-labs-dev/C15/files/2861240/C15-journal.3.tar.gz)

**Comment by hhoegelo** [comment]
Ich habe auf branch 707 mal hinzugefuegt, dass beim Werfen der Exception der CallStack mit ausgegeben wird. Dadurch erhoffe ich mir Erkenntnisse ueber den Code-Pfad, der beim Auftreten des Bugs durchlaufen wird. 
Wenn Du so nett waerst, das nochmal mit dem 707-build nachzustellen, waere das sehr hilfreich,
Danke, Henry

**Comment by hhoegelo** [comment]
Ok, wir haben es gerade reproduziert, Du brauchst es also nicht mehr zu testen, Danke.

**Comment by majjam** [comment]
OK ,
trotzdem hoffe ich , dass ich nicht zusätzliche Arbeit mache, die bei Nutzung Eurer Kompilate unnötig wäre.

**Comment by hhoegelo** [comment]
Nein, im Gegenteil - Du hast einen schwer zu findenden Bug aufgedeckt, dafuer sind wir dankbar!

**Comment by majjam** [comment]
Läuft bei mir ! Kein Crash mehr ;)
