### ISSUE TITLE
UNDO: Macro-Änderungen werden parallel zu Parameteränderungen abgespeichert

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#724]
Wenn man an einer Macro Control herumschraubt, während man einen Parameter ändert, wird dies für den Undovorgang gespeichert => Es wird mehr Rückgängig gemacht (oder wiederhergestellt) als gewünscht ist.
Beispiel :
Preset mit Bender auf MC-C und C auf allen Pitches
1. Parameter anwählen  (z.B Cutoff SVF)
2. Bender auf Anschlag halten
3. Mit Encoder Parameter verändern
4. Bender in Mittelstellung bringen
5. Undo -> Parameter-Wert passt
6. Redo -> Parameter-Wert passt

5 und 6 immer wiederholen .
Bei Schritt 5 oder Schritt 6  ist dann der Pitch verschoben, weil diese Änderung beim Abspeichern des Undo Schritts mitgenommen wird.

Die Veränderung eines Paramters durch eine Macro control, sollte igoriert werden.

**Comment by hhoegelo** [comment]
@nonlinear-labs : Stephan, kannst Du den Bug bitte bewerten? Soll er noch fuer 2019-02 betrachtet werden?

**Comment by nonlinear-labs** [comment]
Ich würde den Bug nicht so hoch priorisieren, da man selten MCs und Parameter gleichzeitig bewegt (und dann noch Undo nutzen will). Die Gefahr, dass wir die Arithmetik verschlimmbessern, ist gegeben. Vielleicht nehmen wir uns das vor, wenn wir die Modulation insgesamt auf nicht-incrementell umstellen.
