### ISSUE TITLE
WiFi: Gerätenamen (und damit SSID) geändert: Verbindung erst möglich, wenn auch ein neues Passwort generiert wurde

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#781]
Stanley: "Name change synth -> wifi connection 'lost' -> reconnected -> geht nicht mit altes Passwort / fehlt, new password generated -> reconnected -> ok"

**Comment by schlenkibus** [comment]
I believe this bug would have been found with the latest epc2 Wifi changes, what do you think @AntonSchmied

**Comment by AntonSchmied** [comment]
Yes, I agree, @schlenkibus. Plus, This looks super old to me ...  28.02.2019 ...
