### ISSUE TITLE
WebUI: Changed-Markierungen werden bei Undo-Steps nicht konsistent wiederhergestellt

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#799]
Müsste man noch genauer analysieren...

Z.B. steht bei den MC Select Buttons irgendwann "Original: None", obwohl das Original "A" war.

Redo-Schritte scheinen zu vollständigeren Markierungen zu führen als Undo-Schritte.

**Comment by schlenkibus** [comment]
Auf welche Version bezieht sich das Ticket? 
Außerdem hätte ich gerne eine Abfolge von Aktionen zur Reproduktion des Problems.

**Comment by nonlinear-labs** [comment]
(Erstmal?) nicht mehr reproduzierbar.
