### ISSUE TITLE
BOLED: immer ein Sternchen am Preset nach dem Laden (in WebUI nicht)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#806]
Physical Control Parameter komplett aus dem Recall-Foo rausnehmen. 
Kein Originalwert speichern und Recall anbieten.

**Comment by nonlinear-labs** [comment]
Vielleicht habe ich es falsch formuliert, also: Das Sternchen an der Presetnummer sollte nach dem Laden überall verschwinden. In der WebUI tut es das, im BOLED leider nicht.

**Comment by schlenkibus** [comment]
Auf der aktuellen Version (RELEASE-2019-02) kann ich das Problem nicht nachvollziehen.
