### ISSUE TITLE
HwUI/WebUi: falscher MC Amount bei einheitenbehafteten Parametern.

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#833]
Die Anzeige passt nicht zum eingestellten Wert, und Webui zeigt "%" wobei HWui [ms] zeigt.
Tesversion RELEASE-2019-02  Commits 1749

Zum reproduzieren : 
1. ENV-A Release  auf 60.8ms (Wert ist eigentlich egal)
2. MC Sel auf D{HWPos 0% ; Pedal 4 on)
3. MC amount von ENV-A Release eröhen

Anzeige rechts im Display : 
       Upper 3170ms
       Mid 60.9 ms
       Lower 60.8 ms
(Soweit ok )
Anzeige MC amount über Softbutton 3 : 
      5.22ms (falsch, sollte meiner Meinung nach Differenz zwischen Upper und Lower sein)

Anzeige in Webui : 
       MC amount : 32.7 % (das müsst Ihr bewerten, ob das gewünscht ist)

Ob es bei älteren Versionen auch der Fall ist weiss ich leider nicht.

**Comment by schlenkibus** [comment]
behandelt in #844
