### ISSUE TITLE
bug? : Modulation von unision detune

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#857]
Branch :   Release-2019-02
commits: 1775 
HEAD :     4e6105e

Irgendwie ist die Modulation der 2nd Voice verdreht.

Beispiel 1
1 - 2 Voices
2 - detune : 0 
3 -  MC SEL (detune) : A
4 - MC Amt : 12ST (upper: 12, mid :0 ,low : 0)
Result :
Modulation wird in Boled angezeigt, man hört keine Veränderung

Beispiel 2
1 - 2 Voices
2 - detune : 12 
3 -  MC SEL (detune) : A
4 - MC Amt : 12ST (upper: 12, mid: 12 ,low : 0)

Man hört das Detune beginned  beim hohen Ton heruntergehendend mit steigender modulation,
boled zeigt nur MC clipping an .

**Comment by nonlinear-labs** [comment]
Hallo Max, ich war auch schon einem Problem mit der MC-Modulation des Detune auf der Spur. Es liegt wahrscheinlich nicht in der hier addressierten UI-Software, sondern in der LPC-Firmware.

Der MC Amount wird durch den Firmware-Bug in der Wirkung verdoppelt. Ein Amount von 6 st wirkt also wie 12 st. Amounts größer als 6 st werden verworfen, wie Dein Beispiel 1 zeigen. Wenn man den Amount halbiert, funktioniert die Modulation, allerdings um den Faktor 2 gestreckt.
Dein Beispiel 2 kann ich nicht reproduzieren. Jenseits von 6 st Amount ist bei mir keine Modulation zu hören.

Ich schliesse den Issue, weil es sehr wahrscheinlich ein LPC-Thema ist. Danke für den Input!

**Comment by nonlinear-labs** [comment]
Ich wollte ihn schliessen...
