### ISSUE TITLE
Preset - Comment und Color Tag gehen beim Speichern an neuer Position verloren

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#863]
- [x] Der Edit-Buffer und das Clipboard unterstützen Comment und Color Tag nicht. Deshalb gehen sie beim Speichern mit Append und Insert und bei Cut/Copy/Paste verloren.

 - [x] Wenn ein Preset verschoben oder kopiert wird, sollten wir alle seine Eigenschaften mitnehmen. Das Clipboard sollte also auch Comment und Color Tag erfassen.

 - [x] Bei Store eines unveränderten Presets sollte es auch Comment und Tag mitnehmen. Dabei müssen auch Änderungen, die nach dem Laden vorgenommen wurden, mitgenommen (also in den Edit-Buffer kopiert) werden.

 - [ ] Bei editierten Presets ist nicht so eindeutig: Sie können so stark verändert sein, dass der alte Comment oder das bisherige Color Tag nicht mehr zutreffen. Hier sollten wir eine Abfrage bringen (aber nur, wenn Comment oder Color Tag nicht leer). Im BOLED nach der "Rename"-Eingabe - falls vorhanden - den Comment anzeigen mit Optionen "Keep" (Enter) und "Edit" (Edit). Das gleiche gilt für den Color Tag.
In der WebUI könnten wir den Rename-Dialog um Comment und Color Tag erweitern.

**Comment by schlenkibus** [comment]
Gegenvorschlag zum letzten und vorletzten Punkt: Alle Änderungen am Preset werden solange in den Editbuffer kopiert bis dieser eine Veränderung gegenüber dem Preset aufweist. 
Sobald sich der EditBuffer vom Preset wegverändert können wir nicht davon ausgehen das die Änderungen am Preset noch einen Bezug zum Editbuffer haben.
