### ISSUE TITLE
Fehlerhafte Changed-Anzeigen nach dem Speichern nach Veränderung von MC Positionen

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#876]
Preset geladen, MC A und B verändert: 7+2 Changed-Markierungen gehen an.
Preset (mit Overwrite) speichern: im BOLED sind immer noch 7+2 Changed-Markierungen an, 

MC Pos, MC Sel, MC Amt werden bei Overwrite wohl mit Init verglichen (weil das Originalpreset nicht mehr da ist?), bei Append wird MC Pos mit dem alten Preset verglichen. Der Parameterwert wohl immer mit dem alten Preset.

In der WebUI sind dann auch gelbe Rahmen an, aber nicht alle. Die veränderten Werte sind meist identisch mit den Originalwerten (oder 0.1 % daneben). MC Pos ist nicht als verändert markiert. Sieht aus wie Rundungsfehler...

Siehe #909

**Comment by schlenkibus** [comment]
Fixed in #919
