### ISSUE TITLE
Editbuffer wird unvollständig geladen

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#903]
Beim hochfahren wird nicht das Vollständige Preset an die Soundengine übermittelt.

1. Sound A geladen
2. C15 heruntergefahren , wieder gestartet
=> Sound A'  ist spielbar. (man hört eine Differenz zu sound A)
3.  Sound A' abspeichern  und das gespeicherte Preset laden 
=> Sound A ist spielbar.

RELEASE-2019-02 von 24.4

**Comment by schlenkibus** [comment]
Danke für die Meldung. Ich schaue mir das an. Kannst du mir ein Preset senden mit dem das Problem, für mich Sound-Laien, gut hörbar ist?

**Comment by majjam** [comment]
heute spät nachmittag bzw abend sende ich dir etwas zu

**Comment by majjam** [comment]
Sorry,
ich kann das Verhalten nicht mehr reproduzieren, daher schliese ich das Issue bis auf weiteres.
Wenn ich mehr weis, melde ich mich wieder.
Gruß
Max
