### ISSUE TITLE
Unterscheidliche Display-Value Auflösung

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#906]
Envelope - Release Time
BOLED: 0.078ms
WebUI:  0.0783ms

Soll das Boled erweitert werden oder WebUI gekürzt? @nonlinear-labs

**Comment by MatthiasSeeber** [comment]
Nach meinem Stand sind nichtlineare Skalierungen (wie Envelope - Release Time) auf drei signifikante Ziffern gerundet, was für die BOLED-Implementierung spricht. Zudem ist der Wertesprung zwischen 0.078 +/- einen Fine Step groß genug (0.067, 0.078, 0.090), dass eine zehntausendstel-Stelle nicht gebraucht wird.
