### ISSUE TITLE
Undo scheint jetzt MC-Veränderungen mit zu erfassen

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#924]
Beim Spielen das Sustain-Pedal genutzt und gleichzeitig Parameter verstellt: 
Beim Undo auf die Parameter-Änderungen wurden auch Bewegungen des Sustain-Pedals wieder wirksam. Bei Undo/Redo-Betätigung wurden dann auch noch die MC-Ranges der Target-Parameter des Sustain-Pedals verfälscht.

Wir hatten die MCs doch aus dem Undo ausgeklammert...

**Comment by hhoegelo** [comment]
@nonlinear-labs Justus hat das feature jetzt konsequenterweise ausgebaut, weil es dieses Ticket gibt. Ist das gewuenscht, dass wir das Feature ausbauen? Soweit ich sehe, ist der EditBufferSnapshotMaker dann obsolet und kann komplett raus.
