### ISSUE TITLE
Default-Values für Pitches sind jetzt leider leicht daneben: 60.01 st

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#935]

**Comment by hhoegelo** [comment]
@majjam: If Stephan remembers correctly, he found this issue on your device. 
An explanation would be, that you changed your default values (Sound/Edit/Store Init) - which would mean: it is a feature, not a bug. Would you be so kind as to check if this is the case?

**Comment by majjam** [comment]
Indeed it is the case ! 
I reset the init preset and pitches are at 60.00 again.
My init patch had pitches at 60.00 definitely some time ago, maybe it changed  while testing the versions.
From my side  this issue can be closed

**Comment by hhoegelo** [comment]
Thanks a lot, @majjam.
