### ISSUE TITLE
Crash Bank-management (sort)

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#940]
RELEASE-2019-05 
Crash des Playground beim sortieren.
ich habe relativ schnell hintereinander Bänke importiert und gelöscht und re-attached. (80% aller _NL_ Bänke -- GUI war schon etwas ruckelig)

Danach habe ich die Bänke neu sortieren lassen. Es sind zwei Bänke "verschwunden".
Bei einem weiteren Versuch zu sortieren, gabe es jedesmal einen Crash im Playground.
Ein Export aller Bänke(tar.gz) hat nach entpacken im XML gezeigt, dass einige Bänke doppelt vorhanden sind. 
Vermutung :Die Doppelten führen beim Sortieren wohl zum Crash.

Das Bank-File werde ich heute abend hier hochloaden.

**Comment by hhoegelo** [comment]
Sorry, cannot reproduce, no matter how hard I try.

**Comment by majjam** [comment]
RELEASE_2019-05 
Commits 1882
HEAD : f13964a
Try try attached backup file:
If i sort my banks after loading backup into my device playground crashes.

[2019-05-22-16-27-nonlinear-c15-banks.xml.tar.gz](https://github.com/nonlinear-labs-dev/C15/files/3213118/2019-05-22-16-27-nonlinear-c15-banks.xml.tar.gz)
