### ISSUE TITLE
PG/Bridge: UI (Display und LEDs) friert ein sobald/solange keine WiFi-Hardware erkannt wird

### ISSUE THREAD

**Issue by KlausStrohhaecker** [nonlinear-labs-dev/C15#950]
Symptom: Abziehen des WiFi-Sticks verhindert jeglichen optischen Update des Hardware-UI solange bis er wieder angesteckt wird.
Fehlt WiFi schon beim Booten, bleibt "initializing..." ewig stehen, ansonsten frieren die Anzeigen auf dem letzten Stand ein.
Offenbar läuft das Gerät aber weiter: geht WiFi wieder werden alle zwischenzeitlich erfolgten Änderungen korrekt angezeigt (sobald ein "changed" Event kommt, also eine weitere Bedienaktion/Bender/Pedal).

System: 1811a. PG/Bridge: Commit #1894
Passiert aber auch mit einem reinen 1811a mit PG #1189, ist also ein schon älteres Problem.
Alte Systeme "1803f" ohne Bridge zeigen dagegen keine Auffälligkeit.

**Comment by hhoegelo** [comment]
I changed configuration files in buildroot to configure loopback device properly and let the playground systemd-service search for the bbbb on the loopback device.
Still, our golden master and the update scripts have to be changed accordingly. @KlausStrohhaecker , please close the issue once this is done.
