### ISSUE TITLE
Verify: Move Bank is undone on following import

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#993]
Move a Bank, Import a Bank, ... , Bank 'unmoved'

also on store?

**Comment by schlenkibus** [comment]
Can't reproduce on master nor my layouts branch. Most likely was related to the broken Preset Manager with multiple banks having the same UUID. @nonlinear-labs Can this be closed?

**Comment by nonlinear-labs** [comment]
Yepp - Hat bestimmt mit dem Preset Manager Problem #1011 zu tun.
